Add ShaderMask benchmark case
flutter/flutter pull request #100957
Opened 2022-03-29 08:47 UTC by JsouLiang

Add ShaderMask test case for this PR: https://github.com/flutter/engine/pull/32027

2022-04-01 11:03 UTC, wangying3426 commented
> I'm sorry I didn't notice that there were 2 PRs from 2 different authors for this same thing, but #100127 already landed so is this PR now a duplicate?

(⊙o⊙)…  @JsouLiang and @wangying3426  work on the same team. 
This test case is added to demonstrates that the saveLayer is need for cached child layer.

2022-04-14 20:21 UTC, flar requested changes
Mostly questions to verify what I'm seeing.

2022-04-14 20:21 UTC, flar commented on dev/benchmarks/macrobenchmarks/android/app/src/main/AndroidManifest.xml
> +            android:exported="true"
I don't see any reason for this flag to be set. These benchmarks aren't exporting any services. Was there a reason this got set here?

2022-04-14 20:21 UTC, flar commented on dev/benchmarks/macrobenchmarks/lib/src/shader_mask_cache.dart
> +          buildShaderMaskWithBlendMode(BlendMode.src, 'BlendMode.src'),
Are all of these items visible on our default test device which is a Moto G4?

2022-04-14 20:22 UTC, flar commented
> > I'm sorry I didn't notice that there were 2 PRs from 2 different authors for this same thing, but #100127 already landed so is this PR now a duplicate?
> 
> (⊙o⊙)… @JsouLiang and @wangying3426 work on the same team. This test case is added to demonstrates that the saveLayer is need for cached child layer.

This is a benchmark. Nobody ever sees what it looks like as it is run in an anonymous lab. If this is testing that the right output is generated then this should not be a benchmark, it should be a golden test.

2022-05-04 21:33 UTC, flar commented on dev/benchmarks/macrobenchmarks/lib/src/shader_mask_cache.dart
> +          buildShaderMaskWithBlendMode(BlendMode.src, 'BlendMode.src'),
I just fetched this PR and ran this on my G4 and the dst is only partially visible some of the time. The src example never appears.

2022-05-04 21:39 UTC, flar commented
This looks like it is modifying an existing benchmark, but that is usually not a practice we encourage because it will disrupt the tracked history of the existing benchmark. We record the performance of all benchmarks over time so we can look for trends.

One reason to modify a benchmark is if we've made breaking changes and it needs to be updated to match the new APIs. That doesn't apply here.

Another reason to modify a benchmark is if it isn't actually exercising the issues that we originally wanted to address (in other words, the execution of the benchmark misses its mark). I don't think that is the case here, but let me know if this applies.

It looks like the existing benchmark was likely measuring something that we want to keep tracking, so it didn't really warrant any updates.

The new code looks like it is testing more conditions beyond the original benchmark, so it will both break the trends we have recorded for the previous version as well as now have 1 benchmark measuring the performance of a couple of cases. If so, then the different conditions warrant being measured in their own benchmarks so that we don't miss regressions when one of the test cases gets faster while the other gets slower - that could hide performance changes that we want to make visible.

I would like to see a better description of what this benchmark was measuring before these changes and what the new changes are measuring and how they differ from or complement each other.

2022-05-06 12:54 UTC, closed without merging