Fix a `Slider` widget accessibility bug
flutter/flutter pull request #102129
Opened 2022-04-19 07:17 UTC by xu-baolin

Fixes https://github.com/flutter/flutter/issues/101868

The `Slider.label` should not write to `SemanticsConfiguration.label`, 
I check the originally introduced PR https://github.com/flutter/flutter/pull/58535/files which is more like a mistake.
Also, I test the Android native talkback, it does not read the label info out.

In addition, improve the docs about when the label will appear.

2022-04-19 16:07 UTC, gspencergoog requested changes
What is the problem with the current label?

Will information about the range labels be missing from the semantics if you do this?

2022-04-19 19:08 UTC, xu-baolin commented
> What is the problem with the current label?
> 
> 
> 
> Will information about the range labels be missing from the semantics if you do this?

As the reference issue report, the android talkback will read 'value + label + slider',such as ' 50% 50 slider '.

I have tested the native slider widget, and the talkback doesn't read labels info out. The semantics label doesn't apply here,right?

2022-04-25 12:34 UTC, xu-baolin commented on packages/flutter/lib/src/material/range_slider.dart
>      if (semanticFormatterCallback != null) {
done

2022-04-25 19:05 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

Sounds good, thanks for the PR!

2022-04-26 01:24 UTC, merged