`Switch`: Add an interactive example
flutter/flutter pull request #103045
Opened 2022-05-04 14:11 UTC by TahaTesser

fixes https://github.com/flutter/flutter/issues/103037

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-05-04 14:40 UTC, guidezpl requested changes

2022-05-04 18:23 UTC, HansMuller reviewed
This is a pretty elaborate example for such a simple component.

There's no harm in including a couple of switches in the example. A simple one might be what developers that want a quick copy-and-paste target are looking for. A more complex example, that demonstrates using MaterialStateProperty values would be helpful if there was some obvious motivations for the overrides (even just a comment explaining what's going on). It would also be helpful to show that a MaterialStateProperty can be used to override the color for just one state and, by returning null for the others, leave the defaults for the other states intact.

2022-05-04 18:33 UTC, TahaTesser commented
@HansMuller 
That makes sense, I'm on it :)

2022-05-18 08:56 UTC, guidezpl commented on examples/api/lib/material/switch/switch.1.dart
> +        // hovered, focused or disabled.
nit: keep oxford comma

2022-05-18 08:56 UTC, guidezpl commented on examples/api/lib/material/switch/switch.1.dart
> +        // hovered or focused.
nit: keep oxford comma

2022-05-24 15:29 UTC, HansMuller approved these changes
LGTM

2022-05-24 20:28 UTC, TahaTesser commented
cc: @guidezpl

2022-05-25 08:40 UTC, guidezpl approved these changes

2022-05-25 08:40 UTC, merged