Fix PageView throws Null check error
flutter/flutter pull request #104405
Opened 2022-05-23 11:33 UTC by bleroux

## Description

This PR fixes a null check error in `PageView`.

The null check was added by the following PR : https://github.com/flutter/flutter/pull/65015

Flutter 3.0 is the first stable release where the null check error surfaces.
It surfaces due to the following PR : https://github.com/flutter/flutter/pull/97971
which added this line https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/scrollable.dart#L454

## Related Issue

Fixes https://github.com/flutter/flutter/issues/101007

## Tests

Adds 1 test.

2022-06-07 22:26 UTC, Piinks approved these changes
LGTM! Thank you for fixing this! @xu-baolin WDYT?

2022-06-08 08:01 UTC, xu-baolin commented
Hey， this issue is similar to this #103328, 
We should override `absorb` when the `_PagePosition` was replaced.
```dart
  @override
  void absorb(ScrollPosition other) {
    super.absorb(other);
    assert(_cachedPage == null);

    if (other is! _PagePosition) {
      return;
    }

    if (other._cachedPage != null) {
      _cachedPage = other._cachedPage;
      other._cachedPage = null;
    }
  }
```

2022-06-08 08:02 UTC, xu-baolin requested changes
See the comment above.

2022-06-08 12:03 UTC, xu-baolin approved these changes
LGTM，need a second review from @Piinks

2022-06-08 21:44 UTC, Piinks approved these changes
Ah nice @xu-baolin! Thanks @bleroux, LGTM!

2022-06-08 21:48 UTC, merged

2022-07-11 19:12 UTC, armandojimenez commented
Anyone knows when is this landing on stable branch>

2022-07-15 13:36 UTC, ffamar commented
The issue still exist in the flutter version 3.0.5.
Anyone knows when the patch will be released?

2022-07-20 13:46 UTC, alexaung commented
Yes still happening in version 3.0.5

2022-07-21 09:36 UTC, tonyshkurenko commented
Is this expected to be fixed in 3.0.5 and it's an issue again or it wasn't included in 3.0.5?

2022-07-21 10:04 UTC, bleroux commented
@tonyshkurenko
It was not included in 3.0.5.
For the moment, this fix is available in the master channel and in the 3.3 beta channel.

2022-08-31 10:18 UTC, ffamar commented
I confirm, issue fixed in 3.3.0 release.