Fix/expansion panel list
flutter/flutter pull request #105926
Opened 2022-06-13 22:53 UTC by funyin

- Added parameter to change expansion icon of expansion panel
- Added parameter to show or hide expansion panel icon

### Issues
- Fixed compulsory icon that comes with ExpansionPaneList

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-06-21 18:18 UTC, Renzo-Olivares commented
Thanks for your contribution. This seems like a reasonable change, but we will need a test before we can land any change.

2022-06-27 13:28 UTC, Gabanelli reviewed
I commented some suggestions to your PR

2022-06-27 13:28 UTC, Gabanelli commented on packages/flutter/lib/src/material/expansion_panel.dart
> +      var onTapIcon = !child.canTapOnHeader
`onTapIcon` can be final

2022-06-27 13:28 UTC, Gabanelli commented on packages/flutter/lib/src/material/expansion_panel.dart
> +              : null
I think you missed a `;`

2022-06-27 13:28 UTC, Gabanelli commented on packages/flutter/lib/src/material/expansion_panel.dart
> +        child: icon==null?ExpandIcon(
Format file to fix code spacing

2022-06-28 17:45 UTC, Renzo-Olivares requested changes
Just a reminder that this PR still needs a test to be merged.

2022-10-04 23:24 UTC, Hixie commented
@funyin Thanks for your contribution. I'm going to close this PR since it doesn't have a test and so can't land in its current state, but please don't hesitate to submit it again when you are ready! If you need help writing tests please don't hesitate to reach out to us on the Discord (link in the contributing guidelines, link to that is below), especially the #hackers-new channel.

2022-10-04 23:24 UTC, closed without merging