Documentation update to advertize timedDrag
flutter/flutter pull request #106489
Opened 2022-06-23 13:18 UTC by bleroux

## Description

This documentation PR adds several 'see also' sections in order to make `WidgetController.timedDrag` more discoverable. 

## Related Issue

Fixes https://github.com/flutter/flutter/issues/96893

## Tests

No Test, documentation update only.

2022-06-29 21:36 UTC, goderbauer approved these changes
LGTM

2022-06-29 21:36 UTC, goderbauer commented
@loic-sharma Can you do a secondary review?

2022-06-29 21:38 UTC, loic-sharma approved these changes

2022-06-29 21:48 UTC, dkwingsmt requested changes
Some bikeshedding on format. Otherwise good!

2022-06-29 21:48 UTC, dkwingsmt commented on packages/flutter_test/lib/src/controller.dart
> +  /// - [WidgetController.fling], a method to simulate a fling.
```suggestion
  ///  * [WidgetController.drag], a method to simulate a drag.
  ///  * [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration.
  ///    It sends move events at a given frequency and it is useful when there are listeners involved.
  ///  * [WidgetController.fling], a method to simulate a fling.
```

2022-06-29 21:48 UTC, dkwingsmt commented on packages/flutter_test/lib/src/test_pointer.dart
> +  /// - [WidgetController.fling], a method to simulate a fling.
```suggestion
  ///  * [WidgetController.drag], a method to simulate a drag.
  ///  * [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration.
  ///    It sends move events at a given frequency and it is useful when there are listeners involved.
  ///  * [WidgetController.fling], a method to simulate a fling.
```

2022-06-29 21:48 UTC, dkwingsmt commented on packages/flutter_test/lib/src/test_pointer.dart
> +  /// - [WidgetController.fling], a method to simulate a fling.
```suggestion
  ///  * [WidgetController.drag], a method to simulate a drag.
  ///  * [WidgetController.timedDrag], a method to simulate the drag of a given widget in a given duration.
  ///    It sends move events at a given frequency and it is useful when there are listeners involved.
  ///  * [WidgetController.fling], a method to simulate a fling.
```

2022-06-30 06:34 UTC, dkwingsmt approved these changes
LGTM

2022-06-30 13:02 UTC, merged