Add shadowColor and surfaceTintColor to Dialog and DialogTheme.
flutter/flutter pull request #108405
Opened 2022-07-27 01:27 UTC by darrenaustin

Currently there is no way to configure the drop shadow and/or the surface tint overlay color used by dialogs. This PR adds exposes for the `shadowColor` and `surfaceTintColor` used by `Dialog`'s underlying `Material` widget. It also adds these properties to `DialogTheme` so they can be configured using themes.

Fixes: #107423

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

2022-07-27 06:20 UTC, TahaTesser approved these changes
LGTM

2022-07-27 08:13 UTC, guidezpl requested changes

2022-07-27 08:13 UTC, guidezpl commented on packages/flutter/lib/src/material/dialog.dart
> +  ///     be applied to the background color based on the [elevation].
Suggest describing what these are rather than repeating sentences above

2022-07-27 08:13 UTC, guidezpl commented on packages/flutter/lib/src/material/dialog.dart
> +  /// This controls how far above the parent the dialog will appear. This is
```suggestion
  /// How far above the parent the dialog will appear. Elevation is
```

2022-07-27 22:53 UTC, HansMuller approved these changes
LGTM

2022-07-27 22:53 UTC, HansMuller commented on packages/flutter/lib/src/material/dialog.dart
> +  /// The color used as a surface tint overlay on the dialog's background
The color used as a surface tint overlay on the dialog's background color, which reflects the dialog's [elevation].

2022-07-27 22:53 UTC, HansMuller commented on packages/flutter/lib/src/material/dialog.dart
> +  /// The color to paint the shadow under the dialog's [Material].
The color to paint the [elevation] shadow under the dialog's [Material].

2022-07-28 02:26 UTC, guidezpl approved these changes
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

2022-07-28 21:54 UTC, merged