Support Material 3 in bottom sheet
flutter/flutter pull request #112466
Opened 2022-09-27 12:19 UTC by hangyujin

issue: #111448

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-09-30 19:06 UTC, darrenaustin requested changes
Nice work @hangyujin. Just have a few suggestions and a question about the M2 defaults. Thx.

2022-10-08 16:13 UTC, hangyujin commented on examples/api/lib/material/bottom_sheet/show_modal_bottom_sheet.1.dart
> +  static const String _title = 'Flutter Code Sample';
Done

2022-10-08 16:13 UTC, hangyujin commented on packages/flutter/lib/src/material/bottom_sheet.dart
> +      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(28.0),)),
Done

2022-10-08 16:13 UTC, hangyujin commented on packages/flutter/lib/src/material/bottom_sheet.dart
> +          final BottomSheetThemeData defaults = Theme.of(context).useMaterial3 ? _BottomSheetDefaultsM3(context) : const BottomSheetThemeData();
Yeah I didn't find any default value for M2

2022-10-11 03:27 UTC, darrenaustin approved these changes
LGTM.

2022-10-11 09:55 UTC, merged