Add warning that `RenderRepaintBoundary.toImage` and `OffsetLayer.toImage` is slow
flutter/flutter pull request #112757
Opened 2022-10-02 01:11 UTC by fzyzcjy

Scene.toImage has doc saying: "This is a slow operation that is performed on a background thread". However, people may use `RenderRepaintBoundary.toImage` and `OffsetLayer.toImage` and never read that comment, so they are unaware of the slowness. This PR simply adds the warning to them.

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-10-02 01:43 UTC, jonahwilliams requested changes
There are a lot of caveats to "slow". I don't know if copying around this comment which is quite implementation specific is the right approach.

2022-10-02 01:46 UTC, fzyzcjy commented
@jonahwilliams Hi thanks for the reply.

* If it is slow, IMHO the users need to know it, otherwise users may abuse it because they may think it is just a normal function.
* If it is fast, then we need to remove the original comment (because it is outdated).
* If it is slow but in the future it becomes fast (hopefully!), seems we can update comments at that time.

2022-10-02 01:50 UTC, fzyzcjy commented
Anyway this is just a small doc change and it does not matter whether it is changed or not for myself (since I already know it is slow and should be careful). I have spent some making this PR simply because I hope other users works correctly with the api :)

2022-10-10 18:31 UTC, goderbauer commented
I agree that this comment alone is not particularly useful. To be useful it would need more context so developers can actually make an informed decision of whether they want to use this or not. Let's close this for now.

2022-10-10 18:31 UTC, closed without merging