update google material icon search site
flutter/flutter pull request #114707
Opened 2022-11-04 18:58 UTC by flyingcircle

The links on the Icon docs no longer points to a usable location for searching material fonts. This is a simple update to fix those links.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-11-06 00:14 UTC, guidezpl requested changes

2022-11-06 00:14 UTC, guidezpl commented on packages/flutter/lib/src/material/icons.dart
> +/// Identifiers for the supported [Material Icons](https://fonts.google.com/icons).
```suggestion
/// Identifiers for the supported [Material Icons](https://fonts.google.com/icons?icon.set=Material+Icons).
```

2022-11-06 00:14 UTC, guidezpl commented on packages/flutter/lib/src/material/icons.dart
> +/// Search and find the perfect icon on the [Google Fonts](https://fonts.google.com/icons) website.
```suggestion
/// Search and find the perfect icon on the [Google Fonts](https://fonts.google.com/icons?icon.set=Material+Icons) website.
```

2022-11-06 00:14 UTC, guidezpl commented on packages/flutter/lib/src/material/icons.dart
> +///  * <https://fonts.google.com/icons>
```suggestion
///  * <https://fonts.google.com/icons?icon.set=Material+Icons>
```

2023-02-28 23:45 UTC, Hixie commented
Thanks for your contribution. Unfortunately, because the CLA has not been signed, I'm afraid we can't look at this proposal. I am therefore going to close this PR. If you would like us to consider this patch in the future, please do not hesitate to open a new PR, after signing the CLA which you can find at: https://cla.developers.google.com/

Thanks!

2023-02-28 23:45 UTC, closed without merging