issue #11126 - Add sample code to TextFormField.
flutter/flutter pull request #11528
Opened 2017-08-05 20:53 UTC by branflake2267

https://github.com/flutter/flutter/issues/11126

2017-08-07 22:15 UTC, cbracken requested changes
Thanks for the PR! Just a few minor nits.

2017-08-07 22:15 UTC, cbracken commented on packages/flutter/lib/src/material/text_form_field.dart
> +/// );
Drop the trailing `;`

2017-08-07 22:15 UTC, cbracken commented on packages/flutter/lib/src/material/text_form_field.dart
> +///     if (value.contains("@")) return "Do not use the @ char.";
Use single-quotes here for style consistency with the above/other examples.

2017-08-07 22:15 UTC, cbracken commented on packages/flutter/lib/src/material/text_form_field.dart
> +///     if (value.contains("@")) return "Do not use the @ char.";
Break the `return` onto the next line, or alternatively you could use a ternary:
```
return value.contains('@') ? 'Input may not contain @.' : null;
```

2017-08-14 18:11 UTC, Hixie commented
@branflake2267 Are you planning on applying the suggested fixes or should we take the PR over? (Either way is fine, just checking so we don't step on your toes.)

2017-11-09 20:38 UTC, Hixie commented
@branflake2267 I'm going to close this PR for now, but please feel free to resubmit it if you get a chance to work on it again. If you don't we'll get to it eventually.

2017-11-10 16:50 UTC, branflake2267 commented
Oops, I had lost this in my noise. Sounds good. :)

2018-11-21 08:57 UTC, goderbauer commented
@jslavitz Can we close this now that your PR has been submitted?

2018-11-21 18:25 UTC, closed without merging