Migrate activation issue template to Github form issues
flutter/flutter pull request #119916
Opened 2023-02-03 12:09 UTC by exaby73

This PR aims to migrate the existing new issue template for activating / installing Flutter to use Github forms. This allows us to add validations for required fields allowing the quality raised issues to be improved.

Closes https://github.com/flutter/flutter/issues/119914

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-02-03 12:26 UTC, darshankawar commented
Please add screenshot of the updated template so that team member(s) reviewing this would see a preview of changes made as part of this PR.

2023-02-03 12:49 UTC, exaby73 commented
@darshankawar Added a screenshot to https://github.com/flutter/flutter/pull/119916#issue-1569743286

2023-02-14 14:34 UTC, stuartmorgan requested changes
Based on the CI failures, it looks like [this code](https://github.com/flutter/flutter/blob/cd125e1f71209b425cc4fdf36b62fcef771ff743/dev/bots/analyze.dart#L1047-L1053) and [these links](https://github.com/flutter/flutter/search?q=1_activation&type=code) will need to be updated as well.

2023-02-14 14:34 UTC, stuartmorgan commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports
Let's remove this last sentence so that it's not duplicated with the new checkbox item below.

2023-02-14 14:34 UTC, stuartmorgan commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        <summary>Logs</summary>
It's a shame there's no attribute to put the result in a `summary` so that we wouldn't need to rely on people putting text in the right place here; I expect some people are going to replace the whole text area contents now that it's a form.

We'll have to see how common that is, and if it happens a lot consider changing to a field that sets the display style automatically so we don't need the backticks, and living without `summary`.

2023-02-14 14:34 UTC, stuartmorgan commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        Include the entire logs of running `flutter doctor -v`
How about: "Please provide the full output of running `flutter doctor -v`"

2023-02-15 10:30 UTC, exaby73 commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +      - label: I have read [our guide to filing a bug](https://flutter.dev/docs/resources/bug-reports)
Changed to `I have read the guide...`

2023-02-15 10:31 UTC, exaby73 commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        share it.
Added it :)

2023-02-15 10:34 UTC, exaby73 commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        <summary>Logs</summary>
We'll keep an eye out for this. 

Upon testing the [`render`](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#textarea) of the Github forms, it doesn't look like they add them in collapsible sections, just as code blocks. I am not sure of how to format the value of a field into a collapsible section. If you have any ideas, do let me know and I can test it and make the necessary changes :)

2023-02-15 10:34 UTC, exaby73 commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        Include the entire logs of running `flutter doctor -v`
Made the change :)

2023-02-15 10:35 UTC, exaby73 commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +      label: Expected results
I agree. Removed it, but kept the `actual results` field

2023-02-15 10:35 UTC, exaby73 commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +      - label: I have searched the existing issues
Added a link to the issue page

2023-02-15 10:35 UTC, exaby73 commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        our guide to filing a bug first: https://flutter.dev/docs/resources/bug-reports
Removed it

2023-02-15 11:21 UTC, exaby73 commented
Updated the screenshot of the form preview to reflect the changes I pushed

2023-02-23 14:44 UTC, stuartmorgan reviewed
Sorry for the delay in getting back to this review. It looks like you ran the autoformatter on the Dart code, which makes it really hard to review the changes there (and violates this repo's style guide). Could you revert the autoformat changes?

2023-02-27 14:30 UTC, stuartmorgan approved these changes
I found a couple of wording/grammar nits I missed before, but otherwise it looks great; LGTM!

2023-02-27 14:30 UTC, stuartmorgan commented on .github/ISSUE_TEMPLATE/1_activation.yml
> +        it as a `txt` file or use online tools like https://pastebin.com to
Nit: This should say "them" instead of "it" since it's referring to "the logs".

2023-02-28 08:08 UTC, merged