Modify the updateChildren method deep copy _children
flutter/flutter pull request #120773
Opened 2023-02-15 09:10 UTC by yiiim

This PR modifies newChildren to deep copy _children in updateChildren method.

Fixes #120762 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-02-16 07:22 UTC, xu-baolin requested changes
Changes looks good with some small nits.
Thank you for yout great work!

2023-02-16 07:22 UTC, xu-baolin commented on packages/flutter/test/widgets/framework_test.dart
> +      'RenderObjectElement updateChildren modifying GlobalKey Widget index and parent',
change test title to `MultiChildRenderObjectElement.updateChildren test`

2023-02-16 07:22 UTC, xu-baolin commented on packages/flutter/test/widgets/framework_test.dart
> +    await tester.pumpWidget(Column(
nit: insert a blank line

2023-02-16 07:22 UTC, xu-baolin commented on packages/flutter/test/widgets/framework_test.dart
> +  });
// Pass without crash
expect(tester.takeException(), isNull);

2023-02-16 07:22 UTC, xu-baolin commented on packages/flutter/test/widgets/framework_test.dart
> +    final GlobalKey globalKey = GlobalKey();
Add a relation link
// Regression test for https://github.com/flutter/flutter/issues/120762

2023-02-16 07:28 UTC, xu-baolin commented on packages/flutter/lib/src/widgets/framework.dart
> +        <Element>[...oldChildren] : List<Element>.filled(newWidgets.length, _NullElement.instance);
We indeed should not modify the input parameters directly, which is dangerous.

2023-02-16 07:54 UTC, yiiim commented
nits have been fixed

2023-02-16 08:51 UTC, xu-baolin approved these changes
LGTM, Thanks!

2023-02-16 09:19 UTC, xu-baolin commented
@goderbauer Hi could you take a second review for this patch? :)

2023-02-16 17:45 UTC, goderbauer commented on packages/flutter/lib/src/widgets/framework.dart
> +        <Element>[...oldChildren] : List<Element>.filled(newWidgets.length, _NullElement.instance);
As far as I can see, there's actually no reason to special-case `oldChildren.length == newWidgets.length` then. Could this just be simplified to:

```suggestion
    final List<Element> newChildren = List<Element>.filled(newWidgets.length, _NullElement.instance);
```

2023-02-17 17:09 UTC, goderbauer approved these changes
LGTM

2023-02-17 18:29 UTC, merged