[integration_test] upgrade androidx test to 1.4.0
flutter/flutter pull request #122437
Opened 2023-03-10 23:08 UTC by micaelcid

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-03-10 23:30 UTC, micaelcid commented
I'm reopening this as a Draft until I solve all CI failures that appeared after merging https://github.com/flutter/flutter/pull/109547

The failures can be found here: https://github.com/flutter/flutter/runs/11827814804

2023-03-13 01:42 UTC, micaelcid commented
Hey, @ricardoamador. My last PR was reverted, but I guess I solved the other issues now. Would you mind reviewing this again?

2023-03-13 16:37 UTC, ricardoamador commented
Yes, will do.

2023-03-14 15:45 UTC, ricardoamador commented
@micaelcid if you are stuck with IOS you can always try the flutter hackers-ios channel on discord and ask for some help there.

2023-03-14 19:47 UTC, micaelcid commented
Thanks for letting me know! I'll do that as soon as I've got spare time.

2023-03-21 21:12 UTC, ricardoamador commented
I can take a look.

2023-03-22 22:14 UTC, ricardoamador approved these changes
LGTM

2023-03-22 22:30 UTC, ricardoamador commented
You need one more review @micaelcid.

2023-03-22 22:43 UTC, micaelcid commented
Hey, @reidbaker. Would you mind reviewing this PR? I'm tagging you because you were one of the approvers of the one that got reverted :)

2023-03-22 22:56 UTC, micaelcid commented
By the way, is there a specific process for requesting a pull request review in this repository? I usually ask for recent contributors, but I am not sure if I should tag specific teams or if there's a guideline for this.

2023-03-28 19:36 UTC, reidbaker requested changes

2023-03-28 19:36 UTC, reidbaker commented on dev/benchmarks/complex_layout/android/gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-8.0.2-bin.zip
I dont think we should downgrade the version of gradle. Is this required or your change?

2023-03-30 14:08 UTC, reidbaker commented
> Hey, @reidbaker. I just solved your requested changes and the pipeline checks have passed. Do you mind reviewing again?

Yep I will do my best to get to it today if not then by EOD Fri.

2023-03-30 15:29 UTC, reidbaker approved these changes

2023-03-30 16:04 UTC, micaelcid commented
Are we aware of flaky tests in the GH Actions pipeline? While coming up with this PR, sporadically a few tests would fail and get solved after a rebase. For example, [these checks](https://github.com/flutter/flutter/pull/122437/checks?check_run_id=12400692862) fail intermittently, but they were previously passing.

2023-03-30 22:36 UTC, micaelcid commented
Can you guys @ricardoamador or @reidbaker add the auto-submit label?

2023-04-05 12:23 UTC, micaelcid commented
Hey, @goderbauer do you mind adding the auto submit label?

2023-04-11 22:22 UTC, merged