Allow multiple KeepAliveNotifications from the same KeepAliveHandle
flutter/flutter pull request #124168
Opened 2023-04-04 23:29 UTC by GregoryConrad

Previously, dispatching multiple `KeepAliveNotification`s would break an assert. However, the assert was faulty because this behavior should be allowed based on the documentation (i.e., should be able to dispatch a notification whenever you want a keep alive, perhaps once every build).

This PR was spun off of #123864.

CC @dnfield @Piinks

2023-04-10 19:29 UTC, Piinks reviewed
Hey @GregoryConrad thanks for this! Is there an open issue this is resolving?
Also, you mentioned this fixes a contradiction with the docs, can you share where that doc is?

2023-04-10 19:48 UTC, GregoryConrad commented
@Piinks No open issue for this other than that this fix is needed for #123864.

I think I actually got a [part of the docs](https://api.flutter.dev/flutter/widgets/KeepAliveNotification-class.html) confused; the current behavior is documented correctly and I'll update that bit within this PR. The reason for opening this PR, other than for #123864, is that the current behavior is unnecessarily restrictive in terms of when a notification can be sent. If you are reusing a handle, which the docs mention, it is often easiest from a developer's standpoint to just bubble up a notification whenever they want a keep alive than to think about when it must be done based on past occurrences. The current implementation forces you to have some mutability somewhere that you have to manage/keep track of; this PR removes that limitation. For a concrete example, previously, you could not fire a keep alive notification during every build in which you want a keep alive.

2023-04-24 22:10 UTC, dnfield requested changes
I appreciate the work and thought you've put into this area.

I'm really not clear on why this is an improvement for developers. It is more important that the KeepAlive related API be easy to use correctly rather than just outright easy to use. It's a bit of a tricky area, and it would be far better to make sure developers do not introduce additional overhead (in time or memory) than that they can more ergonomically use the API.

The test case added is not really a motivating case to support this change, and changing behavior like this may cause subtle and surprising breakages for developers who think they're getting covered by the current way of doing things via asserts only to find that they are not.

Since I do not believe we should land this change without significant discussion about its merits and the improvements it offers, I'm going to close the PR as well to remove it from review triage queues.

2023-04-24 22:10 UTC, dnfield commented on packages/flutter/test/widgets/automatic_keep_alive_test.dart
> +    _handle.dispose();
This isn't really the right time to dispose, is it?

2023-04-24 22:10 UTC, dnfield commented on packages/flutter/test/widgets/automatic_keep_alive_test.dart
> +    KeepAliveNotification(_handle).dispatch(context);
This is just bad practice. Code shouldn't do this and we shouldn't encourage code that does it.

2023-04-24 22:10 UTC, dnfield commented
Please feel free to reach out on discord if you want to discuss this further

2023-04-24 22:10 UTC, closed without merging

2023-04-25 03:42 UTC, dnfield commented on packages/flutter/test/widgets/automatic_keep_alive_test.dart
> +    KeepAliveNotification(_handle).dispatch(context);
More specifically: listeners to a change notifier aren't guaranteed to be cheap or idempotent.

2023-05-02 14:25 UTC, GregoryConrad commented
@dnfield How can I reach out to you on Discord? I joined the [Discord server mentioned here](https://flutter.dev/community) but I am not sure what your username is? Thanks.

2023-05-02 17:26 UTC, dnfield commented
The #hackers-framework channel would be most appropriate for this, my username on there is the same as here :) (dnfield)

2023-05-02 17:27 UTC, dnfield commented
https://discord.com/channels/608014603317936148/608021234516754444

2023-05-03 18:17 UTC, GregoryConrad commented
Discussed on discord; this PR will remain closed since notifications are O(n) and should only be sent when necessary.