fix RectangularRangeSliderTrackShape and RoundedRectRangeSliderTrackS…
flutter/flutter pull request #125483
Opened 2023-04-25 11:39 UTC by arvinwli

fix RectangularRangeSliderTrackShape and RoundedRectRangeSliderTrackShape. These two RangeSliderTrackShape do not take into account the width of RangeThumbShape. If the width of RangeThumbShape is larger than the width of OverlayShape, the RangeSlider will be drawn out of bounds and the display will not meet expectations. And the Slider trackShape calculation logic is in line with expectations, the modified reference BaseSliderTrackShape here, write a new BaseRangeSliderTrackShape

**BaseSliderTrackShape takes the width of the thumbShape into account when calculating 。left As follows**
<img width="994" alt="image" src="https://user-images.githubusercontent.com/13586150/234223975-7e6bd036-dbae-43a9-a1eb-03720a0b9591.png">
**But RoundedRectRangeSliderTrackShape did not consider rangeThumbShape RoundedRectRangeSliderTrackShape width, as follows**
<img width="963" alt="image" src="https://user-images.githubusercontent.com/13586150/234224673-b83247a8-7578-4361-932b-a5e714f96614.png">
**Therefore, the modification plan is:**
- Create BaseRangeSliderTrackShape reference BaseSliderTrackShape getPreferredRect**
- The core modification is to consider the width of rangeThumbShape when calculating the left of RangeSliderTrackShape

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/13586150/234226361-7a86294f-c359-4c8e-820d-cb5505459e61.png">

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/125467

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-04-26 14:09 UTC, TahaTesser requested changes
Thanks for the PR! This looks good to me with some format fixes

2023-04-26 14:09 UTC, TahaTesser commented on packages/flutter/test/material/slider_theme_test.dart
> +        ..rrect(rrect: RRect.fromLTRBAndCorners(
```suggestion
        // active track RRect. Starts 10 pixels from left of screen.
        ..rrect(rrect: RRect.fromLTRBAndCorners(
```

2023-04-27 01:28 UTC, arvinwli commented
@TahaTesser Thanks for these  format fixes. I have commit submitted these fixes

2023-04-27 12:32 UTC, TahaTesser approved these changes
LGTM

2023-04-27 17:55 UTC, Piinks approved these changes
![Flutter_LGTM](https://user-images.githubusercontent.com/16964204/169392212-02bb74fe-c6b9-4eb7-aa62-6ddb43a70d5b.png)

2023-04-27 18:10 UTC, werainkhatri approved these changes
LGTM! thanks for your contribution! nice work creating the mixin.

TIL dart supports writing a mixins to override inherited methods. wow.

2023-04-28 07:33 UTC, TahaTesser commented
Looks like even tho the tree is green, `autosubmit` doesn't merge the PR. Similar to this [case](https://github.com/flutter/flutter/pull/125599#issuecomment-1525387603)

2023-04-28 14:24 UTC, Piinks commented
Strange! What a stubborn bot. Merging!

2023-04-28 14:24 UTC, merged