Timely release the memory of unavailable images evicted by `imagecache`
flutter/flutter pull request #125614
Opened 2023-04-27 08:34 UTC by 0xZOne

Avoid additional keepalive to prevent memory release of unavailable images that have already been evicted by `ImageCache`.

Related issue: https://github.com/flutter/flutter/issues/125608

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-04-28 18:37 UTC, dnfield requested changes
This will not actually release memory.

In the case under test, the image render object is still in the tree holding onto the ui.Image.

2023-05-06 02:24 UTC, 0xZOne commented
> This will not actually release memory.
> 
> In the case under test, the image render object is still in the tree holding onto the ui.Image.

Actually, the image has already been evicted by `ImageCache` and is no longer available. We should dispose of it in time to release memory as soon as possible.

2023-05-16 22:16 UTC, goderbauer commented
(Triage) @0xZOne @dnfield Are there still plans for this PR?

2023-06-13 22:07 UTC, goderbauer commented
(Triage) Since there was no follow-up I am going to close this one. Feel free to reopen if you find the time to work on this again. Thank you for your contribution!

2023-06-13 22:07 UTC, closed without merging