Slider onChangeEnd is never called when arrow keys are used
flutter/flutter pull request #126896
Opened 2023-05-16 01:37 UTC by dleyba042

This PR makes changes to the _actionHandler function used on the Slider.Dart Widget for Key Events. It ensures onChangeStart is called at the beginning of a Key Event and onChangeEnd at the end of one. This PR includes a test for the changes made.
I ran all existing tests after my changes were made and they passed.

## Pre-launch Checklist

- [ X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [X ] I listed at least one issue that this PR fixes in the description above.
- [X ] I updated/added relevant documentation (doc comments with `///`).
- [ X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-05-16 11:26 UTC, TahaTesser commented
Hi @dleyba042 
Please note: https://github.com/flutter/flutter/issues/123315#issuecomment-1532966760

Thanks for attempting to fix this, however several issues in your implementation. 

Check out the [Style guide for Flutter repo](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) and see how `increaseAction` and `decreaseAction` is currently calling `onChanged`.

in order to fix this, first we need to move the `clampDouble`s  from `onChanged` to separate functions then reuse it for the callback including in the action handler. 

For tests, please check out other similar tests in the framework on how to title, format and test the functionality.

2023-05-22 12:50 UTC, TahaTesser commented
Hi @dleyba042 
Do you've plans to update this PR? :)

2023-05-22 19:53 UTC, dleyba042 commented
Hi @TahaTesser, yes, I made some changes based on your comments. I'm not sure at this time how to fix the Linux errors that are happening. If you wanted to use any part of what I have done in your fix, be my guest.

2023-05-23 14:17 UTC, TahaTesser commented
> Hi @dleyba042 Please note: [#123315 (comment)](https://github.com/flutter/flutter/issues/123315#issuecomment-1532966760)
> 
> Thanks for attempting to fix this, however several issues in your implementation.
> 
> Check out the [Style guide for Flutter repo](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo) and see how `increaseAction` and `decreaseAction` is currently calling `onChanged`.
> 
> in order to fix this, first we need to move the `clampDouble`s from `onChanged` to separate functions then reuse it for the callback including in the action handler.
> 
> For tests, please check out other similar tests in the framework on how to title, format and test the functionality.

As mentioned, these tests had several issues including some redundancy. Nevertheless given it is your first PR. I've fixed the tests for you.

2023-05-23 14:31 UTC, TahaTesser requested changes
I just pushed rewritten tests. Jus this extra space needs to be removed.

2023-05-23 14:31 UTC, TahaTesser requested changes
I just pushed rewritten tests. For this change, we don't need a new set of tests, the existing keyboard shortcuts are already testing `onChanged` callback. I just update these tests.

Finally, just this extra space needs to be removed.

2023-05-23 14:31 UTC, TahaTesser requested changes

2023-05-23 14:46 UTC, TahaTesser approved these changes
LGTM

2023-05-23 14:46 UTC, TahaTesser approved these changes
LGTM

2023-05-23 17:54 UTC, TahaTesser commented
@Piinks 
This needs a second review

2023-05-24 22:08 UTC, Piinks approved these changes
Hey @dleyba042, welcome! Thank you for contributing!
Appreciate the review @TahaTesser. This also LGTM! 🎉

2023-05-24 22:13 UTC, merged

2023-05-25 08:46 UTC, dleyba042 commented
@TahaTesser sorry for the slow response currently on vacation. Thank you for the input and the learning opportunity! Thanks @Piinks it was a great learning experience.