Adding ScrollController support for Stepper widget
flutter/flutter pull request #128814
Opened 2023-06-13 18:10 UTC by SwaroopSambhayya

This PR is to add **controller** property to the **Stepper** widget, so that user has the flexibility to control the scroll offset for various purposes(especially in case of scroll animations)!

Fixes #61207 

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-06-16 16:36 UTC, HansMuller reviewed
This looks like a reasonable change. Will need some fixups for the analyzer and test failures.

2023-06-17 14:54 UTC, SwaroopSambhayya commented
@HansMuller as I'm new can you point me to any docs to the fixups for analyser and test failures? seems the issue is not related to my change

2023-06-19 14:06 UTC, TahaTesser requested changes

2023-06-19 14:06 UTC, TahaTesser commented on packages/flutter/test/material/stepper_test.dart
> +  testWidgets('Vertical and Horizontal Stepper controller test', (WidgetTester tester) async {
```suggestion
  testWidgets('ScrollController is passed to the stepper listview', (WidgetTester tester) async {
```

2023-06-19 14:06 UTC, TahaTesser commented on packages/flutter/test/material/stepper_test.dart
> +      ScrollController controller = ScrollController();
Analyzer is failing here
```suggestion
      final ScrollController controller = ScrollController();
```

2023-06-19 16:11 UTC, SwaroopSambhayya commented on packages/flutter/test/material/stepper_test.dart
> +      ScrollController controller = ScrollController();
Okay got it! thanks

2023-06-19 17:09 UTC, SwaroopSambhayya commented on packages/flutter/test/material/stepper_test.dart
> +  testWidgets('Vertical and Horizontal Stepper controller test', (WidgetTester tester) async {
Added the change

2023-06-19 17:09 UTC, SwaroopSambhayya commented on packages/flutter/test/material/stepper_test.dart
> +      ScrollController controller = ScrollController();
Added the change

2023-06-19 17:09 UTC, SwaroopSambhayya commented on packages/flutter/test/material/stepper_test.dart
> +        final ListView listView = tester.widget<ListView>(find.descendant(of: find.byType(Stepper), matching: find.byType(ListView)));
Added change

2023-06-20 07:53 UTC, TahaTesser requested changes
Updating docs to be consistent

2023-06-20 07:53 UTC, TahaTesser commented on packages/flutter/lib/src/material/stepper.dart
> +  final ScrollController? controller;
```suggestion
  /// An object that can be used to control the position to which this scroll
  /// view is scrolled.
  ///
  /// To control the initial scroll offset of the scroll view, provide a
  /// [controller] with its [ScrollController.initialScrollOffset] property set.
  final ScrollController? controller;
```

2023-06-20 07:54 UTC, TahaTesser approved these changes
LGTM!

This will need a second review from @HansMuller before landing.

2023-06-20 16:04 UTC, merged