Make new issue template for 1P package
flutter/flutter pull request #130065
Opened 2023-07-06 12:19 UTC by huycozy

Closes https://github.com/flutter/flutter/issues/117750.

### Demo
<details>
<summary>Preview screenshot</summary>

![screenshot](https://github.com/flutter/flutter/assets/104349824/40968935-b898-4303-b3ee-08abed94f6eb)
</details>

Demo issue template: [Report a bug in Flutter's first party package](https://github.com/huycozy/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml)
Demo a filed issue: https://github.com/huycozy/flutter/issues/2

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-07-07 17:02 UTC, stuartmorgan requested changes
Looks good! I have some small comments, and we may have to iterate as we see how people handle the new structure in practice, but it should definitely help guide people to some common points (like upgrading packages).

2023-07-11 11:07 UTC, huycozy commented on .github/ISSUE_TEMPLATE/9_first_party_packages.yml
> +  You found a bug in Flutter's first party package causing your application to crash or
I thought this sentence could be substituted: **You found a bug in one of Flutter's first-party packages, resulting in your application experiencing unexpected behavior.**

But it seems a bit redundant in the "reporting a bug" context. So I will shorten this sentence. Hope it's ok :)

2023-07-11 11:07 UTC, huycozy commented on .github/ISSUE_TEMPLATE/9_first_party_packages.yml
> +        - xdg_directories
Yes. Added these packages to the dropdown. But we don't have labels for these packages yet. May I create them?

2023-07-11 11:13 UTC, huycozy commented
Thank you for the comments. Demo of the changes I pushed:

<details>
<summary>Demo preview screenshot</summary>

![screenshot (1)](https://github.com/flutter/flutter/assets/104349824/f1dfbd6c-6edb-464e-94f1-ab65f1d08ac7)

</details>

Demo issue template: [Report a bug in one of Flutter's first-party packages](https://github.com/huycozy/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml)

2023-07-11 14:12 UTC, stuartmorgan approved these changes
LGTM with one last nit, thanks for doing this!

> Demo issue template: [Report a bug in one of Flutter's first-party packages](https://github.com/huycozy/flutter/issues/new?assignees=&labels=&projects=&template=9_first_party_packages.yml)

This was really helpful :)

2023-07-11 14:12 UTC, stuartmorgan commented on .github/ISSUE_TEMPLATE/9_first_party_packages.yml
> +      label: Have you already upgraded the package?
Let's actually change this to "upgraded your packages", since in a number of cases what's needed is updates to transitive dependencies, rather than the specific package they are reporting an issue with.

2023-07-11 16:42 UTC, huycozy commented on .github/ISSUE_TEMPLATE/9_first_party_packages.yml
> +      label: Have you already upgraded the package?
Updated this :)

2023-07-12 07:47 UTC, merged