Fix material date picker changing year behavior
flutter/flutter pull request #130486
Opened 2023-07-13 10:09 UTC by Lexycon

This PR changes the CalendarDatePicker behavior when changing the year so that it matches the native android picker.
When selecting another year in the native android picker, the same day will be selected (by respecting the boundaries of the date picker).
The current CalendarDatePicker does not change the selected day when changing the year. This will lead to confusing if you press OK and the date does not change to the new year.

This is now changed. It will try to preselect the day like the native android picker behaves:
 - respecting the boundaries of the date picker (firstDate, lastDate)
 - changing from leapyear 29th february will set 28th february if not a leapyear is selected
 - only set the day if it is selectable (selectableDayPredicate)

The calendar shown in the recording was setup with this parameters:
```
firstDate: DateTime(2016, DateTime.june, 9),
initialDate: DateTime(2018, DateTime.may, 4),
lastDate: DateTime(2021, DateTime.january, 15),
```
 
https://github.com/flutter/flutter/assets/13588771/3041c296-b9d0-4078-88cd-d1135fc343b3

#81547 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-07-21 23:44 UTC, HansMuller approved these changes
Looks like a good fix. @TahaTesser - please take a look

2023-07-24 09:04 UTC, TahaTesser requested changes
Minor nits

2023-07-24 09:04 UTC, TahaTesser commented on packages/flutter/lib/src/material/calendar_date_picker.dart
> +    value = DateTime(value.year, value.month, preferredDay);
```suggestion
    value = value.copyWith(day: preferredDay);
```

2023-07-24 09:04 UTC, TahaTesser commented on packages/flutter/lib/src/material/calendar_date_picker.dart
> +        widget.selectableDayPredicate!.call(date);
```suggestion
    return widget.selectableDayPredicate == null || widget.selectableDayPredicate!.call(date);
```

2023-07-24 09:54 UTC, TahaTesser approved these changes
LGTM

2023-07-24 16:03 UTC, merged