Use utf8.encode() instead of longer const Utf8Encoder.convert()
flutter/flutter pull request #130567
Opened 2023-07-14 09:07 UTC by mkustermann

The change in [0] has propagated now everywhere, so we can use `utf8.encode()` instead of the longer `const Utf8Encoder.convert()`.

Also it cleans up code like

```
  TypedData bytes;
  bytes.buffer.asByteData();
```

as that is not guaranteed to be correct, the correct version would be

```
  TypedData bytes;
  bytes.buffer.asByteData(bytes.offsetInBytes, bytes.lengthInBytes);
```

a shorter hand for that is:

```
  TypedData bytes;
  ByteData.sublistView(bytes);
```

[0] https://github.com/dart-lang/sdk/issues/52801

2023-07-14 12:13 UTC, sstrickl requested changes

2023-07-14 12:13 UTC, sstrickl commented on packages/flutter/lib/src/services/asset_bundle.dart
> +  /// using [ByteData.sublistView]. Lists of bytes can be used with APIs that
```suggestion
  /// using [Uint8List.sublistView]. Lists of bytes can be used with APIs that
```

2023-07-14 12:24 UTC, mkustermann commented on packages/flutter/lib/src/services/asset_bundle.dart
> +  /// using [ByteData.sublistView]. Lists of bytes can be used with APIs that
Thanks, Done!

2023-07-14 12:41 UTC, sstrickl approved these changes

2023-07-18 21:57 UTC, goderbauer commented
(Triage): @mkustermann Is this ready to be submitted?

2023-07-24 09:25 UTC, mkustermann commented
> (Triage): @mkustermann Is this ready to be submitted?

Yes. Merging.

(Apologies, I was a few days OOO)

2023-07-24 09:26 UTC, merged