Fix SubTitleTextStyle For ListTile
flutter/flutter pull request #133422
Opened 2023-08-28 01:35 UTC by burakJs

The difference between header text style and subtitle text style and the reason why it doesn't work is the code difference below. If we make the subtitle text style the same as the title text style it will work

<details>
  <summary>Title Text Style</summary>
  
  ###  All Code
  
  ```dart
  TextStyle titleStyle = titleTextStyle
      ?? tileTheme.titleTextStyle
      ?? defaults.titleTextStyle!;
    final Color? titleColor = effectiveColor;
    titleStyle = titleStyle.copyWith(
      color: titleColor,
      fontSize: _isDenseLayout(theme, tileTheme) ? 13.0 : null,
    );
    final Widget titleText = AnimatedDefaultTextStyle(
      style: titleStyle,
      duration: kThemeChangeDuration,
      child: title ?? const SizedBox(),
    );
  ```
  
  ## Different Code Section
  
  ```dart
  final Color? titleColor = effectiveColor;
  ```
</details>

<details>
  <summary>Subtitle Text Style</summary>
  
  ## All Code
  
  ```dart
  subtitleStyle = subtitleTextStyle
        ?? tileTheme.subtitleTextStyle
        ?? defaults.subtitleTextStyle!;
      final Color? subtitleColor = effectiveColor
        ?? (theme.useMaterial3 ? null : theme.textTheme.bodySmall!.color);
      subtitleStyle = subtitleStyle.copyWith(
        color: subtitleColor,
        fontSize: _isDenseLayout(theme, tileTheme) ? 12.0 : null,
      );
      subtitleText = AnimatedDefaultTextStyle(
        style: subtitleStyle,
        duration: kThemeChangeDuration,
        child: subtitle!,
      );
  ```
  
  ## Different Code Section
  
  ```dart
  final Color? subtitleColor = effectiveColor
        ?? (theme.useMaterial3 ? null : theme.textTheme.bodySmall!.color);
  ```
</details>

<details>
  <summary>Problem solved code</summary>
  
  ## All Code
  
  ```dart
  subtitleStyle = subtitleTextStyle
        ?? tileTheme.subtitleTextStyle
        ?? defaults.subtitleTextStyle!;
      final Color? subtitleColor = effectiveColor;
      subtitleStyle = subtitleStyle.copyWith(
        color: subtitleColor,
        fontSize: _isDenseLayout(theme, tileTheme) ? 12.0 : null,
      );
      subtitleText = AnimatedDefaultTextStyle(
        style: subtitleStyle,
        duration: kThemeChangeDuration,
        child: subtitle!,
      );
  ```
</details>

<details>
<summary>Screenshot of the result after making the necessary change</summary>
<img src="https://github.com/flutter/flutter/assets/70351342/b552fd4c-fdcd-4bf5-b4ba-d6b2cfe527cc" width=250>
</details>

#133412

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-08-28 15:49 UTC, burakJs commented
> It looks like there are some test failures.

I'm investigating and will let you know as soon as possible.

2023-08-28 20:01 UTC, burakJs commented
I couldn't find a correlation between where I made code changes and tests that failed. Can you take a look please @TahaTesser

2023-08-30 07:12 UTC, TahaTesser commented
This was effectively only updated for Material 3 without changing the M2 behavior.
 
This way can have the correct color applied in M3 without breaking existing tests and apps.
```dart
      final Color? subtitleColor = effectiveColor
        ?? (theme.useMaterial3 ? null : theme.textTheme.bodySmall!.color);
```

It looks like your change for M2 is breaking some customer tests.

```console
| 00:18 +78 ~1: /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.OTZXUG/tests/packages/rfw/test/material_widgets_test.dart: Material widgets
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following assertion was thrown while running async test code:
| Golden "goldens/material_test.drawer.png": Pixel test failed, 1.02% diff detected.
| Failure feedback can be found at
| /b/s/w/ir/x/t/flutter_customer_testing.flutter_packages.OTZXUG/tests/packages/rfw/test/failures
```

 Material 2 will eventually be deprecated and this issue will become irrelevant. 


cc: @HansMuller

2023-08-30 15:27 UTC, burakJs commented
```dart
final Color? subtitleColor = effectiveColor
    ?? (theme.useMaterial3 ? null : theme.textTheme.bodySmall!.color);
```

- So why do we change the color property of the subtitleTextStyle given by the user in this code?

2023-08-31 08:53 UTC, TahaTesser commented
> ```dart
> final Color? subtitleColor = effectiveColor
>     ?? (theme.useMaterial3 ? null : theme.textTheme.bodySmall!.color);
> ```
> 
> * So why do we change the color property of the subtitleTextStyle given by the user in this code?

`textColor` & `selectedColor` overrides both `titleTextStyle` & `subtitleTextStyle`, that's `effectiveColor`


If both `text` & `selectedColor` are null, we default to a `null` value so the recently added `subtitleTextStyle`'s color can be used only for M3 and we default `bodySmall` color`  for backward compatibility. 

`bodySmall!.color` has been used for the subtitle in M2 as the default color and you're changing this default behavior hence the test issues.

If we still want the `subtitleTextStyle` color fo the M2 we can do this without the changing M2 default. Please apply the I suggested and revert the default test update.

2023-08-31 08:58 UTC, TahaTesser requested changes

2023-08-31 08:58 UTC, TahaTesser commented on packages/flutter/lib/src/material/list_tile.dart
> +      final Color? subtitleColor = effectiveColor;
Please apply this fix.
```dart
    if (subtitle != null) {
      subtitleStyle = subtitleTextStyle ?? tileTheme.subtitleTextStyle;
      if (theme.useMaterial3) {
        subtitleStyle = (subtitleStyle ?? defaults.subtitleTextStyle)!.copyWith(
          color: effectiveColor,
          fontSize: _isDenseLayout(theme, tileTheme) ? 12.0 : null,
        );
      } else {
        subtitleStyle = subtitleTextStyle?.copyWith(
          color: effectiveColor,
          fontSize: _isDenseLayout(theme, tileTheme) ? 12.0 : null,
        );
        subtitleStyle ??= defaults.subtitleTextStyle!.copyWith(
          color: effectiveColor ??  theme.textTheme.bodySmall!.color,
          fontSize: _isDenseLayout(theme, tileTheme) ? 12.0 : null,
        );
      }
      subtitleText = AnimatedDefaultTextStyle(
        style: subtitleStyle,
        duration: kThemeChangeDuration,
        child: subtitle!,
      );
    }
```

2023-08-31 08:58 UTC, TahaTesser commented on packages/flutter/test/material/list_tile_test.dart
> +      expect(subtitle.text.style!.color, theme.textTheme.bodyMedium!.color);
Please revert this default test update.
```suggestion
      expect(subtitle.text.style!.color, theme.textTheme.bodySmall!.color);
```

2023-08-31 08:58 UTC, TahaTesser commented on packages/flutter/test/material/list_tile_test.dart
> +      expect(subtitle.text.style!.color, theme.textTheme.bodyMedium!.color);
```suggestion
      expect(subtitle.text.style!.color, theme.textTheme.bodySmall!.color);
```

2023-08-31 12:21 UTC, burakJs commented
I will make changes and corrections as soon as possible. Thanks for the help and detailed explanation.

2023-09-01 00:11 UTC, burakJs commented
- I made all the changes you mentioned.
- All tests in `list_tile_theme_test .dart` file pass

<img width="1068" alt="image" src="https://github.com/flutter/flutter/assets/70351342/c65d9f2f-d5dc-47d8-a5f7-7b035d82826d">

- Only Linux `web_canvaskit_tests_6` gives test timeout error

2023-09-01 14:56 UTC, TahaTesser commented
Hey @burakJs 
Since you're a new contributor.  I've improved tests for M3 and added tests for the M2 for this PR.  
I also updated the fix itself to be much more straightforward and pushed changes myself.
I'd advise you to take a look at the changes I've made for future potential PRs.

Thank you for raising this PR.

2023-09-01 15:17 UTC, TahaTesser approved these changes
LGTM

2023-09-01 15:18 UTC, TahaTesser commented
This will need a second review from @HansMuller before we land.

2023-09-06 18:53 UTC, HansMuller approved these changes
LGTM

2023-09-06 18:54 UTC, merged