[CheckedPopupMenuItem] onTap & textStyle props
flutter/flutter pull request #134000
Opened 2023-09-04 20:56 UTC by piedcipher

Adds parent props `onTap` & `textStyle` to CheckedPopupMenuItem.

Fixes #127800

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-09-04 21:50 UTC, piedcipher commented
Something flaky in `<platform>_customer_testing` 🤔

2023-09-05 11:53 UTC, TahaTesser requested changes

2023-09-05 11:53 UTC, TahaTesser commented on packages/flutter/test/material/popup_menu_test.dart
> +  testWidgets('Material2 - CheckedPopupMenuItem honors textStyle', (WidgetTester tester) async {
```suggestion
  testWidgets('Material2 - CheckedPopupMenuItem honors textStyle', (WidgetTester tester) async {
```

We can remove the test as well

2023-09-05 11:54 UTC, TahaTesser commented
> Something flaky in `<platform>_customer_testing` 🤔

Thanks for the PR! Yes, it is unrelated to this PR.

I've provided suggestions

2023-09-05 12:20 UTC, piedcipher commented on packages/flutter/test/material/popup_menu_test.dart
> +  testWidgets('Material2 - CheckedPopupMenuItem honors textStyle', (WidgetTester tester) async {
Sure

2023-09-05 12:20 UTC, piedcipher commented on packages/flutter/lib/src/material/popup_menu.dart
> +    super.textStyle,
Sure

2023-09-05 12:21 UTC, piedcipher commented
> > Something flaky in `<platform>_customer_testing` 🤔
> 
> Thanks for the PR! Yes, it is unrelated to this PR.
> 
> I've provided suggestions

Cool, thanks for the review! I'll work on the suggestions.

2023-09-05 12:24 UTC, piedcipher commented on packages/flutter/lib/src/material/popup_menu.dart
> +    super.textStyle,
Done 👍✅

2023-09-05 18:49 UTC, piedcipher commented on packages/flutter/test/material/popup_menu_test.dart
> +  testWidgets('CheckedPopupMenuItem.onTap callback is called when defined', (WidgetTester tester) async {
Done 👍✅

2023-09-05 18:49 UTC, piedcipher commented
> > Something flaky in `<platform>_customer_testing` 🤔
> 
> Thanks for the PR! Yes, it is unrelated to this PR.
> 
> I've provided suggestions

Implemented all the suggestions! Please have a look. Thanks again for the review 👍

2023-09-06 13:45 UTC, TahaTesser requested changes

2023-09-06 13:45 UTC, TahaTesser commented on packages/flutter/test/material/popup_menu_test.dart
> +  });
```suggestion
  testWidgets('CheckedPopupMenuItem.onTap callback is called when defined', (WidgetTester tester) async {
    int count = 0;
    await tester.pumpWidget(
      TestApp(
        textDirection: TextDirection.ltr,
        child: Material(
          child: RepaintBoundary(
            child: PopupMenuButton<String>(
              child: const Text('button'),
              itemBuilder: (BuildContext context) {
                  return  <PopupMenuItem<String>>[
                  CheckedPopupMenuItem<String>(
                    onTap: () {
                      count += 1;
                    },
                    value: 'item1',
                    child: const Text('Item with onTap'),
                  ),
                  const CheckedPopupMenuItem<String>(
                    value: 'item2',
                    child: Text('Item without onTap'),
                  ),
                ];
              },
            ),
          ),
        ),
      ),
    );

    // Tap a checked menu item with onTap.
    await tester.tap(find.text('button'));
    await tester.pumpAndSettle();
    await tester.tap(find.widgetWithText(CheckedPopupMenuItem<String>, 'Item with onTap'));
    await tester.pumpAndSettle();
    expect(count, 1);

    // Tap a checked menu item without onTap.
    await tester.tap(find.text('button'));
    await tester.pumpAndSettle();
    await tester.tap(find.widgetWithText(CheckedPopupMenuItem<String>, 'Item without onTap'));
    await tester.pumpAndSettle();
    expect(count, 1);
  });
```

2023-09-06 13:45 UTC, TahaTesser commented on packages/flutter/test/material/popup_menu_test.dart
> +  });
Just minor tweaks

2023-09-06 13:47 UTC, TahaTesser approved these changes
LGTM

2023-09-06 17:28 UTC, HansMuller approved these changes
LGTM

2023-09-06 18:33 UTC, merged