✨ `flutter config --list`
flutter/flutter pull request #135401
Opened 2023-09-25 05:33 UTC by AlexV525

Resolves #81831.

The PR improves the `config` command in below ways:
- Does not print the settings in usages or other options.
- Adds the `--list` flag to print the full settings list.
- Separates usages for settings and analytics.
- Prints the restart tip when clearing features.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2023-09-25 16:28 UTC, christopherfujino approved these changes
LGTM

2023-09-25 17:51 UTC, andrewkolos requested changes
Requested one small change. Otherwise LGTM

2023-09-25 17:51 UTC, andrewkolos commented on packages/flutter_tools/lib/src/commands/config.dart
> +    argParser.addFlag('list', help: 'List all settings and their current values.');
Consider adding `negatable: false`, since `--no-list` doesn't make sense as an option.

2023-09-25 22:17 UTC, AlexV525 commented on packages/flutter_tools/lib/src/commands/config.dart
> +    argParser.addFlag('list', help: 'List all settings and their current values.');
Done.

2023-09-25 22:18 UTC, AlexV525 commented
Google tests are still failing because of merge commits. I thought it was maximum retries limit but it seems not. @christopherfujino @andrewkolos Could you help with resolving it?

2023-09-26 17:58 UTC, christopherfujino commented
Hmm, it says "manual started" now (but no link to results). I will give it some more time and if by the end of the day there are no test results, I will override the status. Please don't merge upstream in again unless there is a merge conflict (as it will re-trigger testing).

Also @andrewkolos please give this another review.

2023-09-27 02:20 UTC, AlexV525 commented
Now it's `Please rebase your PR to tip of tree. Your PR is out of date`.

2023-09-27 07:00 UTC, andrewkolos approved these changes
LGTM

2023-09-27 07:02 UTC, merged