Cover more test/material tests with leak tracking.
flutter/flutter pull request #136093
Opened 2023-10-06 21:08 UTC by ksokolovskyi

### Description
This PR changes `testWidgets` by `testWidgetsWithLeakTracking` in number of `flutter/test/material` tests according to the https://github.com/dart-lang/leak_tracker/issues/134.

### Tests
- Updates `animated_size_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `framework_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `html_element_view_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `list_wheel_scroll_view_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `navigator_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `overlay_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `router_restoration_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `scrollable_test.dart` to use `testWidgetsWithLeakTracking`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

2023-10-06 21:55 UTC, ksokolovskyi commented
cc @polina-c

2023-10-10 15:28 UTC, polina-c commented on packages/flutter/test/material/text_field_test.dart
> +    await tester.pump(const Duration(milliseconds: 150));
The same

2023-10-10 15:28 UTC, polina-c commented on packages/flutter/test/material/text_field_test.dart
> +    await tester.pump(const Duration(milliseconds: 150));
And here.

2023-10-10 15:29 UTC, polina-c commented on packages/flutter/test/material/text_field_test.dart
> +    await tester.pump(const Duration(milliseconds: 150));
Here too.

2023-10-10 15:29 UTC, polina-c requested changes
Some comments.

2023-10-10 15:58 UTC, polina-c approved these changes

2023-10-10 16:01 UTC, ksokolovskyi commented
@polina-c, thanks a lot for the review!

2023-10-10 17:05 UTC, merged