Fix memory leaks in DateRangePickerDialog.
flutter/flutter pull request #136034
Opened 2023-10-05 14:07 UTC by ksokolovskyi

This PR mainly fixes several memory leaks in the `DateRangePickerDialog`.

### Description
- Fixes https://github.com/flutter/flutter/issues/136033 by:
    1) adding a disposal of several `RestorableValue`;
    2) creating a separate `_DayItem` stateful widget that creates/updates/disposes internal `MaterialStatesController`.
- Fixes non-disposal of `AnnotatedRegionLayer` in `RenderAnnotatedRegion`, which was detected by the test given in https://github.com/flutter/flutter/issues/136033.

### Tests
- Updates `test/material/date_picker_theme_test.dart` to use `testWidgetsWithLeakTracking`;
- Updates `test/material/date_range_picker_test.dart` to use `testWidgetsWithLeakTracking`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] All existing and new tests are passing.

2023-10-05 14:19 UTC, TahaTesser requested changes

2023-10-05 14:19 UTC, TahaTesser commented on packages/flutter/lib/src/rendering/proxy_box.dart
> +       _handle = LayerHandle<AnnotatedRegionLayer<T>>(),
`RenderAnnotatedRegion` change is unrelated to ` DateRangePickerDialog`. Consider splitting this change into a seperate PR with `RenderAnnotatedRegion` specific tests.

2023-10-05 14:58 UTC, ksokolovskyi commented
cc @polina-c

2023-10-05 18:23 UTC, polina-c approved these changes

2023-10-05 18:27 UTC, polina-c commented
LGTM. I would like @TahaTesser 's lgtm before merging this.

2023-10-06 07:18 UTC, TahaTesser approved these changes
LGTM!

2023-10-06 11:26 UTC, merged