Support --web-header option for flutter run
flutter/flutter pull request #136297
Opened 2023-10-10 23:26 UTC by aran

Adds support for a new --web-header option to flutter run.

Fixes https://github.com/flutter/flutter/issues/127902

This PR is a proof of concept to add additional headers for the flutter run web server. This is useful to add headers like Cross-Origin-Embedder-Policy and Cross-Origin-Opener-Policy without the use of a proxy server. These headers are required enable advanced web features. This approach provides flexibility to the developer to make use of the feature as they see fit and is backward-compatible. One tradeoff is that it increases the surface area to support for future changes to the flutter web server.

I don't know what kind of test the team would like to see for this change.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

2023-10-11 22:00 UTC, michaelnew commented
For whatever it's worth, I just tested this out with `--web-header=Cross-Origin-Opener-Policy=same-origin --web-header=Cross-Origin-Embedder-Policy=require-corp`, and that's allowed me to use sqlite3 wasm with the OPFS to read/write to a sqlite database in the browser. Previously I had to build for web and then host with my own server that set those headers, but now I can run with the debugger attached.

Huge win for me, so thank you for this PR. I hope it gets merged soon!

2023-10-13 19:31 UTC, andrewkolos requested changes
Thanks for the PR!

The intent of this looks good to me from a CLI tool perspective. Please update [this test](https://github.com/flutter/flutter/blob/daea6e00bfc0452cbd3b1c46f3dd2d41a05da0a7/packages/flutter_tools/test/commands.shard/hermetic/run_test.dart#L1080) and add a test for a case where the user provides an invalid header and a tool exit gets thrown. I will be adding another reviewer shortly

2023-10-13 19:39 UTC, andrewkolos commented
@eyebrowsoffire Can you review this from a web perspective and make sure this is an appropriate resolution for #127902 ? Also, if you happen to know of an existing integration test that this feature could be added to, please let us know; it would be nice to have this under test end-to-end.

2023-10-13 23:45 UTC, aran commented on packages/flutter_tools/lib/src/runner/flutter_command.dart
> +      splitCommas: false,
It probably won't make a difference in the real world, but unless I'm mistaken commas and equal-signs are allowed in http header values. One of the test cases I'm adding will discriminate this edge case.

2023-10-16 16:36 UTC, eyebrowsoffire approved these changes
Looks good to me. As discussed on Discord, I don't believe this is a full resolution to https://github.com/flutter/flutter/issues/127902 and we should not close that issue based on just this PR. I think we need more specific and turnkey handling of the CORS headers needed for `crossOriginIsolated` rather than a generic mechanism like this. Nonetheless, this change seems good to me and will be generally useful for end users.

2023-10-16 21:11 UTC, andrewkolos commented
Thanks @eyebrowsoffire!

@aran, I've pushed some changes which simply move and rename the tests to be more consistent with the general pattern found throughout the rest of the CLI tool test code.

I also made some of the `throwsToolExit` checks more strict by adding error message checks. Upon doing this, I noticed some of the `ToolExit`s being thrown weren't the ones we were actually testing for, so I tweaked some of the test setup to resolve this. Feel free to make additional tweaks.

2023-10-16 21:13 UTC, andrewkolos approved these changes
LGTM. I will merge this after CI checks pass and @aran has had ample time to respond to my latest commits should they choose to do so

2023-10-17 16:27 UTC, aran commented
Great collaborating with you on this, thanks for all the help and for taking this change.

2023-10-17 19:32 UTC, andrewkolos commented
> Great collaborating with you on this, thanks for all the help and for taking this change.

Likewise; thanks for your efforts and contribution!

2023-10-17 19:42 UTC, merged