Support wireless debugging for iOS 12 or earlier
flutter/flutter pull request #141439
Opened 2024-01-12 07:44 UTC by jaeyoi

`idevicesyslog` requires the `--network` flag to obtain logs for iOS devices when wirelessly paired. 

When running Flutter on devices with iOS 12 or earlier versions, [the `idevicesyslog` command is used.](https://github.com/flutter/flutter/blob/5931b4f21da0c564b28794f40257b5f660596a3e/packages/flutter_tools/lib/src/ios/devices.dart#L1269-L1277).

Related Issue: #15072
Related PRs: #118104, #118895, #60623

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2024-01-19 18:53 UTC, vashworth commented on packages/flutter_tools/test/general.shard/ios/mac_test.dart
> +        ));
The Flutter Style Guide now recommends [avoiding the use of `setUp`](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#make-each-test-entirely-self-contained).

Try this instead:

```suggestion
      testWithoutContext('starts idevicesyslog when USB connected', () async {
        final FakeProcessManager fakeProcessManager = FakeProcessManager.list(
          <FakeCommand>[
            const FakeCommand(
              command: <String>['HostArtifact.idevicesyslog', '-u', '1234'],
              environment: <String, String>{
                'DYLD_LIBRARY_PATH': '/path/to/libraries'
              },
            ),
          ],
        );
```

2024-01-19 18:57 UTC, vashworth requested changes
Thanks for contributing! Requested a small change to the test, but other than that, looks good!

Just curious, were you able to test with an actual iOS 12 device?

2024-01-19 18:57 UTC, vashworth commented on packages/flutter_tools/test/general.shard/ios/mac_test.dart
> +        ));
The Flutter Style Guide now recommends [avoiding the use of `setUp`](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#make-each-test-entirely-self-contained).

Try this instead:

```suggestion
      testWithoutContext('starts idevicesyslog when USB connected', () async {
        final FakeProcessManager fakeProcessManager = FakeProcessManager.list(
          <FakeCommand>[
            const FakeCommand(
              command: <String>['HostArtifact.idevicesyslog', '-u', '1234'],
              environment: <String, String>{
                'DYLD_LIBRARY_PATH': '/path/to/libraries'
              },
            ),
          ],
        );
```

2024-01-19 18:57 UTC, vashworth commented on packages/flutter_tools/test/general.shard/ios/mac_test.dart
> +        ));
Same as comment above.

2024-01-20 08:39 UTC, jaeyoi commented
@vashworth 
Thank you for the kind review. I have modified the code according to your comments.

> Just curious, were you able to test with an actual iOS 12 device?

I have successfully tested it using iPhone 5S (iOS 12.5.7).

2024-01-22 15:30 UTC, vashworth approved these changes
Thanks for the changes!

2024-01-24 22:02 UTC, jmagman approved these changes
LGTM, thanks for the contribution!

2024-01-24 22:14 UTC, merged