Update Flutter Gallery Xcode project to a publishable state
flutter/flutter pull request #14309
Opened 2018-01-27 01:53 UTC by xster

#14305

2018-01-27 01:55 UTC, xster commented
Fixes #13237

2018-01-27 01:59 UTC, cbracken approved these changes

2018-01-28 16:43 UTC, jacob-greenfield requested changes
@xster @cbracken Could you also add these changes to flutter/packages/flutter_tools/templates/create? Currently all iOS builds using the default icon have the following warning:

    ./AppIcon.appiconset: warning: A 1024x1024 app store icon is required for iOS apps

I was just going to make this into an issue, but figured I could post it here instead.

2018-01-29 09:13 UTC, xster commented
@Coder-256: I did :D

2018-01-29 09:14 UTC, merged