Fix multiple calls to Slider's onChanged.
flutter/flutter pull request #143680
Opened 2024-02-19 04:44 UTC by yiiim

Fixes #143524 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2024-03-01 14:18 UTC, TahaTesser requested changes
Nice fix, thanks for the contribution.

2024-03-01 14:18 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +
```suggestion

  // This is a regression test for https://github.com/flutter/flutter/issues/143524.
```

2024-03-01 14:18 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +  testWidgets('Slider.onChanged is called only once', (WidgetTester tester) async {
```suggestion
  testWidgets('Slider.onChanged with divisions is called only once', (WidgetTester tester) async {
```

2024-03-01 14:18 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +    );
```suggestion
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: Slider(
              max: 5,
              divisions: 5,
              value: 0,
              onChanged: (double newValue) {
                onChangeCallbackCount++;
              },
            ),
          ),
        ),
      ),
    );

```

2024-03-01 14:18 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +    await gesture.moveBy(const Offset(1, 0));
```suggestion
    await gesture.moveBy(const Offset(160.0, 0.0));
    await gesture.moveBy(const Offset(1.0, 0.0));
    await gesture.moveBy(const Offset(1.0, 0.0));
```

2024-03-01 14:19 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +    );
We can omit `LayoutBuilder` layout and add a new line at the bottom. between this and `gesture` line.

2024-03-01 14:20 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +  testWidgets('Slider.onChanged is called only once', (WidgetTester tester) async {
Since the fix is for discrete `Slider`.

2024-03-04 12:05 UTC, TahaTesser requested changes

2024-03-04 12:05 UTC, TahaTesser commented on packages/flutter/lib/src/material/slider.dart
> +  // For discrete sliders, [_handleChanged] might receive the same value
The variable and _handleChanged are private so we don't need the brackets.

2024-03-04 12:05 UTC, TahaTesser commented on packages/flutter/lib/src/material/slider.dart
> +  // multiple times. To avoid calling [widget.onChanged] repeatedly, the
Same here

2024-03-05 10:10 UTC, TahaTesser approved these changes
LGTM!

2024-03-05 10:11 UTC, TahaTesser commented
We'll need a second review from @Piinks before we land this.

2024-03-08 19:18 UTC, Piinks reviewed
![Flutter_LGTM](https://user-images.githubusercontent.com/16964204/169392212-02bb74fe-c6b9-4eb7-aa62-6ddb43a70d5b.png)

Thank you both!

2024-03-09 07:50 UTC, merged