Fix ExpandIcon color when ExpansionPanel.canTapOnHeader true (#147097)
flutter/flutter pull request #147098
Opened 2024-04-20 01:31 UTC by BenjiFarquhar

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

2024-04-25 14:40 UTC, TahaTesser commented
Hi @BenjiFarquhar 
Does this fix https://github.com/flutter/flutter/issues/147097 using `IgnorePointer`?

Looks like this PR is failing some checks and missing test.

2024-04-25 16:22 UTC, BenjiFarquhar commented
Hi @TahaTesser. Cheers for reviewing. Yeah, it fixes the issue, as the 'onPressed' is never null now,which is what was causing the disabled appearance.

Hmmm yeah, I figured the tests were failing due to something unrelated, and wasn't sure if I'd need a test for this as it would kinda be testing if 'IgnorePointer' works which would already be tested. Do you think it should have a test?

2024-04-26 07:29 UTC, TahaTesser commented
>  Do you think it should have a test?

Yes please, bug fixes always need test(s).

2024-05-06 07:00 UTC, BenjiFarquhar commented
@TahaTesser Do you mean a golden test?

2024-05-06 07:25 UTC, BenjiFarquhar commented
@TahaTesser A widget test cannot verify the disabled color is not displayed, as  `ExpandIcon.color` always has the enabled color value even if it is not the displayed color due to onPressed being null. I can look into the trailing space issue soon.

2024-05-06 09:18 UTC, TahaTesser commented
> @TahaTesser A widget test cannot verify the disabled color is not displayed, as `ExpandIcon.color` always has the enabled color value even if it is not the displayed color due to onPressed being null. I can look into the trailing space issue soon.

I can help you with writing test.  However, can you explain how this fixes the expand icon color when adding `IgnorePointer` widget? 

Running your code sample with the fix, i see no difference in the expand icon color.

![Screenshot 2024-05-06 at 12 17 07](https://github.com/flutter/flutter/assets/48603081/98981c60-17c7-4875-94fc-12f4a7a668ff)

2024-05-06 16:59 UTC, BenjiFarquhar commented
Cheers. I don't think you have my changes as I get this result:

<img width="768" alt="Screenshot 2024-05-07 at 4 42 42 AM" src="https://github.com/flutter/flutter/assets/26356162/61134aa9-a66e-4009-87c2-cbaa448dadbc">
<img width="809" alt="Screenshot 2024-05-07 at 4 42 21 AM" src="https://github.com/flutter/flutter/assets/26356162/6b6a9cff-53cb-4b65-80e7-bd028c4f67d3">


I explained earlier how it works. The onPressed is never null anymore. We get the same effect of a null onPressed by ignoring the pointer, and since onPressed is never null, the color of the IconButton is always the enabled color.

2024-05-08 07:23 UTC, BenjiFarquhar commented
@TahaTesser trailing space is fixed. Not sure why some tests (see test commands below) failed in the remote build, as they pass when I run them locally with:

```
flutter test material/app_test.dart                      
flutter test widgets/draggable_scrollable_sheet_test.dart
flutter test painting/star_border_test.dart 
```

Any idea why they failed in this build?

2024-05-08 09:43 UTC, TahaTesser commented
There seems to be a bug on master which doesn't update code so i couldn't the changes from your change. I can confirm it works now.


> flutter test material/app_test.dart                      
> flutter test widgets/draggable_scrollable_sheet_test.dart
> flutter test painting/star_border_test.dart 

These test files are unrelated to this `ExpansionPanel`. Try running test on `expansion_panel_test.dart` file. There is a failure in "'Panel header has semantics, canTapOnHeader = true'" test.

I've updated your fix to mitigate the changing semantics and avoid adding `ignorePointer` when not necessary. 

We can assigned `widget.expandIconColor` to  `disabledColor` in the `ExpandIcon` when `canTapOnHeader`
```dart
        child: ExpandIcon(
          color: widget.expandIconColor,
          disabledColor: child.canTapOnHeader ? widget.expandIconColor : null,
          isExpanded: _isChildExpanded(index),
          padding: _kExpandIconPadding,
          onPressed: !child.canTapOnHeader
              ? (bool isExpanded) => _handlePressed(isExpanded, index)
              : null,
        ),
```

If you still need help testing the changes. let me know. This requires checking icon color when using `canTapOnHeader` prop.

2024-05-09 07:22 UTC, BenjiFarquhar commented
@TahaTesser Thanks. I have implemented the changes with tests. Let me know if it requires any changes.

2024-05-09 07:34 UTC, TahaTesser requested changes

2024-05-09 07:34 UTC, TahaTesser commented on packages/flutter/test/material/expansion_panel_test.dart
> +  });
```suggestion
  testWidgets('ExpandIcon.disabledColor uses expandIconColor color when canTapOnHeader is true', (WidgetTester tester) async {
    const Color expandIconColor = Color(0xff0000ff);

    Widget buildWidget({ bool canTapOnHeader = false }) {
      return MaterialApp(
        home: SingleChildScrollView(
          child: ExpansionPanelList(
            expandIconColor: expandIconColor,
            children: <ExpansionPanel>[
              ExpansionPanel(
                canTapOnHeader: canTapOnHeader,
                headerBuilder: (BuildContext context, bool isExpanded) {
                  return const ListTile(title: Text('Panel'));
                },
                body: const ListTile(title: Text('Content for Panel')),
              ),
            ],
          ),
        ),
      );
    }

    await tester.pumpWidget(buildWidget());

    await tester.tap(find.text('Panel'));
    await tester.pumpAndSettle();

    ExpandIcon expandIcon = tester.widget(find.byType(ExpandIcon));
    expect(expandIcon.disabledColor, isNull);

    await tester.pumpWidget(buildWidget(canTapOnHeader: true));
    await tester.pumpAndSettle();

    expandIcon = tester.widget(find.byType(ExpandIcon));
    expect(expandIcon.disabledColor, expandIconColor);
  });
```

Great job with this test! We can consolidate the two tests and make it concise as well..

2024-05-09 07:35 UTC, TahaTesser approved these changes
LGTM!

2024-05-09 14:25 UTC, bleroux approved these changes
LGTM!

2024-05-09 15:35 UTC, merged