Update `examples/api` for android platform
flutter/flutter pull request #147102
Opened 2024-04-20 03:09 UTC by lamnhan066

In the `examples/api`, the Android platform missed this step while migrating to the declarative plugins {} block described in [flutter-gradle-plugin-apply](https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply), so all examples of `examples/api` cannot run.

Fixes #147100

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

2024-04-21 05:59 UTC, Hixie commented
Are these just regenerated from the `flutter create` template?

2024-04-21 08:50 UTC, lamnhan066 commented
@Hixie No, I removed the `kotlin_version` manually then I took a look at my new project and saw that we need to move the `dev.flutter.flutter-gradle-plugin` to the bottom.

2024-04-22 14:37 UTC, bartekpacia approved these changes
good catch, lgtm

2024-04-22 15:06 UTC, reidbaker requested changes
Hold on understanding what it takes to make your new test run in ci.

2024-04-22 16:41 UTC, lamnhan066 commented
@reidbaker  I found a line that related to the `examples/api` in [this log](https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8749988910130972353/+/u/run_test.dart_for_framework_tests_shard_and_subshard_misc/stdout) is

```
00:00 +0: loading /b/s/w/ir/x/w/flutter/examples/api/integration_test/smoke_integration_test.dart
```

Do you think the test didn't run because of the wrong name of the test file?

2024-04-22 16:54 UTC, reidbaker commented
I just talked to some coworkers and the example API docs that use this code do not use the android or iOS sub directories which is why they were not tested. It turns out the correct fix is to delete the api/android and api/ios sub directories and add them to the local .gitignore. 

Do you want to update this or to do that or do you want to close this pr and have someone from the flutter team delete the code?

2024-04-22 17:47 UTC, lamnhan066 commented
@reidbaker  What should I do with the other platforms or do I just need to remove android and ios subdirectories?

2024-04-22 17:54 UTC, reidbaker commented
> @reidbaker What should I do with the other platforms or do I just need to remove android and ios subdirectories?

You dont need to do anything other than delete android and ios and add those directories to gitignore to prevent them from being re-added accidentally. 

Quote from a teammate below. 
"our API docs we only use the dart code in examples/api/lib and run that code in an embedded dartpad. The platform directories are "unused" as far as I know. They are handy for local development of new samples (so you can just flutter run -d macos them). But for that just having support for desktop platforms is sufficient (hence the smoke test that only covers those platforms)."

2024-04-22 18:24 UTC, lamnhan066 commented
@reidbaker Done. Please give it a look.

2024-04-22 18:35 UTC, reidbaker commented on .gitignore
> +# Platform specific in the examples
Nit: "Unused platform specific files"
```suggestion
# Unused platform specific files
```

2024-04-22 18:35 UTC, reidbaker commented on .gitignore
> +examples/api/android/
Lets put these exclusions in the `/examples/api` directory as a new .gitignore file. The exclusions in this file are ones that should apply to anywhere in the codebase. 

When moved the contents would be 
```
# Unused platform specific files
android/
ios/
```

2024-04-22 18:44 UTC, lamnhan066 commented
Done

2024-04-22 19:03 UTC, reidbaker approved these changes
Thank you contributing to flutter!

2024-04-22 19:04 UTC, reidbaker commented
I have added the autosubmit label. Once the tree is green a bot will merge this pr.

2024-04-22 20:14 UTC, merged