Add tests for callback_shortcuts.0.dart API examples.
flutter/flutter pull request #147536
Opened 2024-04-29 18:08 UTC by ksokolovskyi

This PR contributes to https://github.com/flutter/flutter/issues/130459

### Description
- Corrects the name for `examples/api/test/widgets/shortcuts/callback_shortcuts.0_test.dart` test file
- Update tests for `examples/api/lib/widgets/shortcuts/callback_shortcuts.0.dart`

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

2024-05-06 11:30 UTC, bleroux approved these changes
LGTM! Thanks for adding this missing test.

2024-05-07 09:24 UTC, TahaTesser requested changes

2024-05-07 09:24 UTC, TahaTesser commented on examples/api/test/widgets/shortcuts/callback_shortcuts.0_test.dart
> +  group('CallbackShortcutsApp', () {
`group` isn't necessary here.  As this test file only contains Callback Shortcuts tests.

2024-05-07 09:24 UTC, TahaTesser commented on examples/api/test/widgets/shortcuts/callback_shortcuts.0_test.dart
> +      (WidgetTester tester) async {
```suggestion
      'updates counter on arrowUp and arrowDown press', (WidgetTester tester) async {
```

2024-05-07 14:00 UTC, ksokolovskyi commented
@bleroux @TahaTesser thanks a lot for the review!

2024-05-07 14:32 UTC, TahaTesser approved these changes
LGTM!

2024-05-07 15:21 UTC, merged