Add tests for material banner example
flutter/flutter pull request #147733
Opened 2024-05-02 18:46 UTC by NobodyForNothing

Part of https://github.com/flutter/flutter/issues/130459.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

2024-05-09 14:52 UTC, bleroux requested changes
Thanks for adding these valuable tests.
Just one small comment about capitalizing test descriptions first letter.

2024-05-09 14:52 UTC, bleroux commented on examples/api/test/material/banner/material_banner.0_test.dart
> +  testWidgets('shows all elements', (WidgetTester tester) async {
Consider capitalizing the first letter of test descriptions (same for the other tests below and your other opened PRs).

2024-05-14 04:40 UTC, bleroux approved these changes
LGTM! Thanks for adding those tests.
Taha and I are attending Google/IO this week, expect slow review, we will catch up on reviews next week.

2024-05-21 18:57 UTC, bleroux commented
@NobodyForNothing Thanks for your patience, can you rebase this PR and solve the conflict if there is still one?

2024-05-22 06:37 UTC, bleroux commented
Thanks for the rebase.
Linux analyze step failed because of several trailing space characters, see the corresponding lines in https://ci.chromium.org/ui/p/flutter/builders/try/Linux%20analyze/79407/overview

2024-05-22 20:16 UTC, bleroux requested changes

2024-05-22 20:16 UTC, bleroux commented on examples/api/test/material/banner/material_banner.1_test.dart
> +
Those lines were duplicated, probably during the conflict resolution.

2024-05-23 10:19 UTC, bleroux approved these changes
LGTM!

2024-05-23 12:01 UTC, TahaTesser approved these changes
LGTM! Just minor format issues

2024-05-23 12:01 UTC, TahaTesser commented on examples/api/test/material/banner/material_banner.0_test.dart
> +      const example.MaterialBannerExampleApp()
```suggestion
      const example.MaterialBannerExampleApp(),
```

2024-05-23 12:01 UTC, TahaTesser commented on examples/api/test/material/banner/material_banner.0_test.dart
> +      const example.MaterialBannerExampleApp()
```suggestion
      const example.MaterialBannerExampleApp(),
```

2024-05-23 12:01 UTC, TahaTesser commented on examples/api/test/material/banner/material_banner.1_test.dart
> +        find.byType(MaterialBanner));
```suggestion
    final MaterialBanner banner = tester.widget<MaterialBanner>(
      find.byType(MaterialBanner),
    );
```

2024-05-23 18:48 UTC, merged