Feat add default flavor
flutter/flutter pull request #147968
Opened 2024-05-08 07:49 UTC by holzgeist

This PR adds a new flag `default-flavor` in the `flutter` section of `pubspec.yaml`. It allows developers of multi-flavor android apps to specify a default flavor to be used for `flutter run`, `flutter build` etc.
Using `flutter run` on flavored apps already works without specifying `--flavor` already works on iOS (it defaults to the `runner` schema), so I (and others in #22856) figured this would be nice to have.

fixes #22856

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

2024-05-08 08:00 UTC, holzgeist commented
This probably needs to be reflected in https://github.com/flutter/website
(related to me not yet checking "I updated/added relevant documentation (doc comments with ///)." above

2024-05-08 08:24 UTC, holzgeist commented
looks like the failing windows test OOMed:

```
[ +502 ms] > Task :app:packageDebug FAILED
[        ] AAPT2 aapt2-8.1.0-10154469-windows Daemon #0: shutdown
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:packageDebug'.
[        ] > A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
[        ]    > java.lang.OutOfMemoryError (no error message)
```

This should not be related to my PR

2024-05-08 09:26 UTC, holzgeist commented
ok, I realized now that this doesn't really work on iOS. The `runner` schema is only applied if there is no flavor. If there is one due to the default value, the build doesn't work anymore. Any ideas? Is there a way to tell if we are building for Android in `getBuildInfo` in `flutter_command`?

2024-05-15 06:58 UTC, holzgeist commented
the solution to the ios problem is to rename the default build configuration from `Debug`, `Profile` and `Release` to `Debug <Default Flavor>`, etc.
Works like a charm :)

2024-05-17 00:04 UTC, andrewkolos requested changes
Thanks for the PR! I think this feature will be simple enough to maintain and thus worth having in the tool. Everything here looks correct. I just have a few nitpicks.

2024-05-17 00:04 UTC, andrewkolos commented on packages/flutter_tools/test/general.shard/runner/flutter_command_test.dart
> +        ProcessManager: () => FakeProcessManager.any(),
```suggestion
        ProcessManager: () => FakeProcessManager.empty(),
```

When possible, avoid `FakeProcessManager.any()` as it hides faked processes and can make tests more difficult to reason about.

2024-05-17 00:04 UTC, andrewkolos commented on packages/flutter_tools/test/general.shard/runner/flutter_command_test.dart
> +        ProcessManager: () => FakeProcessManager.any(),
```suggestion
        ProcessManager: () => FakeProcessManager.empty(),
```

2024-05-17 00:11 UTC, andrewkolos commented
I think we should document this new pubspec entry. We could do so on the flutter.dev page, but we could start by mentioning in the help text of `--flavor`:

https://github.com/flutter/flutter/blob/b5f6df7f1c0a6a1bbe60d420170a472ef0400baf/packages/flutter_tools/lib/src/runner/flutter_command.dart#L1093-L1100

What do you think about adding another line here that says something to the effect of

```
Overrides the value of the 'default-flavor' entry in the flutter pubspec.
```

2024-05-21 07:07 UTC, holzgeist commented
Thanks @andrewkolos for the thorough review. I applied all your suggested changes.

Also, I added a (minor) mention to the `Flavors` documentation page: https://github.com/flutter/website/pull/10632

2024-05-21 19:21 UTC, andrewkolos approved these changes
LGTM!

2024-05-21 21:48 UTC, christopherfujino commented
Looks like there are failing tests here

2024-05-21 23:02 UTC, christopherfujino commented
> The test failures might be due to #148704.
> 
> Once the tree goes green again, I will update the PR branch to include [b6bed5a](https://github.com/flutter/flutter/commit/b6bed5aaf2c70e8c5d62a377797234beb923b3e6), which will skip the flaky tests.

oh nice

2024-05-21 23:03 UTC, christopherfujino approved these changes
RSLGTM

2024-05-22 03:54 UTC, andrewkolos commented
> Also, I added a (minor) mention to the `Flavors` documentation page: [flutter/website#10632](https://github.com/flutter/website/pull/10632)

FYI https://github.com/flutter/website/pull/10632 got merged and then reverted since the functionality from this PR won't be available to stable release users until the next major release. Feel free to re-draft the PR and include note in the description that the feature won't be available until then (and thus the PR shouldn't be merged until then).

2024-05-22 05:11 UTC, merged

2024-05-22 06:08 UTC, holzgeist commented
@andrewkolos oh, thanks. Sorry about that. I didn't think about that resp. I had no idea how fast documentation was released

I'll re-send the website PR

2024-05-22 07:08 UTC, navaronbracke commented
@holzgeist Thanks for this! I did file https://github.com/flutter/flutter/issues/139286 in the past as well, which relates to the same problem from a tool perspective. If we get around to solving that issue - using a tool exit with a relevant message - perhaps we can include a reference to this fix in the message? 

For example: `The required flavor variant was not specified. Consider passing it as the "--flavor" option, or specifying the default flavor in the pubspec.`

2024-05-22 09:22 UTC, holzgeist commented
> @holzgeist Thanks for this! I did file #139286 in the past as well, which relates to the same problem from a tool perspective. If we get around to solving that issue - using a tool exit with a relevant message - perhaps we can include a reference to this fix in the message?

Yup, an early exit would be better than the "no output file found" message in the end. Unfortunately I have no idea how to handle that

2024-05-22 20:51 UTC, andrewkolos commented
> @andrewkolos it looks like my warning in the PR description wasn't enough, it got merged again: [flutter/website#10642](https://github.com/flutter/website/pull/10642)
> 
> Can you revert it again? I'll send a new PR once this feature hits stable

Oh no 🤭! Sorry about that. I've went ahead and gotten it reverted again (https://github.com/flutter/website/pull/10646). Per, https://github.com/flutter/website/pull/10646#issuecomment-2125660755, you are welcome to redraft it again now, but I would keep it marked as a [Draft](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft) and include something like "[Next stable]" in the title.

> @holzgeist Thanks for this! I did file https://github.com/flutter/flutter/issues/139286 in the past as well, which relates to the same problem from a tool perspective. If we get around to solving that issue - using a tool exit with a relevant message - perhaps we can include a reference to this fix in the message?

Good idea. I've added a note about this idea on #139286 so that it doesn't get lost to history.

> Yup, an early exit would be better than the "no output file found" message in the end. Unfortunately I have no idea how to handle that

Fixing that issue would indeed be more complicated. I would love to do some digging and provide some helpful hints over on that thread, but alas I don't have the time at the moment 😞

Thanks again for the continued work here!

2024-07-01 11:43 UTC, sbatezat commented
I don't get it.

Adding a "default-flavor" solves Android issue when it's not possible to "flutter build"/"flutter run" an app without flavor, but it introduces a new issue on iOS where, when uses, the iOS platform is now expecting the definition of a default-flavor (where it was not needed before).

Let's me explain further. Let's say i've got a "free" flavor and a normal app, like that :

> 
>     flavorDimensions "default"
> 
>     productFlavors {
>         FREE {
>             dimension "default"
>         }
>     }

I can fix the build of "flutter build" / "flutter run" without the flavor flag on the cli by adding your "default-flavor: PAID" flag on the pubspec with "PAID" also on the gradle file :

> 
>     flavorDimensions "default"
> 
>     productFlavors {
>         PAID {
>             dimension "default"
>         }
>         FREE {
>             dimension "default"
>         }
>     }

But then, on iOS, it's not working anymore (and it was working), because the "PAID" flavor does not exists. So I need to create it where it should not be needed....

Taking this into consideration, I'm not sure this MR is the way to go

2024-07-02 01:42 UTC, andrewkolos commented
> I don't get it.

Unless https://github.com/flutter/flutter/issues/22856 was requesting the ability to configure a default flavor _exclusively_ for Android, this PR is a valid resolution to that issue. You are welcome to file a new feature request.

2025-03-24 18:38 UTC, antfitch commented
Out of curiosity if a developer builds a Flutter app that ports to both iOS and Android, will this produce an error when the iOS app is built for that project?

2025-03-24 23:23 UTC, antfitch commented
> > Out of curiosity, if a developer builds a Flutter app that ports to both iOS and Android, will this produce an error when the iOS app is built for that project?
> 
> Assuming "this" refers to the `default-flavor` feature/field in the pubspec, it should work for both platforms. However, it's very likely this feature doesn't work when building a Flutter app directly from Android Studio/Xcode (as opposed to using the `flutter` CLI or Flutter IDE plugin).

I agree, it makes sense that this wouldn't work from Android Studio/Xcode. I was noticing the thread of messages around iOS issues and the `default-flavor` field. I wanted to make sure that `default-flavor` in the pubspec works with flavors for iOS. It sounds like it does. Thanks!