Test raw autocomplete api examples
flutter/flutter pull request #148234
Opened 2024-05-13 17:04 UTC by NobodyForNothing

Part of #130459.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

2024-05-15 05:15 UTC, bleroux approved these changes
LGTM with minor nits.
Thanks!

2024-05-15 05:15 UTC, bleroux commented on examples/api/test/widgets/autocomplete/raw_autocomplete.focus_node.0_test.dart
> +        of: find.byType(RawAutocomplete)
Too much indentation

2024-05-15 05:15 UTC, bleroux commented on examples/api/test/widgets/autocomplete/raw_autocomplete.1_test.dart
> +  testWidgets('Finds users by mail address', (WidgetTester tester) async {
mail -> email

2024-05-20 08:13 UTC, TahaTesser requested changes
Thanks for the tests!

2024-05-20 08:13 UTC, TahaTesser commented on examples/api/test/widgets/autocomplete/raw_autocomplete.focus_node.0_test.dart
> +    ), findsOneWidget);
```suggestion
    expect(
      find.descendant(
        of: find.byType(AppBar),
        matching: find.byType(TextFormField)
      ),
      findsOneWidget,
    );
```

2024-05-20 08:13 UTC, TahaTesser commented on examples/api/test/widgets/autocomplete/raw_autocomplete.focus_node.0_test.dart
> +    ), findsNothing);
```suggestion
    expect(
      find.ancestor(
        matching: find.byType(AppBar),
        of: find.byType(RawAutocomplete)
      ),
      findsNothing,
    );
```

2024-05-20 08:13 UTC, TahaTesser commented on examples/api/test/widgets/autocomplete/raw_autocomplete.focus_node.0_test.dart
> +    ), findsOneWidget);
```suggestion
    expect(
      find.descendant(
        of: find.byType(TextFormField),
        matching: find.text('bobcat'),
      ),
      findsOneWidget,
    );
```

2024-05-20 08:13 UTC, TahaTesser approved these changes

2024-05-20 09:57 UTC, TahaTesser commented
@NobodyForNothing 
You might need to rebase to fix Google testing

2024-05-21 19:00 UTC, bleroux commented
@NobodyForNothing Can you rebase this PR?

2024-05-23 08:52 UTC, merged