Slide should respect bold text setting
flutter/flutter pull request #148435
Opened 2024-05-15 22:31 UTC by hangyujin

Fix https://github.com/flutter/flutter/issues/147600  

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

2024-05-22 07:27 UTC, TahaTesser requested changes
Thanks for the fix!

2024-05-22 07:27 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +      }) {
```suggestion
      Widget buildSlider({ bool boldText = false }) {
```

2024-05-22 07:27 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +  LoggingValueIndicatorShape(this.logLabel);
Nice!

2024-05-22 07:27 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +                      ),
```suggestion
                        sliderTheme: Theme.of(context).sliderTheme.copyWith(
                          showValueIndicator: ShowValueIndicator.always,
                          valueIndicatorShape: loggingValueIndicatorShape,
                        ),
                      ),
```

2024-05-22 07:27 UTC, TahaTesser commented on packages/flutter/test/material/slider_test.dart
> +          theme: ThemeData(useMaterial3: false),
Unless the fix is specific to M2, we could be testing for M3 by default and remove this line.

2024-05-22 19:09 UTC, TahaTesser approved these changes
LGTM!

2024-05-24 18:30 UTC, closed without merging

2024-05-24 18:32 UTC, hangyujin commented
The PR should be merging into flutter:master instead of flutter:main , reopening it as https://github.com/flutter/flutter/pull/149053, @TahaTesser can you review it again?