Fix InputDecorator default hint text style on M3
flutter/flutter pull request #148944
Opened 2024-05-23 10:32 UTC by bleroux

## Description

This PRs makes the `InputDecoration.hintText` style compliant with the M3 spec.
The hint style is not clearly specified in https://m3.material.io/components/text-fields/specs, but it is in the M3 Figma kit.
('hint' terminology came from the Material1 specification, since M2 the terminology is 'Placeholder').

See this Figma screenshot taken while focusing on the 'Placeholder' text (which corresponds to hint).

![image](https://github.com/flutter/flutter/assets/840911/58d3d5c9-0984-497a-9d47-4724dcd7b2b3)

It seems that the intention is that the 'Placeholder' colors should be the same as the 'supporting text' ones, that is why is reused 'supporting text' tokens.

## Related Issue

Fixes https://github.com/flutter/flutter/issues/148787.

## Tests

Updates several tests.

2024-05-23 16:00 UTC, bleroux commented
@Renzo-Olivares This a follow-up PR to https://github.com/flutter/flutter/pull/148113 where I added the TODOs.

2024-05-23 20:52 UTC, Renzo-Olivares commented on packages/flutter/lib/src/material/input_decorator.dart
> +  /// If null, [TextTheme.bodyLarge] will be used
nit: period at the end of this sentence.

2024-05-27 13:10 UTC, guidezpl requested changes

2024-05-27 13:10 UTC, guidezpl commented on dev/tools/gen_defaults/lib/input_decorator_template.dart
> +      return TextStyle(color: ${componentColor('md.comp.filled-text-field.disabled.supporting-text')});
I think it's the same, but prefer `md.comp.filled-text-field.disabled.label-text`

2024-05-27 13:10 UTC, guidezpl commented on dev/tools/gen_defaults/lib/input_decorator_template.dart
> +    return TextStyle(color: ${componentColor('md.comp.filled-text-field.supporting-text')});
Prefer `md.comp.filled-text-field.label-text`

2024-05-27 13:14 UTC, guidezpl approved these changes
Disreguard previous review, LGTM :)

2024-05-28 12:15 UTC, bleroux commented
@Renzo-Olivares The Google tests failures are probably legit. Can you please have a look?

2024-05-30 22:18 UTC, Renzo-Olivares commented
@bleroux I just looked through the google testing failures and they all look expected. I'll try to land this tomorrow.

2024-05-31 19:01 UTC, Renzo-Olivares approved these changes

2024-05-31 20:56 UTC, merged

2024-05-31 22:02 UTC, Renzo-Olivares commented
@bleroux I missed the golden changes when reviewing this. I took a look https://flutter-gold.skia.org/detail?grouping=name%3Dmaterial.m3_input_decorator.outline_icon_label.rtl%26source_type%3Dflutter&digest=0ebe1c484196c24b21ab16fc22738bab but am a little unsure. It looks like the floating label is being affected which I didn't expect.

2024-05-31 22:04 UTC, loic-sharma commented
Reason for revert: This caused Skia golden changes that might be unexpected. We can reland once we confirm these changes are expected, or, fixed the changes to the floating label.