Add tests for scaffold drawer and end drawer
flutter/flutter pull request #149383
Opened 2024-05-31 03:53 UTC by ValentinVignal

Contributes to https://github.com/flutter/flutter/issues/130459

It adds a test for
- `examples/api/lib/material/scaffold/scaffold.drawer.0.dart`
- `examples/api/lib/material/scaffold/scaffold.end_drawer.0.dart`

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat
[Data Driven Fixes]: https://github.com/flutter/flutter/wiki/Data-driven-Fixes

2024-06-05 12:11 UTC, bleroux approved these changes
LGTM with some formatting nits to correct.
Thanks for the contribution!

2024-06-05 12:11 UTC, bleroux commented on examples/api/test/material/scaffold/scaffold.end_drawer.0_test.dart
> +    );
```suggestion
    expect(
      tester.getCenter(find.byType(Drawer)).dx,
      greaterThan(400),
      reason: 'The drawer should be on the right side of the screen',
    );
```

2024-06-05 12:11 UTC, bleroux commented on examples/api/test/material/scaffold/scaffold.end_drawer.0_test.dart
> +    );
```suggestion
    expect(
      tester.getCenter(find.byType(EndDrawerButton)).dx,
      greaterThan(400),
      reason: 'The drawer button should be on the right side of the app bar',
    );
```

2024-06-05 12:11 UTC, bleroux commented on examples/api/test/material/scaffold/scaffold.drawer.0_test.dart
> +    );
```suggestion
    expect(
      tester.getCenter(find.byType(Drawer)).dx,
      lessThan(400),
      reason: 'The drawer should be on the left side of the screen',
    );
```

2024-06-05 12:11 UTC, bleroux commented on examples/api/test/material/scaffold/scaffold.drawer.0_test.dart
> +    );
```suggestion
    expect(
      tester.getCenter(find.byType(DrawerButton)).dx,
      lessThan(400),
      reason: 'The drawer button should be on the left side of the app bar',
    );
```

2024-06-05 12:11 UTC, bleroux commented on examples/api/test/material/scaffold/scaffold.drawer.0_test.dart
> +    // Closes the drawer by tapping outside the drawer
```suggestion
    // Closes the drawer by tapping outside the drawer.
```

2024-06-05 12:11 UTC, bleroux commented on examples/api/test/material/scaffold/scaffold.end_drawer.0_test.dart
> +    // Closes the drawer by tapping outside the drawer
```suggestion
    // Closes the drawer by tapping outside the drawer.
```

2024-06-06 07:49 UTC, TahaTesser requested changes

2024-06-06 07:49 UTC, TahaTesser commented on examples/api/test/material/scaffold/scaffold.drawer.0_test.dart
> +    // Closes the drawer by tapping the button inside the drawer.
```suggestion
    // Close the drawer by tapping the button inside the drawer.
```

2024-06-06 07:49 UTC, TahaTesser commented on examples/api/test/material/scaffold/scaffold.drawer.0_test.dart
> +    // Opens the drawer by tapping the drawer button in the app bar.
```suggestion
    // Open the drawer by tapping the drawer button in the app bar.
```

2024-06-06 07:49 UTC, TahaTesser commented on examples/api/test/material/scaffold/scaffold.drawer.0_test.dart
> +    // Closes the drawer by tapping outside the drawer.
```suggestion
    // Close the drawer by tapping outside the drawer.
```

2024-06-06 07:49 UTC, TahaTesser commented on examples/api/test/material/scaffold/scaffold.end_drawer.0_test.dart
> +    // Opens the drawer by tapping the button at the center of the screen.
```suggestion
    // Open the drawer by tapping the button at the center of the screen.
```

2024-06-06 07:49 UTC, TahaTesser commented on examples/api/test/material/scaffold/scaffold.end_drawer.0_test.dart
> +    // Closes the drawer by tapping the button inside the drawer.
```suggestion
    // Close the drawer by tapping the button inside the drawer.
```

2024-06-06 07:49 UTC, TahaTesser commented on examples/api/test/material/scaffold/scaffold.end_drawer.0_test.dart
> +    // Opens the drawer by tapping the drawer button in the app bar.
```suggestion
    // Open the drawer by tapping the drawer button in the app bar.
```

2024-06-06 07:49 UTC, TahaTesser commented on examples/api/test/material/scaffold/scaffold.end_drawer.0_test.dart
> +    // Closes the drawer by tapping outside the drawer.
```suggestion
    // Close the drawer by tapping outside the drawer.
```

2024-06-10 11:30 UTC, TahaTesser approved these changes
LGTM

2024-06-11 07:06 UTC, merged

2024-06-11 15:19 UTC, bleroux commented
@ValentinVignal This was reverted due to an infra failure.
Nothing wrong with your PR, but there is a bad infra failure since last week.
Thank you to file this PR again and, before landing it, we will wait before for https://github.com/flutter/flutter/issues/149851 to be fixed.

2024-06-11 15:37 UTC, ValentinVignal commented
Sure, I'll do that

2024-06-11 15:40 UTC, ValentinVignal commented
Here it is @bleroux  https://github.com/flutter/flutter/pull/150047