chore: fix typo korean, cutButtonLabel
flutter/flutter pull request #151364
Opened 2024-07-06 09:17 UTC by n7484443

[Wikipeidia](https://ko.wikipedia.org/wiki/%EC%9E%98%EB%9D%BC%EB%82%B4%EA%B8%B0,_%EB%B3%B5%EC%82%AC,_%EB%B6%99%EC%97%AC%EB%84%A3%EA%B8%B0)
In korea, we use '잘라내기', '복사', '붙여넣기', not '잘라냄', '복사', '붙여넣기'.
![image](https://github.com/flutter/flutter/assets/7384324/34845c96-4e7a-4f95-a44c-19f9917f4a6c)
e.g.) korean translation site, papago 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

2024-07-11 19:55 UTC, LouiseHsu requested changes
Thank you for your PR! do you think you could add a test like this?https://github.com/flutter/flutter/pull/142158/files#diff-484416bbc51eb0d169f9a783e719250552133dd063f117dd45c7ec445d2ef54c

Otherwise this looks good!

2024-07-11 19:56 UTC, LouiseHsu commented
I've also requested a translation change internally here
https://localizer.google.com/messages/edittranslation/Flutter/3991031067551493329/ko

2024-07-13 02:31 UTC, n7484443 commented
> Thank you for your PR! do you think you could add a test like this?https://github.com/flutter/flutter/pull/142158/files#diff-484416bbc51eb0d169f9a783e719250552133dd063f117dd45c7ec445d2ef54c
> 
> Otherwise this looks good!

As per your suggestion, I added the related test code to cut-copy-paste action.

2024-07-16 19:41 UTC, LouiseHsu approved these changes
LGTM! Thanks so much for adding those tests!~

2024-07-16 22:29 UTC, merged