Upgrade module template AGP version
flutter/flutter pull request #151675
Opened 2024-07-12 18:31 UTC by gmackall

Follow up to https://github.com/flutter/flutter/pull/151433.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2024-07-16 18:31 UTC, reidbaker requested changes
Show that custom variants work before merging.

2024-08-07 17:42 UTC, gmackall commented
> I think build variants is supported for modules which means that this feature wont work for people who have custom variants.
> 
> https://docs.flutter.dev/deployment/flavors#using-flavors-in-android
> 
> I think you are going to need to write some dynamic code to handle other variants.
> 
> (blog post for apps) https://medium.com/meeve/build-variants-in-flutter-for-multiple-backend-environments-7e139128949b

I'm not actually sure that modules support flavors, because:
1. it is possible to build a module as an AAR by itself (independently of a pure android host project)
2. Configuring flavors per https://docs.flutter.dev/deployment/flavors#using-flavors-in-android requires Gradle changes
3. The Gradle files are ephemeral for modules, so the user can't change them (reliably)

But I think also this new change would support them anyways, though it's kind of hacky

2024-08-12 17:00 UTC, gmackall commented
@reidbaker This should be ready for review again fyi

2024-08-12 17:37 UTC, reidbaker approved these changes

2024-08-12 18:17 UTC, merged