fix: A referenced default package must be a plugin package
flutter/flutter pull request #152134
Opened 2024-07-22 20:38 UTC by Gustl22

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

Clarify that a referenced default package must also be a plugin package (one, which interacts with the platform).

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

Addresses #152037 (but does not close it (?))
More precisely https://github.com/flutter/flutter/issues/152037#issuecomment-2239909463.

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2024-07-24 06:51 UTC, Gustl22 commented
Open for review @stuartmorgan

2024-07-24 14:45 UTC, stuartmorgan requested changes
Thanks!

2024-07-31 21:13 UTC, Gustl22 commented on packages/flutter_tools/lib/src/flutter_plugins.dart
> +          'Package ${plugin.name}:$platformKey references $defaultImplPluginName:$platformKey as the default plugin, but the package does not exist, or is not a plugin package.\n'
This check involves all plugins, which have [this](https://github.com/flutter/flutter/blob/0b41781c780a2782dd3c2a39bc7e2cf1a0b16e70/packages/flutter_tools/lib/src/flutter_plugins.dart#L62) condition. So it's pre-platform-filtering. Means, all with the `flutter: plugin:` in the pubspec are considered. So I think the error message is correct that way.

We test the specific platform implementation a few lines above, which should cover your mentioned case (if I got it right): https://github.com/flutter/flutter/pull/152134/files#diff-68361f6fc9aafa5fa7de042eec4603dd4f321eb783a00edd57780ef78c1094bbR1259

2024-07-31 21:15 UTC, Gustl22 commented on packages/flutter_tools/lib/src/flutter_plugins.dart
>            'or create a plugin named $defaultImplPluginName.\n',
See the [other](https://github.com/flutter/flutter/pull/152134#discussion_r1699114020) comment.

2024-08-19 17:56 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/flutter_plugins.dart
> +          'Package ${plugin.name}:$platformKey references $defaultImplPluginName:$platformKey as the default plugin, but the package does not exist, or is not a plugin package.\n'
Makes sense, thanks. Ideally the check should be stricter and require a platform implementation, but we can revisit that if it ever actually matters in practice.

2024-08-19 17:56 UTC, stuartmorgan approved these changes
LGTM

2024-08-19 18:26 UTC, christopherfujino approved these changes
LGTM

2024-08-22 21:02 UTC, merged