Don't crash flutter tool if Chrome is not available
flutter/flutter pull request #154941
Opened 2024-09-10 19:14 UTC by saltedpotatos

Instead of unawaiting the future, let's ignore it. 

Fixes issue #154940

I am not sure if tests would be required for this change or not.

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2024-09-24 03:03 UTC, andrewkolos requested changes
Thanks for the PR

This change is nontrivial and should be under test. I would try adding a test to test/general.shard/resident_devtools_handler_test.dart

~~`FlutterResidentDevtoolsHandler` would probably need to be modified to accept an instance of `Chrome` through its constructor. The test would use a fake of `Chrome` (e.g. `class FakeChrome extends Fake implements Chrome`) that would throw an exception from its `start` implementation.~~ Never mind, `Chrome.start` is a static method.

2024-09-25 21:10 UTC, saltedpotatos commented
Thanks! I'll try to write a test to cover this - we will see how that goes.
 
Pedantically, it seems like `ignore()`\`ing the future satisfies the comment guarantee in a way `unawaited()` does not. Thought I could sneak by test-free when I didn't break any existing tests.

```dart
// This must be guaranteed not to return a Future that fails.
  @override
  bool launchDevToolsInBrowser({required List<FlutterDevice?> flutterDevices}) {
    //[...]
}
```

2024-09-25 22:11 UTC, andrewkolos commented
> Thanks! I'll try to write a test to cover this - we will see how that goes.
> 
> Pedantically, it seems like `ignore()``ing the future satisfies the comment guarantee in a way `unawaited()` does not. Thought I could sneak by test-free when I didn't break any existing tests.
> 
> ```dart
> // This must be guaranteed not to return a Future that fails.
>   @override
>   bool launchDevToolsInBrowser({required List<FlutterDevice?> flutterDevices}) {
>     //[...]
> }
> ```

Awesome. Please let me know if turns out to be difficult. I personally would not mind this change landing without a test (though you'll have to fix the formatting and the errors from `flutter analyze` before I can approve). Once I've approved this PR, I can submit a text-exemption request, and we'll see what happens.

2024-09-26 19:30 UTC, saltedpotatos commented
re: code formatting, looking at the style guide, 

> We do not yet use dartfmt (except in flutter/packages). 

I would assume I can `dart format resident_devtools_handler.dart`, but that format changed more than just my additions. Am I misreading the style guide and instead need to hand format?

2024-09-30 17:57 UTC, andrewkolos approved these changes
LGTM as-is.

At your leisure, let me know whether you want to try to get this under test or if you would like to request a test-exemption.

2024-10-07 22:51 UTC, saltedpotatos commented
Can we request a test exemption? Or I can request one in the discord, please let me know your preference. 

Thanks!

2024-10-08 06:41 UTC, andrewkolos requested changes
I've recently found out the flutter tool has its own means to launch chrome without needing the `Chrome` API from package:browser_launcher. Specifically, I'm talking about [`ChromiumLauncher`](https://github.com/flutter/flutter/blob/9cd2fc90af406a5ae798a6e099f3fca3eebd0da0/packages/flutter_tools/lib/src/web/chrome.dart#L114).

If `FlutterResidentDevToolsHandler` could be refactored to accept a `ChromiumLauncher` instance, then a test could be written without having to write an wrapper around the `Chrome` API from package:browser_launcher, and we could drop our dependency on that package altogether.

What do you think?

2024-10-16 18:15 UTC, saltedpotatos commented
Apologies for the delay, I was out of town.

That sounds good to me! I'll start working towards that.

2024-10-31 23:39 UTC, andrewkolos commented
For the sake of expediency, I made a bunch of refactorings. Much of it was just undoing (unintentional?) changes that appeared to come from `dart format` (which isn't used in this repo yet). Feel free to review my commits and tweak things accordingly.

2024-10-31 23:42 UTC, andrewkolos approved these changes
Thanks for the continued work on this change! This looks good to me.

Unfortunately, this PR is going to be blocked on running `"flutter update-packages --force-upgrade"` to update all the pubspecs since this PR touches a pubspec (see the failing `Linux analyze` check). However, doing so now would result in a bunch of tests failing due to issues unrelated to this PR. See https://github.com/flutter/flutter/pull/157392. I'll keep an eye on this and run `flutter update-packages` whenever this is resolved.

2024-11-01 22:14 UTC, saltedpotatos commented
Awesome! Thanks for your help - and patience!

Yep, any formatting changes would be unintentional. I don't normally use VSCode, but my LSP apparently does not like running against the main branch of flutter. Coincidentally, this is also how my first commits included analyzer issues. Oops.

2024-12-06 22:40 UTC, christopherfujino commented
I rebased and ran `flutter update-packages --force-upgrade` to fix Linux analyze

2025-01-09 19:29 UTC, jmagman commented
@andrewkolos can you help get this formatted and merged?  It's been hanging out awhile.

2025-01-09 22:22 UTC, bkonyi approved these changes

2025-01-21 11:37 UTC, merged