[CP-stable]Assert macOS framework artifact contains xcprivacy manifest
flutter/flutter pull request #155556
Opened 2024-09-23 18:13 UTC by flutteractionsbot

This pull request is created by [automatic cherry pick workflow](https://github.com/flutter/flutter/blob/main/docs/releases/Flutter-Cherrypick-Process.md#automatically-creates-a-cherry-pick-request)
Please fill in the form below, and a flutter domain expert will evaluate this cherry pick request.

### Issue Link:
What is the link to the issue this cherry-pick is addressing?

< Replace with issue link here >

### Changelog Description:
Explain this cherry pick in one line that is accessible to most Flutter developers. See [best practices](https://github.com/flutter/flutter/blob/main/docs/releases/Hotfix-Documentation-Best-Practices.md) for examples

< Replace with changelog description here >

### Impact Description:
What is the impact (ex. visual jank on Samsung phones, app crash, cannot ship an iOS app)? Does it impact development (ex. flutter doctor crashes when Android Studio is installed), or the shipping production app (the app crashes on launch)

< Replace with impact description here >

### Workaround:
Is there a workaround for this issue?

< Replace with workaround here >

### Risk:
What is the risk level of this cherry-pick?

  - [ ] Low
  - [ ] Medium
  - [ ] High

### Test Coverage:
Are you confident that your fix is well-tested by automated tests?

  - [ ] Yes
  - [ ] No

### Validation Steps:
What are the steps to validate that this fix works?

< Replace with validation steps here >

2024-10-16 15:59 UTC, itsjustkevin commented
@jmagman is this cherry-pick request still relevant?

2024-10-16 17:20 UTC, christopherfujino commented
> @jmagman is this cherry-pick request still relevant?

Yes, I will follow up on it.

2024-10-18 05:10 UTC, jmagman requested changes
The path is actually incorrect and it was caught during beta codesigning https://github.com/flutter/flutter/issues/157016

This should be updated to https://github.com/flutter/flutter/pull/157136

Let's hold off on this stable PR until we confirm that framework test is passing on the beta branch.

2024-10-23 13:55 UTC, reidbaker commented
Not taking this for the hotfix release. Please message me if that is incorrect and we need to work to get this pr landed.

2024-10-23 18:40 UTC, christopherfujino commented
I am closing this as I believe this is obsolete and we already merged: https://github.com/flutter/flutter/commit/077c0084d24752361cc6d5dbe316916ba710dc4a to the 3.27 branch.

2024-10-23 18:41 UTC, christopherfujino commented
> I am closing this as I believe this is obsolete and we already merged: [077c008](https://github.com/flutter/flutter/commit/077c0084d24752361cc6d5dbe316916ba710dc4a) to the 3.27 branch.

Whoops, I got mixed up, this is to 3.24

2024-10-23 18:46 UTC, christopherfujino commented on packages/flutter_tools/test/host_cross_arch.shard/macos_content_validation_test.dart
> +      final File topLevelPrivacy =  outputFlutterFramework.childFile('PrivacyInfo.xcprivacy');
WDYT @jmagman?

2024-10-23 18:49 UTC, jmagman approved these changes

2024-10-23 18:49 UTC, jmagman commented on packages/flutter_tools/test/host_cross_arch.shard/macos_content_validation_test.dart
> +      final File topLevelPrivacy =  outputFlutterFramework.childFile('PrivacyInfo.xcprivacy');
Perfect, thank you!

2024-10-23 18:58 UTC, christopherfujino commented
I'm confused by the test output of the failing test, however, it occurs that we will probably have to roll the engine this PR, or roll the engine into the upstream branch and then rebase this PR, until the updated test will pass.

2024-10-23 21:55 UTC, jmagman commented
> I'm confused by the test output of the failing test, however, it occurs that we will probably have to roll the engine this PR, or roll the engine into the upstream branch and then rebase this PR, until the updated test will pass.

Oh right, the privacy manifest doesn't exist at all in the engine in master.  The engine roll should happen first.

2024-10-24 14:14 UTC, reidbaker approved these changes

2024-10-24 14:14 UTC, reidbaker commented on bin/internal/engine.version
I updated this to include https://github.com/flutter/engine/pull/56059/

2024-10-24 14:45 UTC, reidbaker commented on bin/internal/engine.version
Oh and post submits passed.

2024-10-24 15:01 UTC, merged

2024-10-24 16:30 UTC, cbracken reviewed
nice!

2024-10-24 17:03 UTC, christopherfujino commented
LGTM