Made Cupertino dialog more like a native dialog in dark mode
flutter/flutter pull request #157218
Opened 2024-10-19 06:14 UTC by thejitenpatel

This PR addresses an issue where the `CupertinoAlertDialog` was not fully visible in dark mode. The dialog now adapts better to dark mode themes, ensuring proper contrast and readability across different UI elements. 

Fixes: #80921 

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2024-10-23 19:06 UTC, victorsanni commented
This PR will need images with side-by-side comparisons with native, new tests, and fixes to existing tests.

2024-10-24 14:05 UTC, thejitenpatel commented
> This PR will need images with side-by-side comparisons with native, new tests, and fixes to existing tests.

Sure @victorsanni! I will add images with a side-by-side comparison with native, and also fix the existing tests. However, I'm having a bit of trouble understanding the golden test documentation. Could you please help me with the following:

Do we need to create or update the golden test case? If yes, what are the steps involved in doing so?

2024-10-24 17:43 UTC, victorsanni commented
> Sure @victorsanni! I will add images with a side-by-side comparison with native, and also fix the existing tests. However, I'm having a bit of trouble understanding the golden test documentation. Could you please help me with the following:
> 
> Do we need to create or update the golden test case? If yes, what are the steps involved in doing so?

Considering its a color change, the goldens are expected to change.

2024-10-24 20:08 UTC, dkwingsmt commented
Can you explain how you got those numbers? And can you illustrate (probably with a side-by-side comparison, as mentioned by comments above) how you verify that those numbers produce native-like effects?

Thank you for you contribution!

2024-10-27 13:59 UTC, thejitenpatel commented
Hi @victorsanni, @MitchellGoodwin, @dkwingsmt, here's the side-by-side comparison with native.

| Native | Flutter |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/ac530161-6014-4a5d-ad8d-d2125cd9dff0" width="400"/> | <img src= "https://github.com/user-attachments/assets/03828f23-1585-4b34-824d-7789a4437474" width="400"/>|
| <img src= "https://github.com/user-attachments/assets/f2e20f31-238e-48ac-8ade-097b728ea941" width="400"/> | <img src= "https://github.com/user-attachments/assets/cff2fd47-60b3-40c7-949a-d0acc2fc174b" width="400"/> | 

Also, @dkwingsmt, I derived those numbers from GitHub Issue #80921, where they were initially suggested for achieving native-like effects.

To verify the results, I created an alert dialog box in SwiftUI and manually compared the colors to ensure accuracy.

2024-10-29 18:24 UTC, victorsanni commented
> Hi @victorsanni, @MitchellGoodwin, @dkwingsmt, here's the side-by-side comparison with native.

Are the Flutter images before or after this PR? It would be easy to see the changes if the images show native, flutter before, and flutter after.

2024-10-29 18:44 UTC, victorsanni commented
> It looks like the separator between the actions and the main content needs to be lightened as well.

And the middle divider is also a little too light. Just from visually looking at it I wonder if the dividers are translucent. @thejitenpatel when trying to fix this, it might be helpful to draw the native dialog in different color backgrounds.

2024-11-03 05:30 UTC, thejitenpatel commented
Hi @victorsanni, @MitchellGoodwin as requested, here's the detailed comparison of before and after PR changes with native.

**Before PR**
| Native | Flutter (master) |
|----------|----------|
| <img src="https://github.com/user-attachments/assets/b4e1f13c-df70-44c1-a908-3734f3e6c56b" width="400"/> | <img src="https://github.com/user-attachments/assets/d045a75c-c20f-48bd-b540-74003cd78fbc" width="400"/> |
| <img src="https://github.com/user-attachments/assets/87dafba9-1ef2-4356-a0c6-0696d3eb328b" width="400"/> | <img src="https://github.com/user-attachments/assets/3eeeaf0f-b637-40b6-8a61-357928523d4e" width="400"/> |

**After PR**

| Native | Flutter (PR #157218) |
|--------|--------|
| <img src="https://github.com/user-attachments/assets/ac530161-6014-4a5d-ad8d-d2125cd9dff0" width="400"/> | <img src= "https://github.com/user-attachments/assets/03828f23-1585-4b34-824d-7789a4437474" width="400"/>|
| <img src= "https://github.com/user-attachments/assets/f2e20f31-238e-48ac-8ade-097b728ea941" width="400"/> | <img src= "https://github.com/user-attachments/assets/cff2fd47-60b3-40c7-949a-d0acc2fc174b" width="400"/> |

2024-11-04 20:12 UTC, dkwingsmt approved these changes
LGTM! The colors indeed look much closer to native. Thank you for your contribution and explanation!

Although I wouldn't mark https://github.com/flutter/flutter/issues/80921 as fixed, because the issue also pointed out the problem of the separation line. Can you change the PR description so that it says something like "Fix part of https://github.com/flutter/flutter/issues/80921" and Github doesn't close the issue right away?

2024-11-04 20:22 UTC, victorsanni commented
@thejitenpatel to add to @dkwingsmt's comment, there's no pressure to add the separator fix. But it would be nice to have that here as well, in order to close the linked issue entirely :)

2024-11-04 20:29 UTC, dkwingsmt commented
Thank you Victor for the addition, although I must note that the separator issue is actually really complicated, and I would recommend doing so in a different PR.

(I don't know why the current screenshots show almost no horizontal separators, maybe it's a bug)

I can't find the issues on this problem for now, but there has been back and forth on how the thickness of the separator is defined, and my latest discovery is that iOS devices draw them with 1 _physical_ pixel thick. Yes, this means that the separator on a low-res iPhone is thicker than a high-res one. But how should Flutter handle it? There used to be complaint on the separators looking differently on Android.

In short, fixing the separator might require further investigation and comparison.

2024-11-04 20:40 UTC, victorsanni commented
I saw there was another open issue for the separators: https://github.com/flutter/flutter/issues/61164

Maybe this issue can be closed with this PR and target the separator fix to that issue instead?

2024-11-04 21:02 UTC, dkwingsmt commented
> I saw there was another open issue for the separators: #61164
> 
> Maybe this issue can be closed with this PR and target the separator fix to that issue instead?

Sounds good!

2024-11-04 22:39 UTC, victorsanni approved these changes
LGTM! Thanks for the PR.

2024-11-05 19:57 UTC, victorsanni commented
> the separator issue is actually really complicated, and I would recommend doing so in a different PR.

> there has been back and forth on how the thickness of the separator is defined, and my latest discovery is that iOS devices draw them with 1 _physical_ pixel thick.

The thickness of the horizontal separator might be complicated, but what about just the color? It looks darker than native. Or maybe that is part of the thickness?

2024-11-05 20:14 UTC, MitchellGoodwin requested changes
It looks like the for the horizontal divider, the CupertinoDynamicColor, `CupertinoColors.separator` isn't resolving itself so it's using the same color for all themes. https://github.com/flutter/flutter/blob/a942ab03399d9fd3e1abc0d13094c94b71806494/packages/flutter/lib/src/cupertino/dialog.dart#L379

The vertical dividers within the actions are resolving so they don't have an issue. Adding a resolve to that line should fix that.

2024-11-06 04:49 UTC, thejitenpatel commented
Hi @MitchellGoodwin,

Thanks for the suggestion! I tried using `CupertinoColors.separator.resolveFrom(context)` &
`final Color dividerColor = CupertinoDynamicColor.resolve(CupertinoColors.separator, context);` as recommended, but it doesn't seem to be working as expected. The divider color still isn’t adapting to the theme correctly. Do you have any additional suggestions or insights on what might be going wrong? Any help would be appreciated!

2024-11-06 05:45 UTC, dkwingsmt commented on packages/flutter/lib/src/cupertino/colors.dart
> +    darkElevatedColor: Color.fromARGB(153, 210, 210, 210),
Can you tell me why this change is needed? Actually I don't see where this variable is used in Cupertino...

2024-11-06 06:11 UTC, dkwingsmt commented
> Hi @MitchellGoodwin,
> 
> Thanks for the suggestion! I tried using `CupertinoColors.separator.resolveFrom(context)` & `final Color dividerColor = CupertinoDynamicColor.resolve(CupertinoColors.separator, context);` as recommended, but it doesn't seem to be working as expected. The divider color still isn’t adapting to the theme correctly. Do you have any additional suggestions or insights on what might be going wrong? Any help would be appreciated!

Have you checked whether the value of `dividerColor` has changed as intended?

2024-11-07 17:33 UTC, MitchellGoodwin commented
> The divider color still isn’t adapting to the theme correctly.

Is it showing as the same color as before? And is it not picking up the brightness, the elevation, or both?

`CupertinoDynamicColor.resolve` may need to be called further down. Possibly in the `_Divider` class itself.

2024-11-07 17:39 UTC, MitchellGoodwin commented
I haven't tested to be sure, but I believe that this PR didn't introduce that behavior, so it's not required to fix it in this PR. But my instinct is that the divider color will be an easy fix *somewhere*, it just may need some trial and error to find where it is. Give it a try and see what happens. If it doesn't work after a bit of trying, I'll approve the PR as-is and make a separate issue for that divider.

2024-11-10 12:26 UTC, thejitenpatel commented
Hi @dkwingsmt, 

I checked the `dividerColor`  is getting changed as intended but the Divider is not getting affected.

> > Hi @MitchellGoodwin,
> > Thanks for the suggestion! I tried using `CupertinoColors.separator.resolveFrom(context)` & `final Color dividerColor = CupertinoDynamicColor.resolve(CupertinoColors.separator, context);` as recommended, but it doesn't seem to be working as expected. The divider color still isn’t adapting to the theme correctly. Do you have any additional suggestions or insights on what might be going wrong? Any help would be appreciated!
> 
> Have you checked whether the value of `dividerColor` has changed as intended?

Hi @dkwingsmt,

I've checked that the `dividerColor` is changing as expected, but it seems the actual Divider itself isn't reflecting this change.

2024-11-10 12:33 UTC, thejitenpatel commented
> Is it showing as the same color as before? And is it not picking up the brightness, the elevation, or both?
> 
> `CupertinoDynamicColor.resolve` may need to be called further down. Possibly in the `_Divider` class itself.

@MitchellGoodwin, It’s showing as the same color as before—no noticeable change. It doesn’t seem to be picking up the brightness correctly, and the elevation appears to be slightly lower than expected. 

Attaching screenshot of this PR for your reference:

 <img src="https://github.com/user-attachments/assets/268dda8d-20c5-4719-aec1-7db1b58bc6e6" width="400"/>

2024-11-10 14:00 UTC, thejitenpatel commented
Hi @MitchellGoodwin,

You’re correct that this PR didn’t introduce the behavior. The issue occurs specifically when a horizontal divider is drawn—it doesn’t resolve the color as expected _(screenshot 1.0)_. It is taking `elevatedColor` property if I'm not wrong, whereas the vertical divider resolves it correctly via the `_CupertinoAlertActionSection` class _(screenshot 1.1)._

To address this, I added `CupertinoDynamicColor.resolve` in the `_CupertinoAlertDialogState` class, which helps resolve the color issue for the horizontal divider. However, it still doesn’t fully address the brightness, and the elevation appears slightly less than expected.

To further address the color issue, as suggested, I also applied `CupertinoDynamicColor.resolve` directly in the Divider class _(screenshot 1.2)_. The Color got resolved but it's not taking brightness if I am not wrong and elevation seems little less as expected _(screenshot 2.0)_.

Interestingly, if there are more than two buttons, all horizontal dividers render with the correct color, except for the first one _(screenshot 3.0)_

**Screenshot 1.0:**
<img width="1050" alt="Screnshot_1 0" src="https://github.com/user-attachments/assets/106be0af-814f-43ff-aadf-80e2fef31909">

**Screentshot 1.1:**
<img width="1047" alt="Screenshot_1 1" src="https://github.com/user-attachments/assets/a678a131-2c5c-453a-8b33-216aeb4592e7">

[Screenshot 1.2:](https://github.com/user-attachments/assets/247f0895-5bfa-4ae0-8214-570c0c154826)
<img width="1052" alt="Screenshot 2024-11-10 at 7 01 13 PM" src="https://github.com/user-attachments/assets/a1df5750-b7c9-4568-969b-a538df15a0fa">

**Screenshot 2.0: Dialog with single button in this PR**
 <img src="https://github.com/user-attachments/assets/d61e53d2-9b3c-452d-90b4-d05c44f5aa57" width="400"/>

**Screenshot 3.0: Current behavior after adding more than two buttons in this PR**
 <img src="https://github.com/user-attachments/assets/247f0895-5bfa-4ae0-8214-570c0c154826" width="400"/>

2024-11-10 19:27 UTC, dkwingsmt commented
Oh! You're right. I think I made a mistake at 
https://github.com/flutter/flutter/pull/150410/files#diff-4ea2907696de4fecf42f2ca56278a7b1d90c28921b1259d18ae28b1a2553d8e8R378

The `dividerColor` is never resolved here before being passed to `_Divider`, which doesn't resolve either. Thank you for your investigation!

2024-11-12 17:58 UTC, MitchellGoodwin approved these changes
@thejitenpatel thank you so much for looking into the divider, and submitting this PR in the first place. That officially sounds like a bigger pain to fix than I expected, so I'm going to approve this PR and create a separate issue for the divider. Thank you so much for the fix!

2024-11-12 17:59 UTC, merged