feature: implement createRegularWindow and add it to the reference app
flutter/flutter pull request #157515
Opened 2024-10-24 16:03 UTC by mattkae

This pull request:

- Lays the foundational data models for multi window Flutter applications
- Implements `createRegular` for the creation of regular toplevel windows
- Add the `multi_window_ref_app` example application to the project to demonstrate the creation of a regular window
- Add an initial unit test for the creation of regular windows
- Adapt the runner code of a typical single window application for multi window

![image](https://github.com/user-attachments/assets/b4d15a12-a38d-4253-8da9-7a153a5c15e6)

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

2024-10-30 18:14 UTC, justinmc commented
@mattkae Should we put all the subsequent PRs in draft mode for now (assuming they are not yet ready for review)? Just so other triagers don't get confused.

Thanks for all of this work by the way!

CC @loic-sharma @cbracken Any idea who should take on getting all of this reviewed?

2024-10-31 09:36 UTC, mattkae commented
> @mattkae Should we put all the subsequent PRs in draft mode for now (assuming they are not yet ready for review)? Just so other triagers don't get confused.

If you would prefer that, I can put the others in draft mode to avoid confusion :+1: 
 
> Thanks for all of this work by the way!

No problem :) Looking forward to working towards landing it !

2024-10-31 22:58 UTC, loic-sharma commented
> CC @loic-sharma @cbracken Any idea who should take on getting all of this reviewed?

I suspect @goderbauer would be the best person to review once he's back :)

2024-12-12 13:41 UTC, mattkae commented
@goderbauer @loic-sharma If you are interested, this PR now reflect "declarative API" that we settled on in the spec. The tests still need to be updated, but this should give you a sense of the general look-and-feel of the API as we've described it so far in the document.

2025-01-09 21:28 UTC, bkonyi commented
@goderbauer @jtmcdole can you find the right reviewers for this non-tool portions of this PR?

2025-02-03 01:54 UTC, robert-ancell commented on engine/src/flutter/shell/platform/windows/windowing_handler.cc
> +constexpr char kInvalidValueError[] = "Invalid Value";
In other channels this would be:
```
constexpr char kBadArgumentsError[] = "Bad Arguments";
```

2025-02-04 11:54 UTC, hbatagelo commented on engine/src/flutter/shell/platform/windows/windowing_handler.cc
> +constexpr char kInvalidValueError[] = "Invalid Value";
Done. Updated to `kBadArgumentsError`

2025-02-28 21:59 UTC, knopp commented
I am wondering if `--enable-multi-window` is the best way to go about this. Is there a reason why this would be a flag that has to be specified for each build, rather then either `flutter config` or enabled simply through embedder API? The launcher needs to be modified for multi-window anyway.

2025-03-01 19:50 UTC, knopp requested changes

2025-03-01 19:50 UTC, knopp commented on engine/src/flutter/shell/platform/common/windowing.h
> +}  // namespace flutter
I don't know how I feel about this. Especially when looking at later PRs, which seem to put quite a bit of additional logic here, like [positioning for popovers](https://github.com/canonical/flutter/blob/popup-menu/engine/src/flutter/shell/platform/common/windowing.cc). Yes, we share some code between embedders already, but this seems very different as it implements a specific algorithm.

We have formal embedder API, "informal" platform channels, and now we have algorithms that embedders are expected to implement, placed at arbitrary location in the engine. What about out of tree embedders?

Wouldn't it be better if something like [this](https://github.com/canonical/flutter/blob/popup-menu/engine/src/flutter/shell/platform/common/windowing.cc) was implemented in dart instead?

2025-03-02 22:54 UTC, robert-ancell commented on engine/src/flutter/shell/platform/common/windowing.h
> +}  // namespace flutter
In the case of positioning, modern compositors do this themselves, as an application never has all the context required to do this correctly (or is not allowed the context to maintain application isolation). For compositors that do not do this, the application needs to perform this, thus each compositor needs to implement this logic.

The difficulty in making shared dart code is the embedder is already running native code when it needs it. If we were to make this code run before requests reach the embedder it would make the API more complicated. In all cases, the shared code is more of a set of helper functions, as the behaviour always depends on the compositor in use.

2025-03-02 23:01 UTC, robert-ancell commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.cc
> +constexpr char kOnWindowCreatedMethod[] = "onWindowCreated";
This seems to be unused.

2025-03-02 23:07 UTC, robert-ancell commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.cc
> +                                        EncodableValue(size->height())})});
How does this compare with `FlutterEngineSendWindowMetricsEvent`? Can the size be different to the size of the view (i.e. the Flutter widget is combined with other native widgets). Can the application make use of the size information?

2025-03-02 23:10 UTC, robert-ancell approved these changes
My Windows knowledge is pretty limited, but the code looks good to me. The only serious thing I noticed is the interaction with the window size and the view size, which might just need some clarification to ensure developers don't mix up the two.

2025-03-02 23:17 UTC, robert-ancell commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.h
> +  // events "onWindowCreated", "onWindowDestroyed", and "onWindowChanged".
onWindowCreated doesn't seem to exist anymore.

2025-03-03 03:22 UTC, knopp commented on engine/src/flutter/shell/platform/common/windowing.h
> +}  // namespace flutter
I don't quite understand how this addresses my concern. There is no precedent for sharing logic between embedders in-tree like this and I think this definitely needs further discussion.

I have proposal for synchronous ffi-based API https://docs.flutter.dev/go/multi-window-api-ffi. With synchronous API we can easily move all this to Dart code so that it can be accessed by all embedders, not just the "blessed" ones.

2025-03-03 03:25 UTC, knopp commented
What is the reason for trying to merge this without the appropriate framework API? This is tightly coupled to new framework API, I don't quite understand how this can be reviewed and merged separately before approving the framework part.

2025-03-03 04:11 UTC, robert-ancell commented on engine/src/flutter/shell/platform/common/windowing.h
> +}  // namespace flutter
Is this not similar to the shared text input model code?

2025-03-03 04:32 UTC, knopp commented on engine/src/flutter/shell/platform/common/windowing.h
> +}  // namespace flutter
Very vaguely. TextInputModel doesn't implement particular algorithm, at least not in a way where all embedders rely on. For example on macOS we're only using a tiny subset of it. iOS or Android is not using it at all. So it's more of a utility class rather than defining logic that embedders are supposed to follow.

Also text input is one of the most problematic parts of Flutter, and if we were starting from scratch we would be likely using a very different approach, see https://github.com/flutter/flutter/issues/150460. So modeling new code after text input doesn't seem like the best idea.

2025-03-03 08:28 UTC, Saviq commented on engine/src/flutter/shell/platform/common/windowing.h
> +}  // namespace flutter
That's actually how this is meant to be used - as helpers - depending on platform, the embedder might use e.g. the positioner information itself (like on Windows) - on others (like Wayland) that context will be passed on verbatim to the compositor, so there's no point in making those calculations in Flutter at all. On others yet, child windows might not be supported altogether (mobile platforms, automotive).

The implementation here will only be shared between platforms that can meaningfully make use of it (floating window desktops - which sure, are the majority of them, but not all). Other platforms should default to not supporting child windows until/unless they grow support for at least a subset of them.

2025-03-03 13:16 UTC, mattkae commented
> What is the reason for trying to merge this without the appropriate framework API? This is tightly coupled to added framework API, I don't quite understand how this can be reviewed and merged separately before approving the framework part.

The reason is that the Google folks don't want to land a public API until (1) all multi-view bugs have been fixed and (2) we are certain that the API changes are more-or-less final.

@loic-sharma can provide more details, but we settled on this in the end to make things move faster :)

2025-03-03 14:10 UTC, knopp commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.cc
> +    case WM_NCDESTROY: {
Window destroying flow probably needs some thought? A very common scenario is displaying a prompt when closing the window (i.e. to prevent closing unsaved documents).

2025-03-03 15:52 UTC, weltkante commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.cc
> +    case WM_NCDESTROY: {
WM_NCDESTROY is just for cleanup of resources after closing, the window is already closed and being torn down

2025-03-04 16:39 UTC, knopp commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.cc
> +    case WM_NCDESTROY: {
I meant the overall flow. For example destroying the window from Flutter involoves sending `WM_CLOSE`. But WM_CLOSE is the one message we should actually handle, prevent default and notify the framework so that we can give the user a way to prevent closing of windows if needed.

2025-03-04 16:49 UTC, knopp commented
Here is my work in progress branch based on this work but converting it to ffi: https://github.com/knopp/flutter/tree/windows_multi_window_ffi

It's bit rough but it mostly works.

If you compare the [`window.dart`](https://github.com/knopp/flutter/blob/windows_multi_window_ffi/packages/flutter/lib/src/widgets/window.dart) to original you will notice that it doesn't need any futures, `isReady` checks or future builders.

It also doesn't need to need to sync state from native (i.e. size). There is only one source of truth and that is whatever winapi provides.

The prototype also allows handling win32 messages in [dart code](https://github.com/knopp/flutter/blob/915c7bb2dbc771159fd19bda78acade8f50a55a9/packages/flutter/lib/src/widgets/window_win32.dart#L183-L195). Down the line this would allow for packages to customized window behavior, i.e. overriding `WM_NCHITTEST` which is required to make custom frame windows.

2025-03-11 15:41 UTC, hbatagelo commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.cc
> +                                        EncodableValue(size->height())})});
They are essentially the same size. `onWindowChanged` sends the size of the client rectangle of the top-level window, which corresponds to the size of root view in logical coordinates.

2025-03-11 17:15 UTC, hbatagelo commented on engine/src/flutter/shell/platform/windows/flutter_host_window_controller.cc
> +    case WM_NCDESTROY: {
`WM_CLOSE` is handled by the app lifecycle manager, but it only works for the last window. We expected to have a proper window lifecycle manager for this. Anyway, the delegate pattern you're using in the FFI branch seems like a nice, cleaner alternative.

2025-03-11 17:24 UTC, knopp commented
I think down the line we want to refer to size as clientSize or contentSize (I'd vote for contentSize). Some platforms support setting frame size too, and we will want to expose it, even if it's per platform specific call. So it would not good to get rid of ambiguity from beginning.

2025-03-27 02:24 UTC, wanjm commented
how much work left before it can be merged?

2025-03-27 08:05 UTC, Saviq commented
@wanjm there's a new approach to crossing the Dart / native boundary in the works:

https://github.com/flutter/flutter/pull/165072
https://docs.google.com/document/d/1UEaxd_aIlsPMzkfB6oyeYaKzwHadrWGyMzOS33oSbK4/edit

Not too long! We have agreement on the Dart API, multi-view prerequisites mostly dealt with, just need to work things out on the three desktop platforms so we're confident with the solution.

2025-04-03 15:51 UTC, GroovinChip commented
> @wanjm there's a new approach to crossing the Dart / native boundary in the works:
> 
> #165072 https://docs.google.com/document/d/1UEaxd_aIlsPMzkfB6oyeYaKzwHadrWGyMzOS33oSbK4/edit
> 
> Not too long! We have agreement on the Dart API, multi-view prerequisites mostly dealt with, just need to work things out on the three desktop platforms so we're confident with the solution.

Is the plan to move over to this approach, or to continue on with method channels until the FFI approach is finalized and ready? If the plan is to switch to FFI now, does that impact the time until multi-window can be delivered?

2025-04-03 17:05 UTC, Saviq commented
> Is the plan to move over to this approach, or to continue on with method channels until the FFI approach is finalized and ready? If the plan is to switch to FFI now, does that impact the time until multi-window can be delivered?

Pan is to go for FFI, no point introducing a lot of code that will be dropped soon. Yes, it does mean it's delayed some weeks. But it's closer than you might think: #165072.

2025-04-03 17:40 UTC, GroovinChip commented
Thanks for the reply! Glad the delay will only be a few weeks.

2025-05-22 18:14 UTC, mattkae commented
The implementation of multi-window in Flutter has drifted a lot since this PR was opened. Please see https://github.com/flutter/flutter/pull/168728 for the latest implementation. We're currently focusing on an FFI-based approach in contrast to the async method channels approach that we implemented here.

2025-05-22 18:14 UTC, closed without merging