Allow namespaces when generating localization
flutter/flutter pull request #157696
Opened 2024-10-27 21:31 UTC by ricardodalarme

## Description

This PR introduces a feature that allows developers to organize their localization files by namespace. This change facilitates improved organization and management of localization files, particularly in projects with extensive localization needs. By segmenting ARB files into logical categories, developers can avoid files with thousands of messages, enhancing maintainability and readability.

#### Namespace-Based Directory Structure

The namespaces are generated based on the subdirectory hierarchy of the input directory. For instance, given the following structure:

```
/arb
- /login
  - login_en.arb
  - login_pt.arb
- /home
  - home_en.arb
  - home_pt.arb
```

each subdirectory (e.g., login, home) creates a distinct namespace for organizing ARB files, allowing localized content to be grouped logically by feature or component.

#### Backward Compatibility

This feature is fully backward-compatible; projects may continue to use a single ARB file structure at the root level if preferred. Existing projects will experience no changes unless they opt into this new organization structure, preserving the default behavior.

## Related Issues

- Closes #107157 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2024-10-28 15:47 UTC, devnoaman commented
Great job. I can't wait to use it 👏🏆

2024-11-07 08:21 UTC, Anemony22 commented
This is exactly what we need! Excited for this to be merged 🎉

2024-11-14 09:43 UTC, devnoaman commented
@TahaTesser please we need you to review this important pull request , thanks

2024-11-14 16:17 UTC, TahaTesser commented
> @TahaTesser please we need you to review this important pull request , thanks

Thanks the nudge. I'm not sure if i'm the best person to review this. @chunhtai might be able to help.

2024-11-14 19:25 UTC, chunhtai reviewed
do we force the developer to be in folder structure if they set the name space? that seems like a breaking change. Previously people can define stock_en.arb and have file in the root folder, but now it will force it to have its subfolder.

Not saving that is a bad change, but it may break some ci of existing project.

2024-11-14 19:25 UTC, chunhtai commented on packages/flutter_tools/lib/src/localizations/gen_l10n_types.dart
> +class Namespace {
This class doesn't seem useful, why not use String as type for namespace directly

2024-11-14 20:52 UTC, ricardodalarme commented
hey @chunhtai, thanks for the review! I made it so that it is fully backwards compatible. All projects that exist today will continue to work normally, users will still be able to define a stock_en.arb in the root directory, and they will still be able to specify the `template-arb-file`.  Nothing will break. The namespace feature will only be "enabled" if they decide to create subfolders (they can also have a file without namespace in the root folder and others in subfolders).

2024-12-04 01:02 UTC, ricardodalarme commented
hey @chunhtai @christopherfujino can I get a review?

2024-12-05 17:20 UTC, andrewkolos requested changes
Hi, sorry for the delay here. Thanks for interest in improving localization in Flutter!

The concept here seems like a good start to me, but the PR description doesn't walk through the full user story here. Let's see if I understand:

Users can create subdirectories within their `arb-dir` (as typically specified within the `l10n.yaml` file). Any directories within these subdirectories are ignored. Let's consider an example directory structure similar to the one from the PR description:

```
.
└── arb/
    ├── home/
    │   ├── home_en.arb
    │   └── home_es.arb
    ├── login/
    │   ├── login_en.arb
    │   └── login_es.arb
    ├── app_en.arb
    └── app_es.arb
```

Let's suppose these files have the following contents:

```jsonc
// arb/home/home_en.arb
{
  "@@locale": "en",
  "heading": "Welcome"
}
// arb/home/home_es.arb
{
  "@@locale": "es",
  "heading": "Bienvenido"
}

// arb/login/login_en.arb
{
  "@@locale": "en",
  "instructions": "Log in"
}
// arb/login/login_es.arb
{
  "@@locale": "es",
  "instructions": "Inicia sesión"
}

// arb/app_en.arb
{
  "@@locale": "en",
  "back": "Back"
}

// arb/app_es.arb
{
  "@@locale": "es",
  "back": "Volver"
}
```

Then, the  `AppLocalizations` class generated to get localized messages at runtime would look like this:
```dart
abstract class AppLocalizations {
  /* ... */
  String get back;
  String get home_heading;
  String get login_instructions;
}
```

Notice the `home_` and `login_` prefixes. This is the namespacing provided by this change. I've published this as a demo here: https://github.com/andrewkolos/_localization_namespaces_example.

Assuming I understand everything correctly, this change makes sense to me and would be a nice improvement at the cost of some additional code complexity and a deprecation process. Still, I wonder if there are projects that would benefit even more from further-nested subdirectories. Like me explain with an example:

```
.
└── arb/
    ├── feature_1/
    │   ├── feature_1_1
    │   ├── feature_1_2
    │   └── feature_1_3
    └── feature_2/
        ├── feature_2_1
        ├── feature_2_2
        └── feature_2_3
```

In this example, any `.arb` files under `feature_1_1`, `feature_1_2`, etc. would be ignored. I wonder if this will surprise some users if they don't carefully read the feature documentation. Maybe we could generate subclasses that are used like so:
```dart
final localizations = AppLocalizations.of(context)!.feature_1.feature_1_1;
return Text(localizations.fooMessage);
```

Regardless, this would make for some significantly more complex code generation logic, so I'm fine with going with this approach as-is. 

While I need to ask around for some more opinions today/tomorrow, I have some feedback I can provide now:
* Code generation needs to ensure that subfolder names are valid Dart identifiers. For example, if I have a `arb/@123@` directory, then generated members would look something like `@123@_heading`, which isn't valid Dart and wouldn't compile.
* The error message explaining that `"Multiple arb files with the same '\<language\>' locale detected."` needs to be updated since multiple arb files with the same locale are now allowed (as long as they aren't in the same directory).
* The name of the new `AppResourceGroupCollection` class is a bit ambiguous when considered together with `AppResourceBundleCollection`. The code comments provided helps explain the differences, but I wonder if this could be improved. Maybe `AppResourceNamespaceCollection` would map better to the idea of the feature being provided here.

2025-01-30 21:07 UTC, bkonyi commented
@QuncCccccc do you have any thoughts on this proposal?

2025-01-31 00:35 UTC, Piinks commented
I am curious for @ricardodalarme's thoughts on @andrewkolos's feedback in https://github.com/flutter/flutter/pull/157696#pullrequestreview-2482394351

There are also some merge conflicts here now.

@ricardodalarme would you like to continue working on this change?

2025-01-31 14:06 UTC, cedvdb commented
While I agree with @andrewkolos comment that subdirectories must be supported, I'm opposed to generating a path based on the directory names. The namespace should be purely based on the .arb file name.

Renaming and moving directories should not cause issues.

2025-04-02 22:19 UTC, Piinks commented
Following up on https://github.com/flutter/flutter/pull/157696#issuecomment-2626021704
Since we have not heard back in a few months, we are going to regrettably close this PR.
Thank you @ricardodalarme for your work here. If you would like to return to this, let us know! Thanks!

2025-04-02 22:19 UTC, closed without merging