Fixes crash in SliverAnimatedList
flutter/flutter pull request #157786
Opened 2024-10-29 12:41 UTC by Mairramer

Fixes https://github.com/flutter/flutter/issues/153922
Refactored reordering logic in SliverAnimatedList to handle duplicate keys and improve removal stability to handle this behavior.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2024-11-10 22:06 UTC, nate-thegrate reviewed
Hi @Mairramer, thanks for the contribution!

And sorry for the delay—I've been deep in the rabbit hole of "making a package for pub.dev" this week 🙂

<br>

I tried running the example code from https://github.com/flutter/flutter/issues/153922#issuecomment-2304830850 against this branch, unfortunately it looks like a crash can still be reliably triggered by following the instructions there, starting with an `assert()` failing in [**sliver_multi_box_adaptor.dart**](https://github.com/Mairramer/flutter/blob/fix/crash-in-sliverAnimatedList/packages/flutter/lib/src/rendering/sliver_multi_box_adaptor.dart):

```diff
bool _debugVerifyChildOrder() {
  if (_debugChildIntegrityEnabled) {
    RenderBox? child = firstChild;
    int index;
    while (child != null) {
      index = indexOf(child);
      child = childAfter(child);
!!    assert(child == null || indexOf(child) > index);    !!
    }
  }
  return true;
}
```

<br>

It's a struggle for me to wrap my head around sliver render object element logic—huge props to you for working on this fix. Hopefully we can figure this one out!

2024-11-11 12:57 UTC, Mairramer commented
@nate-thegrate The problem seems to come from [updateSlot](https://github.com/Mairramer/flutter/blob/5f55630b84a05b4fd0dc3eec80064f568ab82d4a/packages/flutter/lib/src/widgets/framework.dart#L6717C2-L6725C4), inside `framework.dart`. 
It is picking up slots that no longer exist, but that are still somehow active in the tree before being actually removed.

2024-11-12 23:34 UTC, victorsanni approved these changes
LGTM with nits, but I would wait to get feedback from someone more knowledgeable on slivers like @Piinks.

2024-11-12 23:34 UTC, victorsanni commented on packages/flutter/lib/src/widgets/sliver.dart
> +
```suggestion
```

2024-11-12 23:34 UTC, victorsanni commented on packages/flutter/lib/src/widgets/sliver.dart
> +
```suggestion
```

2024-11-12 23:34 UTC, victorsanni commented on packages/flutter/lib/src/widgets/sliver.dart
> +            // Handle duplicates: skip direct reordering, and add to the next available slot later.
This line seems a little confusing to me. Is it stating how duplicates should be handled? A clearer sentence would be nice.

2024-11-12 23:34 UTC, victorsanni commented on packages/flutter/lib/src/widgets/sliver.dart
> +          // Prevents the remapped child from being deactivated during processElement by using availableIndex.
I don't immediately see a benefit to adding the `by using availableIndex` suffix. The line of code just below shows it's being used already?

2024-11-12 23:34 UTC, victorsanni commented on packages/flutter/test/widgets/animated_list_test.dart
> +      // get all list entries in order
```suggestion
      // Get all list entries in order.
```

2024-11-12 23:34 UTC, victorsanni commented on packages/flutter/test/widgets/animated_list_test.dart
> +      // Remove the first item
```suggestion
      // Remove the first item.
```

2024-11-13 00:05 UTC, nate-thegrate reviewed
The linked issue's [code sample](https://github.com/flutter/flutter/issues/153922#issuecomment-2304830850) works now! 🎉

Just a couple of small things from me, but I agree with @victorsanni: it'd be nice to get this looked over by someone with more expertise in this area before we merge.

2024-11-13 18:25 UTC, nate-thegrate approved these changes
LGTM, thanks for the fix!

2024-11-13 18:25 UTC, nate-thegrate commented on packages/flutter/lib/src/widgets/sliver.dart
> +        // Checks if the provided key has a duplicate.
trivial whitespace nit:

```suggestion

      // Checks if the provided key has a duplicate.
      bool hasDuplicate(Key? key) {
```

<br>

(the current version is based on [my suggestion](https://github.com/flutter/flutter/pull/157786#discussion_r1838878412), sorry about that!)

2024-11-13 19:23 UTC, chunhtai requested changes
having a duplicate key in children is not a valid use case. or doc explicitly mentioned that
https://api.flutter.dev/flutter/foundation/LocalKey-class.html

2024-11-13 19:26 UTC, Piinks commented
Yeah, I thought so too when I saw this. A duplicate key does not sound valid to me.

2024-11-13 19:44 UTC, Mairramer commented
@Piinks @chunhtai If that’s the case, the solution might be simpler than I thought. Just one question: can I disregard the implementation I wrote? Blocking duplicates seems easier, but I’ll need to check if there are other scenarios to consider.

2024-11-13 19:46 UTC, nate-thegrate commented
To summarize the request from #153922: if an item's "remove animation" is in progress, and another item with the same key is added, it should just un-remove the item instead of trying to add a different one.

In my opinion, the current PR is an effective solution, but that's not saying much, given my lack of knowledge in this area 😅

2024-11-13 21:19 UTC, chunhtai commented
I agree we should do something about SilverAnimatedList, but we should not relax the restriction on SliverMultiBoxAdaptorElement directly.

Can we do something like having have an internal keysubtree on all the sliveranimatedlist child that can keep track of different "generation" of the child so that it won't crash when readding the child back while the animation is still on going?

2024-11-14 20:06 UTC, Mairramer commented
> I agree we should do something about SilverAnimatedList, but we should not relax the restriction on SliverMultiBoxAdaptorElement directly.
> 
> Can we do something like having have an internal keysubtree on all the sliveranimatedlist child that can keep track of different "generation" of the child so that it won't crash when readding the child back while the animation is still on going?

I implemented a solution within `SliverChildBuilderDelegate`. I created an initial implementation that worked to some extent, but I'm still considering how to handle some regressions that have cropped up.

2024-12-10 23:17 UTC, goderbauer commented
(triage) @Mairramer Just checking in if this PR is still on your radar. Will you continue working on this?

2025-01-10 21:17 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sliver.dart
> +    if (child != null) {
we shouldn't be doing this in the SliverMultiBoxAdaptorElement. This class doesn't have knowledge about why the temporary duplication occur. The reassigning key should be in SliverAnimatedList

2025-01-22 13:29 UTC, Mairramer commented on packages/flutter/lib/src/widgets/sliver.dart
> +    if (child != null) {
Sorry for the delay (1 month away from code).
The reason I put it here is because the key type doesn't affect the assertion. I'm looking to see if there's a better way.

2025-02-04 23:17 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sliver.dart
> +    if (child != null) {
I think we need to do this some where else, if It has to be done in this level, we should consider create a common base class from `SliverMultiBoxAdaptorElement` and the SliverAnimatedList can create its own subclass that allows temporary duplication

2025-02-05 21:25 UTC, chunhtai reviewed
See my latest comment https://github.com/flutter/flutter/pull/157786#discussion_r1942025871

2025-02-06 14:56 UTC, Mairramer commented
@chunhtai I was reviewing the code today and realized I was mistaken—actually, the key type does have an impact. Currently, I'm considering two solutions: one would be to block the insertion of widgets with duplicate keys, or alternatively, insert them at a new index (as I was doing before).

2025-02-11 20:08 UTC, closed without merging