Update CHANGELOG.md to correct ios vs macos issue
flutter/flutter pull request #157822
Opened 2024-10-29 19:28 UTC by reidbaker

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [x] All existing and new tests are passing.

2024-10-29 19:30 UTC, christopherfujino approved these changes
LGTM

2024-10-29 19:33 UTC, jmagman requested changes

2024-10-29 19:33 UTC, jmagman commented on CHANGELOG.md
>  - [flutter/155837](https://github.com/flutter/flutter/pull/15578) - [Tool] Fixes RPCError crash when setting up log filtering for Android devices.
```suggestion
- [flutter/155837](https://github.com/flutter/flutter/pull/155837) - [Tool] Fixes RPCError crash when setting up log filtering for Android devices.
```

2024-10-29 19:33 UTC, jmagman commented on CHANGELOG.md
> +- [flutter/154915](https://github.com/flutter/engine/pull/55366) - [MacOS] Comply with the new Apple privacy manifest policy for the macOS Flutter engine framework and prevent the "Missing privacy ma
```suggestion
- [flutter/154915](https://github.com/flutter/engine/pull/55366) - [macOS] Comply with the new Apple privacy manifest policy for the macOS Flutter engine framework and prevent the "Missing privacy manifest" warning when submitting a macOS app to the App Store.
```

2024-10-29 19:33 UTC, jmagman commented on CHANGELOG.md
>  - [flutter/155837](https://github.com/flutter/flutter/pull/15578) - [Tool] Fixes RPCError crash when setting up log filtering for Android devices.
You beat me to it.

2024-10-29 19:35 UTC, jmagman commented
@reidbaker perhaps the release process should be updated so the author or TL approver also made a reviewer on the CHANGELOG commit?

2024-10-29 19:37 UTC, reidbaker commented
> @reidbaker perhaps the release process should be updated so the author or TL approver also made a reviewer on the CHANGELOG commit?

We recently changed the process from release engineer authored changes to cherry pick requestor authored changes. I do think updating the changelog makes sense. The issue most will run into is that it will cause conflicts as each change is landed.

2024-10-29 20:01 UTC, jmagman approved these changes
LGTM thank you!

2024-10-29 20:03 UTC, jmagman commented
> > @reidbaker perhaps the release process should be updated so the author or TL approver also made a reviewer on the CHANGELOG commit?
> 
> We recently changed the process from release engineer authored changes to cherry pick requestor authored changes. I do think updating the changelog makes sense. The issue most will run into is that it will cause conflicts as each change is landed.

I meant when release engineer sends out the changelog PR they could add the relevant authors as reviewers, or maybe only cc them would be sufficient to not slow down the release engineer.  Just a thought, it's not that important.  Thank you!

2024-10-30 09:33 UTC, kjxbyz commented
Why can't the version and changelog be released synchronously? Why does it take some time or even require creating an issue to solve it?

2024-10-30 14:07 UTC, merged

2024-10-30 14:08 UTC, reidbaker commented
> Why can't the version and changelog be released synchronously? Why does it take some time or even require creating an issue to solve it?

They can if the release engineer (me) does not make a mistake during the release process by shipping a build without the changelog updated. As to the why it takes time that answer is longer than I wish to type but the short version is about the security of the machines that can make a signed build, machine to machine access to signing keys and multi person authorization requirements for generating signed builds.