[tool] Building flavours with native tooling
flutter/flutter pull request #157871
Opened 2024-10-30 17:22 UTC by Sameri11

fixes #155951 

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2025-01-27 20:35 UTC, andrewkolos approved these changes
LGTM overall with a few comments

2025-01-27 20:35 UTC, andrewkolos commented on dev/devicelab/bin/tasks/flavors_test_ios.dart
> +        await _testFlavorsWorkWhenBuiltWithXcodebuild(projectDir),
Similarly to my previous comment, would `_testFlavorsWhenBuildStartsWithXcode` be descriptive of the fact that the build does not start with the `flutter` CLI?

2025-01-27 20:35 UTC, andrewkolos commented on dev/integration_tests/flavors/lib/main.dart
> +              : Text(appFlavor!, key: const ValueKey<String>('flavor')),
I don't _think_ this use of method channels is linked to as an example in any documentation. Assuming this is the case, this should be safe to remove.

Here is the native Android half of this method channel: https://github.com/flutter/flutter/blob/02b1146cff6f6515133c7483b40afbc2f36cf919/dev/integration_tests/flavors/android/app/src/main/java/com/yourcompany/flavors/MainActivity.java#L16

Here is the corresponding iOS part: https://github.com/flutter/flutter/blob/449f4a6673f6d89609b078eb2b595dee62fd1c79/dev/integration_tests/flavors/ios/Runner/AppDelegate.m#L14

2025-01-28 17:53 UTC, Sameri11 commented on packages/flutter_tools/bin/macos_assemble.sh
> +    fi
I don't think that there is *known* need, but:

1. FLAVOR could be used as environment variable earlier. If we let flavor be set exclusively by script (calculating from scheme name) – it might break existing behavior. 
2. There is no enforcement other than documentation for scheme naming, so it's safe to assume that there're projects exist that use other naming. Examples: https://github.com/flutter/flutter/issues/148537 where naming is different.

2025-01-28 18:01 UTC, Sameri11 commented on dev/devicelab/bin/tasks/flavors_test.dart
> +Future<TaskResult> _testFlavorsWorkWhenBuiltWithGradle(String projectDir) async {
It is, thanks!

2025-01-28 18:01 UTC, Sameri11 commented on dev/devicelab/bin/tasks/flavors_test_ios.dart
> +        await _testFlavorsWorkWhenBuiltWithXcodebuild(projectDir),
I agree, thanks!

2025-01-28 18:45 UTC, Sameri11 commented on dev/integration_tests/flavors/lib/main.dart
> +              : Text(appFlavor!, key: const ValueKey<String>('flavor')),
understood, thanks :) Will address this a bit later.

2025-01-29 14:23 UTC, Sameri11 commented on dev/integration_tests/flavors/lib/main.dart
> +              : Text(appFlavor!, key: const ValueKey<String>('flavor')),
Done!

2025-01-29 14:27 UTC, Sameri11 commented
I guess I also need a second review. Maybe, @jmagman as an issue reporter and also expert in iOS/macOS-related stuff ?

2025-01-29 14:31 UTC, Sameri11 commented
Regarding `Mac_ios flavors_test_ios`. This test definitely had hard times in this request 😅 Dashboard is [here](https://ci.chromium.org/ui/p/flutter/builders/try/Mac_ios%20flavors_test_ios), 20+ launches, all failed due to infra issues. My best guess is that device pool is problem here, because on master this suite runs pretty stable and good: [link](https://ci.chromium.org/ui/p/flutter/builders/prod/Mac_ios%20flavors_test_ios). And it runs on different pool.

So, question: is it possible to reassign device pool to test? I can't do this, obviously, but in general, by team-members? And if not, is it okay to merge it with `bringup: true` and monitor (and fix, if necessary) afterwards ?

2025-01-30 21:21 UTC, bkonyi commented
@Sameri11 were the changes to ci.yaml intentional and/or intended to be submitted with this PR? If we revert the changes to that file I _think_ the checks should pass.

2025-01-30 21:26 UTC, andrewkolos commented
I think it's okay to not test this on presubmit CI. In the worst case scenario, `flavors_test` and `flavors_test_ios` will fail in postsubmit, and this PR will get reverted, which isn't a huge deal. When I get back to my desk, I can try running these locally to get some confidence that these will still work. After that, I can revert the ci.yaml changes and get this merged 🙂

2025-01-30 23:22 UTC, andrewkolos requested changes
I think the new `_testFlavorsWhenBuildStartsWithXcode` doesn't work. I tested this on a physical iphone by running
```
dart bin/test_runner.dart test -t flavors_test_ios --exit
```

within the devicelab directory.

I think the `xcodebuild` command might be incorrect (for starters, I think `'-scheme paid'` needs to be `'-scheme', '-paid'`).

Logs: https://gist.github.com/andrewkolos/2786de8d5fd521ea697b151b3fb54906

Perhaps the `xcodebuild` calls in `dev/devicelab/bin/tasks/module_test_ios.dart` could be used for inspiration? Unfortunately, I don't think I have the time to debug this myself.

2025-01-31 00:32 UTC, jmagman requested changes

2025-01-31 00:32 UTC, jmagman commented on packages/flutter_tools/bin/xcode_backend.dart
> +    if (environment['CONFIGURATION'] != null) {
I don't think we should duplicate the existing (more complicated) flavor parsing logic that's already in the tool (this is a stand-alone script).  For example this doesn't handle the difference in casing between configurations and flavors https://github.com/flutter/flutter/pull/161455

In https://github.com/flutter/flutter/issues/155951 I was trying to say that the logic in the assemble build target should reuse the same logic as passed into `--flavor`.  I don't want anything extra to be set by the developer in a build configuration, and I don't want it to be possible for setting an extra build setting to get out of sync with the parsed schemes and build configurations.

2025-01-31 00:32 UTC, jmagman commented on packages/flutter_tools/lib/src/commands/assemble.dart
> +    if (results.containsKey(kFlavor) && results[kFlavor]!.isNotEmpty) {
I think this should be done instead in the ios and macos assemble target steps based on the same logic used to parse configuration and schemes that already exist in xcodeproj, and then from there sent it into the GenSnapshot (if I'm remembering how this works).

2025-01-31 05:28 UTC, Sameri11 commented
@andrewkolos Thanks for your effort and time you spend dealing with new tests. It didn't occur to me that I can test it locally – will try and fix those.

2025-01-31 05:33 UTC, Sameri11 commented
@bkonyi changes to .ci.yaml is a subject to be reverted / reset – the idea was to make tests green, check it in presubmit, and then revert those changes before merge.

2025-02-03 19:11 UTC, Sameri11 commented on packages/flutter_tools/bin/xcode_backend.dart
> +    if (environment['CONFIGURATION'] != null) {
I agree that this is the most fragile part of PR. I just want to clarify the intention here: the idea was to provide some default for the case when a developer didn't provide a custom configuration through which FLAVOR can be obtained inside an Xcode-started build. By custom configuration, I mean `.xcconfig` or any other method that will "inject" this variable.

Imagine the situation:
1. A developer adds flavors as described in [[documentation](https://docs.flutter.dev/deployment/flavors#creating-flavors-in-ios-and-macos)](https://docs.flutter.dev/deployment/flavors#creating-flavors-in-ios-and-macos).
2. Builds the app with `flutter build ...` – everything works.
3. Builds the app with Xcode – everything works too, but `app_flavor` at runtime is still `null`.

I thought this flow was kind of confusing when I implemented this PR and decided to add some default in such a way that it will work for the default case described above. For developers who have already created a custom way to provide FLAVOR from Xcode itself, this shouldn't break anything since there's an early return if FLAVOR is already set. This also won't break `flutter build ...` because the FLAVOR environment variable would be set, and everything will stay in sync.

Now, again, it's fragile, and I won't fight for this change, obviously :) Those changes to the `xcode_backend` scripts can be reverted, and everything will work, with one exception: it will be the developer's responsibility to provide FLAVOR for the build when it's invoked with Xcode.

So yeah, I need an confirmation (after this explanation) that this change is still undesired.

2025-02-03 19:16 UTC, Sameri11 commented on packages/flutter_tools/lib/src/commands/assemble.dart
> +    if (results.containsKey(kFlavor) && results[kFlavor]!.isNotEmpty) {
> should be done instead in the ios and macos assemble target steps

Could you please elaborate on the advantages of this move? I am obviously not an expert here, so I can't see any for now :( But if it is done, I believe there will be code duplication since it will require moving Android's implementation somewhere. Doing the same thing in 2-3 places when it can be done in a single location (as in the current PR state) – I believe that was the main motivation to implement parsing here.

Or maybe I completely misunderstood your comment?

2025-02-04 06:25 UTC, Sameri11 commented on dev/integration_tests/flavors/ios/Runner.xcodeproj/project.pbxproj
> +				);
Seems like these changes have been formatted by Xcode when I opened project in it. Should it be reverted or it's ok ?

2025-02-04 06:26 UTC, Sameri11 commented
`flavors_test_ios` should work now. At least, it worked locally in my environment :)

2025-02-11 16:38 UTC, vashworth commented
@Sameri11 Thanks for working on this issue. I agree with your approach of attempting to parse the flavor/scheme from the configuration, however, I also agree with @jmagman that it should be moved into the assemble targets. Since this would require many changes and is difficult to explain, I went ahead and put together a PR to handle the iOS/macOS/Xcode side of things (https://github.com/flutter/flutter/pull/162907).

I will defer to @andrewkolos and @bkonyi on the Android side of things

2025-02-11 16:50 UTC, bkonyi commented
@reidbaker do you have any thoughts on this WRT the Android side of things?

2025-02-11 17:30 UTC, Sameri11 commented
@vashworth thanks for letting me know.

2025-02-11 17:57 UTC, closed without merging

2025-02-12 16:01 UTC, reidbaker commented
@Sameri11 did you still want review on the android side?