Add optional parameter to FlutterTesterDevices.
flutter/flutter pull request #158133
Opened 2024-11-04 21:21 UTC by polina-c

This is to handle Google testing failures for  https://github.com/flutter/flutter/pull/158126.

2024-11-04 21:26 UTC, matanlurey commented
You _can_ do this, but I think this is better done as a G3Fix when rolling, no?

2024-11-04 21:26 UTC, matanlurey requested changes
Let's consider a G3Fix instead of this approach, if able.

2024-11-04 23:24 UTC, matanlurey commented
Polina, any update?

2024-11-05 00:42 UTC, polina-c commented
There are issues with G3Fix: b/377380166

2024-11-05 00:48 UTC, matanlurey requested changes

2024-11-05 00:48 UTC, matanlurey commented on packages/flutter_tools/lib/src/tester/flutter_tester.dart
> +    // ignore: avoid_unused_constructor_parameters, temporarily unused to prepare G3.
Do you need to add back the parameter?

2024-11-05 00:55 UTC, polina-c commented on packages/flutter_tools/lib/src/tester/flutter_tester.dart
> +    // ignore: avoid_unused_constructor_parameters, temporarily unused to prepare G3.
oh, thanks, added

2024-11-05 00:56 UTC, matanlurey approved these changes

2024-11-05 02:09 UTC, merged

2024-11-05 18:23 UTC, polina-c commented
This PR bypassed testing exempt, because it was high priority to re-land PRs.