[Proof of concept] Implement setting content sensitivity on Android
flutter/flutter pull request #158473
Opened 2024-11-11 19:44 UTC by camsim99

> [!NOTE]  
> This is just a proof of concept that I'm using for discussion purposes with other engineers :)

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2025-01-07 20:52 UTC, camsim99 commented
Looking for feedback on the approach presented in this PR and the open questions I have before writing tests.

2025-01-08 23:03 UTC, justinmc reviewed
Drive-by review here. I still want to look more closely at the SensitiveContent widget and maybe play with it locally. At a high level though, this approach seems good and it looks like things worked as we thought they would. I'll post back tomorrow.

One thing I remember from your Dash Forum session was we thought we would need to use FFI to communicate with the engine. Is that requirement out of date now?

Oh and I struggled in getting one of my engine/framework projects to run in the monorepo when I got back from break. I updated some docs in the process, maybe check that or feel free to reach out if you need to try it in the monorepo and get stuck. https://github.com/flutter/flutter/pull/161184

2025-01-10 15:48 UTC, reidbaker commented
"so we will investigate using JNIgen in the future" I believe we should say that we do not plan to release the feature without evaluating if frame drops can occur.

2025-01-10 15:51 UTC, reidbaker commented
"Implements setting content sensitivity on Android via a new plugin called SensitiveContent" 

Most flutter users would view plugin in this context as something that should probably be in flutter/packages. 
Maybe call it a FrameworkPlugin or just say we are adding a new way to mark content sensitive without mentioning the implementation detail of a plugin.

2025-01-10 15:52 UTC, reidbaker commented
In the pr description consider trying to more cleanly describe what is work that needs to happen in this pr but has intentionally  not happened. What work is future work but still required before we ship the feature and what is work that is future work that is unplanned.

2025-01-10 16:24 UTC, reidbaker reviewed
Reviewed android code will do a different pass on dart code later.

2025-01-10 16:24 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +            Log.v(
This logging is fine for now but probably more verbose than we want to ship.

2025-01-10 16:24 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +            default:
Consider a log here. It isnt actionable for flutter framework users but it would be highly actionable for us if we accidently messed up here.

2025-01-10 16:24 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +            && contentSensitivity != View.CONTENT_SENSITIVITY_SENSITIVE;
I found this a bit tough to parse but what I am seeing is that if the view is sensitive and we just set the view to sensitive the invalidate.

I think the logic you want is 
```
final int currentContentSensitivity = flutterView.getContentSensitivity();
if (currentContentSensitivity != contentSensitivity) { 
    flutterView.setContentSensitivity(contentSensitivity);
    flutterView.invalidate();
}
```
This code is easier to read and only invalidates the view on a changed state. 
Also think the passed in value should be requestedContentSensitivity or something that indicates how it is different from current.

2025-01-10 16:24 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// For Android, the sensitive content is unable to be auto-detected by the
I don't think "For android" adds anything to the clarity since the feature only works on android.

2025-01-10 16:24 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +    flutterView.setContentSensitivity(contentSensitivity);
Where are you protecting against android api levels that dont have this method? 

If you are not I would look at where we landed for @justinmc scribe pr.

2025-01-10 16:24 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// hosting the screen will only be marked as secure if other [SensitiveContent]
+1

2025-01-10 16:24 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +        <int>[flutterViewId, contentSensitivity.index],
I wish we could pass an enum across the wire so this could be typesafe.

2025-01-10 16:24 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      throw FlutterError(
this error should include the view id

2025-01-10 20:30 UTC, justinmc reviewed
Lots of nits and questions here but I think the overall approach is sound. The biggest architectural thing is possibly finding away to avoid the SensitiveContentSetting singleton (commented below), but that is not a blocker.

 I'm not sure about hardcoding the view ids, hopefully someone who knows more about Android and add-to-app scenarios will know the answer. If not, maybe it's something we could expose to the framework via MediaQuery or something like that.

About autoSensitive, how do you see the distinction between Android's [CONTENT_SENSITIVITY_AUTO](https://developer.android.com/reference/android/view/View#CONTENT_SENSITIVITY_AUTO) and the feature where we automatically add a SensitiveContent widget to password fields? Maybe we should allow the user to set CONTENT_SENSITIVITY_AUTO if they really want to. Or will that literally have no effect?

*Edit*: I posted this review without seeing Reid's review from a few hours earlier (thanks GitHub), so sorry if there is redundancy.

2025-01-10 20:30 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +/// Flutter view.
Is it clear to users what a Flutter view is? I want to make sure we have some standard nomenclature here.

I left another comment asking about multiwindow. Does this mean that each window in a multi-window Flutter app would have its own viewId, and that the sensitivity should be handled separately for each? Or, how about the scenario where you have an Android app with add-to-app Flutter instances in two separate places?

2025-01-10 20:30 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    if (contentSensitivityStateForView.getTotalNumberOfWidgets() == 0) {
Maybe I'm getting ahead of myself, but I feel like here as well as in _register above you could use shouldSetContentSensitivity with the previous and next content sensitivity instead of needing to know the total number of widgets. And possibly not need the early return logic where you use numWidgetsWithWidgetSensitivityLevel below or even the `switch` below.

2025-01-10 20:30 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      _sensitiveContentService.setContentSensitivity(viewId, ContentSensitivity.autoSensitive);
Nit: Maybe the default ContentSensitivity should be saved in a constant somewhere and referenced here. I know it's used in the initialization of currentContentSensitivitySetting too.

2025-01-10 20:30 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// native framework.
Nit: Maybe specify that you mean within the Flutter app. Also, this might be more complicated if we add a SensitiveContent widget when a user uses a password field. I guess that's what the TODO below is though.

2025-01-10 20:30 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +        <int>[flutterViewId, contentSensitivity.index],
Another thing you could do is to add an index field to the enum (see [enhanced enums](https://dart.dev/language/enums#declaring-enhanced-enums)), or otherwise encode this in some switch statement somewhere rather than relying on the order of the items in the enum directly.

2025-01-10 20:30 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +enum ContentSensitivity {
I think that the "severity", or the behavior that certain values here override other values, is something that we need to make sure is clearly documented to the user. You explain this well in the docs for each enum value below, but I worry that it's less likely users will find that info there. It's probably worth either summarizing this directly in the docs for the SensitiveContent widget, or referring to this or something else in a "See also". Some other places might be worth adding a "See also" too, like SensitiveContent.sensitivityLevel and maybe these top level ContentSensitivity docs itself.

2025-01-10 20:30 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
(I thought I left a comment about this elsewhere but can't find it, maybe it got deleted.)

I know this is how we already do this all over the framework, but I wish we could avoid this singleton pattern. The problem is that it won't reset itself between test runs or hot restarts. I wonder if we could instantiate this in WidgetsApp or somewhere like that? I probably should poke around and see if I can find an example of something like that.

2025-01-13 21:37 UTC, camsim99 commented
> "Implements setting content sensitivity on Android via a new plugin called SensitiveContent"
> 
> Most flutter users would view plugin in this context as something that should probably be in flutter/packages. Maybe call it a FrameworkPlugin or just say we are adding a new way to mark content sensitive without mentioning the implementation detail of a plugin.

Oops I meant widget not plugin :)

2025-01-13 21:55 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java
> +    if (activity != null) {
Yes; it's not dangerous for them to share the same one as the logic is not inherently tied to anything but the host `Activity`. If that fact changes, then we might need to reconsider my answer.

2025-01-13 22:35 UTC, justinmc commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +    flutterView.setContentSensitivity(contentSensitivity);
This is the PR: https://github.com/flutter/engine/pull/52943

2025-01-14 15:47 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
@justinmc do you have a good example of a plugin that is not a singleton that keeps track of android state?

2025-01-14 15:48 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity currentContentSensitivitySetting = ContentSensitivity.autoSensitive;
I think this helps handle interop with native code since it can also set sensitivity. Imagine an app that always set it launch to sensitive until some flutter based code decides that it is ok to make content not sensitive.

2025-01-14 15:50 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +        return currentSensitivityLevel != ContentSensitivity.sensitive;
+1

2025-01-14 21:20 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
I wasn't able to find a good example. Maybe WidgetsBinding, but that is for communicating from the engine to widgets.

I'll ask around, but if I don't come up with anything then we can disregard this comment.

2025-01-14 21:20 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
This is the comment I was thinking of, we can focus the conversation there: https://github.com/flutter/flutter/pull/158473/files#r1909479844

2025-01-14 21:41 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
Another [question I asked](https://github.com/flutter/flutter/pull/158473#pullrequestreview-2538413929) that may have implications here is whether we need to use FFI or not for this feature.

2025-01-14 22:28 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
I'm just now seeing the issue about switching to JNIgen in the future: https://github.com/flutter/flutter/issues/160050. What's the reason behind not wanting to do that as a part of the initial PR?

I was talking to @chunhtai about how to get around using method channels and he suggested going through dart:ui as in [FlutterView.updateSemantics](https://github.com/flutter/flutter/blob/fa04f4a8d2c02fd981b9b68e50f0f5b899da582f/engine/src/flutter/lib/ui/window.dart#L399) (which I believe is handled [here in the Android embedding](https://github.com/flutter/flutter/blob/fa04f4a8d2c02fd981b9b68e50f0f5b899da582f/engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java#L794)). I've never used this approach before but it seems doable today.

2025-01-14 22:28 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
@justinmc can you explain the implication of using a singleton with FFI versus method channel?

2025-01-14 22:29 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      _contentSensitivityStates[viewId] = ViewContentSensitivityState();
Yeah. As long as we know how to identify the desired Flutter view and track the state of each view separately, we should be fine.

2025-01-14 23:51 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
We're trying to move away from method channels because the contract between the sender and recipient is not enforced. You just send some blob of data and hope that the other side will respond. It's also not discoverable, so someone writing their own embedder needs to find this method channel call in the source code and make sure they handle it correctly. With the FFI approach, at compile time it's checked that the call is handled and uses the correct types.

2025-01-14 23:52 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity currentContentSensitivitySetting = ContentSensitivity.autoSensitive;
This PR doesn't support that case yet right, or did I miss it?

2025-01-15 00:03 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
I understand, but is there a concern particularly with the singleton?

**Concerning native interop vs method channels:**

@justinmc @reidbaker My plan is to land this with method channels, then follow this up by working on converting this to use JNIgen as per https://github.com/flutter/flutter/issues/160050. My reasons for this are:

- Landing this method channels will only improve Flutter's security. There may technically be a lag because we don't use JNIgen (I have not noticed this at all in my testing, though), but landing this first will not hurt. That way too, I get to land the feature pieces.
- Reid and I thought that landing this PR then a follow up conversion PR to JNIgen would serve as a good example of how to do such a conversion.

Please let me know if you have any concerns with this approach!

2025-01-15 00:04 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity currentContentSensitivitySetting = ContentSensitivity.autoSensitive;
No. @reidbaker I assume you're suggesting we actually query the current state versus assuming they are using the default? That's a good idea.

2025-01-15 00:08 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
Oh sorry, I misread your question. I think this plan sounds good then. When you convert it to JNIgen, I think the singleton pattern will still be fine.

2025-01-15 00:18 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
A noob question: If uses JNIgen, will the java source code bundled in the dart code? how would the customer inject java code from their embedding?

Also do you think this feature may be useful for other platform in the future?

2025-01-15 15:03 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity currentContentSensitivitySetting = ContentSensitivity.autoSensitive;
Yes that is what I am suggesting since the value can be changed by native code we have no control over or potentially the system (if they add that feature in the future).

2025-01-15 17:54 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
I initially thought we would bundle the Java code that way, but I remember the engine team alternatively suggesting checking the Java code into the engine and do something similar to dart:ui but I have to investigate how that would work. What do you mean by injecting Java code from their embedding?

And this feature could be useful for other platforms if they add the sensitive content feature. [Windows](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity#remarks) and [iOS](https://developer.apple.com/documentation/sensitivecontentanalysis?language=objc) have similar features that this widget possibly could be used for.

2025-01-15 18:09 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
> What do you mean by injecting Java code from their embedding?
In case if they implement their custom embedding, how would they handle the FFI call?

>  I remember the engine team alternatively suggesting checking the Java code into the engine and do something similar to dart:ui

I think they are referring to something like this 
https://github.com/flutter/flutter/blob/1580a3d3fbe75737e5d8adc067d8c41adc4aab20/engine/src/flutter/lib/ui/platform_dispatcher.dart#L619
create an one-off API and drill it through the engine shell to embedding

2025-01-21 17:48 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
> In case if they implement their custom embedding, how would they handle the FFI call?

I've been giving this some thought. One solution could be keeping the sensitive content service that makes calls right now to a method channel (later will be FFI) overridable such that someone can override it to call into their custom embedding. This is not a great solution because it would require modifying the framework. On one hand, I'm not sure that this would be a huge leap for someone maintaining a custom embedding. On the other, I understand that sensitive content would be one of potentially many features switching from using a method channel to JNI/FFI, so we need to consider the larger scale impact of what that world would look like.

Frankly, I need to read up more on how custom embedders work (https://github.com/flutter/flutter/blob/main/engine/src/flutter/docs/Custom-Flutter-Engine-Embedders.md for my future reference). We'll need to set up some system like that for people to be able to override the behavior of any features that rely on FFI/JNI. I still plan to work on landing this with method channels for now, but I'll add a note to https://github.com/flutter/flutter/issues/160050 to make sure that answering this questions is part of that work.

2025-01-24 19:07 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
I agree that requiring framework changes is not a good approach. Currently I'm under the assumption that a custom embedder can simply listen for the method channel call just like we do in our embedders, so overriding something in the framework wouldn't be necessary.

And my assumption about the dart:ui FFI approach is that custom embedders need to implement some interface exposed in dart:ui, including whatever we add for sensitive content, so again no other changes would be needed.  But I don't have firsthand experience with this. Maybe @stuartmorgan can clarify here?

2025-01-24 19:29 UTC, stuartmorgan commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
I don't have enough context from this thread to know what we are talking about exactly. It sounds like it's about how new Framework->embedding communication systems should work?

If so:

> Currently I'm under the assumption that a custom embedder can simply listen for the method channel call just like we do in our embedders

We should absolutely not be building new features that require this behavior by embedders. Having a de-facto secondary embedding API of a bunch of method channels, which aren't tightly controlled, can much more easily be accidentally broken for third-party embeddings, and are untyped, is a terrible situation, and it should not be exacerbated with new public channels.

If some new feature is being exposed to arbitrary embeddings, it needs to be added to [the formal API for embeddings](https://github.com/flutter/flutter/blob/master/engine/src/flutter/shell/platform/embedder/embedder.h), not require embedding authors to find, reverse engineer, and use a method channel.

2025-01-24 19:40 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static final SensitiveContentSetting _instance = SensitiveContentSetting._();
> One solution could be keeping the sensitive content service that makes calls right now to a method channel (later will be FFI) overridable such that someone can override it to call into their custom embedding

I think this will be more complex then just handle the message in custom embedding.

Also any solution that require changes to framework to support a certain embedding is a big no-no.

Usually things like this we will create a new API surface drill through native dart:ui -> runtimeController -> shell -> each platform views. You can trace through `FlutterView.updateSemantics` to see how it is drill throw these layer.

For custom embedding, you will add a new API in embedder.h. I think the mentality is as long as the custom embedding implement function handler properly in embedder.h. Their embedding should work correctly.

2025-01-28 23:57 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  }
> * What if SensitiveContent is part of an item in ListView.builder, and that item is scrolled off-screen. Will it be disposed and unregister itself? Is that desirable?

I don't see it unregistered and I assume that the `SensitiveContent` widget is actually not getting disposed, keeping the screen obscured. Will need to double check this theory by debugging. I think ideally, the screen is only obscured while the `SensitiveContent` widget is visible on screen; fixing this may be part of https://github.com/flutter/flutter/issues/160051 which I intend to do in a follow up PR.

> * What happens when a new full screen route is pushed on top of the route containing SensitiveContent? Does it get disposed, and is that desirable or not?

If a route is `push`ed then the screen stays obscured. If a route is `pushReplace`d, then the `SensitiveContent` widget gets disposed and the screen does not stay obscured. As I mentioned in the first case, if we want the content sensitivity of the view to rely on widget visibility versus being disposed (meaning `push` and `pushReplace` would behave the same), this can be done as a part of https://github.com/flutter/flutter/issues/160051.

2025-01-31 00:43 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
> +  public static final int FLUTTER_VIEW_ID = 0;
Agreed that this is dangerous; I didn't realize the implications went beyond debugging before.

As of now, I changed my approach to identifying the `View` we want to set the content sensitivity of by initializing `SensitiveContentPlugin`s with the ID of the `View` that is created by a `FlutterActivity` or `FlutterFragment`. My understanding is that every `FlutterActivity` or `FlutterFragment` will (via the `FlutterActivityAndFragmentDelegate` code I added) provide a `SensitiveContentPlugin` to handle the `View` created for each `FlutterActivity` and `FlutterFragment` created.

This should cover regular Flutter apps as well as add-to-app use cases where a `FlutterActivity` or `FlutterFragment` is used. The only case I think left uncovered is adding a `FlutterView` to a native app, but it's my understanding that we are not required to handle `FlutterActivityAndFragmentDelegate` plumbing there (see https://docs.flutter.dev/add-to-app/android/add-flutter-view#general-approach).

2025-01-31 00:45 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java
> +    if (activity != null) {
While digging into flutter view ID stuff, I realized that with this code as it is, they would not share the same plugin. With my current approach to identifying Flutter `View`s to set content sensitivity, they in fact, should not share the same one anymore.

2025-02-03 22:54 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
> +  public static final int FLUTTER_VIEW_ID = 0;
Ok small misunderstanding...we still need the singleton approach because we need to be able to track all `SensitiveContent` widgets in a Flutter app.

2025-02-03 23:12 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
> +  public static final int FLUTTER_VIEW_ID = 0;
We need to track all sensitive content widgets in a flutter app for a flutter view. It seems to me like that singleton can/should be in dart but the android side could not be a singleton.

2025-02-04 18:41 UTC, justinmc commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java
> +  public static final int FLUTTER_VIEW_ID = 0;
Ah it would have been cool to get rid of the Dart singleton but that sounds good anyway.

2025-02-05 18:13 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +        <int>[flutterViewId, contentSensitivity.index],
Changed to an enhanced enum and json/array no longer needed since we don't have to pass a Flutter view ID.

2025-02-05 18:15 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +            && contentSensitivity != View.CONTENT_SENSITIVITY_SENSITIVE;
Changed naming, but kept my logic because we only have to invalidate if we are changing away from sensitive state.

2025-02-06 20:23 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +            && contentSensitivity != View.CONTENT_SENSITIVITY_SENSITIVE;
In general I think when the state changes in any direction we should do the same thing. Selective view invalidation can cause hard to reproduce bugs that are very difficult to reason about.

2025-02-06 20:25 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +            && contentSensitivity != View.CONTENT_SENSITIVITY_SENSITIVE;
Also I would still encourage you to more clearly distinguish between current and requested but you dont have to use those prefixes.

2025-02-24 17:28 UTC, camsim99 commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +  final int defaultContentSensitivitySettingId = ContentSensitivity.autoSensitive.id;
I only tested with this as the default as of right now because I couldn't convince myself that there was greater value in testing other defaults besides the method channel `setContentSensitivity` method getting called. If reviewers think that is valuable, I can make new test files to test the other modes as defaults (I think I have to do this because of the singleton pattern I used for `SensitiveContentSetting`).

2025-02-24 19:03 UTC, camsim99 commented
@justinmc @reidbaker This is ready for a full review! I know this PR is getting lengthy but I tried to address all your feedback + added tests.

2025-02-28 15:57 UTC, camsim99 commented
Just found a small refactor I'd like to make while working on something else -- still ready for review!

2025-02-28 23:09 UTC, justinmc reviewed
I have some ideas in my comments below about the dart classes in sensitive_content.dart, but most other stuff is nits.

I know we talked about mutliwindow already but I keep forgetting how that will work, is there something you can link me to that explains that?

2025-02-28 23:09 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +  final int defaultContentSensitivitySettingId = ContentSensitivity.autoSensitive.id;
I think it's not a big deal, in the code it looks like there is no special behavior for different default values. If you wanted to though, you could quickly do it by looping over ContentSensitivity.values and running the same test(s) for each value.

2025-02-28 23:09 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +        await tester.pumpAndSettle();
Would this still work with just `pump`? I would do that if you can. Here and below there are a bunch more like it.

2025-02-28 23:09 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +
Super nit: Just as a thought to reduce lines of code in these tests, you could write a single test and put it in a loop over ContentSensitivity.values, and use that value as the sensitivity for the widget that gets disposed, or something like that.

2025-02-28 23:09 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +  int setContentSensitivityCallCount = 0;
Nit: Instead of a count, you could do a List<ContentSensitivity>, where the length of the list is the same as the count. Then you could also test what it gets called with. Not sure if this is actually valuable or not here though, up to you.

2025-03-03 19:16 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// This is currently a no-op and thus, will behave the same as [ContentSensitivity.notSensitive].
No; `autoSensitive` will only take priority over `notSensitive`. I'll clarify this comment.

2025-03-03 19:18 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  notSensitive(id: 2);
Yes! If there is a `SensitiveContent( sensitivityLevel: ContentSensitivity.sensitive, ...)` in the tree, the sensitive content setting should be `setting`.

2025-03-03 22:47 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    return FutureBuilder<void>(
My intention was for the (potentially sensitive) child not to be rendered before its parent is registered as a `SensitiveContent` widget, to avoid showing sensitive information. If you don't think this is important or have ideas for a workaround of the behavior you described, though, let me know!

Before, I forgot to make the `FutureBuilder` actually wait for the `Future` to complete before returning the child; fixed that!

2025-03-04 01:03 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  bool shouldSetContentSensitivity(ContentSensitivity desiredSensitivityLevel) {
> Is it possible that the sensitivity level in Android gets changed by something other than Flutter?

Yes, and I think this answer is independent from your next question.

The implementation of `SensitiveContent` here assumes the developer will not set it in native Android code _except_ to change the initial setting. I honestly think we should discourage developers from doing so _except_ if they are going to manually handle marking content sensitive that way without using the `Widget` (I assume this would fall under an advanced Flutter user's use case). We're exposing this widget as the way to set it in non-advanced use cases, so I think handling folks changing it at any time on the Android side is low priority.

> Is it possible that the sensitivity level in Android gets changed by something other than Flutter? If so, maybe we should always set it just in case?

We can't always set it just in case because setting a new setting would override the current one, regardless of what the current one is. This could be bad if we are registering a `notSensitive` widget but there are other `sensitive` widgets in the widget tree, for instance.

As to your first question in relationship to this one, theoretically we could detect if the developer changed the current content sensitivity setting on the native side and factor that in, but as I said before, I think this is low priority if it's something we'd prioritize at all.

2025-03-04 01:05 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      _sensitiveContentService.setContentSensitivity(desiredSensitivityLevel);
@justinmc I added try/catch blocks to the `setContentSensitivity` calls to make it clear that if this fails for some reason, we won't update the current setting. They should just catch the `FlutterError`s that I throw upon an error coming over the method channel. PTAL.

2025-03-04 01:08 UTC, camsim99 commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +
I actually prefer having the tests loop-less so it's clear the exact use case that each one is testing. I think reading the looped version could get kinda hard to understand.

2025-03-04 01:14 UTC, camsim99 commented
To address the multiwindow/multiview concerns:

> I know we talked about mutliwindow already but I keep forgetting how that will work, is there something you can link me to that explains that?

I chatted a bit about this with reidbaker@ offline, and we concluded that we don't need to plan ahead for an unplanned feature; that is, multiwindow won't work with this PR out of the box.

That is because multiwindow would involve multiple native Android `FlutterView`s and as of today, they do not have unique IDs such that the `SensitiveContentPlugin` could differentiate which `View` set content sensitivity for. This is a problem because this ID is most likely what someone would need to link native `FlutterView`s to the Dart ones to implement multiwindow.

I am making a PR to fix this, though, because this impacts the add-to-app multi-`FlutterView` use case as well, so it'd be nice to land as part of this feature work: https://github.com/flutter/flutter/pull/162685.

2025-03-04 01:27 UTC, camsim99 commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +  int setContentSensitivityCallCount = 0;
Love this idea and I think it's useful! Helps us verify what we actually requested the native side set. Done.

2025-03-04 01:29 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    // auto sensitive if it is otherwise unset by the developer.
It will be auto sensitive by default if the developer doesn't do anything; this is set by Android.

2025-03-05 18:30 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentRegistrationFuture = SensitiveContentSetting.register(widget.sensitivityLevel);
Oop! Thank you for pointing this out! Added `didUpdateWidget` + tests.

2025-03-05 18:30 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  notSensitive(id: 2);
Added tests for `SensitiveContent` sub-children just for peace of mind that this works :)

2025-03-05 18:46 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  final int id;
it feels weird that we define the dart enum to platform enum translation in the framework. I think they should be done in the platform embedding. Imagine in the future we may need to add another platform for this feature and it uses a different number for each of the const in Android.

I think here we should just use a plain enum, and send the value to android directly. It will then be translated into Android constants there. Same thing when android sends back the setting.

2025-03-05 18:46 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      final bool? result = await sensitiveContentChannel.invokeMethod<bool>(
we should make sure other platform returns false

2025-03-05 18:46 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// Sets content sensitivity level of the Android `View` that contains the app's widget tree to the level
If this feature is only meant for android then this doc is fine, otherwise, this doc may need to be a bit more generic.
```
Sets content sensitivity level of the screen that contains the app's widget tree to the level

For example, the entire Android `view` will be marked as with the given sensitivity level.
```

2025-03-05 18:46 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      _sensitiveContentService.setContentSensitivity(desiredSensitivityLevel);
I think you can just use a comment to explain that.

2025-03-05 18:46 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _contentSensitivitySetting!.addWidgetWithContentSensitivity(desiredSensitivityLevel);
Can we simply this as
```dart
_contentSensitivitySetting!.addWidgetWithContentSensitivity(desiredSensitivityLevel);
final ContentSenstivity newSenstivity = _contentSensitivitySetting.contentSensitivityBasedOnWidgetCounts;
if (currentContentSensitivityLevel != newSenstivity) {
  setSensitivity(newSenstivity);
 currentContentSensitivityLevel = newSenstivity
}
```

2025-03-05 18:46 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivitySetting? _contentSensitivitySetting;
this can be 
```
late ContentSensitivitySetting _contentSensitivitySetting = ContentSensitivitySetting();

2025-03-05 18:51 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        new MethodChannel(dartExecutor, "flutter/sensitivecontent", StandardMethodCodec.INSTANCE);
There isn't currently. Also this is meant to be replaced with JNIgen in the future.

2025-03-05 18:52 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  final int id;
> I think here we should just use a plain enum, and send the value to android directly. It will then be translated into Android constants there. Same thing when android sends back the setting.

What do you mean by this? Wouldn't this also be clunky because we can't send an enum right? So it would have to be like a String to Android enum translation on the platform side?

2025-03-05 18:58 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  final int id;
I guess I could see doing this if we may need to add another platform. Will do

2025-03-05 21:53 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// Sets content sensitivity level of the Android `View` that contains the app's widget tree to the level
This feature is only meant for Android at the moment. I don't think making it more general would be helpful since we don't know how this would work there (for instance, it may not obscure the entire screen on other platforms).

2025-03-05 21:58 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _contentSensitivitySetting!.addWidgetWithContentSensitivity(desiredSensitivityLevel);
No; we need to know if the current `_contentSensitivitySetting.contentSensitivityBasedOnWidgetCounts` is strictly more sensitive than `newSenstivity`, not just if they aren't the same.

2025-03-05 22:03 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivitySetting? _contentSensitivitySetting;
Oooo I did not know about this--thank you!

2025-03-07 14:41 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java
> +    // Null out the platformPlugin and sensitiveContentPlugin to avoid a possible
Would you file a bug that covers creating an "flutterActivityPlugin" and the methods that should be shared and add a reference to the bug here.

2025-03-07 15:56 UTC, reidbaker reviewed
I still need to do a better pass on the testing in packages/flutter/test/widgets/sensitive_content_test.dart and the java tests.

2025-03-07 15:56 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +    /** Returns whether or not marking content sensitivity is supported on the device. */
This method should also document if isSupported is static or dynamic. Should callers cache the result or can it change over time.

2025-03-07 15:56 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +    final View flutterView = mFlutterActivity.findViewById(mFlutterViewId);
I think findViewById can return null. Please handle that case.

2025-03-07 15:56 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +    if (!isSupported()) {
When you are considering adding an Unknown value also consider if get should return unknown in this situation. 

Even if we dont add unknown it might be worth returning "not sensitive" since we think that is the case on api 35 and prior.

2025-03-07 15:56 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +  public void destroy() {
I also think we need to null out the reference to mFlutterActivity so that this plugin does not hold a reference to the activity that probably cause the destroy.

2025-03-07 15:56 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/test/io/flutter/plugin/view/SensitiveContentPluginTest.java
> +    // TODO: fix
todo fix?

2025-03-07 15:56 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/test/io/flutter/plugin/view/SensitiveContentPluginTest.java
> +    MethodCall methodCall = new MethodCall("getContentSensitivity", null);
Consider constants for method names.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// The level of sensitivity that content in the widget tree has.
This reads awkwardly maybe 
```suggestion
/// The possible values for a widget tree's contentSensitivity. 
```

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// There are only three [ContentSensitivity] levels, and these can be set via a
```suggestion
/// There are three [ContentSensitivity] levels, and these can be set via the
```
[Remove ](https://github.com/flutter/flutter/blob/master/docs/contributing/Style-guide-for-Flutter-repo.md#avoid-empty-prose) 

changed `a` to `the` because we want users to be able to have multiple in the tree.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// [ContentSensitivity.sensitive] is the most severe setting, and if it is set,
I think most severe is correct here but what we are actually trying to convey with this prose is that it is the most important or controlling value.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// in the tree. If there are no `SensitiveContent` widgets in the tree, the default setting as
I think you documentation is probably correct to the code but the code needs to change. The most likely reason someone sets "not sensitive" is because they want to explicitly force the streaming of pixels to work. 

We also want to default to safety so I understand why you authored it this way. 

My gut is that in dart we should say something like "Setting auto likely does nothing." And say that not overrides auto and that sensitive overrides not. Which still leaves us without the ideal way to override.

Will think more on this.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// Android; otherwise, Android uses [ContentSensitivity.autoSensitive] by default.
If you have it link to the source of how we know that is true.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// This mode currently does not work for Flutter, and thus, will never obscure the screen during
I think we should rephrase this. Maybe "This mode in android views attempts to auto detect passwords and 2factor tokens and other sensitive content. Android as of api 35 cannot determine if flutter views contain sensitive content automatically, and thus will never obscure the screen ..."

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// Sets content sensitivity level of the Android `View` that contains the app's widget tree to the level
We can change this to "App window (AndroidView)" to make it multi platform.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// This feature is only supported on Android currently.
Consider adding to documentation if this value is safe to cache.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      // Content sensitivity failed to be set.
I think this comment is still wrong.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      _sensitiveWidgetCount + _autoSensitiveWidgetCount + _notSensitiveWigetCount > 0;
you might consider 
```suggestion
      max(0, _sensitiveWidgetCount) + max(0,_autoSensitiveWidgetCount) + max(0, _notSensitiveWigetCount) > 0;
```
to protect you in case of a bug where  you remove more widgets or you remove with the wrong level of sensitivity.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      return ContentSensitivity.notSensitive;
Added a comment in the documentation but I think we should set not as more important than auto.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _defaultContentSensitivitySetting ??= await _sensitiveContentService.getContentSensitivity();
I dont think this is default. This is current/active here then later it is the restoreValue. I see that the naming here is hard but can you do a second pass and see if there are some more accurate names to help maintainers of this code later.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentService.setContentSensitivity(desiredSensitivityLevel);
+1 not sure why this is resolved.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      _sensitiveContentService.setContentSensitivity(_defaultContentSensitivitySetting!);
I think this ! is dangerous here.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    late final ContentSensitivity? contentSensitivityToRestore =
I dont think this needs a late?  (or if it does then maybe it doenst need to be final or nullable but all three feels weird) Especially because it is being given a value on the right hand side of =.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +        contentSensitivityToRestore != currentContentSensitivityLevel) {
I am not sure this check helps with efficiency because the java code will only set the value if it needs to be.

2025-03-07 15:56 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  bool shouldSetContentSensitivity(ContentSensitivity desiredSensitivityLevel) {
I think the most important thing is to be predictable and to document what we will and wont do in the corner cases.  I think the code as written has a bunch of if A==B dont do any more work. That look like they are for efficiency reasons but might be to enforce some predictability. Consider doing a pass on each and adding documentation. FWIW I think there are too many places in code where we have the if A==B and that reducing the number of them would make the code easier to read. That said if it was easy I would have pointed them out so it may be that you are already in the minimal number of conditions.

2025-03-07 16:23 UTC, camsim99 commented
@reidbaker there were todos because I am in the middle of addressing another review :) once that and your review is addressed, I'll re-request review. Might be easier to review the tests in that state.

2025-03-07 18:16 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        new MethodChannel(dartExecutor, "flutter/sensitivecontent", StandardMethodCodec.INSTANCE);
I don't think converting to JNIgen should be blocking the release. I think I commented on this elsewhere but TLDR my reasoning is that given the frame issue is unlikely observable, releasing this would only strictly improve the security of flutter on Android. In addition, the likely observable use cases should have workarounds.

As an aside, I would like to note too that if we decide to block on JNIgen, the timeline of this project probably would have to be extended due to the complexity involved.

2025-03-07 18:19 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  final int id;
> Wouldn't this also be clunky because we can't send an enum right? So it would have to be like a String to Android enum translation on the platform side?

enum will send as an int, and the android needs to create a lookup from that int to its own constant

2025-03-07 18:22 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _contentSensitivitySetting!.addWidgetWithContentSensitivity(desiredSensitivityLevel);
I thought contentSensitivityBasedOnWidgetCounts will taking the senitivity level into account?

2025-03-07 18:27 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    late final ContentSensitivity? contentSensitivityToRestore =
the late here will make it a lazy initializer. so if the platform doesn't support is contentsensitivity, we won't create this at all (thus save some memory)

2025-03-07 18:32 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// in the tree. If there are no `SensitiveContent` widgets in the tree, the default setting as
I don't agree with making `notSensitive` a setting that can override others. Because we are implementing it as a widget and there can be multiple in the tree, when one is sensitive, I do think we must follow that for security's sake. I think this is an unfortunate consequence of the fact that we can not obscure widget by widget versus the entire screen.

I will work on rewording the `autoSensitive` method because it technically overrides `notSensitive` but behaviorally, does nothing.

2025-03-07 18:34 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +        contentSensitivityToRestore != currentContentSensitivityLevel) {
But then we are sending messages across the method channel for no reason

2025-03-07 19:13 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        new MethodChannel(dartExecutor, "flutter/sensitivecontent", StandardMethodCodec.INSTANCE);
ok if we do not decide to block then I would like to block on an attempt to show a frame that has content we want to protect. 

maybe an app that has a button to show a widget that is sensitive then screen record what is streamed to confirm no frames are visible. This is a security feature and we have to assume people will try to break the security.

2025-03-07 21:52 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        new MethodChannel(dartExecutor, "flutter/sensitivecontent", StandardMethodCodec.INSTANCE);
Filed https://github.com/flutter/flutter/issues/164820 and linked it in the PR description as part of the required steps.

2025-03-07 22:12 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +            // No SensitiveContentChannel registered, call not forwarded to sensitive content
Programming

2025-03-07 22:13 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +              } catch (IllegalStateException exception) {
It shouldn't you're right! Removed.

2025-03-07 22:24 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +                result.error("error", exception.getMessage(), null);
Bad code...removing these since the code should not throw errors we wouldn't otherwise catch.

2025-03-07 22:25 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +                result.error("error", exception.getMessage(), null);
These should catch serialization issues!

2025-03-07 22:25 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        throw new IllegalArgumentException(
Agreed

2025-03-07 22:28 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        throw new IllegalArgumentException(
I'm open to the "unknown" but unless there's pushback, I won't implement this because I personally find it unlikely Android would add a new value. Even if they do and I'm completely wrong (likely), then I don't find any additional value in having an unknown value than running into this exception.

2025-03-07 22:46 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +    if (!isSupported()) {
Since I'm not implementing that now, going to throw the same error here as `setContentSensitivity` for when `isSupported` is not called first.

2025-03-07 23:33 UTC, camsim99 commented
Note to reviewers: There's a lot of comments to get through, so I'm merging and commenting as I fix locally, but this PR may not reflect those changes. I'll re-request review when this is ready.

cc @justinmc because I requested your review earlier this week, but I'll ping when I'm actually ready!

2025-03-10 21:43 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      throw FlutterError('Failed to retrieve content sensitivity: $e');
I was under the impression that we did but I am wrong! Removing.

2025-03-10 21:47 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      return ContentSensitivity.notSensitive;
Left a comment on this; let's discuss further there.

2025-03-10 21:55 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _defaultContentSensitivitySetting ??= await _sensitiveContentService.getContentSensitivity();
Renaming to `_fallbackContentSensitivitySetting` with clearer documentation.

2025-03-10 22:00 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentService.setContentSensitivity(desiredSensitivityLevel);
There are so many comments so it got lost but @chunhtai suggested we leave a comment explaining why tis may fail because I otherwise would just rethrow the same error. The errors would be if `isSupported` was not called first to see if sensitive content is supported or if the `FlutterView` to set content sensitivity for was not found, both being programming errors.

2025-03-10 22:05 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// [ContentSensitivity.sensitive] is the most severe setting, and if it is set,
Changed "severe" wording to "prioritized". Let me know what you think

2025-03-10 22:30 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    late final ContentSensitivity? contentSensitivityToRestore =
I think the `late final` method was for `_contentSensitivitySetting`. I think this was an accidental edit that was caught while I was still messing around with this file; removed.

2025-03-10 22:53 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java
> +    // Null out the platformPlugin and sensitiveContentPlugin to avoid a possible
https://github.com/flutter/flutter/issues/164945, will link above where the `sensitiveContentPlugin` is initialized.

2025-03-10 22:56 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +          switch (method) {
Note to reviewers: I refactored this handler to only catch exceptions I throw in `SensitiveContentPlugin` to signal various errors that could be made by the user.

2025-03-10 23:01 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        throw new IllegalArgumentException(
I left a comment above but I'm currently catching this to result with an error instead, but open to pushback on how to handle it. This would only happen due to programming error.

2025-03-10 23:08 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  final int id;
I used the enum name instead, but if anyone has strong opinions, let me know

2025-03-10 23:12 UTC, camsim99 commented
> I think the most important thing is to be predictable and to document what we will and wont do in the corner cases. I think the code as written has a bunch of if A==B dont do any more work. That look like they are for efficiency reasons but might be to enforce some predictability. Consider doing a pass on each and adding documentation. FWIW I think there are too many places in code where we have the if A==B and that reducing the number of them would make the code easier to read. That said if it was easy I would have pointed them out so it may be that you are already in the minimal number of conditions.

I did a pass and I don't see anything that can easily be refactored for readability purposes. The only one maybe is what you commented on which is that we could perhaps tell the platform to set a content sensitivity setting already set instead of having a check for it to avoid that situation, but like I said above, I think removing it sorta relies on our assumption that our embedder will be used. Besides that point, I don't have strong feelings.

2025-03-11 19:52 UTC, reidbaker requested changes

2025-03-11 19:52 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        throw new IllegalArgumentException(
Following the chain of code we eventually call `serializeContentSensitivity` on the result from `flutterView.getContentSensitivity` https://developer.android.com/reference/android/view/View#getContentSensitivity() 

This value can return new unknown values on api 36 and beyond. 
If you agree then this error is more than just a programming mistake it has the potential to throw an error on new versions of android.

2025-03-11 19:52 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        new MethodChannel(dartExecutor, "flutter/sensitivecontent", StandardMethodCodec.INSTANCE);
Is there any way to land this pr but prevent this feature from being used until we have validated #164820?

2025-03-11 19:52 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        throw new IllegalArgumentException(
I do think you should catch it if you are going to throw it.

2025-03-11 19:52 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +    int getContentSensitivity();
Is this method limited to returning ints that are known or can it return unknown ints.

2025-03-11 19:52 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +    boolean isSupported();
if this is about marking (as opposed to getting) then maybe it should be named `isSetContentSensitvitySupported` 
 
 I realize this might change a lot of other method names. What do you think?

2025-03-11 19:52 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +    if (!isSupported()) {
"Even if we dont add unknown it might be worth returning "not sensitive" since we think that is the case on api 35 and prior." 

Why not make this method safe to call even on earlier versions of android? 
This will especially be important if we back port sensitivity.

2025-03-11 19:52 UTC, reidbaker commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// in the tree. If there are no `SensitiveContent` widgets in the tree, the default setting as
OK then how does someone turn off sensitivity for a debug build or dogfood build for their entire app while leaving the support around for their users.

2025-03-11 19:52 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentService.setContentSensitivity(desiredSensitivityLevel);
Those are the errors right now. There could be different error cases in the future and setting calculated to desired when the call fails feels wrong. If it cant fail when isSupported is checked then I think it should be safe to set calculated only if setContentSensitivity succeeds.

2025-03-11 19:52 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      'SensitiveContentHost.register must be called before SensitiveContentHost.unregister',
Dont use asserts in java they are stripped out. Make an actual check and have an actual error or handle the condition and break out early.

2025-03-11 21:23 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        throw new IllegalArgumentException(
Ok I understand that and agree. However, I think only a Flutter contributor/someone using a modified Flutter would run into this, so adding an `unknown` value wouldn't add value for Flutter users, and I personally don't think it would help that group of users much since the exception would let them know they need to fix something.

For example, let's say we bump to compileSdk 36 and there are new values. We won't expose the new values to the user unless we change the `SensitiveContent` widget/`ContentSensitivity` enum to do so. If we do that, then we would have to update the serialization methods. The only other way I could see hitting the error is if you are using a modified `SensitiveContentService`. In this case, I think that developer could understand if we don't handle their new values in the embedder directly by default.

2025-03-11 21:41 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      'SensitiveContentHost.register must be called before SensitiveContentHost.unregister',
You mean in Dart? @justinmc recommended this assert for debug purposes: https://github.com/flutter/flutter/pull/158473#discussion_r1975956813

I think this is sufficient because this would only happen if someone is messing with the `SensitiveContent` widget internals.

2025-03-11 21:56 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentService.setContentSensitivity(desiredSensitivityLevel);
I'm confused. I agree, but wouldn't this code already do that? If this throws, then the next line won't be called and calculated won't be set?

2025-03-11 23:04 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +/// in the tree. If there are no `SensitiveContent` widgets in the tree, the default setting as
They can create a global variable that all the `SensitiveContent` widgets set as the `sensitivityLvel` in debug mode:

```dart
static ContentSensitivity debugModeContentSensitivity = ContentSensitivity.notSensitive;

SensitiveContent(
  sensitivityLevel: kDebugMode  ? debugModeContentSensitivity : myOtherContentSensitivitySetting,
  child: MyChildWidget(),
);

```

2025-03-11 23:05 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +    boolean isSupported();
Oops! It is for getting/setting! Updated the docs.

2025-03-11 23:18 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +    int getContentSensitivity();
It should only return known ints. Updated the docs to make this clear.

2025-03-11 23:19 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        new MethodChannel(dartExecutor, "flutter/sensitivecontent", StandardMethodCodec.INSTANCE);
I actually have time to validate that before we land this :) so I'll put a note on this PR for now not to land.

2025-03-11 23:27 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/plugin/view/SensitiveContentPlugin.java
> +    if (!isSupported()) {
Agreed. Done.

2025-03-12 14:10 UTC, reidbaker commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        throw new IllegalArgumentException(
Lets sit down and talk about the code path when there is a new value what should callers on this version of flutter expect.

2025-03-12 18:19 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +///    [SensitiveContent] widget can set.
Add something about what the behavior is on platforms that dont support sensitive content and how/where to tell if sensitive content is supported.

2025-03-12 22:29 UTC, camsim99 commented
> I do think handling unknown values is something that needs to be addressed in this pr.

Can't find the original comment for implementing an unknown value, but consider it done :)

2025-03-13 19:20 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +import '../../widgets.dart' show ConnectionState;
we should not import the widgets.dart directly, instead import the file required in the widget folder directly

2025-03-13 19:20 UTC, chunhtai commented on packages/flutter/lib/widgets.dart
> +export 'src/widgets/sensitive_content.dart';
If we want to go with visibleForTest we should not export the file here. and import the file directly in the test with a todo to fix it once the widget is ready for consumption.

and we should only ever do this if this is temporary which i assume it is.

2025-03-13 19:27 UTC, reidbaker approved these changes

2025-03-13 19:56 UTC, camsim99 commented on packages/flutter/lib/widgets.dart
> +export 'src/widgets/sensitive_content.dart';
Ok I'll make these changes, address Reid's review, and run this past @justinmc since you mentioned this goes against the style guide.

2025-03-14 16:40 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +class _SensitiveContentState extends State<SensitiveContent> {
Where do we handle the cases for OffStage and Navigator?

2025-03-14 16:42 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +class _SensitiveContentState extends State<SensitiveContent> {
https://github.com/flutter/flutter/issues/160051 is not addressed in this PR. It will be a follow up.

2025-03-14 19:42 UTC, justinmc commented on packages/flutter/lib/widgets.dart
> +export 'src/widgets/sensitive_content.dart';
This sounds good to me per https://github.com/flutter/flutter/issues/164820#issuecomment-2725474314.

2025-03-14 22:44 UTC, justinmc reviewed
A few comments and questions about error handling and some edge cases, but otherwise this is looking good. I like the overall approach.

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +class ContentSensitivitySetting {
Could this class be private?

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      throw UnsupportedError(
Nit: Could you get rid of `ContentSensitivity._unknown` if you throw for any value that doesn't match an enum value? Then you could also get rid of the `ignore_no_default_cases` in widgets/sensitive_content.dart.

```dart
    final ContentSensitivity contentSensitivity = ContentSensitivity.values.firstWhere(
      (ContentSensitivity cs) => cs.name == result,
      orElse: () => throw UnsupportedError(
        'Android Flutter View has a content sensitivity mode '
        'that is not recognized by Flutter. If you see this error, '
        'it is possible the View uses a new mode that Flutter needs to '
        'support; please file an issue.',
      ),
    );

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      // ignore: no_default_cases
See my idea I posted in another comment to get rid of ContentSensitivity._unknown.

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +      0;
Should you also assert that these values are not less than zero? Here and/or in removeWidgetWithContentSensitivity.

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +class ContentSensitivitySetting {
By the way, I really like this class now after the recent round of changes. It has a good tight definition of what it does without needing to understand anything else.

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity? calculatedContentSensitivityLevel;
Looking at the code, this variable seems to track what the framework thinks that Android has for the ContentSensitivity. It's not really calculated. Maybe change the name and the docs here?

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivitySetting? getContentSenstivityState() {
This could be an actual getter: `ContentSensitivitySetting? get contentSenstivityState {`

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  static Future<void> register(ContentSensitivity desiredSensitivityLevel) {
Nit: Would the naming be any simpler if you dropped the word "Level" from these variables? Since they are all instances of ContentSensitivity, maybe it makes for sense to be desiredContentSensitivity.

Same for other ones like calculatedContentSensitivityLevel => calculatedContentSensitivity.

2025-03-14 22:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +        _fallbackContentSensitivitySetting = potentialFallbackContentSensitivity;
Nit: You could condense this:

```dart
_fallbackContentSensitivitySetting = await _sensitiveContentService.getContentSensitivity();
```

2025-03-17 18:34 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity? calculatedContentSensitivityLevel;
I actually discussed this name with Reid. I think it is calculated because kinda like you said, it's what the framework has calculated the setting to be. I think it's appropriate naming, but if you have strong feelings about changing it, let me know.

2025-03-17 18:45 UTC, reidbaker commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity? calculatedContentSensitivityLevel;
Yes, naming is hard. if either of yall can some up with something better I am all for it. Apart from a suggestion for a better name I think the only thing we can do is explain the complexity in the dart doc which this variable has.

2025-03-18 18:05 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      throw UnsupportedError(
Can you remove _unknown from the enum entirely?

2025-03-18 18:12 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  ContentSensitivity? calculatedContentSensitivityLevel;
Ok I see, yeah no strong feelings on the name, but I think we should explain in the docs. Maybe something like:

> The last known [ContentSensitivity] held by the platform for this Flutter view.

2025-03-20 01:01 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentRegistrationFuture = SensitiveContentHost.register(widget.sensitivityLevel);
Updated the calls to `setContentSensitivity` to log an error!

2025-03-20 01:37 UTC, camsim99 commented
@chunhtai I need to do some minor cleanup + add comments, but if you want to take a look tomorrow and give another review PTAL :)

2025-03-20 17:10 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    SensitiveContentHost.unregister(oldWidget.sensitivityLevel);
I can confirm that 1 is pretty thoroughly tested in `sensitive_content_host_test.dart` and I added new tests for 2.

2025-03-20 18:56 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +        throw FlutterError(
This should use FlutterError.reportError

2025-03-20 18:56 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +        throw FlutterError(
consider refactor this out with the other FlutterError.reportError in this file

2025-03-20 18:56 UTC, chunhtai commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +        await Future<void>.delayed(const Duration(milliseconds: 500), () async {
Do you know where is the async operation this is waiting on? It will be better if we wait for a completer future instead of a delay

2025-03-20 19:08 UTC, camsim99 commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +        await Future<void>.delayed(const Duration(milliseconds: 500), () async {
Ok I thought this was needed to make sure that re-registering the `SensitiveContent` widget happens, but it seems to pass without it. Let's see what happens in CI because I did see a failure before.

We use a completer to complete the fake async method call, but I thought we needed to wait for the `Future` that the `FutureBuilder` relies on to finish to check that the actual `SensitiveContent` widget `child` is built. I thought we couldn't use a `Completer` for this without faking/mocking the `Future` that the `FutureBuilder` relies on.

2025-03-20 20:08 UTC, chunhtai commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +        await Future<void>.delayed(const Duration(milliseconds: 500), () async {
a pump should be enough since unittest uses a fake async. Unless you are introducing scheduleTask or other type a random delay future in the widget, we shouldn't need to wait a real future in unittest. and even then, we should expose a future for test to await in the `await tester.runAsync`

2025-03-20 22:21 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      throw UnsupportedError(
True, I'm on board with keeping it 👍

2025-03-20 23:26 UTC, chunhtai approved these changes
Since this is widget is marked as not production ready and is unreachable in common way. None of my comments are blocking, but I hope we can address them before they become public

2025-03-20 23:26 UTC, chunhtai commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        return UNKNOWN_CONTENT_SENSITIVITY;
shouldn't this return error result instead?

2025-03-20 23:26 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      result = await sensitiveContentChannel.invokeMethod<String>(
Why are we using string intead of index of enum to communicate the sensitivity level?

2025-03-20 23:26 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      result = await sensitiveContentChannel.invokeMethod<String>(
right now the communication is the following.

andoird (int) -> converting to String -> channel ->  converting string to enum -> dart(enum)

dart(enum) -> converting to String -> channel -> converting string to int -> andoird (int)


we could just do the following

android (int) -> converting to enum int in dart -> channel -> recast int to enum -> dart(enum)

dart(enum) -> recast to int -> channel -> converting to android int -> andoird (int)

2025-03-20 23:26 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  _unknown,
for cases where you send _unknown through channel, can we just return error instead?

2025-03-20 23:26 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    final ContentSensitivity contentSensitivity = ContentSensitivity.values.firstWhere(
If we use int, we don't need to do a linear look up and can just recast with `ContentSensitivity.values[result]`

2025-03-20 23:26 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentRegistrationFuture = SensitiveContentHost.register(widget.sensitivity);
we should have one method to replace the new old registration with new one instead of two. having two separate setSenstiveContent call worries me a bit.

2025-03-20 23:26 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentRegistrationFuture = SensitiveContentHost.register(widget.sensitivity);
this way, you only need to keep track of one future

2025-03-20 23:26 UTC, chunhtai commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +class SensitiveContentHost {
some where in the doc should mention this is not ready for production

2025-03-20 23:44 UTC, justinmc approved these changes
LGTM with nits, assuming the checks pass 👍

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  /// not change and thus, is safe cache.
"is safe cache" => "is safe to cache"

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    return (await sensitiveContentChannel.invokeMethod<bool>('SensitiveContent.isSupported'))!;
Why the `!` here?

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +          'Removing a SensitiveContent widget with ContentSensitivity $sensitivity is unsupported by _ContentSensitivitySetting',
This says "Removing", but is also called when adding.

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  String _getNegativeWidgetCountErrorMessage(ContentSensitivity sensitivity, int count) {
I think this could be static.

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +  void _reportUnknownContentSensitivityDetected(ContentSensitivity sensitivity) {
I think this could be static.

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +            stack: StackTrace.current,
Nit: Would it be better to get the stacktrace from `catch`? Or is it not passed here?

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +          exception: FlutterError('Attempted to set $desiredSensitivity sensitivity failed: $e}'),
Nit: "Attempted" => "Attempt" I think

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +}
This class looks good now, thanks for making the changes. Management of async stuff and error handling all make sense to me.

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentUnregistrationFuture = SensitiveContentHost.unregister(oldWidget.sensitivity);
Is there any reason to await here or might as well fire them both off at the same time?

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_error_handling_test.dart
> +      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler(
I think after doing this you also should remove it:

```dart
      addTearDown(
        () => tester.binding.defaultBinaryMessenger.setMockMethodCallHandler(
          SystemChannels.sensitiveContent,
          null,
        ),
      );
```

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_error_handling_test.dart
Thanks for splitting the tests into different files like this.

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_host_test.dart
> +          isTrue, //here
`//here` can be deleted.

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_host_test.dart
> +      testWidgets('with another sensitive widget ca', (WidgetTester tester) async {
What is `ca`?

2025-03-20 23:44 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_test.dart
> +      await tester.pump();
Thanks for explaining this. I'm glad you ended up not needing pumpAndSettle or expectLater.

2025-03-21 00:04 UTC, camsim99 commented
My understanding from the reviews and an offline discussion earlier was that this is ready to land. There's some cleanup and significant comments here, so I'm not sure I agree anymore.

I'll be OOO starting midday tomorrow, so I will try to address these comments, but will likely not land it. @reidbaker if I get it to a place where I feel confident that the reviews are addressed, I'll let you know in case you can land this while I'm out. Thank you everyone for the feedback and helping push this forward!

2025-03-21 12:16 UTC, camsim99 commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        return UNKNOWN_CONTENT_SENSITIVITY;
No. The idea here was that it a user calls `getContentSensitivity` and an unknown content sensitivity is returned by Android, we should not crash because the user may have no idea that an unknown one was returned, e.g. if we bump to Android 16 and the default content sensitivity changes. Instead, we return unknown to signal to the framework side to handle this accordingly.

I'm sure we could throw an error to accomplish the same thing but I think using the unknown value is a bit clearer in terms of our intent.

2025-03-21 12:30 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      result = await sensitiveContentChannel.invokeMethod<String>(
Isn't this the same level of work?

2025-03-21 12:32 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  _unknown,
@reidbaker and I discussed this at length. I'm sure we could accomplish the same thing that way, as I mentioned before, but this gives a standardized way for any platform to signal that an unknown value was detected and we should gracefully fail and not crash the app.

2025-03-21 12:33 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      result = await sensitiveContentChannel.invokeMethod<String>(
Also, I think the `String`s are more readable for the serialization/deserialization done on the platform side.

2025-03-21 12:33 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    final ContentSensitivity contentSensitivity = ContentSensitivity.values.firstWhere(
I'm not sold on converting back to ints. See https://github.com/flutter/flutter/pull/158473#discussion_r2006584854.

2025-03-21 12:36 UTC, camsim99 commented on packages/flutter/lib/src/widgets/sensitive_content.dart
> +    _sensitiveContentRegistrationFuture = SensitiveContentHost.register(widget.sensitivity);
I actually did this before but I thought it was breaking something. It was not; fixed.

2025-03-21 12:43 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    return (await sensitiveContentChannel.invokeMethod<bool>('SensitiveContent.isSupported'))!;
The method channel call results in `Future<bool>` which according to the analyzer, can be null.

2025-03-21 12:48 UTC, camsim99 commented on packages/flutter/test/widgets/sensitive_content_error_handling_test.dart
> +      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler(
Won't the `tearDown` do this?

2025-03-21 13:35 UTC, camsim99 commented on packages/flutter/test/widgets/sensitive_content_host_test.dart
> +      testWidgets('with another sensitive widget ca', (WidgetTester tester) async {
Accident. There are some others like this, as well. Removed!

2025-03-21 13:53 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      throw FlutterError('Content sensitivity $contentSensitivity failed to be set: $e');
Undid this.; now the `SensitiveContentost` just catches the `PlatformException`

2025-03-21 16:36 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +  _unknown,
sgtm

2025-03-21 16:55 UTC, chunhtai commented on engine/src/flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SensitiveContentChannel.java
> +        return UNKNOWN_CONTENT_SENSITIVITY;
sgtm.

2025-03-21 17:02 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    return (await sensitiveContentChannel.invokeMethod<bool>('SensitiveContent.isSupported'))!;
Oh right. This is probably another thing that we should do error handling for. Currently it looks like there is no try/catch where this is called in _register. Currently if this call fails, or if it unexpectedly returns null, then the app will crash. Instead I guess we should just consider it to be unsupported?

2025-03-21 17:03 UTC, justinmc commented on packages/flutter/test/widgets/sensitive_content_error_handling_test.dart
> +      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger.setMockMethodCallHandler(
Ah sorry I totally missed that above, this is good as-is :+1:

2025-04-01 21:37 UTC, chunhtai commented
Tangential to this pr.  for detecting visibility, looks like we already have this widget https://github.com/google/flutter.widgets/blob/master/packages/visibility_detector/lib/src/render_visibility_detector.dart#L17

2025-04-11 19:09 UTC, camsim99 commented
> Tangential to this pr. for detecting visibility, looks like we already have this widget https://github.com/google/flutter.widgets/blob/master/packages/visibility_detector/lib/src/render_visibility_detector.dart#L17

Noted this in https://github.com/flutter/flutter/issues/160051

2025-04-14 18:34 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    return (await sensitiveContentChannel.invokeMethod<bool>('SensitiveContent.isSupported'))!;
Sure, changed!

2025-04-14 18:44 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +      result = await sensitiveContentChannel.invokeMethod<String>(
I think the piece I was missing is that sending `String`s through the channel is slightly more costly, thanks.

Changed to use the index of enums instead of the name. I didn't make a matching enum on the Android side to do this (I don't think it adds much value since there aren't many modes), but if you feel strongly, let me know.

2025-04-14 18:45 UTC, camsim99 commented
This is ready for another look!

2025-04-16 20:20 UTC, camsim99 commented
> ### Timeline
> 
> #### Required for feature shipping
> -  Land this PR with the method channel implementation of content sensitivity.
> 
> #### Short-term follow up tasks
> - Ensure every `FlutterView` has a unique ID for the native `SensitiveContentPlugin` to identify them by: https://github.com/flutter/flutter/pull/162685
> - Add `SensitiveContent` widget to relevant Flutter widgets: https://github.com/flutter/flutter/issues/167302
> 
> #### Long-term follow up tasks
> - Convert this PR to use JNIgen: https://github.com/flutter/flutter/issues/160050. Verify no frames are dropped, revealing sensitive content during media projection: https://github.com/flutter/flutter/issues/164820.
> 
> #### Stretch goals
> - Make the `SensitiveContent` widget sensitive to the visibility of child widgets: https://github.com/flutter/flutter/issues/160051
> - Implement `autoSensitivity` mode: https://github.com/flutter/flutter/issues/160879
> - Investigate backwards compatibility for APIs < 35: https://github.com/flutter/flutter/issues/159208

Update: Had an offline @reidbaker and @jmagman, and we have decided that this feature is ok to ship into master without implementing it without JNIgen (ensuring  https://github.com/flutter/flutter/issues/164820 is fixed). By ship, I mean exposing the `SensitiveContent` widget to users in the widgets library and noting the security vulnerability in the `SensitiveContent` widget documentation in this PR, then landing it. I'll follow up with these changes shortly.

After this lands, I'll work on the short term tasks listed above, including implementing relevant Flutter widgets with `SensitiveContent`.

In the long term, I'll plan to return to the JNIgen work, though this would have to follow the architectural work of determining how we (Flutter) plans for JNI/FFI gen to work in the embedder for all platforms. This will require significant time and effort to do it right, which was a significant factor for making the decision to ship this feature as-is. When the work of determining how to use JNI/FFI gen in the embedder is picked up, the sensitive content feature will be a concrete example that can be used to demonstrate a proof of concept.

2025-04-17 17:32 UTC, reidbaker approved these changes
Last comment from me before we merge. Lets assume that we add this widget to a password field in the material library. How does a user turn off sensitive content for an integration test they have already built after updating to this version of flutter and the new version of material.

2025-04-17 20:02 UTC, camsim99 commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    final ContentSensitivity contentSensitivity = ContentSensitivity.values.firstWhere(
Yeah; we discussed in https://github.com/flutter/flutter/pull/158473#discussion_r2006584854

2025-04-17 20:06 UTC, camsim99 commented
>  Lets assume that we add this widget to a password field in the material library. How does a user turn off sensitive content for an integration test they have already built after updating to this version of flutter and the new version of material.

I assume we would add a field to `TextField` that would act as a switch for setting the sensitivity of the wrapper `SensitiveContent` widget in its implementation. By default, we can set it to `notSensitive` to not break people. Even if we don't, though, they can then just use the field to `notSensitive` to fix any other breakages.

2025-04-17 20:12 UTC, reidbaker commented
> > Lets assume that we add this widget to a password field in the material library. How does a user turn off sensitive content for an integration test they have already built after updating to this version of flutter and the new version of material.
> 
> I assume we would add a field to `TextField` that would act as a switch for setting the sensitivity of the wrapper `SensitiveContent` widget in its implementation. By default, we can set it to `notSensitive` to not break people. Even if we don't, though, they can then just use the field to `notSensitive` to fix any other breakages.

That would mean that in test runs they would need to build a way to override the value.

This value is sensitive and they want to protect their users but they dont want the protection during debug mode during testing. 

I think this user journey, the one where you want it off during testing is the one that I am the most worried about.

2025-04-17 20:33 UTC, camsim99 commented
If the `TextField` is baked deep into their implementation, then yes, they would need to expose a way to override the field we add from a test. Maybe I have to think deeper, but I think that's unavoidable; the only other alternative is to not bake it into Flutter widgets like `TextField` to begin with.

I think it's fair to ask developers to build that functionality, and I don't think that making them do so is a good enough reason to decide against baking `SensitiveContent` into relevant Flutter widgets. Building that functionality is likely not super difficult and certainly wouldn't outweigh the added security benefits.

2025-04-17 23:46 UTC, justinmc reviewed
I think I caught a place where errors can be silently swallowed, see comment below.

About the integration test discussion [above](https://github.com/flutter/flutter/pull/158473#pullrequestreview-2776484926), does that situation only apply to integration tests that are actually testing sharing their screen to another device?

2025-04-17 23:46 UTC, justinmc commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    }
This method looks like it will swallow errors and app developers might not be aware that something went wrong. They probably do want to assume that an error or null means `false`, but in addition I would probably do FlutterError.reportError.

You may want to do the error handling at the level of the caller of this method in order to align with how error handling is done for the other methods in this file, but it's up to you. The important part is just that errors don't get swallowed.

2025-04-18 14:10 UTC, reidbaker commented
> I think I caught a place where errors can be silently swallowed, see comment below.
> 
> About the integration test discussion [above](https://github.com/flutter/flutter/pull/158473#pullrequestreview-2776484926), does that situation only apply to integration tests that are actually testing sharing their screen to another device?

Yes it only applies to integration tests where the output of the screen is streamed.

2025-04-18 17:46 UTC, justinmc approved these changes
LGTM 👍 . Thanks for the error handling fix, looks great now.

About the integration test thing. Ok at least it's a rare case we're talking about here, but I agree we should provide a way to do this.

Would it be possible to mock isSupported and fake that sensitive content is not supported at all? It's easy to do this in a unit test ([example](https://github.com/flutter/flutter/blob/457e98a1e70b74b27a209721484c28e73a80caef/packages/flutter/test/services/text_input_test.dart#L232-L236)) but I'm not sure about in an integration test.

2025-04-21 22:21 UTC, chunhtai approved these changes
LGTM

2025-04-21 22:21 UTC, chunhtai commented on packages/flutter/lib/src/services/sensitive_content.dart
> +    final ContentSensitivity contentSensitivity = ContentSensitivity.values.firstWhere(
this can just be ContentSensitivity.values[result];

2025-04-25 13:56 UTC, closed without merging

2025-04-25 13:57 UTC, reidbaker commented
My force push was after running `git rebase --onto main HEAD`

2025-04-25 14:00 UTC, reidbaker commented
Well @camsim99 I messed this up. Now that the pr is closed I cant push to this branch anymore.