Added enum isLight, isDark and isSystem getter to ThemeMode enum
flutter/flutter pull request #159570
Opened 2024-11-27 20:57 UTC by stan-at-work

Added the following enums to the ThemeMode enum:

`isLight` => quick way to check if enum is ThemeMode.light.
`isDark` => quick way to check if enum is ThemeMode.dark.
`isSystem` => quick way to check if enum is ThemeMode.system.

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/159569

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide] and the [C++, Objective-C, Java style guides].
- [X] I listed at least one issue that this PR fixes in the description above.
- [ ] I added new tests to check the change I am making or feature I am adding, or the PR is [test-exempt]. See [testing the engine] for instructions on writing and running engine tests.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [ ] I signed the [CLA].
- [ ] All existing and new tests are passing.

2024-12-04 02:01 UTC, nate-thegrate reviewed
It's great to see the enhanced enum features here!

Let me know what you think about the `isLight`/`isDark` fields.

2024-12-04 08:28 UTC, stan-at-work commented on packages/flutter/lib/src/material/app.dart
> +  bool get isDark => this == ThemeMode.dark;
This is a good idea.

2024-12-04 18:35 UTC, Piinks reviewed
Hey @stan-at-work welcome! Thank you for contributing! This will also need tests to verify it works as expected. Thanks!

2024-12-04 23:28 UTC, stan-at-work commented
> Hey @stan-at-work welcome! Thank you for contributing! This will also need tests to verify it works as expected. Thanks!

They are added

2024-12-04 23:53 UTC, nate-thegrate requested changes
I think implementing [enhanced enum](https://dart.dev/language/enums#declaring-enhanced-enums) features here would be a missed opportunity if the `isDark` field doesn't accurately reflect whether the current theme brightness is dark.

I think it'd be easiest to mark this guy as a draft until https://github.com/flutter/engine/pull/56841 lands. @stan-at-work how does that sound?

2024-12-04 23:53 UTC, nate-thegrate commented on packages/flutter_test/test/theme_mode_test.dart
> +  });
This is hilarious 😂 (and also very well done!)

2024-12-04 23:56 UTC, stan-at-work commented
> I think implementing [enhanced enum](https://dart.dev/language/enums#declaring-enhanced-enums) features here would be a missed opportunity if the `isDark` field doesn't accurately reflect whether the current theme brightness is dark.
> 
> I think it'd be easiest to mark this guy as a draft until [flutter/engine#56841](https://github.com/flutter/engine/pull/56841) lands. @stan-at-work how does that sound?

What do you mean by this exacly ?

2024-12-04 23:57 UTC, stan-at-work commented
> I think implementing [enhanced enum](https://dart.dev/language/enums#declaring-enhanced-enums) features here would be a missed opportunity if the `isDark` field doesn't accurately reflect whether the current theme brightness is dark.
> 
> I think it'd be easiest to mark this guy as a draft until [flutter/engine#56841](https://github.com/flutter/engine/pull/56841) lands. @stan-at-work how does that sound?

I'm creating the test right now. will be pushing them when ready

2024-12-05 00:01 UTC, nate-thegrate commented
> > I think implementing [enhanced enum](https://dart.dev/language/enums#declaring-enhanced-enums) features here would be a missed opportunity if the `isDark` field doesn't accurately reflect whether the current theme brightness is dark.
>
> What do you mean by this exacly?

I would expect `isDark` to be true if we're using `ThemeMode.system` and the system brightness is dark. It'd be great if we could replace the current getter with something similar to the idea from https://github.com/flutter/flutter/pull/159570#discussion_r1868589981.

2024-12-05 23:57 UTC, matanlurey commented
Similar to https://github.com/flutter/engine/pull/56841#issuecomment-2521751434 I'm not supportive of this change, and have identical advice to what is provided in that comment.

2024-12-05 23:58 UTC, matanlurey requested changes
No LGTM; respective feature proposal was never reviewed prior to this PR. Leaving open to see if other members of the team feel strongly otherwise.

2024-12-06 17:06 UTC, matanlurey commented
Closing for same reason as https://github.com/flutter/engine/pull/56841#issuecomment-2523753544.

2024-12-06 17:06 UTC, closed without merging

2024-12-06 21:25 UTC, nate-thegrate commented
Sounds good! I'm down with closing this one and exploring other ways to improve the related APIs.

However: based on the interactions in [a previous Code of Conduct PR](https://github.com/flutter/flutter/pull/158195), I feel entitled to share my thoughts at this point, despite how they won't affect the outcome here.

<br><br>

> respective feature proposal was never reviewed prior to this PR.

Whether or not the proposal was reviewed prior to this PR is inconsequential, given that I reviewed these changes and was decidedly in support of expanding on the enums.

> I prefer that we keep dart:ui itself as "minimal" as possible.

This is a reasonable preference, though it only applies to the engine PR, not this one.

> If you want to define convenience getters in your own projects/packages that is of course possible via extension methods.

Unfortunately the style guide prohibits use of extension methods.

<br>

There are several alternative ways to improve the existing "theme brightness" APIs, and I also feel that the style guide's advice regarding `extension` ought to be revisited.

But I'd like to mention a few things from Flutter's [code of conduct](https://github.com/flutter/flutter/blob/master/CODE_OF_CONDUCT.md):

- When multiple contributors disagree on the direction for a particular patch or the general direction of the project, the conflict should be resolved by communication.
- A conflict is addressed when the participants agree that the final solution is _better_ than all the conflicting proposals.
- Listen. Consider and acknowledge people's points before responding.

<br>

The opinion of a more senior project member is especially valuable, but it's not a substitute for open discussion. I made a few points in [a previous comment](https://github.com/flutter/engine/pull/56841#issuecomment-2521932495), and there's no indication that any of them were acknowledged before the pull requests were closed:

- Having null safety enforced by static analysis makes it easier to catch a potentially `null` value.
- Using `.isDark(context)` ensures that a MediaQuery dependency is only created if `ThemeMode.system` is selected, and incorporating this logic into the enum makes it easy for this type of performance tweak to apply everywhere.

<br>

In the grand scheme of things, "adding enum fields" isn't anywhere near as important as "giving every contributor a chance to be heard". I will continue making effort to promote a spirit of openness and mutual respect in this community, and I expect other team members to do the same.

2024-12-06 21:29 UTC, Piinks commented
> Unfortunately the style guide prohibits use of extension methods.

FWIW, the style guide is specific to the flutter repo, not other users' projects.

2024-12-06 21:32 UTC, nate-thegrate commented
True that.

My intent was for the benefit to apply to the framework as well, per https://github.com/flutter/engine/pull/56841#issuecomment-2521932495:

> I created [a draft PR](https://github.com/nate-thegrate/flutter/pull/10/files) to show how this API could be utilized in Flutter's codebase.

2025-02-01 08:38 UTC, dabblingwithcode commented
What does fwiw mean?