Fix NavigationRail examples overflow alignment
flutter/flutter pull request #159937
Opened 2024-12-07 23:01 UTC by yaostyle

Fix the NavigationRail examples overflow alignment

### Before
Example 1:
<img src="https://github.com/user-attachments/assets/b9f54cd2-b2d1-44ee-a159-f1f04ed011e2" alt="NavigationRail Example 1 - Before" height="450">

Example: 2:
<img src="https://github.com/user-attachments/assets/be78bee7-f03d-40ff-ae36-679416c9c3d2" alt="NavigationRail Example 2 - Before" height="450">

### After
Example 1:
<img src="https://github.com/user-attachments/assets/5cda4599-b5e3-486b-8a54-583d209f8065" alt="NavigationRail Example 1 - After" height="450">

Example 2:
<img src="https://github.com/user-attachments/assets/60787799-dbcc-459e-b9a3-6f6631a57ecf" alt="NavigationRail Example 2 - After" height="450">

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making, or this PR is [test-exempt].
- [X] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2024-12-09 08:09 UTC, TahaTesser commented
@yaostyle Thanks for your contribution! It is a good practice to link an issue in the PR description. If the issue doesn't exist, please file one describing the bug.

2024-12-09 08:28 UTC, TahaTesser requested changes
There are format issues to address. 

Could you also please remove ThemeData with `useMaterial3` flag from example 1 as it is no longer needed to enable Material 3.  The `useMaterial3` flag defaults to true. 

```dart
    return const MaterialApp(
      home: NavRailExample(),
    ); 
```

2024-12-09 08:28 UTC, TahaTesser commented on examples/api/lib/material/navigation_rail/navigation_rail.0.dart
> +                    }),
```suggestion
                SegmentedButton<NavigationRailLabelType>(
                  segments: const <ButtonSegment<NavigationRailLabelType>>[
                    ButtonSegment<NavigationRailLabelType>(
                      value: NavigationRailLabelType.none,
                      label: Text('None'),
                    ),
                    ButtonSegment<NavigationRailLabelType>(
                      value: NavigationRailLabelType.selected,
                      label: Text('Selected'),
                    ),
                    ButtonSegment<NavigationRailLabelType>(
                      value: NavigationRailLabelType.all,
                      label: Text('All'),
                    ),
                  ],
                  selected: <NavigationRailLabelType>{labelType},
                  onSelectionChanged:
                      (Set<NavigationRailLabelType> newSelection) {
                    setState(() {
                      labelType = newSelection.first;
                    });
                  },
                ),
```

This fixes indents and adds comma to the line.

2024-12-09 08:28 UTC, TahaTesser commented on examples/api/lib/material/navigation_rail/navigation_rail.0.dart
> +                    }),
```suggestion
           SegmentedButton<double>(
                  segments: const <ButtonSegment<double>>[
                    ButtonSegment<double>(
                      value: -1.0,
                      label: Text('Top'),
                    ),
                    ButtonSegment<double>(
                      value: 0.0,
                      label: Text('Center'),
                    ),
                    ButtonSegment<double>(
                      value: 1.0,
                      label: Text('Bottom'),
                    ),
                  ],
                  selected: <double>{ groupAlignment },
                  onSelectionChanged: (Set<double> newSelection) {
                    setState(() {
                      groupAlignment = newSelection.first;
                    });
                  },
                ),
```

2024-12-09 08:28 UTC, TahaTesser commented on examples/api/lib/material/navigation_rail/navigation_rail.0.dart
> +                  },
```suggestion
                  onChanged: (bool value) {
                    setState(() {
                      showLeading = value;
                    });
                  },
```

I think we can assign the switch value to flip bool value.

2024-12-09 08:28 UTC, TahaTesser commented on examples/api/lib/material/navigation_rail/navigation_rail.0.dart
> +                  },
```suggestion
                  onChanged: (bool value) {
                    setState(() {
                      showTrailing = value;
                    });
                  },
```

2024-12-09 08:28 UTC, TahaTesser commented on examples/api/lib/material/navigation_rail/navigation_rail.1.dart
> +                ),
```suggestion
                  SwitchListTile(
                    title: Text(showLeading ? 'Hide Leading' : 'Show Leading'),
                    value: showLeading,
                    onChanged: (bool _) {
                      setState(() {
                        showLeading = !showLeading;
                      });
                    },
                  ),
                  SwitchListTile(
                    title: Text(showTrailing ? 'Hide Trailing' : 'Show Trailing'),
                    value: showTrailing,
                    onChanged: (bool _) {
                      setState(() {
                        showTrailing = !showTrailing;
                      });
                    },
                  ),
```

2024-12-09 08:28 UTC, TahaTesser commented on examples/api/lib/material/navigation_rail/navigation_rail.1.dart
> +                    }),
```suggestion
                    onSelectionChanged: (Set<double> newSelection) {
                      setState(() {
                        groupAlignment = newSelection.first;
                      });
                    },
                  ),
```

2024-12-09 08:28 UTC, TahaTesser commented on examples/api/lib/material/navigation_rail/navigation_rail.1.dart
> +                    }),
```suggestion
                    onSelectionChanged: (Set<NavigationRailLabelType> newSelection) {
                      setState(() {
                        labelType = newSelection.first;
                      });
                    },
                  ),
```

2025-01-02 12:51 UTC, TahaTesser commented
(Back from vacation)

@yaostyle 
Looks like there some branch conflicts to be resolved before we can merge this.

2025-01-02 12:52 UTC, TahaTesser requested changes
Please resolve conflicts

2025-01-28 23:09 UTC, goderbauer commented
(triage): @yaostyle Do you still plan to came back to this PR to address the feedback given above?

2025-01-31 13:30 UTC, TahaTesser commented
@yaostyle asked to help out. I've updated the PR. Removed redundant code sample and resolved conflict.

2025-01-31 13:31 UTC, TahaTesser commented
@bleroux could you please review the changes. If you approve, I'll also approve and land this since I pushed the new changes. :)

2025-01-31 14:34 UTC, bleroux approved these changes
LGTM!

2025-01-31 14:37 UTC, TahaTesser approved these changes
LGTM

2025-01-31 16:57 UTC, merged