Only bundle assets from transitive closure of dependencies
flutter/flutter pull request #160443
Opened 2024-12-17 15:25 UTC by sigurdm

Fixes https://github.com/dart-lang/pub/issues/4473

We could have used `pub deps` to obtain the dependency graph, but given the fact that we already read all the pubspec.yaml files to gather assets, we might as well use those directly, and avoid a process invocation.

Not sure if we should also bundle assets from dev_dependencies - not doing it might be breaking something - it would not be hard to change.

2025-01-10 16:33 UTC, sigurdm commented
I think all local tests are passing now. (perhaps we should refactor some tests, so package_config.json doesn't have to be created uniquely for so many tests....)

Not sure what happens in the customer tests, but I think it might be unrelated to this change.

2025-01-13 18:07 UTC, bkonyi reviewed
Initial quick review. Wil give this another pass later.

2025-01-13 20:55 UTC, bkonyi commented on packages/flutter_tools/lib/src/asset.dart
> +    // To Avoid bundling assets from dev_dependencies and other pub workspace
Nit: s/Avoid/avoid/

2025-01-13 20:55 UTC, bkonyi commented on packages/flutter_tools/lib/src/asset.dart
> +        throwToolExit('Could not locate package:$packageName. Try running `flutter pub get`');
Nit: Does this message need a period after it?

2025-01-13 20:55 UTC, bkonyi commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +import 'package:file/file.dart';
I don't think we should be importing `package:file` here. Instead, we should be importing `base/file_system.dart`.

2025-01-13 20:55 UTC, bkonyi commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +  while (packageNamesToVisit.isNotEmpty) {
I think this loop can be refactored. It's quite large and has some very large conditional blocks that are hard to follow. Can the logic setting rootUri and pubspec be moved into a helper function that returns a record? Then the operations adding to the `dependencies` list can be handled separately.

2025-01-13 20:55 UTC, bkonyi commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +    if (current == project.manifest.appName) {
This will only happen during the first iteration of the loop, right? If so, can we hoist it out of the loop?

2025-01-13 20:55 UTC, bkonyi commented on packages/flutter_tools/lib/src/flutter_plugins.dart
> +    final Dependency dependency = transitiveDependencies[packageName]!;
Ubernit: this variable declaration could be moved after the conditional below.

2025-01-14 09:04 UTC, sigurdm commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +import 'package:file/file.dart';
Thanks!

2025-01-14 10:12 UTC, sigurdm commented on packages/flutter_tools/lib/src/flutter_manifest.dart
> +    return devDependencies != null ? <String>{...devDependencies.keys.cast<String>()} : <String>{};
Yes

2025-01-14 10:13 UTC, sigurdm commented on packages/flutter_tools/lib/src/flutter_plugins.dart
> +    final Dependency dependency = transitiveDependencies[packageName]!;
Done

2025-01-21 09:58 UTC, sigurdm commented
Gentle ping on this one

2025-01-22 08:37 UTC, gabrielgarciagava commented
@spydon I know you are one of the melos maintainers. I would suggest you to keep track of this pull request. I would say this is a blocker to release the workspaces support to melos.

2025-01-22 08:46 UTC, spydon commented
> @spydon I know you are one of the melos maintainers. I would suggest you to keep track of this pull request. I would say this is a blocker to release the workspaces support to melos.

Thanks, I'm already subscribed to it. I've created one of the issues above. :)

2025-01-23 19:23 UTC, andrewkolos approved these changes
LGTM with nits

2025-01-23 19:24 UTC, andrewkolos commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +  bool followDevDependencies = false,
On yeah, I forgot about this comment. Let me look into this 😛

2025-01-24 09:08 UTC, sigurdm commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +    for (final dynamic name in dependenciesMap.keys) {
Done

2025-01-24 09:08 UTC, sigurdm commented on packages/flutter_tools/test/general.shard/web/compile_web_test.dart
> +import 'package:file/file.dart';
Done

2025-01-24 09:09 UTC, sigurdm commented on packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart
> +    List<String> excusiveDevDependencies,
Thanks! Done

2025-01-24 09:09 UTC, sigurdm commented on packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart
> +    final Map<String, dynamic> packageConfigMap = <String, dynamic>{'configVersion': 2};
Better! Done!

2025-01-24 09:13 UTC, sigurdm commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +  bool followDevDependencies = false,
I think we can just delete it.

Thanks for spotting!

2025-01-24 13:41 UTC, sigurdm commented
Do you think you could help me out with the customer_testing tests?

I cannot understand how my change could cause errors like:
```
 00:11 +8: /b/s/w/ir/x/t/flutter_customer_testing.super_editor.UDMNRS/tests/super_text_layout/test/super_text_test.dart: SuperText RenderSuperTextLayout calculates line count for one line of text
| ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
| The following TestFailure was thrown running a test:
| Expected: <1>
|   Actual: <2>
|
| When the exception was thrown, this was the stack:
| #4      main.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///b/s/w/ir/x/t/flutter_customer_testing.super_editor.UDMNRS/tests/super_text_layout/test/super_text_test.dart:203:11)
| <asynchronous suspension>
| #5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:193:15)
| <asynchronous suspension>
| #6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1064:5)
| <asynchronous suspension>
| <asynchronous suspension>
| (elided one frame from package:stack_trace)
```

But also I don't want to land this with red tests I don't understand...

2025-01-28 18:35 UTC, andrewkolos commented
> So in general when testing, you might want to use assets from your dev_dependencies, but not when building for deployment I had not really realized that.

Yeah, I was thinking the same. There are probably edge cases where including a font from a dev dependency would _unexpectedly_ cause a test to pass (i.e. the font was meant to be included from a regular dependency or the `assets` section in your pubspec); but I expect such a case would be extremely rare. That is to say, I think it is fine to continue to include assets from dev dependencies in tests—at least for now.

2025-01-30 16:14 UTC, bkonyi commented
I think including assets from dev dependencies in tests is fine since I assume our main concern here is reducing bundle size in shipped applications.

2025-01-30 16:39 UTC, bkonyi approved these changes

2025-01-30 16:39 UTC, bkonyi commented on packages/flutter_tools/lib/src/asset.dart
> +
Nit: extra whitespace

2025-01-30 16:39 UTC, bkonyi commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +    return null;
Is it worth adding verbose logging with the reason we failed to load package details where we return null?

2025-01-31 09:25 UTC, sigurdm commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +    return null;
Yeah - that is a good idea!

Added `printTrace` statements

2025-01-31 09:30 UTC, sigurdm commented
Attached g3fix https://critique.corp.google.com/cl/721374511

2025-01-31 15:24 UTC, bkonyi commented
Thanks for addressing the comments! LGTM!

2025-02-03 22:41 UTC, camsim99 commented
> Seems #161826 and #161343 are interferring with this.
> 
> @camsim99 do you know the desired semantics around plugins and assets from dev-dependencies? Should they be included in debug builds but not in release? Or should they be included for testing only (or not at all)?

My understanding is that we are working towards what I think https://github.com/flutter/flutter/issues/79261 proposes, i.e. assets from dev dependencies should be included in debug builds but not release. The changes I made are irrespective to testing I think. cc @matanlurey for input

2025-02-04 01:03 UTC, matanlurey requested changes
So the reason this failing is because the feature that @camsim99 and I implemented, which is, to omit plugins specified in `dev_dependencies` from release mode apps, looks like was broken as a result of the refactoring in this PR.

I can try cloning it locally and debug a bit tomorrow morning if you are still stuck, but as a starting point:
- <https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8723951633781029105/+/u/run_test.dart_for_tool_tests_shard_and_subshard_general/stdout> "plugins injectPlugins in release mode excludes dev dependencies from MacOS plugin registrant"
- <https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8723951633490693953/+/u/run_android_release_builds_exclude_dev_dependencies_test/stdout> "android_release_builds_exclude_dev_dependencies_test"

Not directly related: It's nice that this code was refactored to be synchronous and read the file system instead of shelling out to `pub deps`, but this was a large refactoring and in the future I should be included as a PR reviewer as someone who has to also maintain and understand these changes.

2025-02-04 02:28 UTC, matanlurey requested changes
Had a chance to do a longer review. Still needs more work, and I still think it makes sense to break this up into 2+ PRs.

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/lib/src/asset.dart
> +      }
Can you expand on this comment? From my understand it is because `computeTransitiveDependencies` (as implemented) might return packages listed in `{CURRENT_APP}/pubspec.yaml` that are not resolvable to a package (i.e. because no package config is present or it is out of date).

(If that's not true, let's expand on why).

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
This is a large change.

I am supportive - but I would have liked and prefer seeing this change made in isolation, i.e. _just_ changing `computeExclusiveDevDependencies` -> `computeTransitiveDependencies` in a PR, and fixing tests as needed, instead of making this refactor _and_ adding new features in a single PR.

For example, there will now be quite of a bit of unused code/technical debt; one example are the instances of [`FakePubWithPrimeDeps`](https://github.com/search?q=repo%3Aflutter%2Fflutter%20%22FakePubWithPrimedDeps%22&type=code) that were created and used the previous code branch that is now unused, and I'd want to see that cleaned up in the same PR that moves this from `pub deps` to walking the file system.

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +    isExclusiveDevDependency: true,
I'm confused here, why is the project itself listed as a dev-dependency of itself?

If it's because *everything* starts as a dev dependency and then is changed, please leave a comment.

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +      isExclusiveDevDependency: true,
Ditto above.

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +  List<String> dependencies;
Can this be final as well?

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/lib/src/flutter_manifest.dart
> +  /// Returns null on missing or invalid manifest.
Now that this is a public API: please expand on the comment and explain what exactly this does.

In particular, it would also be nice to explain what `yamlDocument` is expected to be as its a spooky `Object?` type (i.e. anything). Is that still necessary?

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/lib/src/flutter_plugins.dart
> +  final Map<String, Dependency> transitiveDependencies = computeTransitiveDependencies(
This is a change in behavior: previously unless `determineDevDependencies` we would not do any work.

It might be fine to make this unconditional, but just pointing that out if that was not your intent (the flag that flips on `determineDevDependencies` is _not `true` yet).

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/build_system/targets/assets_test.dart
> +void writePackageConfigFile(
Should this be moved into test/src and used through test instead of hard-coding a small variant of this across other tests?

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/asset_bundle_test.dart
>                'name': entry.key,
This is a good example, there are so many copy-pastes of this function across the flutter_tools tests.

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/asset_test.dart
> +  uses-material-design: true
Is this true while the main app is false intentionally?

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart
> +      FakeLogger(),
Why was the logger disabled? It's useful for understanding failures.

Instead, I'd:
- Keep BufferLogger
- Add assertions that the logger is free of errors (or warnings or both) in this function.

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart
> +class FakeLogger implements Logger {
I don't think we should do this (see comment above), but in general this is a better pattern:

```
class FakeLogger extends Fake implements Logger {}
```

It has the behavior you are looking and just dispatches the noral NSM, not requiring an ignore or anything.

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart
> +  void writePackages(List<Package> graph) {
Can you leave a short comment for the next person on what exactly this does?

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart
> +  Future<void> validateComputeGraph(
Ditto, what is it validating? Can you explain in the comment, thanks!

2025-02-04 02:28 UTC, matanlurey commented on packages/flutter_tools/test/general.shard/plugins_test.dart
In `injectPlugins in release mode` below, you'll find `fakePubWithTestPluginDevDependency = FakePubWithPrimedDeps`. That code branch will need to be updated to simulate a dev dependency using your new approach with reading the file system, it still assumes we're shelling out to `pub deps` which is why it's failing at your PR.

2025-02-04 02:33 UTC, matanlurey commented on packages/flutter_tools/test/commands.shard/hermetic/pub_test.dart
If it is no longer used after this PR (or another PR if we split it up), can you also delete the implementation and tests for `Pub.deps` (see https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/dart/pub_deps_test.dart and usages).

2025-02-04 02:34 UTC, matanlurey commented on packages/flutter_tools/test/commands.shard/hermetic/pub_test.dart
Similar, we should remove (3) in the error message here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/src/throwing_pub.dart

2025-02-04 10:42 UTC, sigurdm commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
> +    isExclusiveDevDependency: true,
Yes exactly! - we build the graph with everything marked as exclusive dev-dependencies, and then re-traverse the non-dev-dependencies part to remove that marker.

I'll add a comment!

2025-02-04 10:43 UTC, sigurdm commented on packages/flutter_tools/lib/src/compute_dev_dependencies.dart
I agree - this grew in scope.

I'll try to split it up!

2025-02-04 10:46 UTC, sigurdm commented
> in the future I should be included as a PR reviewer as someone who has to also maintain and understand these changes.

I'll keep you in mind going forward!

2025-02-04 21:56 UTC, matanlurey commented
> Thanks for the review - I got through some of it.

Thank you! Let me know if you can use any help, I'm free early AM/late PM if needed.

2025-02-07 15:01 UTC, spydon commented
@sigurdm when you split this PR up, can you link the other one here so that we can subscribe to that one too? :)

2025-02-07 15:02 UTC, sigurdm commented
@spydon sure!

Will be off next week, so might take a little while :/

2025-02-07 15:04 UTC, spydon commented
> @spydon sure!

Thanks!

> Will be off next week, so might take a little while :/

Have a good well deserved vacation (vinterferie I'm guessing)!

2025-02-07 15:06 UTC, sigurdm commented on packages/flutter_tools/test/general.shard/asset_test.dart
> +  uses-material-design: true
I don't remember - probably a mistake - I'll turn it to true in the main app also.

2025-02-07 15:14 UTC, sigurdm commented on packages/flutter_tools/test/general.shard/compute_dev_dependencies_test.dart
> +  Future<void> validateComputeGraph(
It should be renamed - I believe at one point I called `computeTransitiveDependencies` `computeTransitiveDependencies`... 
I'll add a comment also

2025-02-07 15:16 UTC, sigurdm commented on packages/flutter_tools/test/general.shard/plugins_test.dart
Fixed - they are now added to the FakeFlutterManifest

2025-03-06 13:09 UTC, gabrielgarciagava commented
Hello @sigurdm . What is the status of this PR? Just wondering since the last message was from 1 month ago

2025-03-06 13:10 UTC, sigurdm commented
> Hello @sigurdm . What is the status of this PR? Just wondering since the last message was from 1 month ago

Still working on this - sorry it is taking some time

2025-03-18 12:39 UTC, sigurdm commented on packages/flutter_tools/lib/src/dart/package_map.dart
> +  Directory candidateDir = fileSystem.directory(fileSystem.path.normalize(dir.absolute.path));
This is extracted in https://github.com/flutter/flutter/pull/165392

2025-04-29 14:03 UTC, sigurdm commented
@matanlurey I am fighting the google builder - I have attached a [g3fix](https://critique.corp.google.com/cl/721374511), but it seems to have become out of sync, but I don't seem to be able to delete it. Do you know of a button to push?

2025-05-16 11:56 UTC, sigurdm commented
@matanlurey are you ok with landing this in this state?
I'm not sure it is really meaningful to separate the last changes.

2025-05-16 15:30 UTC, matanlurey approved these changes
LGTM, thanks for pushing on this.

2025-05-19 16:02 UTC, merged

2025-05-23 08:33 UTC, gabrielgarciagava commented
@sigurdm I suppose this PR could not land on the current flutter stable release, right?
Do you have any idea if this is going to be cherry-picked to the current stable version or will we need to wait for the next stable release? :')

2025-07-10 09:03 UTC, davidnwaneri commented
When will it be possible to have this fix on stable

2025-07-10 09:08 UTC, spydon commented
> When will it be possible to have this fix on stable

Since it's in beta now I would guess that it will land in stable around the end of August.