Revert "[Reland] Force automatic ndk download when building for Andro…
flutter/flutter pull request #160454
Opened 2024-12-17 18:30 UTC by gmackall

…id (#160260)"

This reverts commit 2948917a470470c1ee2a3b5897dc229417776829.

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue. An issue is not required if the PR fixes something trivial like a typo.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] I followed the [breaking change policy] and added [Data Driven Fixes] where supported.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#overview
[Tree Hygiene]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md
[test-exempt]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md
[Features we expect every widget to implement]: https://github.com/flutter/flutter/blob/main/docs/contributing/Style-guide-for-Flutter-repo.md#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/blob/main/docs/contributing/Tree-hygiene.md#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/blob/main/docs/contributing/Chat.md
[Data Driven Fixes]: https://github.com/flutter/flutter/blob/main/docs/contributing/Data-driven-Fixes.md

2024-12-18 18:23 UTC, matanlurey requested changes
Please update the PR template/description and explain why this is being reverted (links to a bug or discussion, or at minimum a short summary of the change)

2024-12-18 18:28 UTC, gmackall commented
> Please update the PR template/description and explain why this is being reverted (links to a bug or discussion, or at minimum a short summary of the change)

Will do, made it for this [discord conversation](https://discord.com/channels/608014603317936148/608020293944082452/1318257329027809402) but then didn't update because I remembered tree is closed and rollers are off

2025-01-07 19:23 UTC, bparrishMines commented
@camsim99 @gmackall Does this need to land to fix the roller? The Flutter->packages roller has ndk warnings: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8726382232811460785/+/u/Run_package_tests/Firebase_Test_Lab/stdout?format=raw

2025-01-07 19:27 UTC, gmackall commented
> @camsim99 @gmackall Does this need to land to fix the roller? The Flutter->packages roller has ndk warnings: https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8726382232811460785/+/u/Run_package_tests/Firebase_Test_Lab/stdout?format=raw

I don't think those warnings are of particular concern - this revert was speculatively put up because I saw some errors of the form
```
* What went wrong:
Script compilation errors:

  Line 36:     compileSdk = flutter.compileSdkVersion
                                    ^ Unresolved reference: compileSdkVersion

  Line 37:     ndkVersion = flutter.ndkVersion
                                    ^ Unresolved reference: ndkVersion

  Line 45:         minSdk = flutter.minSdkVersion
                                    ^ Unresolved reference: minSdkVersion
```

As [the commit](https://github.com/flutter/flutter/commit/2948917a470470c1ee2a3b5897dc229417776829) also included the use of the `FlutterExtension` values in `integration_test`. At this point (if we are still seeing those errors) I'd prefer to fix forward, if that is okay with you though (I have high confidence that those errors would be coming from that specific portion of the original commit, which isn't necessary to the original commits core functionality).

2025-01-07 19:28 UTC, closed without merging