Add platform_view_swift based on platform_view example
flutter/flutter pull request #18394
Opened 2018-06-12 06:40 UTC by mblaughton

This is a port of the Objective-C platform_view example in Swift. I tried to keep it true to the original, and the port matches the Objective-C version's behavior on my device.

2018-07-25 16:15 UTC, redbrogdon requested changes
Ian's got a good point. We could land this here and then move it over along with the others, but that's adding useless code to the commit history of a crowded repo.

@mblaughton, how about dropping the entire platform_view_swift directory into the root of flutter/samples? I can come along afterward and update the README and travis script to accommodate it.

2018-07-25 16:15 UTC, RedBrogdon commented on examples/platform_view_swift/ios/Runner/AppDelegate.swift
> +// Copyright 2017, the Flutter project authors.  Please see the AUTHORS file
I'd bump this to 2018 here and everywhere else.

2018-07-25 16:15 UTC, RedBrogdon commented on examples/platform_view_swift/lib/main.dart
> +                          child: Platform.isIOS
Unless you're planning to add Android (which I wouldn't recommend), I'd nip out this platform check.

2018-07-25 17:13 UTC, mblaughton commented
@RedBrogdon wrote: how about dropping the entire platform_view_swift directory into the root of flutter/samples?

Absolutely, will do -- Thanks for the feedback.

I'm away from my development environment for a couple weeks but will make the suggested changes around the week of August 6.

2018-07-26 20:07 UTC, RedBrogdon commented
Awesome. 

Thanks for putting this together. I'll go ahead and close this PR, and look for one in `flutter/samples` when you're ready.

2018-07-26 20:07 UTC, closed without merging