Always honor explicitly set keyboardType and inputAction for TextField
flutter/flutter pull request #20547
Opened 2018-08-13 22:57 UTC by goderbauer

With this change you can now create "wrapping" text fields that do not show the new line button:

```dart
new TextField(
  maxLines: null,
  keyboardType: TextInputType.text,
);
```

Fixes https://github.com/flutter/flutter/issues/20208

2018-08-14 00:14 UTC, goderbauer commented
@matthew-carroll @HansMuller

2018-08-14 00:21 UTC, matthew-carroll requested changes

2018-08-14 00:30 UTC, goderbauer commented on packages/flutter/test/widgets/editable_text_test.dart
> +  testWidgets('Correct keyboard is requested when maxLines = null', (WidgetTester tester) async {
As far as I can tell there is nothing to split. This is testing that I get the expected keyboard type (multiline) with expected keyboard button (newline) when maxLines = null.

I did rename the test cases to be explicit about what's expected.

2018-08-14 00:30 UTC, matthew-carroll approved these changes

2018-08-15 18:35 UTC, merged

2019-09-23 14:12 UTC, MappingSteve commented
@goderbauer - but suppose coder *wants* a newline button?  Or does multi-line text field not support newline character?