ensure that ScrollPosition._pixels is non-null after construction
flutter/flutter pull request #23508
Opened 2018-10-25 13:45 UTC by SteveAlexander

When an app uses scrollable widgets, but there is no PageStorage in the context, it can happen that `ScrollPosition.pixels` is never initialized, and remains `null`. Later on, if we're running in debug mode, when the widget gets disposed, the following `assert` in `dispose()` gets called, crashing the app.

```
  @override
  void dispose() {
    assert(pixels != null);
    activity?.dispose(); // it will be null if it got absorbed by another ScrollPosition
    _activity = null;
    super.dispose();
  }
```

This patch ensures that `_pixels` is set to something during ScrollPosition construction.

See https://github.com/flutter/flutter/issues/21630 (part 2) for more discussion of this, when the problem shows up, and why I believe this is a good remedy.

2018-10-25 14:39 UTC, SteveAlexander commented
This comment in particular helps explain what I think is going on here:

https://github.com/flutter/flutter/issues/21630#issuecomment-419854991

I'll paste the relevant part here:


Also, for reference as it might help understand why `ScrollController.dispose()` has `assert(pixels != null)` — I think this was carried over a couple of refactors from `ScrollPositionWithSingleContext.dispose()` in this commit:

https://github.com/flutter/flutter/commit/c288c7064f9e2a9f9e3f4188fcccf1ad103ef61b?diff=split

There's a doc / comment in the commit that explains:

```
  /// The `initialPixels` argument can be null, but in that case it is
  /// imperative that the value be set, using [correctPixels], as soon as
  /// [applyNewDimensions] is invoked, before calling the inherited
  /// implementation of that method.
```

This comment is missing in the code on master now.

So, I believe the semantics of `pixels` have changed since this code was written, and it is now okay for `pixels` to be `null`, although it needs setting (via `correctPixels`) before certain methods are called.

If an app has a `PageStorage` as an `InheritedWidget` then `pixels` will be set properly. From today's code, the `restoreScrollOffset` method is called as the last thing the `ScrollPosition` constructor does.

```
  /// The default implementation reads the value from the nearest [PageStorage]
  /// found from the [context]'s [ScrollContext.storageContext] property, and
  /// sets it using [correctPixels], if [pixels] is still null.
  ///
  /// This method is called from the constructor, so layout has not yet
  /// occurred, and the viewport dimensions aren't yet known when it is called.
  @protected
  void restoreScrollOffset() {
    if (pixels == null) {
      final double value = PageStorage.of(context.storageContext)?.readState(context.storageContext);
      if (value != null)
        correctPixels(value);
    }
  }
```

So another approach to fixing this is to keep `assert(pixels != null)` in `dispose()`, but ensure that all users of `ScrollPosition` that aren't using `PageStorage` in their context always explicitly call `correctPixels` after creating the `ScrollPosition`.

The fix would be tracking down all times a `ScrollPosition` or subclass is created, determining if it will exclusively be used in a `PageStorage` context, and if not calling `correctPixels(0.0);` before it is used. Or, setting `initialPixels` when constructing the `ScrollPosition`.

Now this approach sounds fragile — the only time a developer will see that they didn't set `correctPixels` as needed is later on, when the `ScrollPosition` is disposed. And it's hard to see a cause-effect relationship there. This is different than other methods on `ScrollPosition` that require a non-null `pixels` value, as there you can see a direct causal relationship when the code fails.

It also introduces a kind of extra coupling between `ScrollPosition` and the app it is to be used in. An app could be working just fine, and when it's reorganised to no longer use `PageStorage`, a seemingly unrelated error about `pixels != null` appears.

Therefore, I think the right thing to do here is to allow `pixels` to be `null` on `ScrollController.dispose()`.

2018-10-25 14:41 UTC, SteveAlexander commented
I see the automated test runner failed on "tool_tests-windows" — but looking at the logs, it looks like a fault in the test runner infrastructure — a lock was not released from a previous test run.

2018-11-01 17:08 UTC, dnfield commented
Can you add a test for this to make sure we don't regress it?

I've re-kicked the windows bot that flaked out.

2019-01-02 18:46 UTC, HansMuller requested changes
Just a reminder. This PR needs a test per the review.

2019-01-18 00:36 UTC, goderbauer commented
Closing this PR since it has been open for a very long time without much activity. @SteveAlexander feel free to re-open it when you're able to address the review feedback.

2019-01-18 00:36 UTC, closed without merging