Added sample code for TextField widget [flutter#21136]
flutter/flutter pull request #23608
Opened 2018-10-27 02:19 UTC by raacker

adding a simple sample code :)

2018-10-27 07:13 UTC, Hixie commented
cc @gspencergoog for review

2018-11-01 16:39 UTC, gspencergoog approved these changes

2018-11-01 16:39 UTC, gspencergoog commented on packages/flutter/lib/src/material/text_field.dart
> +  /// allows 25 characters only and calls callback method when user presses the
```suggestion
  /// allows input of up to 25 characters and calls a callback method when the user presses the
```

2018-11-01 16:39 UTC, gspencergoog commented on packages/flutter/lib/src/material/text_field.dart
> +  /// This example shows how to create [TextField] as password input which
```suggestion
  /// This example shows how to create a [TextField] as a password input field which
```

2018-11-01 16:39 UTC, gspencergoog commented on packages/flutter/lib/src/material/text_field.dart
> +  ///
You should add a 
```dart
/// ...
///
```
here, just to indicate that these two statements are probably separated by some logic in a real app.

2018-11-01 16:39 UTC, gspencergoog commented
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2018-11-01 16:39 UTC, gspencergoog commented
Thanks for the PR!

2018-11-05 06:39 UTC, gspencergoog requested changes

2018-11-05 06:39 UTC, gspencergoog commented on packages/flutter/lib/src/material/text_field.dart
> +  /// ...
Sorry, I made a mistake, it should be this (so that the example code is evaluated properly by the compiler):
```suggestion
  /// // ...
```

2019-01-07 20:42 UTC, gspencergoog commented on packages/flutter/lib/src/material/text_field.dart
> +  /// ...
Yes, you should rebase.

2019-01-07 20:44 UTC, gspencergoog commented
Sorry for not responding, this fell off my radar.  Rebase and see that the precommit checks pass still, and I'll commit it.

![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2019-01-07 20:44 UTC, gspencergoog approved these changes

2019-01-22 20:33 UTC, goderbauer commented
@raackerAny chance you can rebase these changes as per the previous message above? Once you do that (and all checks pass) we can submit this PR.

2019-01-28 18:41 UTC, goderbauer commented
I am going to close this PR as stale since there hasn't been any activity for a while. @raacker if you ever find the time to address the comments above, feel free to re-open.

2019-01-28 18:41 UTC, closed without merging

2019-04-20 08:50 UTC, raacker commented
@goderbauer Very sorry about late response. I totally forgot about this PR. But I found that example for TextField is already on dev branch so I'll just leave it and try to find another pickles I can contribute on. Thanks!