<Improve ReorderableListView. When start Dragging, Extend list by add…
flutter/flutter pull request #25781
Opened 2018-12-26 13:20 UTC by mugku

…ing last item>

2018-12-26 13:41 UTC, mugku commented
Improve ReorderableListView. Improve ReorderableListView. When start Dragging, Extend list by adding last item.
change file : ..src/material/reorderable_list.dart

2019-07-19 19:31 UTC, dnfield commented on packages/flutter/lib/src/material/reorderable_list.dart
> +    this.canControlexpandedReorderList = false,
nit: this parameter name seems a it confusing to me, and should probably have a capital `Expanded` anyway.

Also, please revert the formatting changes made in this file.

2019-07-19 19:31 UTC, dnfield commented on packages/flutter/lib/src/material/reorderable_list.dart
> +  /// When start Dragging, Control to Extend list by adding last item
I'm not really sure what this means and it is not a complete sentence.  What is this actually doing?

All doc comments should start with a complete sentence ending with a `.`.

2019-07-19 19:32 UTC, dnfield requested changes
This needs tests.  It also could use some clarification about what's actually happening here for docs.  Formatting changes should be reverted.

2019-07-20 04:59 UTC, closed without merging