Tighten up TextField animations
flutter/flutter pull request #26706
Opened 2019-01-17 15:47 UTC by marcoms

This fixes a linear animation where the `TextField` floating label ascends to the top, as well as some extra fine-tuning.

Commit message with extra context:
```
    Tighten up text field animations

    The floating label was previously linear, so I introduced a CurvedAnimation
    and wired it up to _kTransitionCurve for consistency.
    The previous curve used for _kTransitionCurve had a longer ramp-up time
    compared to the example on material.io, so I changed it to Curves.ease,
    which matches more closely. I also reduced the duration very slightly,
    again to resemble the material spec video.

    New-style text fields with floating labels and rounded borders aren't
    very common natively on Android yet, so that's why I primarily used
    https://material.io as my source for this
```

2019-01-17 17:51 UTC, HansMuller commented
I think you're on the right track here.

The latest material motion specification for selecting an outline textfield has a duration of 150ms.

The label's Y, scale, the label's outline color and the outline's stroke width, and the label's gap opening animations are all eased with "80% incoming, 40% outgoing". I believe that would be a `const Curve(0.8, 0.0, 0.4, 1.0)`.

2019-01-18 18:17 UTC, marcoms commented
Do you mean the Standard Easing at [Motion > Speed > Easing](https://material.io/design/motion/speed.html#easing)? I tried to find a part of the spec that defined the animation curve for a text field but couldn't find it.

I just tried finding the closest matching curve to [this video example](https://storage.googleapis.com/spec-host-backup/mio-design%2Fassets%2F1Bna_M1j7fpIpDbNOLR1d32fjB7kARjLE%2Ftextfields-anatomy-label-text-do.mp4), which seemed to match `Curves.ease`, but I could be wrong.

2019-01-18 22:02 UTC, marcoms commented
No worries, we'll use that then. Although apparently it should be `Cubic(0.4, 0, 0.2, 1)` instead of `Cubic(0.8, 0, 0.4, 1)` according to this:

![screenshot from 2019-01-18 21-58-36](https://user-images.githubusercontent.com/4211302/51415046-58199400-1b6c-11e9-8e17-fdab61b08558.png)

... Which is `Curves.fastOutSlowIn` which we were using before :D

So I'll switch back to that, and just change the duration to 150ms.

2019-07-19 19:39 UTC, dnfield requested changes
Can you add some tests for this?

2019-08-15 05:47 UTC, dnfield commented
I'm going to close this PR due to lack of activity.  If you plan to continue with it, please feel free to re-open it once it's been synced up to HEAD and has some test(s) added.  If you need help with that feel free to reach out to me.

2019-08-15 05:47 UTC, closed without merging