Support using flutter with specific version
flutter/flutter pull request #26840
Opened 2019-01-21 07:17 UTC by lext-7

Add a `version` command in flutter_tools to support using flutter with specific version.  

`flutter version`: list a flutter versions.
`flutter version 1.1.5`: use flutter version 1.1.5.

2019-01-22 18:23 UTC, jonahwilliams requested changes
This will need some tests. You can see the examples in the test folder, they will use `testUsingContext` to inject a mock processManager. You can then have this return whatever you want for the various git commands.

This command should also warn the user if they checkout an older version which does not support this command.

2019-01-22 18:23 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +  final String description = 'Flutter version commands.';
Please describe what the command does.

2019-01-22 18:23 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +      return null;
Return a successful result here

2019-01-22 18:23 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +      tags.forEach(print);
printStatus

2019-01-22 18:23 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +    int code;
Remove: see below

2019-01-22 18:23 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +    code = await runCommandAndStreamOutput(<String>[
```suggestion
    int code = await runCommandAndStreamOutput(<String>[
```

2019-01-22 18:23 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +          context: PubContext.pubUpgrade,
nit: here and elsewhere, indent by 2 spaces

2019-01-22 18:23 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +    return null;
Here and elsewhere for returns
```suggestion
    return return FlutterCommandResult(ExitStatus.success);
```

2019-01-24 13:43 UTC, lext-7 commented
@jonahwilliams Tests are added.

2019-01-30 02:46 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +// Copyright 2016 The Chromium Authors. All rights reserved.
```suggestion
// Copyright 2019 The Chromium Authors. All rights reserved.
```

2019-01-30 02:46 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/version.dart
> +      'Switching Flutter to version ${flutterVersion.frameworkVersion}${withForce ? ' with force' : ''}...');
Move to one line
```suggestion
      printStatus('Switching Flutter to version ${flutterVersion.frameworkVersion}');
```

2019-01-30 02:46 UTC, jonahwilliams commented on packages/flutter_tools/test/commands/version_test.dart
> +// Copyright 2015 The Chromium Authors. All rights reserved.
```suggestion
// Copyright 2019 The Chromium Authors. All rights reserved.
```

2019-01-30 02:47 UTC, jonahwilliams commented
Just some minor nits, cc @dnfield for a second pass

2019-01-30 05:53 UTC, dnfield requested changes
Sorry for being late to the party on this, but I'm a little skeptical of including this in the Flutter tooling.  I think it's a great idea, and I think it can certainly be useful, but probably as a separate package (perhaps a `pub global` package.

This seems like it would work something like `rvm` or `pyenv` or perhaps even `gradlew` (which we also recently discussed as something that is clearly valuable but doesn't really belong in the tooling itself).  Making it part of the tool runs the risk of having  user downgrade to a version of Flutter that doesn't support this command, and it also runs the risk of some day downgrading to a version that no longer uses the most current method(s) of distributing Flutter.

2019-01-30 06:09 UTC, jonahwilliams commented
@dnfield we do already have the flutter channel command, this is fairly similar and I think is okay - provided there are warnings for going back to old versions.

2019-01-30 06:14 UTC, dnfield commented
Fair enough.

I'm not sure how we can properly determine the "safe" version for this though.  That won't be determined until after this patch lands, and depending on a variety of factors it's really hard to say what version would be safe to put in there.  Perhaps it could be set to the commit has immediately before this one - although even that is slightly risky, as someone could land something between updating it here and actually merging this.

2019-01-30 06:20 UTC, jonahwilliams commented
We could simply push it a bit in the future and err on false-positive

2019-02-02 15:03 UTC, lext-7 commented
Is there any other problem? Can this pr be merged?

2019-02-02 15:25 UTC, dnfield approved these changes

2019-02-04 19:20 UTC, jonahwilliams approved these changes
LGTM

2019-02-04 19:26 UTC, merged

2019-02-11 18:26 UTC, Hixie commented
Thanks for this contribution.

In the future please first file a bug to discuss the rationale for a change.
For details see: https://github.com/flutter/flutter/wiki/Tree-hygiene

2020-12-30 09:33 UTC, Denesh11 commented
can you help me guys..I have a flutter version 1.22.4 ,dart sdk version 2.10.3 but i need dart sdk less than 2.0.0... how to solve this

2021-07-07 00:38 UTC, dpedrinha commented
> can you help me guys..I have a flutter version 1.22.4 ,dart sdk version 2.10.3 but i need dart sdk less than 2.0.0... how to solve this

Found your answer @Denesh11?

2021-07-07 04:49 UTC, Denesh11 commented
> > can you help me guys..I have a flutter version 1.22.4 ,dart sdk version 2.10.3 but i need dart sdk less than 2.0.0... how to solve this
> 
> Found your answer @Denesh11?

yes, I have found a solution.

2021-07-07 06:13 UTC, dpedrinha commented
> > > can you help me guys..I have a flutter version 1.22.4 ,dart sdk version 2.10.3 but i need dart sdk less than 2.0.0... how to solve this
> > 
> > 
> > Found your answer @Denesh11?
> 
> yes, I have found a solution.

@Denesh11 do you really think I was just worried about you?? We don't know each other man, I was asking for the solution. But never mind, I found it too.