Refactor ios bundleid/android application process logic.
flutter/flutter pull request #27471
Opened 2019-02-03 16:23 UTC by kangwang1988

When creating a flutter project,
Make sure: applicationid for android conforms to: https://developer.android.com/studio/build/application-id

Make sure: bundleid for ios conforms to:
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/understanding_utis/understand_utis_conc/understand_utis_conc.html
(Not only the name,but also the organization, as it's a check for whole bundleid.)

2019-02-08 20:32 UTC, gspencergoog requested changes

2019-02-08 20:32 UTC, gspencergoog commented on packages/flutter_tools/lib/src/commands/create.dart
> +  final RegExp disallowed = RegExp(r'[^a-zA-Z0-9_\.]');
```suggestion
  final RegExp disallowed = RegExp(r'[^\w\.]');
```

2019-02-08 20:32 UTC, gspencergoog commented on packages/flutter_tools/lib/src/commands/create.dart
> +  final RegExp segmentPatternRegex = RegExp(r'^[a-zA-Z][a-zA-Z0-9_]*$');
```suggestion
  final RegExp segmentPatternRegex = RegExp(r'^[a-zA-Z]\w*$');
```

2019-02-08 20:32 UTC, gspencergoog commented on packages/flutter_tools/lib/src/commands/create.dart
> +  //It must have at least two segments (one or more dots).
```suggestion
  // It must have at least two segments (one or more dots).
```

2019-02-08 20:32 UTC, gspencergoog commented on packages/flutter_tools/lib/src/commands/create.dart
> +  name = name.replaceAll(disallowed, '');
You could just call `replaceAll` once on the merged value that is returned below, instead of calling it for each part.

2019-02-09 06:52 UTC, kangwang1988 commented
@gspencergoog 
Issues resolved.

2019-02-11 16:18 UTC, gspencergoog commented
Thanks, those look good.

Can you also please add a test in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands/create_test.dart
That verifies that the application ID and bundle ID conform to the right pattern/number of segments?

2019-02-11 16:19 UTC, gspencergoog commented
And you'll need to make sure that the tool_tests that are currently failing pass, of course.

2019-02-11 16:24 UTC, kangwang1988 commented
@gspencergoog 
Got it, will do it soon.

2019-02-13 00:17 UTC, kangwang1988 commented
@gspencergoog 
Test issues resolved.

2019-02-13 03:37 UTC, gspencergoog approved these changes

2019-02-13 03:39 UTC, gspencergoog commented
Thanks for the PR!  I'll merge this as soon as the tree is green.

2019-02-13 03:40 UTC, merged