Cupertino TextField Cursor Fix
flutter/flutter pull request #27697
Opened 2019-02-08 20:38 UTC by Piinks

Fix for #26261

Changes CupertinoTextField's cursorColor to read from CupertinoTheme instead of prior default of activeBlue. CursorColor will still default to activeBlue for light theme and activeOrange for dark theme if a primary color has not been specified for the CupertinoTheme.

2019-02-08 21:02 UTC, gspencergoog requested changes

2019-02-08 21:02 UTC, gspencergoog commented on packages/flutter/lib/src/cupertino/text_field.dart
> +          cursorColor: _cursorColor,
```suggestion
          cursorColor: CupertinoTheme.of(context).primaryColor,
```

2019-02-08 21:02 UTC, gspencergoog commented on examples/flutter_gallery/ios/Runner.xcodeproj/project.pbxproj
> +		19B5D85DA1BD905553A8E437 /* Pods-Runner.release.xcconfig */ = {isa = PBXFileReference; includeInIndex = 1; lastKnownFileType = text.xcconfig; name = "Pods-Runner.release.xcconfig"; path = "Pods/Tar
You probably don't want this XCode project change in this PR: they're unrelated changes that are easily separable, so I'd put them in separate PRs. (or just revert this change if you didn't mean to make it).

2019-02-08 21:31 UTC, Hixie commented on packages/flutter/lib/src/cupertino/text_field.dart
> +  /// Defaults to activeBlue for light theme, activeOrange for dark theme, or
please hyperlink to `activeBlue` et al (put the fully qualified name in square brackets)

2019-02-08 21:35 UTC, Hixie commented on packages/flutter/lib/src/cupertino/text_field.dart
> +  /// settable primaryColor for customization.
I would say `Defaults to the [CupertinoThemeData.primaryColor] of the ambient theme, which itself defaults to [CupertinoColors.activeBlue] in the light theme and [CupertinoColors.activeOrange] in the dark theme.`

2019-02-08 21:35 UTC, Hixie commented
test?

2019-02-08 21:44 UTC, xster reviewed
In general, we want to add tests to any behaviour we implement. You can copy things from this test https://github.com/flutter/flutter/blob/master/packages/flutter/test/cupertino/text_field_test.dart#L158 as an example to implement in test/cupertino/text_field_test.dart

2019-02-08 21:44 UTC, xster commented on packages/flutter/lib/src/cupertino/text_field.dart
> +          cursorColor: widget.cursorColor ?? CupertinoTheme.of(context).primaryColor,
small detail but since themeData is already pulled out above, you can just write `themeData.primaryColor` here.

2019-02-09 00:30 UTC, xster reviewed
LGTM, thanks

2019-02-09 00:30 UTC, xster commented on packages/flutter/test/cupertino/text_field_test.dart
> +    await tester.pump();
I suspect things will work without this additional pump since the line above is pumping a frame already

2019-02-09 00:36 UTC, gspencergoog approved these changes

2019-02-11 20:54 UTC, merged