Make FAB's icon optional
flutter/flutter pull request #27711
Opened 2019-02-09 04:28 UTC by ocavue

2019-02-13 20:01 UTC, HansMuller requested changes
This change looks reasonable however a test will be needed.

It would be enough for the test to create an extended FAB with just a label and then verify the geometry of the button and the label.

2019-02-14 08:32 UTC, ocavue commented
@HansMuller Test has been added.

2019-02-21 07:02 UTC, ocavue commented
@HansMuller Do you have time to re-review this PR? ⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄

2019-02-22 00:07 UTC, HansMuller approved these changes

2019-02-22 00:08 UTC, HansMuller commented
This fix looks good (nice test). I'm going fix one trivial formatting problem and then land it.

2019-02-22 20:47 UTC, merged