Alf master refactor build number name logic
flutter/flutter pull request #27743
Opened 2019-02-10 12:47 UTC by kangwang1988

This PR aims at several things:
1. Use pub_semver to check a version in pubspec.yaml meets the requirements specified in https://semver.org/.
2. Don't limit build-number/build-name as a fixed format. Instead, validate it according to the target(ios/android).
3. Make sure that build-number/build-name are always validated no matter it's specified by the `flutter command` or version in pubspec.yaml.

This will also fix:
https://github.com/flutter/flutter/issues/27589

2019-02-12 00:02 UTC, gspencergoog requested changes
Thanks for the this!

2019-02-12 00:02 UTC, gspencergoog commented on packages/flutter_tools/test/build_info_test.dart
> +// Copyright 2016 The Chromium Authors. All rights reserved.
Should be 2019 if this is a new file.

2019-02-13 15:47 UTC, gspencergoog approved these changes

2019-02-13 15:48 UTC, merged

2019-02-13 15:50 UTC, gspencergoog commented
Oh! Sorry, @kangwang1988, I thought you still needed someone to merge your changes for you, but I see you're a project member now.  I'll let you merge your own from now on...

2019-02-13 15:55 UTC, kangwang1988 commented
@gspencergoog 
Thank you~