Fix backspace and clear length in AnsiStatus
flutter/flutter pull request #28477
Opened 2019-02-25 23:35 UTC by liyuqian

Might be related to https://github.com/flutter/flutter/issues/26922

Without the fix, the newly added test failed with the following error:

```
00:07 +24 -4: Spinners AnsiStatus works for fuchsia [E]
  Expected: a non-negative value
    Actual: <-1>
     Which: is not a non-negative value
  The following line have overflow backtraces:
                                                                                                                                                                                                                                                                                                                           ⡿ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣟ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣯ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣷ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣾ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣽ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣻ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⢿ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⡿ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣟ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣯ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣷ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣾ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣽ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣻ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⢿ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⡿ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣟ (This is taking an unexpected                                                                                                                                                                                                                                                                                                                           ⣯ (This is taking an unexpectedly long time.)
```

2019-02-25 23:37 UTC, jonahwilliams commented
@gspencergoog should review this PR

2019-02-26 20:01 UTC, gspencergoog requested changes

2019-02-26 23:08 UTC, liyuqian commented on packages/flutter_tools/lib/src/base/logger.dart
> +    stdout.write('${_kBackspaceChar * _totalMessageLength}${_kClearChar * _totalMessageLength}${_kBackspaceChar * _totalMessageLength}');
I believe that `_totalMessageLength` already considered padding.

2019-02-26 23:16 UTC, liyuqian commented on packages/flutter_tools/lib/src/base/logger.dart
> +const String _kBackspaceChar = '\b';
Done.

2019-02-26 23:16 UTC, liyuqian commented on packages/flutter_tools/lib/src/base/logger.dart
> +const String _kClearChar = ' ';
Done.

2019-02-26 23:16 UTC, liyuqian commented on packages/flutter_tools/lib/src/base/logger.dart
> +    stdout.write('$_backspace');
Done.

2019-02-26 23:30 UTC, gspencergoog approved these changes

2019-02-26 23:30 UTC, gspencergoog commented
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

Thanks for fixing that!

2019-02-27 01:15 UTC, merged