Add semantics label to FadeInImage.
flutter/flutter pull request #28799
Opened 2019-03-03 10:28 UTC by salihgueler

This PR is adding semantics label and Semantics to FadeInImage. It has two semantics label one for placeholder and another for the real image. It brings the semantics label according to the image shown on screen. I got the idea to add different semantics for placeholder and image from @jonahwilliams on the related issue.

This fixes https://github.com/flutter/flutter/issues/26040

2019-03-03 10:28 UTC, salihgueler commented
I signed it!

2019-03-03 10:29 UTC, salihgueler commented
I signed it!

2019-03-03 18:03 UTC, jonahwilliams requested changes
This needs a test that verifies that the correct label is used when the placeholder or regular image is shown.

2019-03-03 18:03 UTC, jonahwilliams commented on packages/flutter/lib/src/widgets/fade_in_image.dart
> +        ? _placeholderResolver._imageInfo
nit: revert unrelated change

2019-03-03 18:03 UTC, jonahwilliams commented on packages/flutter/lib/src/widgets/fade_in_image.dart
> +        ? widget.placeholderSemanticLabel
nit: 2 space indent

2019-03-04 08:51 UTC, salihgueler commented on packages/flutter/lib/src/widgets/fade_in_image.dart
> +    if (widget.excludeFromSemantics)
I prefer this usage as well, I haven't included them because it was used this way in the Image class. I will add it.

2019-03-04 14:09 UTC, salihgueler commented
@jonahwilliams All changes requested are done.

2019-03-04 14:17 UTC, salihgueler commented on packages/flutter/lib/src/widgets/fade_in_image.dart
> +        ? _placeholderResolver._imageInfo
That's true, I reverted it. 👍

2019-03-04 14:17 UTC, salihgueler commented on packages/flutter/lib/src/widgets/fade_in_image.dart
> +        ? widget.placeholderSemanticLabel
Fixed it as well 👍

2019-03-06 05:29 UTC, goderbauer commented
@salihgueler Can you please fix the analyzer warnings? 
https://cirrus-ci.com/task/6272263532838912

2019-03-06 10:10 UTC, salihgueler commented
@goderbauer Just fixed it, sorry about that :)

2019-03-06 23:38 UTC, jonahwilliams approved these changes

2019-03-06 23:38 UTC, jonahwilliams commented
LGTM

2019-03-06 23:38 UTC, merged

2019-05-28 20:05 UTC, tvolkert commented
@salihgueler in https://github.com/flutter/flutter/pull/33370 I propose that we remove the `placeholderSemanticLabel` property.  The logic is that a placeholder image is a transient visual artifact, not something that affects the underlying semantic meaning of the image -- and that the semantic label should persist across the loading of the image.

Based on a quick code search, I didn't see any usages of this property either.

Do you have any objections to this removal?  If so, please comment in https://github.com/flutter/flutter/pull/33370

Thanks!