Replace flutter.io -> flutter.dev in dart and java files.
flutter/flutter pull request #29065
Opened 2019-03-08 21:59 UTC by GaryQian

Since we are now switching to using flutter.dev, we should refer to the new site in the docs/comments/code/etc.

This is a partial conversion that changes all framework dart and java files.

I have skimmed this to make sure the places where we change the URL are reasonable.

The complete transition will involve slightly more technical examination to make sure we are not converting binary files or places where a conversion is invalid/impractical.

2019-03-08 22:09 UTC, gspencergoog requested changes

2019-03-08 22:09 UTC, gspencergoog commented on dev/docs/platform_integration/lib/android.dart
> +/// [Flutter platform integration APIs for Android.](https://docs.flutter.dev/javadoc/)
```suggestion
/// [Flutter platform integration APIs for Android.](https://api.flutter.dev/javadoc/)
```

2019-03-08 22:09 UTC, gspencergoog commented on dev/docs/platform_integration/lib/ios.dart
> +/// [Flutter platform integration APIs for iOS.](https://docs.flutter.dev/objcdoc/)
```suggestion
/// [Flutter platform integration APIs for iOS.](https://api.flutter.dev/objcdoc/)
```

2019-03-08 22:09 UTC, gspencergoog commented on dev/tools/dartdoc.dart
> +/// docs.flutter.dev/flutter for now, so we need to manipulate paths
```suggestion
/// api.flutter.dev/flutter for now, so we need to manipulate paths
```

2019-03-08 22:09 UTC, gspencergoog commented on dev/tools/dartdoc.dart
> +/// at the root of docs.flutter.dev. We are keeping the files inside of
```suggestion
/// at the root of api.flutter.dev. We are keeping the files inside of
```

2019-03-08 22:09 UTC, gspencergoog commented on dev/tools/dartdoc.dart
> +    branch == 'stable' ? 'https://docs.flutter.dev/' : 'https://master-docs.flutter.dev/',
```suggestion
    branch == 'stable' ? 'https://api.flutter.dev/' : 'https://master-api.flutter.dev/',
```

2019-03-08 22:09 UTC, gspencergoog commented on dev/docs/platform_integration/lib/android.dart
> +/// [Flutter platform integration APIs for Android.](https://docs.flutter.dev/javadoc/)
And below, everywhere...

2019-03-08 22:09 UTC, gspencergoog commented on dev/tools/dartdoc.dart
> +    branch == 'stable' ? 'https://docs.flutter.dev/' : 'https://master-docs.flutter.dev/',
And below, everywhere, for https://master-api.flutter.dev.

2019-03-08 22:09 UTC, gspencergoog commented on packages/flutter_tools/test/ios/mac_test.dart
> +Signing iOS app for device deployment using developer identity: "iPhone Developer: test@flutter.dev (1122334455)"
@kf6gpe, are the MX records set up to do mail correctly to .dev too?  This is just text, so it doesn't really do anything, but the thought just occured to me...

2019-03-08 22:18 UTC, GaryQian commented
FYI, api.flutter.dev is currently a redirect to docs.flutter.io

2019-03-08 22:46 UTC, gspencergoog commented
Yeah, but that will change. @kf6gpe is doing that.

2019-03-08 22:48 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2019-03-09 08:26 UTC, DanTup commented on dev/docs/platform_integration/lib/android.dart
> +/// [Flutter platform integration APIs for Android.](https://api.flutter.dev/javadoc/)
I don't believe the redirects handle this properly - these two URLs are not the same - the .dev one is redirecting to the root (and non-folder URLs on the new domain are 404!).

2019-03-09 08:29 UTC, DanTup commented on examples/flutter_gallery/lib/demo/material/buttons_demo.dart
> +        documentationUrl: 'https://api.flutter.dev/flutter/material/RaisedButton-class.html',
eg. this one is currently a 404. Though if you're not planning on landing this until the domains are swapped over properly, that's probably not an issue.

2019-03-11 14:46 UTC, gspencergoog commented
Sorry, I thought we had a DNS alias already in place for this, not just the HTML redirect.  I agree, don't commit this yet.

2019-03-11 15:46 UTC, kf6gpe commented
Yes. I'm thinking we can actually point the new URL at the old firebase
project and then commit this, and when we publish to the new Firebase
project as part of our next stable release, just switch the back end
project.

Does that make sense?



On Mon, Mar 11, 2019 at 7:47 AM Greg Spencer <notifications@github.com>
wrote:

> Sorry, I thought we had a DNS alias already in place for this, not just
> the HTML redirect. I agree, don't commit this yet.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/flutter/flutter/pull/29065#issuecomment-471569154>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABXoRF95lyVlehEvOLBXiSwZYjx24Myjks5vVmxngaJpZM4bmM6W>
> .
>

2019-06-04 18:15 UTC, GaryQian commented
Closing this, as lots of conflicts means it is probably easier to just remake this PR.

2019-06-04 18:15 UTC, closed without merging