Made stepper size dynamic
flutter/flutter pull request #31036
Opened 2019-04-14 15:31 UTC by sanket143

Converted array entries for ListView to ListView.builder to build ListView and will add GlobalKey everytime the Steps are changed.

2019-08-15 06:14 UTC, dnfield requested changes
This change seems like it is likely incorrect - I don't think we want to introduce GlobalKeys for this widget, and it's not clear why using a `ListView.builder` is better here than the other method - we don't expect steppers to have large numbers of children.

If you do plan to address this feedback, it would probably be best to open an issue with a description and reproduction of the bug you're trying to fix. This change would also need a test to help us make sure we don't regress whatever bug it's fixing.

2019-08-15 06:14 UTC, dnfield commented on packages/flutter/lib/src/material/stepper.dart
> +      itemBuilder: (BuildContext context, int i){
nit: The style guide says there should be a space there

2019-08-15 06:14 UTC, dnfield commented on packages/flutter/lib/src/material/stepper.dart
> +        i < _keys.length ? _keys[i] : _keys.add(GlobalKey());
Why are we introducing a GlobalKey here? This seems like it will introduce some pretty serious overhead...

2019-08-15 06:14 UTC, dnfield commented on packages/flutter/lib/src/material/stepper.dart
> +            _buildVerticalBody(i)
nit: trailing comma

2019-08-15 06:14 UTC, dnfield commented on packages/flutter/lib/src/material/stepper.dart
> +              child: _buildVerticalHeader(i)
nit: trailing comma

2020-01-07 19:05 UTC, Piinks commented
This PR has not been updated in a few months, so I am going to close it. If you would like to revisit and address the changes requested above, please feel free to reopen it! :) Thanks!

2020-01-07 19:05 UTC, closed without merging