[fluttter_tool] Set IPHONEOS_DEPLOYMENT_TARGET to 8
flutter/flutter pull request #36117
Opened 2019-07-13 05:25 UTC by lookfirst

## Description

Prevents this warning in xcode during build:

`The iOS deployment target is set to 7.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'Flutter')`

- [x ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x ] I signed the [CLA]
- [x ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [ x] No, this is *not* a breaking change.

2019-07-25 17:03 UTC, jonahwilliams commented
cc @jmagman

2019-07-25 17:58 UTC, jmagman requested changes
I don't think we want to force pods to 8.0 if the pod doesn't support it, or even worse force it down if it only supports a later version.
How about we add `:inhibit_warnings` to the pod install?  I'm all for not clogging up my pristine project no-warning with deprecation warnings, etc from dependencies.
```
pod 'Flutter', :path => engine_dir, :inhibit_warnings => true
```
```
pod 'Flutter', :path => File.join(symlink, File.basename(p[:path])), :inhibit_warnings => true
```
And if you could add it to the following places to keep it all consistent that would be really helpful!
```
packages/flutter_tools/templates/cocoapods/Podfile-ios-swift:    pod p[:name], :path => File.join(symlink, 'ios')
packages/flutter_tools/templates/cocoapods/Podfile-ios-objc:    pod p[:name], :path => File.join(symlink, 'ios')
packages/flutter_tools/templates/cocoapods/Podfile-macos:      pod p[:name], :path => File.join(symlink, 'macos')
```

2019-07-25 18:24 UTC, lookfirst commented
> I don't think we want to force pods to 8.0 if the pod doesn't support it

The error message is saying that `the range of supported deployment target versions for this platform is 8.0`, so you kind of have to force it to 8, no?

2019-07-25 18:31 UTC, jmagman commented
> How about we add `:inhibit_warnings` to the pod install?

Actually, I just tried this and it doesn't suppress that warning.

After reading https://github.com/CocoaPods/CocoaPods/issues/7314 I don't really want to imply libraries support a higher version than they claim to, but I also really hate warnings in dependencies you have no power to fix.

At a minimum, the the 8.0 version in the change doesn't match the version at the top.
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
```
And now we're chasing a moving target of whatever Xcode decides is the minimum deploy version.
What if we did this:
```
config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
```
Then the individual pod targets will inherit IPHONEOS_DEPLOYMENT_TARGET either from the Pods project from that `platform :ios` call, or inherit from the SDK platform?

Whatever we do in this Podfile should be duplicated in Podfile-ios-swift and Podfile-macos.

2019-07-29 18:25 UTC, jmagman commented
> What if we did this:
> 
> ```
> config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
> ```
> 
> Then the individual pod targets will inherit IPHONEOS_DEPLOYMENT_TARGET either from the Pods project from that `platform :ios` call, or inherit from the SDK platform?
> 
> Whatever we do in this Podfile should be duplicated in Podfile-ios-swift and Podfile-macos.

@lookfirst What do you think about this proposal?

2019-07-29 21:25 UTC, LinusU commented
I think that this value needs to be controlled by the end user, forcing it to 8.0 would not be good. It would break our project which uses API:s only available on iOS 12.0 and later.

I've posted about this before, here are some relevant threads:

https://github.com/flutter/flutter/pull/32791#issuecomment-500885428
https://github.com/CocoaPods/CocoaPods/issues/4859#issuecomment-500838635
https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-516167158

2019-07-29 21:33 UTC, jmagman commented
> I think that this value needs to be controlled by the end user, forcing it to 8.0 would not be good. It would break our project which uses API:s only available on iOS 12.0 and later.

@LinusU Would it work for your use-case if the pods did not have a deployment version, but instead inherited the value from the `platform :ios` specified in your Podfile?

![Screen Shot 2019-07-29 at 2 31 32 PM](https://user-images.githubusercontent.com/682784/62084211-9ecc0300-b20d-11e9-9325-8a919d44b78f.png)

with `platform :ios, '12.0'` becomes
![Screen Shot 2019-07-29 at 2 31 41 PM](https://user-images.githubusercontent.com/682784/62084228-a2f82080-b20d-11e9-84ae-b9c66a2cf87b.png)

2019-07-30 02:07 UTC, lookfirst commented
I just discovered that https://github.com/flutter/plugins/tree/master/packages/google_sign_in requires 9.0 (there was warnings in Xcode when I included it), so now I'm past 8 anyway.

2019-07-30 02:09 UTC, lookfirst commented
In order to move from 8 to 9, I had to edit the Podfile as well as the xcode project. It was a pain.  If you can simplify it so that I just edit the Podfile, that would be great.

2019-07-30 09:58 UTC, LinusU commented
@jmagman 

> Would it work for your use-case if the pods did not have a deployment version, but instead inherited the value from the platform :ios specified in your Podfile?

Yes, that would be perfect 👍

2019-07-30 17:04 UTC, jmagman commented
> In order to move from 8 to 9, I had to edit the Podfile as well as the xcode project. It was a pain. If you can simplify it so that I just edit the Podfile, that would be great.

@lookfirst Would you like me to take this over then?

2019-08-08 17:37 UTC, christopherfujino commented
@jmagman Are you going to fix this in a separate PR?

2019-08-08 17:58 UTC, jmagman commented
> @jmagman Are you going to fix this in a separate PR?

I was going to just take this one over. 

I started with:
```
post_install do |installer|
...
{{^withPluginHook}}
      # Inherit the deployment target from the `platform :ios` call above to avoid un-fixable warnings.
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
{{/withPluginHook}}
```
but it doubles down on the Podfile being a template, which goes against @xster's request for it to become dynamically generated here https://github.com/flutter/flutter/issues/9827

I need to find a mechanism to know if the app is a plugin example app AFTER the project is already generated, which there isn't right now AFAIK.

2019-08-08 19:28 UTC, jmagman commented
> > @jmagman Are you going to fix this in a separate PR?
> 
> I was going to just take this one over.

Actually it looks like there's no way to transfer a PR to another fork.  I will make a new one.

> but it doubles down on the Podfile being a template, which goes against @xster's request for it to become dynamically generated here https://github.com/flutter/flutter/issues/9827

I guess that issue has been open awhile though and the Podfile are already templates, so we can add it to the list of behaviors that needs to be migrated if it ever becomes generated on `flutter builds`.

2019-08-08 19:37 UTC, jmagman commented
Oh yeah, and the other issue is that the Podfile isn't added on create, it's actually added when the first plugin is added.  So at that point `withPluginHook` isn't available, either.

2019-08-10 04:03 UTC, xster commented
#9827 indeed probably needs a re-summary at the bottom. Based the issues I originally wanted us to fix, likely 75% of it is already done.

2019-09-05 17:09 UTC, zanderso commented
@jmagman What is the status of this PR? Can in be closed?

2019-09-09 22:27 UTC, jmagman commented
I documented the issue and proposed solutions in https://github.com/flutter/flutter/issues/40109.  Closing this PR.

2019-09-09 22:27 UTC, closed without merging