Fix missing version in iOS plugin example project
flutter/flutter pull request #37707
Opened 2019-08-06 17:21 UTC by szotp

## Description

I encountered this problem when working on a plugin.

1. Run `flutter create --template plugin hello_world`.
2. Build example on simulator - works ok.
3. Build example on simulator again - fails with very cryptic `Could not hardlink copy...` error.

After some investigation, I found out that Info.plist specifies build versions to be FLUTTER_BUILD_NUMBER & FLUTTER_BUILD_NAME. These variables were never defined because version parameter was missing. This caused very strange behavior when trying to install the app for the second time.

Adding version in pubspec fixes the problem.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

2019-08-08 19:55 UTC, jmagman approved these changes
This makes sense to me.  I wonder how was this ever working?

2019-08-08 19:57 UTC, jmagman requested changes
Actually, can you move the comment, too?

2019-08-09 17:25 UTC, jmagman commented
@collinjackson @iskakaushik What should we do with this one?

2019-08-09 18:37 UTC, collinjackson commented
@amirh I'm curious what you think about this.

Browsing through pub it seems like most Dart packages (including web and non-plugin Flutter) don't version their example apps.

Would it make sense for Flutter provide some sensible defaults for FLUTTER_BUILD_NUMBER and FLUTTER_BUILD_NAME rather than requiring every pubspec.yaml to specify a version?

2019-08-09 21:00 UTC, jmagman commented
It's really a shame the pub version and build number is overloaded to map to the iOS CFBundleShortVersionString and the build number is mapped to the iOS CFBundleVersion.  They really are different concepts.  Both are required to build iOS and macOS apps, but in pub-world version should only be required for publishing, and build number should most of the time not be present.

https://github.com/flutter/flutter/pull/37036#discussion_r308944932

@gspencergoog and I recently discussed proposing something similar to iosBundleIdentifier, like iosBundleShortVersionString, iosBundleVersion, but in the context of the new platform-specific plugin pubspec, depending on how that gets formatted.  And it's the same concept on macOS, but apps will likely have different build numbers between platforms.  You can imagine an app like Slack shipping to the iOS App Store at a different cadence than to the Mac App Store.
 
+@jonahwilliams

2019-08-22 17:04 UTC, christopherfujino commented
@collinjackson @amirh any update on this one?

2019-08-29 17:43 UTC, amirh commented
> Would it make sense for Flutter provide some sensible defaults for FLUTTER_BUILD_NUMBER and FLUTTER_BUILD_NAME rather than requiring every pubspec.yaml to specify a version?

I like @collinjackson's suggestion as it works for existing packages, and should be simple to do I believe.
Also when we do what @jmagman proposed above the example app's version won't be needed anyway...

@szotp would you be willing to trade this PR with a one that's using a default value for `FLUTTER_BUILD_NUMBER` if the buildNumber is unset? (as a stop gap until we do Jenn's proposal).

@jmagman is there a tracking issue for your proposal?

2019-08-30 14:36 UTC, szotp commented
@amirh yes, a default FLUTTER_BUILD_NUMBER would be better
Should I close this PR?

2019-08-30 15:36 UTC, amirh commented
Yes I think it make sense to close this PR and send a new one for a default value.

2019-09-02 06:11 UTC, closed without merging