Pass RouteSettings into all callers of showGeneralDialog. fixes #31261
flutter/flutter pull request #38631
Opened 2019-08-15 19:37 UTC by hpoul

## Description

Right now there is no way to customize the `RouteSettings` when using the `showDialog` functions. I can't think of a good reason to omit this, since it's pretty useful for e.g. analytics to track page names.

## Related Issues

* #31261

## Tests

I added the following tests:

* added test for `showDialog` to demonstrate how it is passed to the `NavigatorObserver`

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [x] No, this is *not* a breaking change.

2020-02-14 03:07 UTC, darrenaustin requested changes
Thanks for the PR, sorry this took us a while to review.

This looks great. I would only want to use `routeSettings` in place `settings` for the parameter names as it makes it more explicit when you are looking at parameter lists without the types.

If you could make these updates I will go ahead and approve this. If you are no longer interested in pursuing this, just let us know and we will have someone take it over and get it in. Thx.

2020-02-19 23:11 UTC, darrenaustin commented
I just attempted to do this myself and fix the merge conflicts, but I don't have write permission to your branch. If you like, I can just push this from one of my branches and close this PR.

2020-02-27 07:56 UTC, hpoul commented
@darrenaustin sorry, didn't check guthub notifications, and missed your message.. thanks, feel free to close this PR in favor of your own 👍

2020-02-27 20:47 UTC, darrenaustin commented
@hpoul thanks again for your contribution. Sorry we didn't get this in from your branch.  Closing as #51525 recreates this with some updates.

2020-02-27 20:47 UTC, closed without merging