[windows] Refactor to optimize vswhere queries
flutter/flutter pull request #40197
Opened 2019-09-11 00:01 UTC by franciscojma86

## Description
visual_studio.dart is not keeping track whether it has queried vswhere and didn't find an installation, of it hasn't performed any queries at all. This may cause unnecessary queries on the former case. This PR assigns a sentinel value of an empty map to the cached installation details to avoid repeating the queries.

## Related Issues
https://github.com/flutter/flutter/issues/40196

## Tests

I added the following tests:

This is a refactor so the behavior should continue as before.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

2019-09-11 03:18 UTC, stuartmorgan-g requested changes
Thanks! Sorry for writing this technical debt into the implementation in the first place.

2019-09-11 03:18 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/windows/visual_studio.dart
> +  Map<String, dynamic> get _catalog => _bestVisualStudioDetails[_catalogKey];
Optional: you could simplify the call sites using this by having it return an empty map instead of null; then they don't need to do null checks.

2019-09-11 03:18 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/windows/visual_studio.dart
> +    if (details == null || details.isEmpty) {
As above, you only need the second part.

2019-09-11 03:18 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/windows/visual_studio.dart
> +  /// that has all required components. If no installation is found, the cached
Let's add ", or {} if there is no such installation" to the end of the first sentence so the return contract is explicit up front.

The second part should be a new paragraph [per Dart style](https://dart.dev/guides/language/effective-dart/documentation#do-separate-the-first-sentence-of-a-doc-comment-into-its-own-paragraph).

Same for the other two *Details getters.

2019-09-11 03:18 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/windows/visual_studio.dart
> +    // or none is found, assign a sentinel empty value to avoid querying vswhere again.
This is essentially duplicating the note a few lines above; remove one or the other copy.

2019-09-11 03:18 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/windows/visual_studio.dart
> +        _cachedUsableVisualStudioDetails = <String, dynamic>{};
Optional: I found this re-assignment construction (where the usable version variable is set to a value that might not actually be usable, then unset if needed) a bit hard to follow; I think a local variable for the lookup would make it clearer:
```
if (_cachedUsableVisualStudioDetails == null) {
  Map<String, dynamic> visualStudioWithComponentsDetails = [...];
  visualStudioWithComponentsDetails ??= [...];
  if (visualStudioWithComponentsDetails != null) {
    if (installationHasIssues(visualStudioWithComponentsDetails) {
      _cachedUsable... = visualStudioWithCompontesDetails;
    } else {
      _cachedAny... = visualStudioWithCompontesDetails;
    }
  }
  _cachedUsableVisualStudioDetails ??= <String, dynamic>{};
}
return _cachedUsableVisualStudioDetails;
```

2019-09-11 03:18 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/windows/visual_studio.dart
> +    if (_usableVisualStudioDetails != null && _usableVisualStudioDetails.isNotEmpty) {
Simplify.

2019-09-12 21:03 UTC, stuartmorgan-g approved these changes

2019-09-12 22:48 UTC, merged