Fix Arm64 detection logic for devices
flutter/flutter pull request #40373
Opened 2019-09-12 18:34 UTC by markdiener

## Description

Flutter tools assumes that all 64 bit ARM cpus are able to run 64 bit code.

There are manufacturers that use 64 bit ARM cpus while installing 32 bit Android OS on it.

Added code that looks at the OS for 32 or 64 bit arm so dev tools do not try to download
64 bit code to 32 bit Operating systems.

## Tests

As far as tests, I have tested with my available android devices including Kindle Fire 8 and Motorola LG v30.

But this is device detection, so it requires physical devices more than I have available.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x] I signed the [CLA].
- [ x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [?] I updated/added relevant documentation (doc comments with `///`).
- [?] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [X ] No, this is *not* a breaking change.

2019-09-12 19:40 UTC, jmagman requested changes
1. You have analyzer issues, braces go on the same line, spaces between `//` and the comment text.  Match the code around where you are changing.
```
   info • Prefer final for variable declarations if they are not reassigned • packages/flutter_tools/lib/src/android/android_device.dart:195:18 • prefer_final_locals
```
Check out the style guide: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
2. You will needs tests for this.  See `android_device_test.dart`.

2019-09-12 19:41 UTC, jonahwilliams requested changes
We should have some existing tests that cover this code. They should be updated with new cases  + synthetic devices to ensure this logic is covered and doesn't get accidentally reverted

2019-10-03 14:00 UTC, markdiener commented
I will get back to this very shortly.  I am just trying to get some other deadlines met in the meantime.

2019-11-15 18:47 UTC, jonahwilliams commented
Closing due to lack of activity. I've filled https://github.com/flutter/flutter/issues/44999 to capture the issue here

2019-11-15 18:47 UTC, closed without merging