Fixes bug where route navigation rebuilds all below materialApp
flutter/flutter pull request #44731
Opened 2019-11-12 17:32 UTC by jonataslaw

## Description

This issue fixes unexpected MaterialApp rebuild errors when MaterialRoutePage or CupertinoRoutePage is called.

## Related Issues

opaque should be false for Screens Navigators, and true only for modals (ShowDialog should darken the rest of the screen).
MaterialPageRoute and CupertinoPageRoute navigation are inheriting "true" from PageRoute <T>, which causes an unexpected app rebuild bug.
For large apps with many routes (+20 Navigator.push) this can greatly degrade performance. Since all previous pages that are still in the widget tree will be rebuilt.
This pull fixes the errors in:

https://github.com/flutter/flutter/issues/39770
https://github.com/flutter/flutter/issues/11655
https://github.com/flutter/flutter/issues/29800
https://github.com/flutter/flutter/issues/16117
https://github.com/flutter/flutter/issues/11655

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Does your PR require Flutter developers to manually update their apps to accommodate your change?

- [ ] Yes, this is a breaking change (Please read [Handling breaking changes]). *Replace this with a link to the e-mail where you asked for input on this proposed change.*
- [x] No, this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2019-11-13 00:46 UTC, jonataslaw commented
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need an exemption to this rule, contact Hixie.
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

I add tests now. Thanks.

2019-11-21 20:12 UTC, goderbauer commented
> opaque should be false for Screens Navigators, and true only for modals (ShowDialog should darken the rest of the screen).

This seems backwards. `opaque: true` means that the route is completely covering all previous routes. So, a full screen route (like a PageRoute) should have `opaque: true`, whereas a dialog that keeps portions of the route below it visible should set `opaque: false`.

2019-11-21 22:34 UTC, jonataslaw commented
> > opaco deve ser falso para os navegadores de tela e verdadeiro apenas para os modais (ShowDialog deve escurecer o restante da tela).
> 
> Isso parece ao contrário. `opaque: true`significa que a rota está cobrindo completamente todas as rotas anteriores. Portanto, uma rota em tela cheia (como um PageRoute) deve ter `opaque: true`, enquanto uma caixa de diálogo que mantém partes da rota abaixo dela visíveis deve ser definida `opaque: false`.



> > opaque should be false for Screens Navigators, and true only for modals (ShowDialog should darken the rest of the screen).
> 
> This seems backwards. `opaque: true` means that the route is completely covering all previous routes. So, a full screen route (like a PageRoute) should have `opaque: true`, whereas a dialog that keeps portions of the route below it visible should set `opaque: false`.

Ok, I'll scan the code to find out where opaque = true is rebuilding all materialApp. The performance gap is very high, we are talking about almost triple ram usage, and creating a CPU spike that causes unexpected application shutdown.
(I used in this example 2 Text() and 1 CircularProgressIndicator() and the difference was almost triple, if you take the default example video_player plugin and use it, the app can't reach the eighth route without closing.)
https://www.youtube.com/watch?v=yVBqT6hg4VA
Anyway, I think it would be important to be able to control opaque = true or false (PageRouteBuilder allows this, only MaterialPageRoute and CupertinoPageRoute not), and this pull only does so, giving the dev an option to use if it deems it necessary.

2019-12-03 23:02 UTC, bleroux commented
@jonataslaw Could you share the small example app you run in your video ?

2019-12-09 02:42 UTC, SBDavid commented
I fix the "rebuild" problem by adding a key to Overlay build function.

First I add a GlobalKey to `OverlayEntry` class. For example `_key2`. This key will be used in `TickerMode`, the purpose is to give a Key to overlay offstage elements. 
```dart
class OverlayEntry {

  OverlayState _overlay;
  final GlobalKey<_OverlayEntryState> _key = GlobalKey<_OverlayEntryState>();

  final GlobalKey _key2 = GlobalKey();
}
```

And the next step is add `_key2` to build function.

```dart
class OverlayState extends State<Overlay> with TickerProviderStateMixin {
@override
  Widget build(BuildContext context) {
    final List<Widget> onstageChildren = <Widget>[];
    final List<Widget> offstageChildren = <Widget>[];
    bool onstage = true;
    print("overlay build");
    for (int i = _entries.length - 1; i >= 0; i -= 1) {

      final OverlayEntry entry = _entries[i];
      if (onstage) {
        print("onstage ${entry._key}");
        onstageChildren.add(_OverlayEntry(entry));
        if (entry.opaque)
          onstage = false;
      } else if (entry.maintainState) {
        offstageChildren.add(TickerMode(key: entry._key2, enabled: false, child: _OverlayEntry(entry)));
        print("offstage ${entry._key}");
      } else {
        print("!maintainState ${entry._key}");
      }
    }
    return _Theatre(
      onstage: Stack(
        fit: StackFit.expand,
        children: onstageChildren.reversed.toList(growable: false),
      ),
      offstage: offstageChildren,
    );
  }

}
```

And then Flutter diff algorithm will know how to update offstage element properly, other than just inflateWidget. The inflateWidget method will reload images which were used in offstage elements, thus cause serious performance issue.

2020-01-10 16:11 UTC, tony123S commented
Hi, why I get "The named parameter 'opaque' isn't defined" ?

```
 case ABC.ROUTE:
         return MaterialPageRoute(
           opaque: false,
          builder: (_) => ProxyProvider<Repository, ABCBloc>(
           builder: (context, repository, abcBLoc) =>
                 ABCBloc(repository: repository),
            dispose: (context, abcBLoc) => abcBLoc.dispose(),
             child: ABC(),
         ),
        );
```

2020-01-10 16:11 UTC, tony123S commented
opaque: false,

2020-02-04 09:13 UTC, dnfield reviewed
Is this still needed after https://github.com/flutter/flutter/pull/48900?

2020-02-06 18:24 UTC, jonataslaw commented
> Is this still needed after #48900?
I think PR #48900 was reversed by #49376

This PR is a workround for the material and cupertino routes that are already being treated more specifically by the goderbauer's PR. 
I preferred to create this PR for not interfering in the structure of the Overlay, and I was facing problems with the tests.
However, it also brings a feature, which is the possibility to define opaque / non-opaque routes without a PageRouteBuilder, in the MaterialPageRoute itself. The default behavior is still opaque routes, but it is possible to define them as translucent and obtain, for example, this behavior:

[https://i.stack.imgur.com/eSLPE.png]

In addition to adding this feature, it could be a quick solution for those who have a critical problem, since this problem has no side effects in all types of applications, but only in those that have many routes, or routes with listViews with many widgets.

2020-02-06 18:26 UTC, dnfield commented on packages/flutter/test/cupertino/route_test.dart
> +
Please remove this blank line.

2020-02-06 18:26 UTC, dnfield commented on packages/flutter/test/material/page_test.dart
> -
Please do not modify other files like this :)

2020-02-06 18:28 UTC, dnfield commented on packages/flutter/lib/src/cupertino/route.dart
> +  /// Use caution and awareness that rebuilding is necessary to properly display the back button.
This doc doesn't quite follow our style guide.  The first sentence should be on its own, and describe in one line what this does.  I'm not sure we should document this as preventing route reconstruction - it seems like it's more about whether the route is opaque or not.  Reconstruction is about an optimization that might happen if the route if opaque.

The second lines should be expanded a bit more - what does it mean for this to be true or false? Why do I care?

2020-02-06 18:28 UTC, dnfield commented on packages/flutter/lib/src/material/page.dart
> +  /// Use caution and awareness that rebuilding is necessary to properly display the back button.
Ditto.

2020-02-06 18:30 UTC, dnfield commented on packages/flutter/lib/src/cupertino/route.dart
> +  final bool opaque;
It seems strange to me to have a child class of page route change this behavior.

Perhaps we should consider adding a new class for this instead, that has the desired behaviors of MaterialPageRoute but also is transparent?

2020-02-06 18:31 UTC, dnfield requested changes
This will need tests to move forward.

I'm also not sure it feels quite right to have inheritors of PageRoute changing the way PageRoute wants to do opacity.  We should either let PageRoute be transparent and take it as a parameter in the ctor, or make these new classes that inherit from some other route type.

2020-02-06 18:33 UTC, dnfield commented
> > It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need an exemption to this rule, contact Hixie.
> > **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.
> 
> I add tests now. Thanks.

Perhaps you forgot to save files before committing?  Your changes to the test files only added and removed blank lines, which are not tests.

2020-02-10 18:03 UTC, goderbauer commented
With the change in #48900 it shouldn't matter for performance whether `opaque` is set to true or false. If you have a test that shows otherwise, please share that test with me.

Regardless of that, we should not tie the concept of Route opaqueness to whether routes rebuild or not as it's currently done in the documenting comment of this PR. 

Also, a PageRoute is explicitly designed as a Route that fully covers all Routes below it. Hence, `opaque` is hard-coded to true. If you want a non-opaque PageRoute (like in your example) you can always subclass PageRoute (or MaterialPageRoute) to override the value of the `opaque` property for your specific use case.

With that, I am going to close this PR.

2020-02-10 18:03 UTC, closed without merging