[flutter_tools] Fix for Unsupported Android Plugin version.
flutter/flutter pull request #46260
Opened 2019-12-06 22:59 UTC by slightfoot

Fix for Unsupported Android Plugin version.

2019-12-06 23:33 UTC, blasten commented
This probably needs a unit test

2019-12-07 00:21 UTC, timsneath commented
Marking for consideration as release blocker. cc @tvolkert

2019-12-07 00:38 UTC, blasten commented
I don't think it's a release blocker since we don't expect folks to upgrade Gradle/Android Gradle plugin on their own. We also need to make sure that those components are compatible with the Flutter Gradle plugin.  This AGP version might work, but generally speaking we want to have test for each version that we support.

2019-12-07 01:53 UTC, blasten commented
To summarize, Android Studio 3.5.3 started showing a banner that recommends to update the Android Gradle plugin to a version that the tool doesn't handle.

<img width="548" src="https://user-images.githubusercontent.com/1410613/70366997-e06e5980-1850-11ea-8b95-def74332a182.png">

I'm not sure about the full impact of this issue though.

2019-12-07 01:57 UTC, blasten requested changes

2019-12-07 01:57 UTC, blasten commented on packages/flutter_tools/lib/src/android/gradle_utils.dart
> +  if (Version.parse(androidPluginVersion) > Version.parse('3.5.0')) {
maybe just return '5.6.4' and remove this check and `throwToolExit`.  Finally, update the unit test.

2019-12-07 07:26 UTC, tvolkert commented
This definitely needs a test.

Also, are we sure this is a release blocker?  How common do we expect this failure mode to be?

2019-12-07 14:23 UTC, dnfield commented
I don't think this should be a release blocker.  We need to do testing to make sure this all plays nicely.  It's not on our default templates yet and using it may have other problems that need to be vetted out.

We should definitely fix this but it should really go through a longer cycle on dev/beta before being brought into the release.

2019-12-07 19:31 UTC, timsneath commented
I'll trust you all for making the right call on release blocker or not.

A better tag at this point might be "hotfix candidate", perhaps?

On Sat, Dec 7, 2019 at 6:23 AM Dan Field <notifications@github.com> wrote:

> I don't think this should be a release blocker. We need to do testing to
> make sure this all plays nicely. It's not on our default templates yet and
> using it may have other problems that need to be vetted out.
>
> We should definitely fix this but it should really go through a longer
> cycle on dev/beta before being brought into the release.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/flutter/flutter/pull/46260?email_source=notifications&email_token=AARWL67GDCB2VHOMZGRPLALQXOWWXA5CNFSM4JXDBNGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGGH4CA#issuecomment-562855432>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AARWL63FQVMV2NK22GCXCNLQXOWWXANCNFSM4JXDBNGA>
> .
>

2019-12-09 18:34 UTC, tvolkert commented
Removing release blocker label.  As @dnfield and @blasten say, we really should do more comprehensive testing of this through the normal channels and give it time to bake.

2020-01-09 18:09 UTC, zanderso commented
@blasten is this PR still relevant?

2020-01-09 18:59 UTC, blasten commented
I think so. @slightfoot are you still interested in working on this PR?

2020-01-10 02:38 UTC, slightfoot commented
> I think so. @slightfoot are you still interested in working on this PR?

Sure.

2020-01-11 17:40 UTC, sidhijakpat commented
In my case this is happening when I enable 
`setProperty("archivesBaseName", "AppName-" + versionName + "_" + versionCode)`,

when I disable those line, `flutter build apk` is running just fine.

I try to build the release apk using android studio, by opening `android` folder on project, and it turn out to be fine with those line enabled.

maybe it can help you tracing the error.

---
additional note:
```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale en)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)
```

`classpath 'com.android.tools.build:gradle:3.5.3'`

2020-01-22 06:25 UTC, sidhijakpat commented
turn out the problem is occur too when try to run on android, 
not only `flutter build apk`, 

> In my case this is happening when I run `flutter build apk` with
> `setProperty("archivesBaseName", "AppName-" + versionName + "_" + versionCode)` enabled,
> 
> when I disable those line, `flutter build apk` was running just fine.
> 
> I try to build the release apk using android studio, by opening `android` folder on project, and it turn out to be fine with those line enabled.
> 
> maybe it can help you tracing the error.
> 
> additional note:
> 
> ```
> ➜  ~ flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
>     locale en)
> 
> [!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
>       --android-licenses
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3)
> [✓] Android Studio (version 3.5)
> [✓] Connected device (1 available)
> ```
> 
> `classpath 'com.android.tools.build:gradle:3.5.3'`
> 
> Another note:
> running
> `flutter clean`
> `flutter pub cache repair`
> 
> didn't fix the issue

2020-01-24 19:13 UTC, blasten commented
I filed https://github.com/flutter/flutter/issues/49438. This will likely involve updating the Gradle version in the template as well.

2020-01-24 19:13 UTC, closed without merging

2020-01-27 13:20 UTC, abhimangalms commented
I'm also  facing the same issue.
current Gradle version is 5.4.1. But still nothing happens.