Changed old way of detecting debugMode to kReleaseMode
flutter/flutter pull request #46974
Opened 2019-12-13 14:27 UTC by Afsar-Pasha

## Description

Changed checking `inDebugMode` with `assert` to const `kReleaseMode`

## Related Issues

## Tests

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [X] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2019-12-13 17:10 UTC, dnfield requested changes
This is not the same.

The old code checks if asserts are enabled, which is true for debug but false for release and profile.

The new code checks if you're in release mode, which is false for profile.

2019-12-13 17:35 UTC, Afsar-Pasha commented
> This is not the same.
> 
> The old code checks if asserts are enabled, which is true for debug but false for release and profile.
> 
> The new code checks if you're in release mode, which is false for profile.

Fixed now

2019-12-13 17:41 UTC, dnfield reviewed
This maintains the same behavior now, but it's not clear to me why we should change this.  What's broken?  What are we improving?

It's possible this is allowing some more code to be shaken out of a debug build, but stripping dead code from a debug build isn't usually as much of a concern...

2019-12-13 17:47 UTC, Afsar-Pasha commented
I think that code was written when `kDebugMode` wasn't introduced, also isn't this the preferred way?

2019-12-18 22:50 UTC, goderbauer approved these changes
LGTM

2019-12-19 21:32 UTC, goderbauer commented
On second thought, Dan is right. This is not really improving anything. I am going to close it.

2019-12-19 21:32 UTC, closed without merging