Fix "boolean expression must not be null" when returning from the background
flutter/flutter pull request #48983
Opened 2020-01-16 18:54 UTC by priezz

## Description

Fixes an assertion when returning to the flutter app from another app, called with a custom scheme url:
```
The following assertion was thrown during a scheduler callback: 
Failed assertion: boolean expression must not be null
```

## Related Issues

#29838, #36778, #43373

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*

2020-01-16 19:00 UTC, priezz commented
> It looks like this pull request may not have tests. Please make sure to add tests before merging. If you need an exemption to this rule, contact Hixie.
> 
> **Reviewers**: Read the [Tree Hygiene page](https://github.com/flutter/flutter/wiki/Tree-hygiene#how-to-review-code) and make sure this patch meets those guidelines before LGTMing.

@Hixie. Hi, contacting you as I thing no tests are required for this PR. It just covers the case, when the boolean value is not set.

2020-01-16 19:01 UTC, priezz commented
@googlebot I signed it!

2020-01-16 22:07 UTC, goderbauer commented
@priezz This code will need a test to ensure that we never re-introduce the bug again.

2020-01-22 23:05 UTC, goderbauer commented
@priezz Do you have any plans to come back to this PR in the near future to implement a test?

2020-01-22 23:38 UTC, priezz commented
Sorry, have no time to take care of tests. However I see no reason not to merge the fix as it really solves the issue.
23 янв. 2020 г., 00:05 +0100, Michael Goderbauer <notifications@github.com>, писал:
> @priezz Do you have any plans to come back to this PR in the near future to implement a test?
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-01-24 00:32 UTC, Piinks requested changes
Hi @priezz, welcome! 🎉  and thank you for the contribution.

> Sorry, have no time to take care of tests. However I see no reason not to merge the fix as it really solves the issue. 

We won't be able to merge this change without a test. This is to make sure it has truly been fixed (See [write test find bug](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#write-test-find-bug)), and to make sure that your fix does not end up being undone later by another change.

2020-01-29 18:06 UTC, goderbauer commented
I am going to close this PR for now until somebody finds the time to write a test for it. Feel free to re-open if you want to contribute one.

2020-01-29 18:06 UTC, closed without merging

2020-01-30 13:52 UTC, priezz commented
> I am going to close this PR for now until somebody finds the time to write a test for it. Feel free to re-open if you want to contribute one.

I really love Flutter and appreciate all the job is being done in respect to Flutter by the team. However I can't understand, why PRs like this are closed instead of improving them to be compliant with the framework codebase. Is'n it the Flutter team responsibility to fix the bugs? Doesn't it help when someone from the community tries to help and not just finds the issue in the code, but also proposes the solution? For sure, the changes proposed could fix just the consequence of some deeper bug, but at least it prevents crashes in described cases. I can't understand, why you prefer to keep opened issues for months instead of accepting fixes and adding the task for yourself to create respective tests some day.

2020-01-30 16:39 UTC, Hixie commented
Without a test, the code will just regress when we accidentally break it later, so it's not really a fix. In addition, all code has a risk of breaking other things. So code without a test is effectively a net negative, not a net positive.