switching channel prompts to run flutter upgrade
flutter/flutter pull request #49511
Opened 2020-01-26 16:40 UTC by mannprerak2

## Description

Added print statements to prompt user to run `flutter upgrade` after running `flutter channel foo`

## Related Issues

resolves #16030

## Tests
None... simply added print statements

Here's an output from my system:
```
Switching to flutter channel 'beta'...
git: Switched to branch 'beta'
git: Your branch is up-to-date with 'origin/beta'.
Successfully switched to flutter channel 'beta'.
Now run "flutter upgrade" to ensure that you're on the latest build from this channel.
```
## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-01-26 16:44 UTC, mannprerak2 commented
Can this also close #14979 ?

2020-01-27 17:53 UTC, zanderso commented
@jonahwilliams is this consistent with your plans for `flutter upgrade` ?

2020-01-29 15:50 UTC, jonahwilliams requested changes
I would adjust the phrasing slightly. Maybe "To ensure you're on the lastest build for this channel, run flutter upgrade"

2020-01-29 15:58 UTC, jonahwilliams commented
There are some existing tests in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart

that check if stdout contains the right strings, this addition should have a basic smoke test there

2020-01-29 16:31 UTC, mannprerak2 commented
> https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/permeable/upgrade_test.dart

@jonahwilliams but the changes are related to running `flutter channel`, where should I add those tests?

2020-01-29 16:33 UTC, jonahwilliams commented
Oh, sorry I wasn't thinking. It would go in the channel_test.dart file

2020-01-29 16:47 UTC, mannprerak2 commented
@jonahwilliams added a test

2020-01-29 16:49 UTC, jonahwilliams commented on packages/flutter_tools/test/general.shard/channel_test.dart
> +      expect(testLogger.statusText, contains("To ensure that you're on the latest build from this channel, run 'flutter upgrade'"));
Make sure that we output the right branch name too

2020-01-29 16:49 UTC, jonahwilliams approved these changes
LGTM with nit

2020-01-29 17:11 UTC, mannprerak2 commented
@jonahwilliams I added the complete line `Successfully switched to flutter channel 'beta'.`
Also, If this seems fine, can you add the label for automated merging

2020-01-29 17:17 UTC, jonahwilliams commented
Thanks for the contribution!

2020-01-29 18:10 UTC, jonahwilliams commented
Looks like this change broke another test:

```
00:25 +880 ~5 -1: test/general.shard/channel_test.dart: channel removes version stamp file when switching channels [E]                                                                                 
  Expected: <1>
    Actual: <2>
```

@mannprerak2 can you take a look?

2020-01-29 18:58 UTC, mannprerak2 commented
Fixed.. I didn't know calls to verify were neccesary
```dart
verify(mockProcessManager.start(
        <String>['git', 'fetch'],
        workingDirectory: anyNamed('workingDirectory'),
        environment: anyNamed('environment'),
      )).called(1);
```

2020-01-30 04:57 UTC, mannprerak2 commented
@jonahwilliams can you look into why tool_tests-commands-macos test is failing?
If it's some other network or device error shouldn't this be set to automatic re-run?

2020-01-31 17:33 UTC, merged