Add support for custom xcode toolchain
flutter/flutter pull request #52822
Opened 2020-03-18 15:26 UTC by AntonKukoba1

## Description

When using a custom Swift toolchain it's impossible to use it in flutter when building from command line. Added XCODE_TOOLCHAIN environment variable to pass the custom toolchain name into xcodebuild.

2020-03-18 15:35 UTC, jonahwilliams commented
FYI @jmagman

2020-03-18 17:52 UTC, jmagman requested changes
We don't generally add ad-hoc env variables to override Xcode build settings.
Does exporting `FLUTTER_XCODE_TOOLCHAIN_DIR=path/to/toolchain` work?  [You can inject (almost) any build settings you want by prefixing with `FLUTTER_XCODE_`.](https://github.com/flutter/flutter/pull/43553)
```
FLUTTER_XCODE_TOOLCHAIN_DIR=path/to/toolchain flutter run
```
Also, this has no tests.

2020-03-18 18:21 UTC, jmagman commented
`FLUTTER_XCODE_TOOLCHAIN_DIR` didn't work, as far as I can tell it needs to be passed into `-toolchain`, as you have.

1. Please fix any analyzer warnings and test failures.
2. You're missing a bunch of `xcodebuild` locations, like https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/macos/build_macos.dart#L87.  
3. It would be better if this these additional flags were added processed holistically in [`environmentVariablesAsXcodeBuildSettings`](https://github.com/flutter/flutter/blob/db1f33fd701deca11dc145239f2dc9cecf658ff7/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L409) and tested in 
[xcodeproj_test](https://github.com/flutter/flutter/blob/db1f33fd701deca11dc145239f2dc9cecf658ff7/packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart#L416) (required: you must have tests!). 
4. One way to do this  would be to a new `FLUTTER_XCODE_OPTION_` prefix like `FLUTTER_XCODE_OPTION_TOOLCHAIN` that parsed everything after `FLUTTER_XCODE_OPTION_` as a flag with the value set.  I didn't test it, but something like this:
```dart
List<String> environmentVariablesAsXcodeBuildSettings(Platform platform) {
  // Build setting, like `ARCHS`.
  const String xcodeBuildSettingPrefix = 'FLUTTER_XCODE_';

  // Additional option passed as a flag, like `-toolchain`.
  const String xcodeOptionPrefix = 'FLUTTER_XCODE_OPTION_';
  return platform.environment.entries.where((MapEntry<String, String> mapEntry) {
    return mapEntry.key.startsWith(xcodeBuildSettingPrefix);
  }).expand<String>((MapEntry<String, String> mapEntry) {
    if (mapEntry.key.startsWith(xcodeOptionPrefix)) {
      // Remove FLUTTER_XCODE_OPTION_ prefix from the environment variable to get the flag.
      final String trimmedOptionKey = mapEntry.key.substring(xcodeOptionPrefix.length);
      return <String>['-$trimmedOptionKey ${mapEntry.value}'];
    }

    // Remove FLUTTER_XCODE_ prefix from the environment variable to get the build setting.
    final String trimmedBuildSettingKey = mapEntry.key.substring(xcodeBuildSettingPrefix.length);
    return <String>['$trimmedBuildSettingKey=${mapEntry.value}'];
  }).toList();
}
```
5. Another way to do this is [this suggestion](https://github.com/flutter/flutter/issues/49378#issuecomment-593455688) to allow the user to plop in any blob, like a new `FLUTTER_XCODE_ADDITONAL_OPTIONS` that let's the user set whatever additional things they want to be injected `FLUTTER_XCODE_ADDITONAL_OPTIONS=-toolchain XcodeWhatever.xctoolchain CODE_SIGN_STYLE=Manual`

2020-03-19 10:04 UTC, AntonKukoba1 commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter%2Fpull%2F52822) for more info**.

@googlebot I signed it!

2020-03-19 10:06 UTC, AntonKukoba1 commented
> `FLUTTER_XCODE_TOOLCHAIN_DIR` didn't work, as far as I can tell it needs to be passed into `-toolchain`, as you have.
> 
> 1. Please fix any analyzer warnings and test failures.
> 2. You're missing a bunch of `xcodebuild` locations, like https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/macos/build_macos.dart#L87.
> 3. It would be better if this these additional flags were added processed holistically in [`environmentVariablesAsXcodeBuildSettings`](https://github.com/flutter/flutter/blob/db1f33fd701deca11dc145239f2dc9cecf658ff7/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L409) and tested in
>    [xcodeproj_test](https://github.com/flutter/flutter/blob/db1f33fd701deca11dc145239f2dc9cecf658ff7/packages/flutter_tools/test/general.shard/ios/xcodeproj_test.dart#L416) (required: you must have tests!).
> 4. One way to do this  would be to a new `FLUTTER_XCODE_OPTION_` prefix like `FLUTTER_XCODE_OPTION_TOOLCHAIN` that parsed everything after `FLUTTER_XCODE_OPTION_` as a flag with the value set.  I didn't test it, but something like this:
> 
> ```dart
> List<String> environmentVariablesAsXcodeBuildSettings(Platform platform) {
>   // Build setting, like `ARCHS`.
>   const String xcodeBuildSettingPrefix = 'FLUTTER_XCODE_';
> 
>   // Additional option passed as a flag, like `-toolchain`.
>   const String xcodeOptionPrefix = 'FLUTTER_XCODE_OPTION_';
>   return platform.environment.entries.where((MapEntry<String, String> mapEntry) {
>     return mapEntry.key.startsWith(xcodeBuildSettingPrefix);
>   }).expand<String>((MapEntry<String, String> mapEntry) {
>     if (mapEntry.key.startsWith(xcodeOptionPrefix)) {
>       // Remove FLUTTER_XCODE_OPTION_ prefix from the environment variable to get the flag.
>       final String trimmedOptionKey = mapEntry.key.substring(xcodeOptionPrefix.length);
>       return <String>['-$trimmedOptionKey ${mapEntry.value}'];
>     }
> 
>     // Remove FLUTTER_XCODE_ prefix from the environment variable to get the build setting.
>     final String trimmedBuildSettingKey = mapEntry.key.substring(xcodeBuildSettingPrefix.length);
>     return <String>['$trimmedBuildSettingKey=${mapEntry.value}'];
>   }).toList();
> }
> ```
> 
> 1. Another way to do this is [this suggestion](https://github.com/flutter/flutter/issues/49378#issuecomment-593455688) to allow the user to plop in any blob, like a new `FLUTTER_XCODE_ADDITONAL_OPTIONS` that let's the user set whatever additional things they want to be injected `FLUTTER_XCODE_ADDITONAL_OPTIONS=-toolchain XcodeWhatever.xctoolchain CODE_SIGN_STYLE=Manual`

ok I will.

2020-04-09 17:42 UTC, jmagman commented
What's the status on this change?  In addition to my previous comments, you need to sign the CLA with the same email address as your git commit email address.  You should also rebase onto master and fix the merge conflicts.

2020-04-30 20:33 UTC, zanderso commented
@AntonKukoba1 This has been waiting for a response for some time, so I'll go ahead and close it, but feel free to re-open if you'd like to continue working on it. Thanks!

2020-04-30 20:33 UTC, closed without merging