[flutter_tools] remove indirection around App.framework production
flutter/flutter pull request #53853
Opened 2020-04-02 19:25 UTC by jonahwilliams

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behaviour with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: *Replace with a link to your migration guide*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-04-03 19:45 UTC, jonahwilliams commented
@jmagman are there presubmit tests that run this for real? Or is that only on postsubmit

2020-04-03 20:40 UTC, jmagman requested changes
I ran `build_ios_framework_module_test` and it crashed:
```
[build_ios_framework_module_test] [STDOUT] stderr: Oops; flutter has exited unexpectedly: "NoSuchMethodError: The method 'build' was called on null.
[build_ios_framework_module_test] [STDOUT] stderr: Receiver: null
[build_ios_framework_module_test] [STDOUT] stderr: Tried calling: build(Instance of 'AotAssemblyProfile', Instance of 'Environment')".
```

2020-04-03 20:40 UTC, jmagman commented on packages/flutter_tools/lib/src/commands/build_ios_framework.dart
> +      buildDir: FlutterProject.current().dartTool.childDirectory('flutter_build'),
`_project.dartTool.childDirectory('flutter_build')`

2020-04-03 20:40 UTC, jmagman commented on packages/flutter_tools/lib/src/commands/build_ios_framework.dart
> +        true,
Don't need bitcode as a param to `_buildAotFrameworkWithAssemble`, set true directory in Environment 
 `kBitcodeFlag`

2020-04-03 20:40 UTC, jmagman commented on packages/flutter_tools/lib/src/commands/build_ios_framework.dart
> +  Future<void> _buildAotFrameworkWithAssemble(
This doesn't need to be a separate method from `_produceAotAppFrameworkIfNeeded`, just combine them.

2020-04-09 18:32 UTC, jonahwilliams commented
Fixed crash on startup, also we now have some semblance of caching:

```
Building frameworks for com.example.foobar in debug mode...
 ├─Populating Flutter.framework...                                  0.2s
 ├─Adding placeholder App.framework for debug...                   751ms
 ├─Assembling Flutter resources for App.framework...                6.7s
 └─Moving to build/ios/framework/Debug                              0.0s
Building frameworks for com.example.foobar in profile mode...
 ├─Populating Flutter.framework...                                  0.2s
 ├─Building Dart AOT for App.framework...                          20.9s
 ├─Assembling Flutter resources for App.framework...                0.1s
 └─Moving to build/ios/framework/Profile                            0.0s
Building frameworks for com.example.foobar in release mode...
 ├─Populating Flutter.framework...                                  1.7s
 ├─Building Dart AOT for App.framework...                          15.1s
 ├─Assembling Flutter resources for App.framework...                0.1s
 └─Moving to build/ios/framework/Release                            0.0s
Frameworks written to /Users/jonahwilliams/Documents/foobar/build/ios/framework.
jonahwilliams-macbookpro2:foobar jonahwilliams$ flutter build ios-framework
Building frameworks for com.example.foobar in debug mode...
 ├─Populating Flutter.framework...                                  0.2s
 ├─Adding placeholder App.framework for debug...                   147ms
 ├─Assembling Flutter resources for App.framework...                1.8s
 └─Moving to build/ios/framework/Debug                              0.0s
Building frameworks for com.example.foobar in profile mode...
 ├─Populating Flutter.framework...                                  0.2s
 ├─Building Dart AOT for App.framework...                           9.2s
 ├─Assembling Flutter resources for App.framework...                0.1s
 └─Moving to build/ios/framework/Profile                            0.0s
Building frameworks for com.example.foobar in release mode...
 ├─Populating Flutter.framework...                                  2.5s
 ├─Building Dart AOT for App.framework...                           7.0s
 ├─Assembling Flutter resources for App.framework...                0.1s
 └─Moving to build/ios/framework/Release                            0.0s
Frameworks written to /Users/jonahwilliams/Documents/foobar/build/ios/framework.
```

Though not everything is cached yet

2020-04-09 20:31 UTC, jmagman commented
Hm, `build_ios_framework_module_test` is still failing:
```
Task result:
{
  "success": false,
  "reason": "FileSystemException: Expected file to exist., path = '/var/folders/mv/qlhc4vsj6tqct166rw3zwmth00mfq2/T/flutter_module_test.4RuI9C/hello/flutter-frameworks/Profile/App.framework/App'"
}
```

2020-04-09 21:04 UTC, jonahwilliams commented on packages/flutter_tools/lib/src/commands/build_ios_framework.dart
>        await _bundleBuilder.build(
This is just doing extra work now. Once there is only a single assemble call it can go away

2020-04-09 21:05 UTC, jonahwilliams commented
Actually fixed, confirmed by switching to crappy mac :) 

I noticed that build ios-frameworks seems to be stepping on its own output, so we never get full caching. Is that a known issue?

2020-04-10 01:22 UTC, jmagman commented
> I noticed that build ios-frameworks seems to be stepping on its own output, so we never get full caching. Is that a known issue?

If you mean https://github.com/flutter/flutter/blob/e23c4796a387cf994fddc9433b2f68628c644167/packages/flutter_tools/lib/src/commands/build_ios_framework.dart#L187 then it's a workaround from before you did https://github.com/flutter/flutter/pull/53962 to remove frameworks from removed plugins, and can probably be removed now.

2020-04-10 01:26 UTC, jmagman commented
> I'll file an issue.

https://github.com/flutter/flutter/issues/54410

2020-04-10 01:33 UTC, jmagman commented
> > I'll file an issue.
> 
> #54410

Never mind, I closed that.  https://github.com/flutter/flutter/pull/53962 doesn't help with stale plugins only stale App.framework  files.

2020-04-10 01:34 UTC, jmagman approved these changes
```
Task result:
{
  "success": true,
  "data": null,
  "benchmarkScoreKeys": []
}
```
LGTM!  Thank you!

2020-04-10 20:34 UTC, merged