setState optional fn
flutter/flutter pull request #54009
Opened 2020-04-04 19:28 UTC by jacobaraujo7

It would be very interesting if the Anonymous Function was OPTIONAL.
Here is a small example:

```dart
setState();
//instead of
setState(() {});
```

2020-04-04 19:33 UTC, jacobaraujo7 commented
@googlebot I signed it

2020-04-06 17:07 UTC, chunhtai commented on packages/flutter/lib/src/widgets/framework.dart
> +    //assert(fn != null);
This should be removed.

2020-04-06 17:11 UTC, chunhtai commented
This will be a breaking change unfortunately

2020-04-06 17:24 UTC, jacobaraujo7 commented
@chunhtai
Thank you!
Any suggestions to enrich this idea?

2020-04-06 17:26 UTC, jacobaraujo7 reviewed
removed comment

2020-04-06 17:27 UTC, jacobaraujo7 commented on packages/flutter/lib/src/widgets/framework.dart
> +    //assert(fn != null);
removed comment

2020-04-06 17:49 UTC, Zazo032 commented
If `VoidCallback fn` is `null`, should it be defaulted to `() {}`?

Something like:
```dart
void setState([VoidCallback fn = () {}]) {
  // Code...
}
```
(Not sure if syntax would be correct on this).

2020-04-06 18:30 UTC, jacobaraujo7 commented
> If `VoidCallback fn` is `null`, should it be defaulted to `() {}`?
> 
> Something like:
> 
> ```dart
> void setState([VoidCallback fn = () {}]) {
>   // Code...
> }
> ```
> 
> (Not sure if syntax would be correct on this).

No, because closures cannot be const :(

2020-04-07 17:39 UTC, dnfield requested changes
We should not make this change.

`setState` should feel uncomfortable to call if you are calling it without actually providing a synchronous closure that updates the state you call about.  Otherwise, it is very easy to fall into bugs like this:

```dart
someFutureMethod().then((result) {
  _stateVar = result;
});
// _stateVar may get updated after `setState`, and not get reflected in the UI.
setState();
```

That's not what you actually want.  You want:

```dart
someFutureMethod().then((result) {
  setState(() { _stateVar = result; });
});
```

or perhaps some kind of `FutureBuilder` widget or somesuch.  

There may be times where you're calling `setState` with a no-op callback, but that should usually require documentation of some sort and thought about whether it's really the right thing to do, e.g.

```dart
void _someCallbackFromAnAnimationController(Duration duration) {
  setState(() {
    // The animation controller's value is read in `build`
   // Not using an AnimatedBuilder because ...
  });
}
```

This way, it's clear as to why you're not actually setting an instance variable when setting state, and if those conditions change, other authors (or future you) will know _why_ this call was done this way and whether or not it's still true.

2020-04-07 18:12 UTC, dnfield commented
Another drawback for this: it will encourage people to call `setState` more often than needed, because it feels cheap, when in fact it should be called as infrequently as possible, after all your state is set for the frame.

2020-04-07 18:42 UTC, Zazo032 commented
So, imagine you need to do an expensive operation, assign it to a variable, and then update the state.

```dart
// Expensive operation
// Assignment
setState(() {});
```

```dart
// Expensive operation
setState(() {
  // Assignment
});
```

```dart
setState(() {
  // Expensive operation
  // Assignment
});
```

Which of the 3 option would be better, since `setState` is not a cheap operation?

2020-04-07 19:24 UTC, dnfield commented
It's a little hard to say without understanding what exactly makes the expensive operation expensive.  Is it expensive because it just takes a lot of wall time to make a network request?  Is it expensive because it uses a lot of CPU time to do tons of calculations?  Is it expensive because it allocates lots of memory for its duration?

Either way, the idea is that the assignment should normally happen within the closure passed to `setState`, and that `setState` should be called as few times as possible with as much state as you can set.

2020-04-08 17:38 UTC, goderbauer requested changes
We should not make this change exactly for the reasons stated by Dan. We want to encourage people to set the state within setState. Calling setState with an empty closure is usually an anti-pattern and we should not make it easier to engage in that anti-pattern.

2020-04-08 17:43 UTC, goderbauer commented
> [...] and that setState should be called as few times as possible [...].

I believe this one is not true. When you call setState multiple times for the same state within the same frame, the subsequent calls will short-circuit pretty quickly. You don't have to batch up state changes to only call setState once.

In general, I would only put things in the setState closure that actually change the state.

2020-04-08 18:08 UTC, chunhtai commented
> > [...] and that setState should be called as few times as possible [...].
> 
> I believe this one is not true. When you call setState multiple times for the same state within the same frame, the subsequent calls will short-circuit pretty quickly. You don't have to batch up state changes to only call setState once.
> 
> In general, I would only put things in the setState closure that actually change the state.

Having more separate setState all over the place will also increase the chance that frames are schedule more often. I think encouraging people to call it as few times as possible is a good advice.

2020-04-08 21:42 UTC, goderbauer commented
I am going to close this one since at the current time we do not want to make this change as outlined in the comments above.

2020-04-08 21:42 UTC, closed without merging