Add autofill support for TextFormField
flutter/flutter pull request #57332
Opened 2020-05-15 19:19 UTC by pedromassango

## Description

The `TextFormField` widget currently have no support for autofill hints, wich is what this PR resolves.

## Related Issues

https://github.com/flutter/flutter/issues/57312

## Tests

I added the following tests: I'm asserting that autofillHints list is passed into parent widget (`TextField`)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

2020-05-15 20:00 UTC, LongCatIsLooong requested changes
Thank you for the pull request! Looks like the hints need to be passed into the `TextField` in the builder.

2020-05-15 22:22 UTC, pedromassango commented on packages/flutter/lib/src/material/text_form_field.dart
> +    autofillHints: autofillHints,
OMG What I just did 😑 Fixing it right now.

2020-05-15 22:27 UTC, LongCatIsLooong approved these changes
LGTM. Waiting for the tests to turn green. Thank you for the pull request!

2020-05-15 22:29 UTC, pedromassango commented
@LongCatIsLooong I was wondering if this can also be applied for other widgets that also uses `TextField` (or `EditableText`) to also have support for auto fill hints.

2020-05-15 22:49 UTC, LongCatIsLooong commented on packages/flutter/test/material/text_form_field_test.dart
>  }
The closing `)` is missing here

2020-05-15 23:32 UTC, LongCatIsLooong commented
> @LongCatIsLooong I was wondering if this can also be applied for other widgets that also uses `TextField` (or `EditableText`) to also have support for auto fill hints.

I did a quick search, there're 2 remaining components, `_SearchPage` and `InputDateRangePicker`.

 I'm not sure if `SearchPage` really merits an autofillable `TextField`. The date range picker seems autofillable but I couldn't think of a good use case (you can autofill dates like birthday or credit card expiration date, but these don't seem common for `InputDateRangePicker`). @darrenaustin WDYT?

2020-05-16 02:25 UTC, Zazo032 commented
What about `CupertinoTextField`?

2020-05-18 09:32 UTC, merged