Progress indicator demo should look good in landscape
flutter/flutter pull request #6088
Opened 2016-09-26 23:21 UTC by abarth

This patch fixes the issue in two ways:

1. The content area is now scrollable, which means you can scroll to reveal any
   parts that don't fit on screen.
2. The content area is now small enough to fit on screen in landscape on a
   Nexus 5.

Fixes #6054

2016-09-26 23:21 UTC, abarth commented
@HansMuller

2016-09-26 23:59 UTC, dragostis commented on examples/flutter_gallery/lib/demo/progress_indicator_demo.dart
> +          new Text('${(_animation.value * 100.0).toStringAsFixed(1)}%${ _controller.isAnimating ? "" : " (paused)" }'),
Laying them out in a row like this causes the animation to jank a bit because of the changing size of the `Text`.

2016-09-27 00:01 UTC, abarth commented on examples/flutter_gallery/lib/demo/progress_indicator_demo.dart
> +          new Text('${(_animation.value * 100.0).toStringAsFixed(1)}%${ _controller.isAnimating ? "" : " (paused)" }'),
That's a good point.  I should pick a fixed size for the text.

2016-09-27 16:24 UTC, abarth commented
Done.  PTAL.

2016-09-27 16:24 UTC, dragostis approved these changes
LGTM.

2016-09-27 17:13 UTC, dragostis requested changes

2016-09-27 17:13 UTC, dragostis commented on examples/flutter_gallery/lib/demo/progress_indicator_demo.dart
> +            child: new Text('${(_animation.value * 100.0).toStringAsFixed(1)}%${ _controller.isAnimating ? "" : " (paused)" }',
Hm, you don't actually see 'paused'. I vouch for removing it.

2016-09-27 17:19 UTC, abarth commented on examples/flutter_gallery/lib/demo/progress_indicator_demo.dart
> +            child: new Text('${(_animation.value * 100.0).toStringAsFixed(1)}%${ _controller.isAnimating ? "" : " (paused)" }',
Fixed.

2016-09-27 17:19 UTC, dragostis approved these changes

2016-09-27 19:31 UTC, merged