Enable InkWell to sync its hovered state when its enabled or disabled
flutter/flutter pull request #62913
Opened 2020-08-04 22:46 UTC by HansMuller

Currently, if an InkWell is disabled while it contains the mouse-pointer it remains stuck in the hovered state. Similarly, if a disabled InkWell contains the mouse when it is enabled, it will not enter the hovered state.

Changed InkWell to allow a mouse-exit event to clear the hovered state, even if the InkWell is disabled.  When the widget's disabled state changes, `didUpdateWidget()` now sets the hovered state to true if the InkWell contains the mouse-pointer, false otherwise.

2020-08-04 23:32 UTC, dkwingsmt commented
The logic is a bit complicated, I think partially because there are 2 variables `_hovering` and `_containsMouse `. Do we really need both? Isn't `_hovering` equal to `_containsMouse & enabled`?

2020-08-05 17:23 UTC, HansMuller commented
@dkwingsmt - good point, I was able to simplify the logic quite a bit.

2020-08-05 21:36 UTC, dkwingsmt commented
This PR fails the following test:

```dart
  testWidgets('MaterialButton should work when being enabled or disabled while being hovered over', (WidgetTester tester) async {
    Widget scaffold({Widget child}) {
      return Directionality(
        textDirection: TextDirection.ltr,
        child: Center(
          child: SizedBox(
            width: 100,
            height: 100,
            child: child,
          ),
        ),
      );
    }
    await tester.pumpWidget(scaffold(
      child: const FlatButton(
        onPressed: null,
        child: Text('button'),
      ),
    ));

    final TestGesture gesture = await tester.createGesture(kind: PointerDeviceKind.mouse);
    await gesture.addPointer();
    await gesture.moveTo(tester.getCenter(find.byType(FlatButton)));
    await tester.pumpAndSettle();

    await tester.pumpWidget(scaffold(
      child: FlatButton(
        onPressed: () {},
        child: const Text('button'),
      ),
    ));

    // Refresh just in case
    await tester.pumpAndSettle();
    await gesture.moveBy(const Offset(1, 1));

    await tester.pumpWidget(scaffold(
      child: const FlatButton(
        onPressed: null,
        child: Text('button'),
      ),
    ));
  });
```

The problem only emerges when `InkWell` is used by an external widget so that `onHover` calls a `setState`.

2020-08-05 21:37 UTC, dkwingsmt requested changes
See the comment for a constructed failing test

2020-08-05 22:12 UTC, HansMuller commented
Isn't that the same as the existing limitation of onHighlightChanged() - https://api.flutter.dev/flutter/material/InkResponse/onHighlightChanged.html?

2020-08-05 23:15 UTC, dkwingsmt commented
Yeah, I'd be ok if we add `onHover` _now_ and say it shouldn't call `setState`, but in the case of this PR, we're breaking a very common use case.

2020-08-07 22:12 UTC, dkwingsmt approved these changes
LGTM

2020-08-09 01:21 UTC, merged