[WIP] Dispatch hover events in the same way as regular events
flutter/flutter pull request #63834
Opened 2020-08-15 03:06 UTC by dkwingsmt

## Description

This PR changes the handling of hover events, so that they are dispatched the same way as regular events (the regular hit test, `HitTestTarget.handleEvent`, etc.)

### Why?

The direct reason is for https://github.com/flutter/flutter/issues/45910, which complains that single taps in a11y mode are hard to detect, because they will be transformed to hover events and ignored by gesture binding. It's _not_ the first time we've met this problem: https://github.com/flutter/flutter/pull/46124 extended platform views with `MouseTrackingAnnotation` so that they can receive mouse events in a11y mode. It was good until recently an internal ticket (b/163613117) wanted widgets other than platform views to detect a11y single taps too. 

It then came to my mind that, if hover events _can_ be triggered by non-mouse devices, where entering and exiting do not make sense, it means that hover events should be treated in the same way as other regular events, instead of the derivative of the calculation of enter and exit events. If hover events are dispatched to the `handleEvent` of _all_ render objects in the tree, then it can bring the following benefits:
- Fixes https://github.com/flutter/flutter/pull/46124, as mentioned before.
- It fixes https://github.com/flutter/flutter/issues/33312, which demands gesture recognizers to be able to receive hover events. (Although no one has yet to bring up valid use cases for this feature.)
- It clarifies the definition of `MouseTracker` and `MouseTrackerAnnotation`: they calculates pointer entering and exiting, which can not be derived without keeping extra states (in contrast to hover events, which do _not_ need extra states to dispatch.)

###  Major API changes
`MouseTrackerAnnotation` no longer has an `onHover` callback. `MouseTrackerAnnotation` and `MouseTracker` now only deals with logics that require keeping track of "what was hovered in the last frame", which means entering, exiting, and cursors. 

All render objects now receive `PointerHoverEvent` in their `handleEvent`. 

The order of hover events is slightly changed. They used to be a post-order traversing a _subtree_ formed by `RenderMouseRegion`, controlled by `opaque`. Now they traverses the full object tree, controlled by hit test behaviors.

#### What is not changed
- The `MouseRegion` still has `onHover` callback`.
- The mouse event order is unchanged: enter, exit, hover.

### Implementation API changes
The interface between `MouseTracker` and `RendererBinding`&`RenderView` have been redesigned.
- `MouseTracker` no longer takes `PointerRouter` as a parameter. It exposes a new method `dispatchEvent`, which is used by `RendererBinding` to feed new events as well as the corresponding hit test result.
- To keep things symmetric, `MouseTracker` now also exposes a new method `dispatchPostFrameUpdate`, which updates all pointers and is used in post frame callbacks. `MouseTracker` used to wrap the scheduling within itself, which is now handled by `RendererBinding`.
- In this way, `MouseTracker` is now completely initiated from external triggerers.

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-09-08 18:00 UTC, gspencergoog requested changes

2020-09-08 18:00 UTC, gspencergoog commented on packages/flutter/lib/src/widgets/basic.dart
> +  /// Triggered when a pointer changes into a position within this widget without
```suggestion
  /// Triggered when a pointer moves to a position within this widget without
```

2020-09-08 18:00 UTC, gspencergoog commented on packages/flutter/lib/src/widgets/basic.dart
> +  /// not down (e.g. mouse pointers). Certain devices also fires this event on
```suggestion
  /// not down (e.g. mouse pointers). Certain devices also fire this event on
```

2020-09-08 21:16 UTC, dkwingsmt commented
@gspencergoog Thanks for the suggestions, I've fixed them

2020-09-10 21:32 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2020-09-22 20:39 UTC, dkwingsmt commented
Update: This PR is blocked by https://github.com/flutter/flutter/pull/63813, which is further blocked by another issue.

2020-10-05 19:12 UTC, merged

2021-04-24 04:54 UTC, tvolkert commented
> The performance is no longer an issue thanks to #59883

But this still causes us to hit test the whole tree on every mouse move event, right?

2021-04-24 04:56 UTC, tvolkert commented
This PR is listed as a breaking change, but there's no link to a design doc or migration guide.

2021-04-24 08:02 UTC, dkwingsmt commented
@tvolkert 

> But this still causes us to hit test the whole tree on every mouse move event, right?

Yes.

> This PR is listed as a breaking change, but there's no link to a design doc or migration guide.

That might have been a misjudgement according to the standard in the wiki. It didn't cause breakages in internal or flutter/tests.