Add sample code to FadeTransition
flutter/flutter pull request #64240
Opened 2020-08-20 11:34 UTC by jsh-me

## Description
I added FadeTransition sample code.
Reference: https://api.flutter.dev/flutter/widgets/FadeTransition-class.html

## Related Issues

N/A

## Tests

N/A. Only the doc changed.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-09-08 16:47 UTC, gspencergoog requested changes

2020-09-08 16:47 UTC, gspencergoog commented on packages/flutter/lib/src/widgets/transitions.dart
>  /// {@animation 300 378 https://flutter.github.io/assets-for-api-docs/assets/widgets/fade_transition.mp4}
Since you added a Dartpad example, you can remove the video.

2020-09-08 16:47 UTC, gspencergoog commented on packages/flutter/lib/src/widgets/transitions.dart
> +///         padding: const EdgeInsets.all(8),
Move the `const` to the `Padding` widget, since it can be const too.

2020-09-09 16:58 UTC, jsh-me commented
@gspencergoog 
Thank you! I fixed it. Could you check it again?

2020-09-09 18:02 UTC, gspencergoog commented
I've restarted the failing tests: they were infrastructure problems, so hopefully they just pass this time.  If not, you can rebase to master and push again, but hopefully that won't be necessary.

2020-09-10 23:43 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2020-09-11 00:17 UTC, gspencergoog commented
@jsh-me can you please try rebasing your changes on top of `master/HEAD` again, and push the result to this PR?  Those test failures aren't going away by just re-running them, but I know that they aren't due to your change.

2020-09-12 11:11 UTC, jsh-me commented
@gspencergoog 
hi :) could you check it again?

2020-09-12 21:42 UTC, merged