Updated material's icon button to prevent overflow in appbar
flutter/flutter pull request #64717
Opened 2020-08-27 14:02 UTC by sidrao2006

Solves issue #64702

## Description

As mentioned in issue #64702 , the icon button splash (which is auto generated) always overflows. Hence by reducing the splash radius, the overflow is prevented. 

## Related Issues

Issue #64702 

## Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

- [x] No, this is *not* a breaking change.

2020-08-27 14:10 UTC, sidrao2006 commented
@Hixie, please exempt this PR from tests as it only updates the value of the `IconButton`'s `splashRadius` property.
If this is not possible, I will definitely add tests.

2020-08-27 14:17 UTC, sidrao2006 commented
@TahaTesser , @pedromassango , @dnfield 
Can you please look into this PR?

2020-08-27 14:21 UTC, dnfield requested changes
We should not change the default for sake of a different widget.  Is it not possible to set the parameter when. Using this in an app bar?

This also is too small for a11y guidelines.

2020-08-27 14:24 UTC, sidrao2006 commented
@dnfield , it is possible to manually set the splashRadius, however it is not possible to set it for auto generated `IconButton`s

2020-08-27 14:29 UTC, dnfield commented
This change affects the size of the whole button, not just the splash radius.

2020-08-27 14:32 UTC, sidrao2006 commented
@dnfield , I am really sorry, I meant to change the splash radius.
I will revert the change and make the necessary changes

2020-08-27 14:54 UTC, dnfield commented
It's still not clear to me why we would change the default here. Someone from material would know better but this is probably not what the spec wants now.

Ill comment on your issue as well, but why not just pass your desired radius for app bars instead of changing it everywhere?

I would also expect this change to fail tests.

2020-08-27 15:02 UTC, sidrao2006 commented
> Ill comment on your issue as well, but why not just pass your  desired radius for app bars instead of changing it everywhere?

I have set the value as 20 because it is approximately the maximum value that does not cause the splash to overflow in accordance with the `AppBar`

2020-08-27 18:45 UTC, Hixie commented
The overflow is intentional, though maybe the material spec has changed since we implemented this.

In any case, this kind of change would definitely need tests. (Probably golden image tests.)

2020-08-28 12:09 UTC, closed without merging

2020-08-28 12:10 UTC, sidrao2006 commented
Please follow up on #64789