[ReorderableListView] remove extra margin added after picking up the item
flutter/flutter pull request #65080
Opened 2020-09-02 07:53 UTC by nero-angela

## Description
As you can see under the gif when picking up an item in `ReorderableListView`, the others below it move slightly downward. this is because the extra margin is added to the selected item after lifting. So I removed the extra margin and modified the related test.

|before|after|
|:--:|:--:|
|![before](https://user-images.githubusercontent.com/26322627/91946550-433a4600-ed3a-11ea-8342-28950d77740e.gif)|![after](https://user-images.githubusercontent.com/26322627/91946420-39b0de00-ed3a-11ea-8424-c286e133ab2f.gif)|

## Related Issues
Fixes https://github.com/flutter/flutter/issues/58411

## Tests

I modified the following tests: 
- [properly determines the vertical drop area extents](https://github.com/flutter/flutter/blob/780f5f99044ce7fcbcd868e2cf6878da02022db5/packages/flutter/test/material/reorderable_list_test.dart#L144)
- [properly determines the horizontal drop area extents](https://github.com/flutter/flutter/blob/780f5f99044ce7fcbcd868e2cf6878da02022db5/packages/flutter/test/material/reorderable_list_test.dart#L659)

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-09-10 21:55 UTC, dkwingsmt requested changes
Good change, with small change requests.

Also it'd be better if you can add a golden test to make sure it looks exactly how we want after picking up the item. If you're up for the challenge, refer to https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package:flutter or search from `matchesGoldenFile` in existing test files.

2020-09-10 21:55 UTC, dkwingsmt commented on packages/flutter/lib/src/material/reorderable_list.dart
> +  static const double _dropAreaMargin = 0.0;
This variable should no longer be necessary. Remove to simplify code.

2020-09-10 21:55 UTC, dkwingsmt commented on packages/flutter/test/material/reorderable_list_test.dart
> +        const double kDraggingListHeight = 292.0;
Combine `kNonDraggingListHeight` and `kDraggingListHeight` to simplify code.

2020-09-11 16:42 UTC, nero-angela commented
Thank you @dkwingsmt ! I've simplified the unnecessary code and added golden test. The images are in the description. :)
This is my first time making golden file changes, I'm not sure if I performed the golden test correctly 🤔
Could you please take a look?

2020-09-12 00:48 UTC, dkwingsmt commented
The Linux analyzer seems unhappy. Can you resolve the lint errors?

2020-09-12 03:13 UTC, nero-angela commented
sorry for missing declaring const. @dkwingsmt I've resolved the lint error.

2020-09-12 04:16 UTC, dkwingsmt approved these changes
LGTM

2020-09-12 06:52 UTC, dkwingsmt commented
Theoretically the bot should comment that a golden test has been modified... I'll check it out next week.

2020-09-12 07:59 UTC, nero-angela commented
Okay. Thank you for reviewing. Check it out and tell me if there is anything I need to do.
Have a nice weekend :)

2020-09-16 23:37 UTC, merged

2020-09-17 16:18 UTC, justinmc commented
@dkwingsmt @nero-angela The golden tests added in this PR failed when I tried to revert a TextField layout PR from just before this: https://github.com/flutter/flutter/pull/66027

Can you guys think of any reason why that would happen?  These new tests have nothing to do with TextField or InputDecoration layout, right?

2020-09-17 16:27 UTC, justinmc commented
Actually it seems to be happening on many PRs:
https://github.com/flutter/flutter/pull/61981
https://github.com/flutter/flutter/pull/65884

2020-09-17 16:39 UTC, Piinks commented
These images don't appear to have arrived on the gold dashboard after landing: https://flutter-gold.skia.org/
There is nothing under by blame, and I can't find reference to the tests. Checking the logs now on master.
fyi @kjlubick

2020-09-17 16:45 UTC, Piinks commented
Looks like our luci recipes have been changed and disabled gold again. Will file an infra ticket.

2020-09-17 16:49 UTC, Piinks commented
https://github.com/flutter/flutter/issues/64969 for tracking