Fab for search delegate
flutter/flutter pull request #65340
Opened 2020-09-07 12:50 UTC by Maverick099

## Description

FAB for SearchDelegate to only exit (navigate back) to the previous context.
Since due to unusual and large screen sizes an implementation of FAB to only exit the search delegate is required. 

The following code will add the FAB if the user makes 'showFloatingActionButton ' as true which is defaulted to false;
The FAB is also given a default size of 54.0 and Icon (Material Arrow -back icon) is given a default size of the size of 44.0.
The Icon colour follows the primary Icon theme colour. 
The FAB background colour follows the primary colour described in the theme.
The FAB has a default elevation of 10.0,

The FAB also pops with the result as specified by the user for the close function to return on pop context. 

## Related Issues

 #65309 

## Tests

I added the following tests:

- Added test to open the Search Delegate and then close using FAB.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-09-07 13:09 UTC, Maverick099 commented
@googlebot I signed it!

2020-09-08 16:43 UTC, dnfield commented on packages/flutter/lib/src/material/search.dart
> +import '../../material.dart';
Do not import the whole material library from within the material library.

2020-09-08 16:50 UTC, dnfield requested changes
According to https://material.io/components/buttons-floating-action-button, the FAB is supposed to be for the primary action of the screen. Going back, OTOH, is typically a back arrow in the nav bar (https://material.io/components/app-bars-top#anatomy). 

I don't think the framework should create a feature for this. This seems much more application specific, and will raise a bunch of questions about things like what if you want the FAB to animate in or out, what if you want a different icon, what if you want it to actually perform some search query rather than exit, etc.

2020-09-09 04:32 UTC, dnfield commented
Based on feedback inthe issue, I'm going to close this PR. Please feel free to discuss further in the issue.

2020-09-09 04:32 UTC, closed without merging