Warn tapping of non-visible area when test
flutter/flutter pull request #67287
Opened 2020-10-05 07:27 UTC by shouichi

## Description

Hi,

In unit tests, finding widget (`find.text('foo')`) works even if it's invisible but tapping it (`tester.tap`) does nothing. This behavior makes it harder to write tests. It would be nice if `flutter test` warns tapping of non-visible area.

NOTE: I honestly don't think the change is well-written but mainly wanted to get attention from the maintainers.

Thank you.

## Related Issues

https://github.com/flutter/flutter/issues/48463.

## Tests

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

2020-10-05 21:29 UTC, dnfield commented on packages/flutter_test/lib/src/controller.dart
> +      print('Trying to tap non-visible area.');
I'm pretty sure this is incorrect - `tap` is expecting logical, not physical pixels. 

This print is also likely to be missed/ignored by developers or CI.

I think the idea here could be valuable, but we'd probably want it to be opt-in (or perhaps opt-out), so the developer could choose to have a `fail` here if the tap is outside the tappable area of the screen.

2020-10-05 21:30 UTC, dnfield requested changes
This change needs a bit of work and some tests. If you intend to keep working on it we can re-open, otherwise we can leave the issue open for now.

2020-10-05 21:30 UTC, closed without merging

2020-10-06 02:22 UTC, shouichi commented
@dnfield Hi, thanks for the review! I know the current change is not sufficient to merge. Could you give me the direction? I'd love to get this done 💪

2020-10-09 09:28 UTC, Valentin-Seehausen commented
Hey, I consider this one to be super important. It did cost me two hours or so and I guess I am not the only one to have stumbled upon it. Can I help in any way? I never contributed to flutter, but would give it a try.

2020-10-09 09:31 UTC, Valentin-Seehausen commented
I see two options:

1. The tester fails, because the element is not visible and thus can't be tapped.
2. The tester scrolls to the element automatically (with ensureVisible) and only fails if the element does not exist.

I guess solution 1. is better, what do you think?