Added Dartpad Sample to Hero Widget closes #69477
flutter/flutter pull request #69800
Opened 2020-11-04 20:15 UTC by cv692001

## Description

*Replace this paragraph with a description of what this PR is doing. If you're modifying existing behavior, describe the existing behavior, how this PR is changing it, and what motivated the change. If you're changing visual properties, consider including before/after screenshots (and runnable code snippets to reproduce them).*

## Related Issues

*Replace this paragraph with a list of issues related to this PR from our [issue database]. Indicate, which of these issues are resolved or fixed by this PR. There should be at least one issue listed here.*

## Tests

I added the following tests:

*Replace this with a list of the tests that you added as part of this PR. A change in behavior with no test covering it
will likely get reverted accidentally sooner or later. PRs must include tests for all changed/updated/fixed behaviors. See [Test Coverage].*

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I signed the [CLA].
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] All existing and new tests are passing.
- [ ] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [ ] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [ ] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

closes #69477

2020-11-04 22:41 UTC, goderbauer commented on packages/flutter/lib/src/widgets/heroes.dart
> +    box.getTransformTo(ancestorContext?.findRenderObject()),
can you please revert all the formatting changes in this PR?

2020-11-04 22:42 UTC, goderbauer commented
Once the formatting changes are reverted, the analyzer check should also be happy with this.

2020-11-05 07:35 UTC, cv692001 commented
> Once the formatting changes are reverted, the analyzer check should also be happy with this.

Can you please help me how to revert the formatting changes , actually I am new to contributing :)

2020-11-10 00:01 UTC, johnpryan requested changes
Looks good overall, it would be great if this were a DartPad sample.

2020-11-10 00:01 UTC, johnpryan commented on packages/flutter/lib/src/widgets/heroes.dart
> +///        body: Center(
I would add an AppBar so that the user can navigate back

2020-11-18 18:05 UTC, johnpryan commented
@cv692001 the easiest way is to probably re-apply your changes and make sure you're not running the formatter.

2020-12-09 22:54 UTC, goderbauer commented
@@cv692001 Do you still have plans to follow up on the feedback?

2020-12-13 09:18 UTC, yash1200 commented
@goderbauer If the assignee doesn't respond, can you assign me for the issue?

2021-01-06 23:06 UTC, goderbauer commented
I am going to close this one since there hasn't been any activity. Feel free to re-open when you have time to work on this again.

2021-01-06 23:06 UTC, closed without merging