[showModalBottomSheet] fix: showModalBottomSheet does not move along keyboard #71418
flutter/flutter pull request #71636
Opened 2020-12-03 06:02 UTC by ZainUrRehmanKhan

## Description

This issue was found in release 1.22, 1.23, 1.24 that the `showModelBottomSheet` was not moving along the keyboard, the bottom sheet contains a `TextField` which open up the keyboard on focus, so if the height of bottom sheet is less then the height of keyboard then the bottom sheet was hidden behind the keyboard.

**showModelBottomSheet with `TextField` unfocused:**

![unfocus](https://user-images.githubusercontent.com/67098758/100968907-09085c80-3554-11eb-8c76-c1f2db0a4f7f.jpeg)

**When we Focus on `TextField` - Before Changes:**
Bottom Sheet is hidden behind the keyboard.

![before](https://user-images.githubusercontent.com/67098758/100969079-571d6000-3554-11eb-8b26-a6f5b524678b.jpeg)

**When we Focus on `TextField` - After Changes:**

![after](https://user-images.githubusercontent.com/67098758/100969209-8cc24900-3554-11eb-8383-4197c39799ce.jpeg)

## Related Issues

https://github.com/flutter/flutter/issues/71418

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [ ] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [ ] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [ ] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [ ] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

2020-12-09 07:10 UTC, ZainUrRehmanKhan commented
Kindly review my pull request.

2020-12-09 22:51 UTC, dkwingsmt requested changes
The change looks solid. Please add a unit test to make sure someone doesn't accidentally revert it (probably a [golden test](https://github.com/flutter/flutter/wiki/Writing-a-golden-file-test-for-package%3Aflutter)).

2020-12-09 22:51 UTC, dkwingsmt commented on packages/flutter/lib/src/material/bottom_sheet.dart
> +        )
```suggestion
        ),
```

2020-12-30 15:52 UTC, ZainUrRehmanKhan commented
I'm writing a test for this PR.

2021-01-11 22:22 UTC, dkwingsmt requested changes
Tiny issues. Everything else looks great!

2021-01-11 22:22 UTC, dkwingsmt commented on packages/flutter/test/material/bottom_sheet_test.dart
> +  testWidgets('showModalBottomSheet should move along keyboard',
```suggestion
  testWidgets('showModalBottomSheet should move along on-screen keyboard',
```

2021-01-11 22:22 UTC, dkwingsmt commented on packages/flutter/test/material/bottom_sheet_test.dart
> +    //Wrapping Builder with MediaQuery for KeyboardHeight
```suggestion
    // Show a keyboard (simulate by space at the bottom of the screen).
```

2021-01-12 04:57 UTC, ZainUrRehmanKhan commented
Suggested changes done.

2021-01-20 06:49 UTC, ZainUrRehmanKhan commented
@dkwingsmt Updated my branch to the latest master. That should resolve the failing customer tests.

2021-01-21 18:30 UTC, ZainUrRehmanKhan commented
?

2021-01-21 19:06 UTC, dkwingsmt approved these changes
LGTM

2021-01-22 01:19 UTC, merged

2021-01-23 09:40 UTC, davidmartos96 commented
@dkwingsmt Could we have a way to make this change opt out? I currently have some modal bottom sheets where I place the textfields (usually for filtering results) at the top of a quite large bottomSheet, so the keyboard will not hide it. With this PR everything will be pushed above the keyboard which may be considered somewhat breaking. What are your thoughts?

2021-01-23 20:15 UTC, dkwingsmt commented
@davidmartos96 You are right. Although to make a modal bottom sheet hidden by the on-screen keyboard does not really sound correct to me. When a displayed modal bottom sheet is supposed to prevent the user from interacting with the rest of the app. Will normal `showBottomSheet` suit your needs?

2021-01-23 20:26 UTC, davidmartos96 commented
@dkwingsmt I may have not expressed myself correctly. Sorry about that.
The usecase I'm referring to is a TextField inside the modal bottom sheet, but where the bottom sheet will be about 70% tall of the screen height. I have some of those modal sheets in my app, but I display the text field at the top knowing that up to now the keyboard would hide the lower portion of the bottom sheet (and I'm fine with that in my usecase). 
With the PR I worry that all the bottom sheet will be pushed too much overflowing the screen height. I agree with the changes made in the PR but I would suggest including an option similar to `resizeToAvoidBottomInset` in the Scaffold so that this behavior can be opted out (https://api.flutter.dev/flutter/material/Scaffold/resizeToAvoidBottomInset.html)
If the Flutter team agrees to such new option I could open a PR with it.

2021-01-23 20:45 UTC, dkwingsmt commented
Can you achieve the same result by manually applying a negative bottom padding? Actually, you can get the height of your sheet and the screen height to calculate the exact amount of underflow for you to avoid overflowing.

2021-01-23 20:54 UTC, davidmartos96 commented
@dkwingsmt I'm not sure I follow you with the negative padding. Does Flutter support negative padding?

2021-03-03 11:39 UTC, Peng-Qian commented
Personally, I think this is a bad idea to force ModalBottomSheet to resize itself. I am experiencing the same issue as @davidmartos96 says.

At least we need a parameter to control if the ModalBottomSheet should resize or not (). And why padding should wrap BottomSheet to force resize to avoid keyboard? (we can just add padding inside ModalBottomSheet to achieve the same effect.)

2021-03-03 11:48 UTC, dkwingsmt commented
@HansMuller Are you more familiar with how Material Design defines ModelBottomSheet? Can you take a look at the requests above?

2021-03-03 11:59 UTC, Peng-Qian commented
Thanks for your quick response!

Please imagine ModalBottomSheet takes 5/6 of full-screen height and it used to pick a country(e.g. New Zealand), so it will be a scrollable list and contains many items, and on the top of this list, there is a search bar that contains a TextField.

If the ModalBottonSheet forcibly resizes as the keyboard shows, It will push the search bar to the very top of the screen, it not only breaks the UI looking but also break the feature. Because the phone notification bar will overlay on it.

Moreover, padding when the keyboard shows is a brutal way to avoid keyboard overlay. Please check out this https://pub.dev/packages/keyboard_avoider package. I don't think flutter should limit us on how to design the Application.

2021-03-04 20:43 UTC, dkwingsmt commented
We're reverting this PR in https://github.com/flutter/flutter/pull/77286. Various sources have reported that the previous behavior is the desired one. /cc @ZainUrRehmanKhan

2021-05-07 15:13 UTC, totroi commented
> We're reverting this PR in #77286. Various sources have reported that the previous behavior is the desired one.

Any tips on what to do to have the behavior of the original commit (moving up with the keyboard)?

Maybe an specific modal could be created, like _showModalBottomSheetFlexible_ ? I'd prefer to have it behave that way

2021-05-07 15:50 UTC, totroi commented
> > We're reverting this PR in #77286. Various sources have reported that the previous behavior is the desired one.
> 
> Any tips on what to do to have the behavior of the original commit (moving up with the keyboard)?
> 
> Maybe an specific modal could be created, like _showModalBottomSheetFlexible_ ? I'd prefer to have it behave that way

Actually it you be much better if one could simply define the "height" of it. Being able to elongate it up just a little would solve my problem.

2021-05-07 19:36 UTC, totroi commented
> @totroi You can get the behavior by wrapping the bottom sheet builder with:
> 
> ```dart
> Padding(
>   padding: MediaQuery.of(context).viewInsets
> )
> ```
> 
> That's essentially what the reverted PR was doing

Thanks! Problem is I'm seeking to move a Card inside the modal up, and move the modal up just the amount required for the Card to move. Like about 30 pixels...

I managed to shrink all the paddings inside the Card widget and it looks okay, but the best result would be those 30 pixels up whenever the keyboard is opened.