Add --dart-define option support to build aar command
flutter/flutter pull request #71829
Opened 2020-12-07 07:17 UTC by hyiso

## Description
Add --dart-define option support to `flutter build aar` command

## Related Issues
https://github.com/flutter/flutter/issues/71827

2020-12-07 07:21 UTC, hyiso commented
@googlebot I signed it!

2020-12-08 21:28 UTC, jmagman requested changes
This needs a test.

See https://github.com/flutter/flutter/blob/6a2bc2617e0b0197f33e00ce804f81b4b93474c0/packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart#L161

2020-12-11 09:38 UTC, hyiso commented
Sorry for late, I will add some test code for this PR on this weekend.

2020-12-11 17:26 UTC, jmagman reviewed
Looks good other than the nit about removing the extra `isNotEmpty`.

2020-12-11 17:26 UTC, jmagman commented on packages/flutter_tools/test/commands.shard/permeable/build_aar_test.dart
> +      expect(buildInfo.dartDefines.isNotEmpty, isTrue);
Nit: this check isn't necessary with the `contains` check below.

2020-12-14 18:20 UTC, jmagman approved these changes
Looks good, thanks for the contribution!

2020-12-14 18:21 UTC, merged