hourOfPeriod fails at noon
flutter/flutter pull request #72480
Opened 2020-12-17 01:21 UTC by Arkangel12

## Description

When you need the time in 12 hours format this `hourOfPeriod` send back a failed value at noon.

if you looks like this at 10am - 11 am - 0pm - 1pm which is wrong it should be `12pm` it needs an extra validation to subtract `periodOffset` only if `hour` is bigger than `hoursPerPeriod`.

## Related Issues

![showTimePicker](https://user-images.githubusercontent.com/29683014/102425637-edc53480-3fca-11eb-8103-7f5516b48830.png)
![showTimePicker - using hourOfPeriod](https://user-images.githubusercontent.com/29683014/102425642-f0278e80-3fca-11eb-968f-369ef09b2417.png)

2020-12-17 01:36 UTC, Arkangel12 commented
@googlebot I signed it!

2020-12-17 19:35 UTC, Hixie commented
This will definitely need tests, because otherwise we might accidentally break this fix without noticing. That's what the tests are for: to make sure accidental regressions don't happen.

2020-12-17 19:43 UTC, Arkangel12 commented
> This will definitely need tests, because otherwise we might accidentally break this fix without noticing. That's what the tests are for: to make sure accidental regressions don't happen.

got it, will work on this as soon as i can, thanks @Hixie!

2021-02-16 06:54 UTC, darrenaustin requested changes
@Arkangel12 this looks good, but as @hixie pointed out, we will need a test to ensure we don't break this change in the future. Thx.

2021-02-16 14:38 UTC, Arkangel12 commented
thanks, @darrenaustin I will do the tests as soon as I can, I have been busy with the release deadline. will try to add the test this weekend.

2021-03-17 19:51 UTC, Piinks commented
Hi @NWalker1208, thank you for the contribution. This has not been updated in a while, and is not in a state for code review, so I am going to close it for now. If you would like to come back and continue working on it, feel free to re-open! thanks!

2021-03-17 19:51 UTC, closed without merging

2021-03-17 22:42 UTC, Arkangel12 commented
thanks, @Piinks I was so busy the last few months I forgot this.

I just made the changes and create a new PR (I do not have the option to reopen) but you can keep track of it here #78478  

sorry for the delay 😅

2021-03-17 23:01 UTC, Piinks commented
> thanks, @Piinks I was so busy the last few months I forgot this.
> 
> I just made the changes and create a new PR (I do not have the option to reopen) but you can keep track of it here #78478
> 
> sorry for the delay 😅

No worries! Welcome back, thanks for opening a fresh PR!