Fix crash when do three finger gesture
flutter/flutter pull request #72611
Opened 2020-12-18 14:16 UTC by Water-bamboo

## Description

1. The issue([69431](https://github.com/flutter/flutter/issues/69431)) description very clear how reproduce.
Three finger gesture + Redmi device(not only);
When problem happen, it will make app unusable unless restart.

2. crash stack:
2020-12-16 10:39:34.509 11957-12095/com.xx.yy I/flutter: RuntimeException: exception=Null check operator used on a null value
2020-12-16 10:39:34.510 11957-12095/com.xx.yy I/flutter: RuntimeException: stackTrace=#0      _AndroidMotionEventConverter.toAndroidMotionEvent.<anonymous closure> (package:flutter/src/services/platform_views.dart:602:73)
    #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
    #2      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
    #3      new List.from (dart:core-patch/array_patch.dart:38:29)
    #4      new List.of (dart:core-patch/array_patch.dart:68:17)
    #5      ListIterable.toList (dart:_internal/iterable.dart:211:44)
    #6      _AndroidMotionEventConverter.toAndroidMotionEvent (package:flutter/src/services/platform_views.dart:603:12)
    #7      AndroidViewController.dispatchPointerEvent (package:flutter/src/services/platform_views.dart:867:31)
    #8      _PlatformViewGestureRecognizer.handleEvent (package:flutter/src/rendering/platform_view.dart:535:26)
    #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
    #10     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer

## Related Issues

https://github.com/flutter/flutter/issues/69431

## Tests

I added the following tests:

1. With my app, the crash no long happen.
2. The return null solution will go next to handlePointerCancelEvent function, these will clear pointers variables.
And next time whatever one finger or two finger or more fingers, the pointer will dispatch normally to app view(PlatformView);
3. Three finger gesture usually is for screen snapshot, it also works normally.

## Checklist

Before you create this PR, confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I signed the [CLA].
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [] I updated/added relevant documentation (doc comments with `///`). 
- [x] All existing and new tests are passing.
- [x] The analyzer (`flutter analyze --flutter-repo`) does not report any problems on my PR.
- [x] I am willing to follow-up on review comments in a timely manner.

About comment, sorry, not '///' style, because  just keep the same style with nearby code.

## Breaking Change

Did any tests fail when you ran them? Please read [Handling breaking changes].

- [x] No, no existing tests failed, so this is *not* a breaking change.
- [x] Yes, this is a breaking change. *If not, delete the remainder of this section.*
   - [x] I wrote a design doc: https://flutter.dev/go/template *Replace this with a link to your design doc's short link*
   - [x] I got input from the developer relations team, specifically from: *Replace with the names of who gave advice*
   - [x] I wrote a migration guide: https://flutter.dev/go/breaking-changes-template *Replace this with a link to a pull request that adds the migration guide to https://flutter.dev/docs/release/breaking-changes*

[issue database]: https://github.com/flutter/flutter/issues
[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Test Coverage]: https://github.com/flutter/flutter/wiki/Test-coverage-for-package%3Aflutter
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Handling breaking changes]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes

2020-12-18 14:57 UTC, surda19-jin requested changes
Remember god is good

2020-12-20 12:16 UTC, ThexXTURBOXx commented
I can also confirm, that this fixes the mentioned issue with `google_maps_flutter` and therefore closes #69431

2020-12-21 11:13 UTC, Water-bamboo commented
> I can also confirm, that this fixes the mentioned issue with `google_maps_flutter` and therefore closes #69431

I encounter a simillar issue on Xiaomi phone's three finger feature, but not 'map';

2020-12-23 06:15 UTC, Water-bamboo commented
> Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please visit https://cla.developers.google.com/ to sign.**
> 
> Once you've signed (or fixed any issues), please reply here with `@googlebot I signed it!` and we'll verify it.
> 
> #### What to do if you already signed the CLA
> ##### Individual signers
> * It's possible we don't have your GitHub username or you're using a different email address on your commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> 
> ##### Corporate signers
> * Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to [go/cla#troubleshoot](http://go/cla#troubleshoot) ([Public version](https://opensource.google/docs/cla/#troubleshoot)).
> * The email used to register you as an authorized contributor must be the email used for the Git commit. Check [your existing CLA data](https://cla.developers.google.com/clas) and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * The email used to register you as an authorized contributor must also be [attached to your GitHub account](https://github.com/settings/emails).
> 
> ℹ️ **Googlers: [Go here](https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fflutter%2Fflutter%2Fpull%2F72611) for more info**.

@googlebot I signed it!

2020-12-23 06:19 UTC, Water-bamboo commented
> @googlebot I fixed it.

2020-12-23 06:23 UTC, Water-bamboo commented
@googlebot I fixed it.

2020-12-23 06:27 UTC, Water-bamboo commented
> @googlebot I fixed it.

2020-12-28 01:43 UTC, Water-bamboo commented
What should I do to do next? I want to view the 'flutter-build', but fail to filter out errors.

2020-12-28 01:44 UTC, Water-bamboo commented
It builds success  on local 'flutter build ios/apk/web', @flutterbuildbot

2021-01-06 22:55 UTC, goderbauer commented
This PR is missing tests, can you add some to ensure that this never breaks again?

/cc @iskakaushik

2021-01-08 08:03 UTC, chenenyu commented
This pr fixed my issue! 👍

2021-01-20 23:24 UTC, goderbauer commented
@Water-bamboo Do you have plans to come back to this PR and add a test? Thanks.

2021-01-25 17:39 UTC, iskakaushik reviewed
Looking good, please add a test.

2021-02-04 05:17 UTC, Water-bamboo commented
> @Water-bamboo Do you have plans to come back to this PR and add a test? Thanks.
> Looking good, please add a test.

Ok, will do that.

2021-02-05 23:50 UTC, Water-bamboo commented
After run: flutter analyze --flutter-repo
```
Analyzing 3 directories...                                              
No issues found! (ran in 107.8s)
```

2021-02-06 00:36 UTC, Water-bamboo commented
@goderbauer @iskakaushik As the modification is in service/platform_views, I have passed the test coverage there.
![image](https://user-images.githubusercontent.com/1687218/107102643-18f33400-6856-11eb-9260-19c4ea5864d4.png)

2021-02-06 11:20 UTC, Water-bamboo commented
@goderbauer Did the "add a test" mean 'flutter test'?
Here it's the result,  and finally show "All test passed". 

![image](https://user-images.githubusercontent.com/1687218/107116699-01489980-68b0-11eb-96a4-e45120f32163.png)
...
![image](https://user-images.githubusercontent.com/1687218/107116687-ea09ac00-68af-11eb-8823-f245865febc9.png)

2021-02-10 22:53 UTC, goderbauer commented
@goderbauer In order for us to merge this you'll have to add a new test that passes now, but would be failing if your change ever gets reverted.

2021-02-19 07:24 UTC, Water-bamboo commented
> @Water-bamboo In order for us to merge this you'll have to add a new test that passes now, but would be failing if your change ever gets reverted.

@goderbauer Sorry, how to add a new test? Write a new test case or do pull code and do 'flutter test' again?
Another solution, would you commit the fix by your way, my modification just prevent **Array Overflow**, and the 'flutter-build' was green once.

2021-03-03 23:53 UTC, goderbauer commented
Yes, you will have to write a new test case.

2021-03-17 19:47 UTC, Piinks commented
Hi @Water-bamboo, this has not been updated in a while, and is not in a state for code review, so I am going to close it for now. If you would like to come back and continue working on it, feel free to re-open! thanks!

2021-03-17 19:47 UTC, closed without merging

2021-03-31 09:21 UTC, idootop commented
> Hi @Water-bamboo, this has not been updated in a while, and is not in a state for code review, so I am going to close it for now. If you would like to come back and continue working on it, feel free to re-open! thanks!

Please reopen it, we really need it to be merged into Flutter to fix this problem: tobrun/flutter-mapbox-gl#578

2021-03-31 09:28 UTC, ThexXTURBOXx commented
@idootop Follow up this PR: https://github.com/flutter/flutter/pull/78874

2021-04-01 01:33 UTC, idootop commented
> @idootop Follow up this PR: #78874
> 
> Please note that there is not really a solution yet. We need to pinpoint the problem down to its core and not only apply workarounds

Ok, thanks.