[Document]Added BottomNavigation sample with different interactions
flutter/flutter pull request #80652
Opened 2021-04-17 20:07 UTC by obitodarky

Follow-up to #70525 since it was outdated

Added additional use case for BottomNavigationBar.
- Added a scroll-to-top behavior at the first index that scrolls to the top of the ListView.
- Having a unique item that doesn't update the selectedIndex

Fixes #33810

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-04-26 20:40 UTC, craiglabenz requested changes
Thanks so much for adding this!

The goal of this sample is to get the reader to understand wiring up a `BottomNavigationBar.onTap` handler, so I've suggested a few slight changes that, I think, will reduce how much they have to think about before honing in on the important lines.

2021-04-26 20:40 UTC, craiglabenz commented on packages/flutter/lib/src/material/bottom_navigation_bar.dart
> +///       onTap: _onItemTapped,
To simplify reading this sample, I recommend we inline this tap handler.

2021-04-26 20:40 UTC, craiglabenz commented on packages/flutter/lib/src/material/bottom_navigation_bar.dart
> +///           icon: Icon(Icons.arrow_circle_up),
Maybe use `Icon(Icons.format_bold)` to further communicate what we're doing.

2021-04-26 20:40 UTC, craiglabenz commented on packages/flutter/lib/src/material/bottom_navigation_bar.dart
> +///           icon: Icon(Icons.arrow_circle_up),
Maybe use `Icon(Icons.format_clear)` to further communicate what we're doing.

2021-04-26 20:40 UTC, craiglabenz commented on packages/flutter/lib/src/material/bottom_navigation_bar.dart
> +///       _selectedIndex = index;
Instead of setting a `_selectedIndex` (which, admittedly, is a common use case), this should directly set a `FontWeight` attribute.

2021-04-26 20:40 UTC, craiglabenz commented on packages/flutter/lib/src/material/bottom_navigation_bar.dart
> +///                 fontWeight: _selectedIndex == 1? FontWeight.bold : FontWeight.normal,
This line could directly leverage a `FontWeight` attribute if the tap handler stored one of those instead of an integer.

2021-06-10 17:57 UTC, Piinks commented
(triage) Hi @obitodarky would you like to continue with this change?

2021-06-11 01:58 UTC, obitodarky commented
Hi @Piinks, somehow Craig's comment completely missed my radar, sorry about that. I'd like to continue with the change!

2021-07-15 22:09 UTC, goderbauer commented
Closing this one since there hasn't been any activity in some time. Feel free to reopen when you find the time to address the feedback.

2021-07-15 22:09 UTC, closed without merging