Support flavors out of the box on macOS
flutter/flutter pull request #80701
Opened 2021-04-19 08:16 UTC by roughike

There's a tiny bug in the `macos_assemble.sh` script that causes the build to fail in the last phase. If the name of your custom scheme is `dev`, running `flutter run --flavor dev` will fail with an error message saying _"No target named "debug-dev_macos_bundle_flutter_assets" defined"_:

![image](https://user-images.githubusercontent.com/13744304/115202327-f9eb0b00-a0fe-11eb-8d68-8fbab49026bf.png)

It happens because [this line](https://github.com/flutter/flutter/blob/e94f36a7c5edc4389baa2baf86b87aa9280561b8/packages/flutter_tools/bin/macos_assemble.sh#L103) should be calling `debug-macos_bundle_flutter_assets` instead of `debug-dev_macos_bundle_flutter_assets`. This happens because `macos_assemble.sh` is missing [this part from xcode_backend.sh](https://github.com/flutter/flutter/blob/e94f36a7c5edc4389baa2baf86b87aa9280561b8/packages/flutter_tools/bin/xcode_backend.sh#L41-L65), which causes the `build_mode` variable to be parsed improperly to `debug-dev` instead of `debug`.

Fixes #64088.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

2021-04-19 19:07 UTC, ened commented
hi @roughike thank you so much for adding this PR. Should this PR also cover flavor support for `flutter create`?

Currently it fails as follows:

```
$ flutter create --flavor=standard --platforms=macos . 
Could not find an option named "flavor".


Run 'flutter -h' (or 'flutter <command> -h') for available flutter commands and options.
```

2021-04-19 19:15 UTC, roughike commented
The only thing I'm aiming for in this PR is to support `flutter run --flavor <name>` where `<name>` is the name of the custom XCode scheme that already exists in the project (so it was created manually).

`flutter create --flavor=<name>` would be awesome, but I'm afraid my time is very limited.

2021-04-20 05:39 UTC, ened commented
OK clear @roughike. Do you want to have a go at writing a test to verify the new behavior?

2021-04-20 06:47 UTC, roughike commented
I'll take a look at that and get back during this week.

2021-04-21 07:33 UTC, roughike commented
Actually, I'm not sure when I have the time to get back to this and write tests. If someone wants to take over, feel free to do so.

2021-04-21 18:08 UTC, jonahwilliams commented
Some tests that we have for the other tool backend are https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/integration.shard/tool_backend_test.dart -  that would be an integration test that directly invokes the script and asserts on the output.

Generally speaking, we do not take over PRs that do not have tests but I'm happy to provide guidance on what sort of tests would be needed.

2021-04-22 07:28 UTC, ened commented
@jonahwilliams yes please - be great if you can document the testing requirements.

2021-04-23 07:23 UTC, roughike commented
It's actually more complicated than this. 

This PR requires at least one (possibly more) change to support flavors on macOS.

`flutter run --flavor dev` builds `build/macos/Build/Products/Debug-dev/<app name>.app` successfully, but the Flutter tooling tries to run `build/macos/Build/Products/Debug/<app name>.app` and fails. Running the `dev` scheme from XCode works just fine though.

2021-04-23 17:30 UTC, jmagman requested changes
This change only maps a non-standard configuration (other than Debug, Profile, or Release) to a Flutter build mode from Xcode.  It doesn't do any of the tooling work to map the concept of flavors to a configuration when coming from the command line.  I don't think this is close to a complete change (as you pointed out).

Check out all the places in the tool where flavor is handled for iOS.  You can follow the `expectedBuildConfigurationFor` trail, and all the places the `-configuration` flag is passed into `xcodebuild`. 

And as @jonahwilliams pointed out, this feature would require thorough tests.

2021-04-23 20:21 UTC, jmagman commented
We'd also want a mac host integration test like https://github.com/flutter/flutter/blob/307e381935606276d1efb45f45974bbb254decd3/dev/devicelab/bin/tasks/flavors_test_ios.dart though unfortunately I don't think `DriverTest` handles desktop apps yet.

2021-04-26 05:33 UTC, roughike commented
As it turned out to be a bigger task than I thought and I don't have a lot of time, I'm closing this one.

Thanks for all the help - I pointed the discussions out in #64088 in case someone picks this work up later on.

2021-04-26 05:33 UTC, closed without merging