Add barrierLabel in showModalBottomSheet
flutter/flutter pull request #83181
Opened 2021-05-22 18:29 UTC by 838

Allows us to pass a custom `barrierLabel` to `modalBottomSheet` to make them more descriptive for the ScreenReaders.

Fixes:  #83180 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

2021-05-22 18:34 UTC, 838 commented
@googlebot I signed it!

2021-05-25 09:14 UTC, 838 commented
Hi @HansMuller
Can you please review this PR?
Thanks

2021-06-01 08:31 UTC, darrenaustin requested changes
Thanks for the contribution. In addition to a doc comment I mention below, we will also need a test to ensure this new parameter is working correctly (and won't be accidentally broken in the future). You can do this by adding a test to `packages/flutter/test/material/bottom_sheet_test.dart`.

2021-06-01 08:31 UTC, darrenaustin commented on packages/flutter/lib/src/material/bottom_sheet.dart
> +  String? barrierLabel,
There should be a description of this new parameter in the dartdoc above.

2022-01-06 20:08 UTC, darrenaustin commented
It looks like it this PR hasn't been updated in quite a while, so I am closing it for now. Feel free to reopen it again later if you want to complete this work. Thanks.

2022-01-06 20:08 UTC, closed without merging

2023-10-04 15:43 UTC, 838 commented
Fixed in #126431