Migrate microbrenchmarks
flutter/flutter pull request #83619
Opened 2021-05-30 06:25 UTC by Abhishek01039

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-05-30 07:26 UTC, Abhishek01039 commented
Hello @jmagman 
can you please review this PR?
Thanks

2021-06-01 18:28 UTC, jmagman requested changes
microbenchmarks_ios passes on this PR.

2021-06-01 18:28 UTC, jmagman commented on dev/benchmarks/microbenchmarks/lib/language/sync_star_semantics_bench.dart
> +        workingLabel += info.semanticsLabel!;
Put it in a local, then you don't need the `!`.
```dart
      final String infoSemanticsLabel = info.semanticsLabel;
      if (infoSemanticsLabel != null) {
        workingLabel += infoSemanticsLabel;
```

2021-06-01 18:28 UTC, jmagman commented on dev/benchmarks/microbenchmarks/lib/language/sync_star_semantics_bench.dart
> +        workingLabel += info.semanticsLabel!;
Same here.

2021-06-02 17:27 UTC, jmagman approved these changes
LGTM

2021-06-02 17:59 UTC, merged