Fix widgets with built-in scrollbars
flutter/flutter pull request #83828
Opened 2021-06-02 20:47 UTC by Piinks

Fixes #83819 

This updates widgets that have built-in scrollbars to not have scrollbars applied by inherited ScrollBehaviors.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-06-02 23:51 UTC, gspencergoog requested changes

2021-06-02 23:51 UTC, gspencergoog commented on packages/flutter/test/material/about_test.dart
> +  }, variant: const TargetPlatformVariant(<TargetPlatform>{ ...TargetPlatform.values }));
```suggestion
  }, variant: const TargetPlatformVariant.all());
```

2021-06-02 23:51 UTC, gspencergoog commented on packages/flutter/test/material/dropdown_test.dart
> +  }, variant: const TargetPlatformVariant(<TargetPlatform>{ ...TargetPlatform.values }));
```suggestion
  }, variant: const TargetPlatformVariant.all());
```

2021-06-02 23:51 UTC, gspencergoog commented on packages/flutter/test/cupertino/dialog_test.dart
> +  }, variant: const TargetPlatformVariant(<TargetPlatform>{ ...TargetPlatform.values }));
```suggestion
  }, variant: const TargetPlatformVariant.all());
```

2021-06-02 23:51 UTC, gspencergoog commented on packages/flutter/test/cupertino/action_sheet_test.dart
> +  }, variant: const TargetPlatformVariant(<TargetPlatform>{ ...TargetPlatform.values }));
```suggestion
  }, variant: const TargetPlatformVariant.all());
```

2021-06-03 19:33 UTC, Piinks commented on packages/flutter/test/material/about_test.dart
> +  }, variant: const TargetPlatformVariant(<TargetPlatform>{ ...TargetPlatform.values }));
Oh goodness! My brain must've still been on vacation. 😋  Thanks!

2021-06-03 20:12 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

2021-06-04 00:44 UTC, merged