Add SizedBox.square() constructor
flutter/flutter pull request #84041
Opened 2021-06-05 13:24 UTC by pedromassango

Fixes https://github.com/flutter/flutter/issues/82613

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

2021-06-06 08:34 UTC, dkwingsmt requested changes
Other than the comments, I probably don't have the say on whether we should add this. @goderbauer Do you think we should add this?

2021-06-06 08:34 UTC, dkwingsmt commented on packages/flutter/lib/src/widgets/basic.dart
> +  /// Creates a box whose its [width] and [height] are equals.
```suggestion
  /// Creates a box whose [width] and [height] are equal.
```

2021-06-06 08:34 UTC, dkwingsmt commented on packages/flutter/test/widgets/basic_test.dart
> +  testWidgets('SizedBox.square tests', (WidgetTester tester) async {
There's a `sized_box_test.dart` where this test should be put in.

2021-06-10 17:12 UTC, HansMuller approved these changes
Although this only seems marginally useful, we already have `Size.square()`, so OK.

2021-06-10 18:49 UTC, merged