Feat(cupertino): [date_picker] Date order parameter
flutter/flutter pull request #84599
Opened 2021-06-14 22:37 UTC by ayshiff

Closes #84550 

This PR adds a new `dateOrder` parameter to  `CupertinoDatePicker` to define the order of the columns in date mode which overrides the default order value defined by `localizations.datePickerDateOrder`.

## Pre-launch Checklist

- [X] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [X] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [X] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [X] I signed the [CLA].
- [X] I listed at least one issue that this PR fixes in the description above.
- [X] I updated/added relevant documentation (doc comments with `///`).
- [X] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [X] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-06-17 13:15 UTC, pedromassango requested changes
LGTM once the comments are addressed

2021-06-17 13:15 UTC, pedromassango commented on packages/flutter/test/cupertino/date_picker_test.dart
> +      lastOffset = tester.getTopLeft(find.text('January'));
Is this last line required? I mean the assignment is not being used.

Maybe you meant to remove it or add another `expect` statement.

2021-06-17 17:00 UTC, pedromassango requested changes
One more nit and should be go to go

2021-06-17 17:00 UTC, pedromassango commented on packages/flutter/lib/src/cupertino/date_picker.dart
> +  final DatePickerDateOrder? dateOrder;
Nit: space between

2021-06-18 07:03 UTC, pedromassango approved these changes
LGTM

I would like to get a final approval from @LongCatIsLooong to make sure we're not missing anything.

2021-06-18 09:03 UTC, LongCatIsLooong commented on packages/flutter/test/cupertino/date_picker_test.dart
> +      expect(tester.getTopLeft(find.text('January')).dx > lastOffset.dx, true);
```suggestion
      expect(
        tester.getTopLeft(find.text('14')).dx,
        lessThan(tester.getTopLeft(find.text('January')).dx,
      );
```

2021-06-21 17:35 UTC, LongCatIsLooong commented on packages/flutter/lib/src/cupertino/date_picker.dart
> +  /// Defaults to [localizations.datePickerDateOrder].
`[localizations]` does not exist I think? Maybe just say defaults to the locale's default date format/order?

2021-06-22 16:10 UTC, pedromassango commented
@ayshiff could you please rebase for the CI to re-run?

2021-07-01 03:26 UTC, merged