Clarify ReorderableListView drag handles on desktop and mobile
flutter/flutter pull request #86737
Opened 2021-07-20 19:11 UTC by idkq

Prevents this https://github.com/flutter/flutter/issues/80553

More info here https://github.com/flutter/flutter/pull/80576

Comments only change. These changes were pre-approved on the pull 80576 but not pushed.

2022-01-12 00:18 UTC, Hixie commented on packages/flutter/lib/src/material/reorderable_list.dart
> +/// a drag. To change this behavior use
instead of "use" the Flutter voice would normally say "consider"

2022-01-12 21:50 UTC, darrenaustin requested changes
Sorry for the delay on this review. Thanks for the contribution, this looks good. I agree with Ian that we should probably reword that to 'consider'. Thx.

2022-01-14 04:45 UTC, darrenaustin requested changes
@idkq thanks for the update. Unfortunately it looks like the analyzer didn't like the trailing space:

```
sdk/packages/flutter/lib/src/material/reorderable_list.dart:35: trailing U+0020 space character
```

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket/8825148537102622513/+/u/Analyze/analyze/test_stdout

Can you fix that? Then I think we should be good to go. Thx.

2022-02-22 23:42 UTC, darrenaustin commented
Looks like it has been a while on this, so I just submitted these changes with some other doc fixes with #98954. Closing this PR. Thanks @idkq.

2022-02-22 23:42 UTC, closed without merging