[tools] Add Xcode version to non-verbose Flutter doctor
flutter/flutter pull request #87022
Opened 2021-07-26 00:17 UTC by TahaTesser

Fixes https://github.com/flutter/flutter/issues/86902

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-07-27 17:54 UTC, jmagman requested changes
Instead of adding `versionInfo` to `ValidationResult` which won't be used by any of the existing validators that report a version (and will therefore be unexpectedly null) and it looks like in your change is only used in the unit test?, instead fix the regression introduced in #73808 and just set `xcodeVersionInfo` with its `,` parsing logic.
```dart
      if (versionText != null) {
        xcodeVersionInfo = versionText;
        if (xcodeVersionInfo.contains(',')) {
          xcodeVersionInfo = xcodeVersionInfo.substring(0, xcodeVersionInfo.indexOf(','));
        }
```

2021-07-27 17:54 UTC, jmagman commented on packages/flutter_tools/lib/src/doctor_validator.dart
> +import './base/version.dart';
```suggestion
import 'base/version.dart';
```

2021-07-27 17:54 UTC, jmagman commented on packages/flutter_tools/lib/src/doctor_validator.dart
> +  final Version? versionInfo;
This is only used in the unit test?

2021-07-27 18:19 UTC, jmagman requested changes

2021-08-12 20:56 UTC, christopherfujino commented
@TahaTesser are you still working on this?

2021-08-15 18:29 UTC, TahaTesser commented
@jmagman 
That was interesting, I made the changes in the code and tests, please take a look, thank you

2021-08-16 22:59 UTC, jmagman requested changes

2021-08-16 22:59 UTC, jmagman commented on packages/flutter_tools/lib/src/base/user_messages.dart
> +  String xcodeVersion(String version) => 'version $version';
This is unused.
```suggestion
```

2021-08-16 22:59 UTC, jmagman commented on packages/flutter_tools/lib/src/doctor_validator.dart
> +import './base/version.dart';
Now this can be removed.
```suggestion
```

2021-08-16 22:59 UTC, jmagman commented on packages/flutter_tools/lib/src/doctor_validator.dart
> +  const ValidationResult(this.type, this.messages, { this.statusInfo, this.versionInfo });
Revert this.
```suggestion
  const ValidationResult(this.type, this.messages, { this.statusInfo });
```

2021-08-16 22:59 UTC, jmagman commented on packages/flutter_tools/lib/src/doctor_validator.dart
> +  final Version? versionInfo;
Revert.
```suggestion
```

2021-08-16 22:59 UTC, jmagman commented on packages/flutter_tools/lib/src/macos/xcode_validator.dart
> +    return ValidationResult(xcodeStatus, messages, statusInfo: xcodeVersionInfo, versionInfo: _xcode.currentVersion);
Revert.
```suggestion
    return ValidationResult(xcodeStatus, messages, statusInfo: xcodeVersionInfo);
```

2021-08-16 22:59 UTC, jmagman commented on packages/flutter_tools/test/general.shard/macos/xcode_validator_test.dart
> +    testWithoutContext('Check for Xcode version in non-verbose flutter doctor', () async {
> Also, the xcode validator doesn't have a concept of doctor verbosity, you're just checking that the result status info is correct.

See my comment in https://github.com/flutter/flutter/pull/87022#discussion_r677692728, this test is the same case as `Succeeds when all checks pass` so it doesn't add any test coverage.  Do you can remove it, you're covered by the new `statusInfo` expectations.

If you want you can add the `ValidationMessage` test expectations I already wrote in that comment, but that's optional.

2021-08-17 19:55 UTC, TahaTesser commented
@jmagman 
I should have reverted these changes earlier for `versionInfo`, my bad, now it's done, still getting used to get to this process 

> expect(result.messages.length, 2);

messages length is only 1, so I have updated the for `ValidationMessage` for the first message only 

Thank you so much!

2021-08-17 20:56 UTC, jmagman approved these changes
LGTM, thanks @TahaTesser!

2021-08-17 21:18 UTC, TahaTesser commented on packages/flutter_tools/test/general.shard/macos/xcode_validator_test.dart
>        expect(result.type, ValidationType.installed);
@jmagman 
This was accidentally removed, restored it cb7aa1b65f8dba5a8a47b681c0b45c05577263b8

2021-08-17 22:52 UTC, merged