update ScrollMetricsNotification
flutter/flutter pull request #87421
Opened 2021-08-01 06:25 UTC by xu-baolin

1, notify the first scroll metrics initialize change(null -> non-null)
2,remove the first empty scroll notification request

CC @Piinks @chunhtai

2021-08-02 18:09 UTC, chunhtai approved these changes
LGTM

2021-08-02 19:04 UTC, Piinks requested changes

2021-08-02 19:04 UTC, Piinks commented on packages/flutter/lib/src/widgets/scrollbar.dart
> +    assert(_debugScheduleCheckHasValidScrollPosition());
Won't this result in the scrollbar not being triggered in release builds? Asserts are disabled in release.

2021-08-02 19:04 UTC, Piinks commented on packages/flutter/lib/src/widgets/scrollbar.dart
> -        scrollController!.position.didUpdateScrollPositionBy(0);
Removing this hack is nice! 👍

2021-08-02 19:08 UTC, Piinks commented on packages/flutter/lib/src/widgets/scrollbar.dart
> +        _fadeoutTimer?.cancel();
Oh I see, the rest was factored out of the assert. This is a really nice clean up.

2021-08-02 19:08 UTC, Piinks approved these changes
LGTM

2021-08-02 20:09 UTC, Piinks commented
Rebasing after https://github.com/flutter/flutter/pull/87518 should fix the failing check. See  https://github.com/flutter/flutter/issues/87517 for more info

2021-08-03 03:16 UTC, xu-baolin commented on packages/flutter/lib/src/widgets/scrollbar.dart
> -        scrollController!.position.didUpdateScrollPositionBy(0);
😄

2021-08-03 04:40 UTC, merged