Master fix buildable mac os app
flutter/flutter pull request #87930
Opened 2021-08-09 03:22 UTC by wanglikun7342

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

MacOSApp use placeholder to projectBundleId, this pr complete the macos version projectBundleId parse to replace the placeholder

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/pull/87264

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-08-09 03:24 UTC, wanglikun7342 commented
@jmagman please review this pr

2021-08-09 07:17 UTC, wanglikun7342 commented
@jmagman i think the checks make mistake

2021-08-09 17:41 UTC, jmagman requested changes
What problem exactly are you trying to solve?  I don't think the macOS bundle ID is used anywhere, so while this is more correct than the placeholder bundle ID, it's adding seconds to the macOS build without actually adding any functionality.

From https://github.com/flutter/flutter/pull/87264#discussion_r682274575
> Which seems like a lot since the `BuildableMacOSApp` id isn't used. I'm actually okay with this staying a placeholder hack until it's actually used somewhere.

I like the `abstract class XcodeBasedProject extends FlutterProjectPlatform` refactoring work to share more logic between macOS and iOS and would happy to review just that change.

2021-08-09 17:41 UTC, jmagman commented on packages/flutter_tools/lib/src/xcode_project.dart
> +    final Map<String, String> buildSettings = await xcodeProjectInterpreter.getBuildSettings(
I don't think `XcodeProjectInterpreter.getBuildSettings()` is set up to match how macOS builds.  Ideally they would be shared, but I believe the macOS build code was kind of thrown together until it worked and no one went back to use `XcodeProjectInterpreter` in macOS build.

For example
https://github.com/flutter/flutter/blob/089323487fe1b5cc402bbe65c47383f61eba241c/packages/flutter_tools/lib/src/ios/xcodeproj.dart#L187
vs
https://github.com/flutter/flutter/blob/db930ba32f320cb0ca53595a2df0e4a9fe15101d/packages/flutter_tools/lib/src/macos/build_macos.dart#L104-L106

Though in practice it probably doesn't matter for `PRODUCT_BUNDLE_IDENTIFIER`.

2021-08-10 02:30 UTC, wanglikun7342 commented
@jmagman I have changed the pr,please review again

2021-08-11 02:25 UTC, wanglikun7342 commented
@jmagman this pr need your review again

2021-08-11 17:13 UTC, jmagman reviewed
This refactor looks good to me.  Can you update the title and description with what it's now doing, and we can merge it.

2021-08-12 01:57 UTC, wanglikun7342 commented
@Hixie this pr need a test exemption

2021-08-12 02:08 UTC, Hixie commented
test-exempt: code refactor with no semantic change

2021-08-12 02:11 UTC, wanglikun7342 commented
@jmagman done

2021-08-12 03:45 UTC, jmagman approved these changes
LGTM, thanks!

2021-08-12 04:47 UTC, merged