Add build and startup tests for the Platform Services app
flutter/flutter pull request #8826
Opened 2017-03-16 17:48 UTC by szakarias

2017-03-16 19:21 UTC, yjbanov reviewed
You've got all the devicelab bits right. I'm not really sure that `StartupTest` is the right thing to do if our goal is to test correctness. A start-up test waits for the first frame of the application to render, then quits immediately declaring a victory. A driver test might be a better option, since it would allow you to exercise the platform services functionality.

2017-03-16 19:21 UTC, yjbanov commented on dev/devicelab/bin/tasks/platform_services_ios__start_up.dart
> +  await task(createFlutterGalleryStartupTest());
Did you mean `createPlatformServicesStartupTest()`?

2017-03-16 19:21 UTC, yjbanov commented on dev/devicelab/bin/tasks/platform_services__build.dart
> +  await task(createPlatformServicesBuildTest());
You don't need a build test unless you are interested in code size and build speed metrics. The start-up test has to build anyway and therefore will make sure that we can build the example app successfully.

2017-03-16 19:21 UTC, yjbanov commented on dev/devicelab/lib/tasks/perf_tests.dart
> +      '${flutterDirectory.path}/examples/platform_services',
My understanding was that we are interested in testing correctness of platform services. If so, then `StartupTest` may not be a suitable way of testing them. Consider writing a driver test that exercises the platform services, and then a devicelab task that runs the driver test.

2017-03-16 23:21 UTC, szakarias commented
Actually my initial thought was just to check if the app could build and launch, but you are right of course, that testing functionality is much better! I haven't cleaned up/removed the old tests yet, but I would be very happy if you could take a look at the driver test and let me know if this is the way forward.

2017-03-17 20:51 UTC, yjbanov requested changes
Getting very close. Let's restructure the tasks a little and it should be good to go.

2017-03-17 20:51 UTC, yjbanov commented on examples/platform_services/test_driver/button_tap_test.dart
> +            return await driver.getText(batteryLevelLabel);
I think the retry API is too heavyweight for this test. How about this:

```dart
String batteryLevel;
while(batteryLevel == null || batteryLevel.isEmpty) {
  batteryLevel = await driver.getText(batteryLevelLabel);
}
expect(batteryLevel, isNotEmpty);
```

The test framework should (hopefully) handle the timeout if the text never appears.

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/bin/tasks/platform_services__build.dart
> +// Copyright 2017 The Chromium Authors. All rights reserved.
Each task defined in `bin/tasks` creates a new column in our [test matrix](https://flutter-dashboard.appspot.com/build.html). We therefore try to make our tests coarse grained. If we want to test multiple things, we bundle them in one task. For example, `flutter_gallery__transition_perf` tests all demo apps in the gallery app and measures performance all as part of one task. I intend to fix this at some point by supporting "task bundles". For now, I think we just need one task for platform services that tests everything we need. So let's remove `platform_services__build.dart` and do everything we need in the other one.

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/bin/tasks/platform_services__button_tap.dart
> +// Copyright 2017 The Chromium Authors. All rights reserved.
`button_tap` is too much detail for a task. We want the task to be coarse-grained. Let's call it `platform_services_test` and encapsulate the specifics.

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/bin/tasks/platform_services__start_up.dart
> +// Copyright 2017 The Chromium Authors. All rights reserved.
Let's remove this task. One task should be sufficient to test platform services. We can on-board more fine-grained tests after we teach our test infrastructure to scale in the future.

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/bin/tasks/platform_services_ios__button_tap.dart
> +// Copyright 2017 The Chromium Authors. All rights reserved.
Similarly, let's rename this to `platform_services_test_ios`.

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/bin/tasks/platform_services_ios__start_up.dart
> +// Copyright 2017 The Chromium Authors. All rights reserved.
Let's remove this task.

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/lib/tasks/perf_tests.dart
> +  return new PerfTest(
Could you please create a copy of `PerfTest` called `DriverTest` and remove the performance metrics? We don't want to publish metrics that we do not set goals and baselines for.

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/manifest.yaml
> +  platform_services__build:
let's remove

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/manifest.yaml
> +  platform_services__button_tap:
let's rename to `platform_services_test`

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/manifest.yaml
> +  platform_services__start_up:
let's remove

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/manifest.yaml
> +  platform_services_ios__button_tap:
let's rename to `platform_services_test_ios`

2017-03-17 20:51 UTC, yjbanov commented on dev/devicelab/manifest.yaml
> +  platform_services_ios__start_up:
let's remove

2017-03-20 13:00 UTC, szakarias commented
Thank you so much for the comments, would you please take another look?

2017-03-20 17:34 UTC, yjbanov approved these changes
LGTM! This marks the day we finally began testing platform services! Hurrah! :)

2017-03-20 21:19 UTC, merged

2017-03-21 21:25 UTC, Hixie commented
Unfortunately the tests are red on iOS.

2017-03-22 00:25 UTC, yjbanov commented
> Unfortunately the tests are red on iOS.

That was half-expected.

2017-03-22 21:00 UTC, szakarias commented
Fixed with #8946 . It seems an old version of Xcode is used for the tests. Would it be possible to upgrade to Xcode 8?

2017-03-22 22:39 UTC, yjbanov commented
> Fixed with #8946

Thanks!

> Would it be possible to upgrade to Xcode 8?

It would take a little work, because Xcode 8 has new provisioning profile rules that our test infra needs to learn.

2017-03-23 15:21 UTC, szakarias commented
I see. Unfortunately, Xcode will automatically undo the change. That is, every time a storyboard file is opened it is saved in the new format.