Update text_painter.dart
flutter/flutter pull request #88536
Opened 2021-08-19 15:55 UTC by aadarshadhakalg

This PR adds default value to the `textDirection` of `TextPainter` class. `textDirection` was nullable value, and was null by default but if we don't give `TextDirection` then no text was painted in the canvas. This creates confusion among users. So there were two options, one was to make it required or give it a default value. In this PR I gave the default value of `TextDirection.ltr` to the `textDirection` of `TextPainter` class.

## Pre-launch Checklist

- [x  ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ x ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ x ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ x ] I signed the [CLA].
- [ x ] I listed at least one issue that this PR fixes in the description above.
- [ x ] I updated/added relevant documentation (doc comments with `///`).
- [ x ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ x ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-08-19 18:50 UTC, goderbauer requested changes
In Flutter, we are staying away from making default assumptions about the text direction. That means, we should not default to LTR or RTL here.

2021-08-20 16:49 UTC, aadarshadhakalg commented
> In Flutter, we are staying away from making default assumptions about the text direction. That means, we should not default to LTR or RTL here.

@goderbauer  Hey, I have done some changes. Is it acceptable? If now we can close this PR.

2021-08-25 21:16 UTC, Piinks reviewed
Hey @aadarshadhakalg, it looks like many tests are failing here. Can you take a look? It also looks like there is not a test to validate the change works as expected.

2021-09-08 21:51 UTC, goderbauer commented
Given that this is causing so many test failures, this change is probably not a good idea.

2021-09-08 21:51 UTC, closed without merging