feat: add Image support to finder
flutter/flutter pull request #88761
Opened 2021-08-24 02:49 UTC by wanglikun7342

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*
add Image Finder to support a widget use ImageProvider

*List which issues are fixed by this PR. You must list at least one issue.*
https://github.com/flutter/flutter/issues/88760

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*
I add new Finder way to find widget, but will not influence old tests

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making or feature I am adding, or Hixie said the PR is test-exempt.
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-08-24 02:51 UTC, wanglikun7342 commented
@jmagman @jonahwilliams please give a review to this pr

2021-08-24 03:20 UTC, jmagman commented
Maybe @dkwingsmt? I'm not familiar with the framework/finder code at all...

2021-08-24 06:03 UTC, wanglikun7342 commented
@goderbauer

2021-08-24 23:38 UTC, dkwingsmt requested changes

2021-08-24 23:38 UTC, dkwingsmt commented on packages/flutter_test/lib/src/finders.dart
> +  /// Finds [Image] and [FadeInImage] widgets containing ImageProvider equal to the
```suggestion
  /// Finds [Image] and [FadeInImage] widgets containing `image` equal to the
```

2021-08-24 23:38 UTC, dkwingsmt commented on packages/flutter_test/lib/src/finders.dart
> +      print(widget);
```suggestion
```

2021-08-24 23:38 UTC, dkwingsmt commented on packages/flutter_test/test/finders_test.dart
> +        const Image(image: _TestAssetImageProvider('test')),
Does it mean, if a developer would like to unit test a widget tree that contains `AssetImage`, they would always need to replace the `AssetImage` into something like `_TestAssetImageProvider`? If that's the case, this method is close to unusable.

2021-08-25 06:04 UTC, wanglikun7342 commented
@dkwingsmt I change the Test to FileImage

2021-08-26 07:44 UTC, dkwingsmt approved these changes
LGTM

2021-08-26 19:51 UTC, merged