Bottom sheet add enable drag
flutter/flutter pull request #90932
Opened 2021-09-29 07:28 UTC by sanlittt

fixed #90664 

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

2021-09-29 07:29 UTC, sanlittt commented
@googlebot I signed it!

2021-09-29 07:47 UTC, sanlittt commented
@googlebot I fixed it.

2021-10-04 17:55 UTC, gspencergoog commented
Hi @sanlittt, thanks for the PR!

Looks like there are some analysis errors and test failures that need to be fixed, but this looks like a reasonable change to me.  Thanks for writing some good tests!

Please correct the failures, and I'll be happy to give it a final review.

2021-11-18 23:10 UTC, gspencergoog approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d](https://user-images.githubusercontent.com/8867023/37737237-66e9c9dc-2d10-11e8-8797-13a405eace49.png)

Remove the extra parenthesis, and this is good to go.

2021-11-18 23:10 UTC, gspencergoog commented on packages/flutter/lib/src/material/scaffold.dart
> +      enableDrag: enableDrag ?? (!isPersistent),
The extra parenthesis are not needed.

2021-11-19 09:14 UTC, skia-gold commented
Gold has detected about 1 new digest(s) on patchset 9.
View them at https://flutter-gold.skia.org/cl/github/90932

2021-11-19 09:29 UTC, skia-gold commented
Gold has detected about 1 new digest(s) on patchset 10.
View them at https://flutter-gold.skia.org/cl/github/90932

2021-11-22 23:15 UTC, Piinks requested changes
Hi @sanlittt welcome! 🎉 
For the public `showBottomSheet` methods where you have added `enableDrag`, can you add some documentation for what `enableDrag` means and what the default behavior is?

2021-11-25 03:41 UTC, sanlittt commented
> Hi @sanlittt welcome! 🎉 For the public `showBottomSheet` methods where you have added `enableDrag`, can you add some documentation for what `enableDrag` means and what the default behavior is?

done

2021-11-29 23:30 UTC, Piinks approved these changes
LGTM! Thank you for the contribution.

2021-12-01 01:09 UTC, merged