Change project.buildDir in standalone `subprojects` property
flutter/flutter pull request #91030
Opened 2021-09-30 14:42 UTC by littleGnAl

If there is a plugin project name's lexicographical order before 'app', the prject ':app' buildDir is not set correctly.

This PR revert the changes made by https://github.com/flutter/flutter/pull/77942, I'm not sure it's the right way to fix this issue, but I add a test for this case to ensure it works as expected.

*List which issues are fixed by this PR. You must list at least one issue.*

Fixed https://github.com/flutter/flutter/issues/91018

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-09-30 23:56 UTC, jmagman commented
@blasten

2021-10-01 00:38 UTC, blasten commented
we need a test for this. would you be able to wire a plugin in the test that has the desired name?


The code below has an example about how to create a plugin in a test:

https://github.com/flutter/flutter/blob/34059eec2c671472ee95f5093705fb9fed0b3919/packages/flutter_tools/test/integration.shard/generated_plugin_registrant_test.dart#L76

2021-10-01 01:29 UTC, littleGnAl commented
Hello @blasten, I have reused the `android_plugin_example_app_build_test.dart`, should I add a standalone integration.shard for this case?
https://github.com/flutter/flutter/pull/91030/files#diff-0a03b0a0c8e091b09635cd4d75bd08462084a15c4333fbc9fa95eab9bf2537e1R129-R130

2021-10-01 01:38 UTC, littleGnAl commented on packages/flutter_tools/test/integration.shard/android_plugin_example_app_build_test.dart
> +  test('plugin example android/app/build should not exists after flutter build', () async {
@blasten I have added a new test case here, should I move it to a standalone test file?

2021-10-01 01:46 UTC, blasten commented
ah - that should work. does the test fail if you revert the changes to the template?

2021-10-01 01:47 UTC, blasten approved these changes

2021-10-01 01:50 UTC, littleGnAl commented
> ah - that should work. does the test fail if you revert the changes to the template?

@blasten It seems no

2021-10-01 01:52 UTC, blasten requested changes
I see. Please verify the test fail without the fix

2021-10-01 02:17 UTC, littleGnAl commented
@blasten The test fails without the fix.
```
➜  flutter_tools git:(littlegnal/fix-subprojects-builddir-not-correct-2) ../../bin/cache/dart-sdk/bin/pub run test /Users/fenglang/codes/source/flutter/packages/flutter_tools/test/integration.shard/android_plugin_example_app_build_test.dart
The top level `pub` command is deprecated. Use `dart pub` instead.
01:49 +1 -1: plugin example android/app/build should not exists after flutter build [E]
  Expected: false
    Actual: <true>

  package:test_api                                                          expect
  test/integration.shard/android_plugin_example_app_build_test.dart 72:5    main._createAndBuildPlugin
  test/integration.shard/android_plugin_example_app_build_test.dart 130:5   main.<fn>
  test/integration.shard/android_plugin_example_app_build_test.dart 129:82  main.<fn>
  test/src/common.dart 163:18                                               test.<fn>
  test/src/common.dart 159:5                                                test.<fn>

01:49 +1 -1: loading /Users/fenglang/codes/source/flutter/packages/flutter_tools/test/integration.shard/android_plugin_example_app_build_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
01:49 +1 -1: Some tests failed.
```
```
diff --git a/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle b/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle
index 24047dce5d..ed45c65885 100644
--- a/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle
+++ b/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle
@@ -21,8 +21,6 @@ allprojects {
 rootProject.buildDir = '../build'
 subprojects {
     project.buildDir = "${rootProject.buildDir}/${project.name}"
-}
-subprojects {
     project.evaluationDependsOn(':app')
 }
```

2021-10-01 03:20 UTC, littleGnAl commented
@blasten I finally move the test to a standalone file to fill more test cases, pls take a look again, thanks.

2021-10-01 03:29 UTC, littleGnAl commented
The tests fail without this fix.
```
➜  flutter_tools git:(littlegnal/fix-subprojects-builddir-not-correct-2) ✗ ../../bin/cache/dart-sdk/bin/pub run test /Users/fenglang/codes/source/flutter/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart
The top level `pub` command is deprecated. Use `dart pub` instead.
01:08 +0 -1: android/app/build should not exists after flutter build apk [E]
  Expected: not a file system entity that exists
    Actual: LocalDirectory:<LocalDirectory: '/private/var/folders/gk/3g8dn2ys3nv01yxsd0j_1cz00000gr/T/flutter_flutter_plugin_test.tUCf5b/aaa/example/android/app/build'>

  package:test_api                                                                  expect
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 55:5  main._checkBuildDir
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 68:7  main.<fn>
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 60:5  main.<fn>
  test/src/common.dart 163:18                                                       test.<fn>
  test/src/common.dart 159:5                                                        test.<fn>

01:08 +0 -1: loading /Users/fenglang/codes/source/flutter/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
01:47 +0 -2: android/app/build should not exists after flutter build appbundle [E]
  Expected: not a file system entity that exists
    Actual: LocalDirectory:<LocalDirectory: '/private/var/folders/gk/3g8dn2ys3nv01yxsd0j_1cz00000gr/T/flutter_flutter_plugin_test.D0m6sd/aaa/example/android/app/build'>

  package:test_api                                                                  expect
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 55:5  main._checkBuildDir
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 82:7  main.<fn>
  test/integration.shard/flutter_build_android_app_project_builddir_test.dart 74:5  main.<fn>
  test/src/common.dart 163:18                                                       test.<fn>
  test/src/common.dart 159:5                                                        test.<fn>

01:47 +0 -2: loading /Users/fenglang/codes/source/flutter/packages/flutter_tools/test/integration.shard/flutter_build_android_app_project_builddir_test.dart
Consider enabling the flag chain-stack-traces to receive more detailed exceptions.
For example, 'dart test --chain-stack-traces'.
01:47 +0 -2: Some tests failed.
```

```
diff --git a/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle b/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle
index 24047dce5d..ed45c65885 100644
--- a/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle
+++ b/packages/flutter_tools/templates/app_shared/android-kotlin.tmpl/build.gradle
@@ -21,8 +21,6 @@ allprojects {
 rootProject.buildDir = '../build'
 subprojects {
     project.buildDir = "${rootProject.buildDir}/${project.name}"
-}
-subprojects {
     project.evaluationDependsOn(':app')
 }
```

2021-10-01 23:40 UTC, blasten approved these changes
nice! LGTM

2021-10-02 00:18 UTC, merged

2021-10-02 02:15 UTC, gspencergoog commented
This appears to have broken the build.  I'm going to try and revert and see if it fixes this.

2021-10-02 02:27 UTC, gspencergoog commented
Actually, it doesn't appear to be the case: the revert PR failed too. Probably an infra issue.