[Stepper] Add Alternative Label on horizontal-type Stepper
flutter/flutter pull request #91496
Opened 2021-10-08 16:07 UTC by KKimj

# Add Alternative Label on horizontal-type Stepper

## Linked issues

#91337

### Before
![image](https://user-images.githubusercontent.com/40026920/136127620-b88e814c-0bfe-4072-b50c-06cb14955455.png)

---

## Screenshots

### Horizontal

![image](https://user-images.githubusercontent.com/40026920/136651484-15950aaa-fbc7-40dc-839a-c986b2ecfcef.png)

<del>
### Vertical

![image](https://user-images.githubusercontent.com/40026920/136651500-269d4bb2-c984-4668-85e3-4889bf82b108.png)

### [important!] Remained issues

- Padding, Align
![image](https://user-images.githubusercontent.com/40026920/136590084-9a91988d-300b-4eee-8dc9-575cc79c073e.png)

- Up and down number-icon
![image](https://user-images.githubusercontent.com/40026920/136590135-fb445fb5-4b22-42ca-b3f6-96fa45633aa9.png)
</del>

## Reproduce code
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: 'Stepper Alternative Label',
      home: MyStatefulWidget(),
    );
  }
}

class MyStatefulWidget extends StatefulWidget {
  const MyStatefulWidget({Key? key}) : super(key: key);

  @override
  State<MyStatefulWidget> createState() => _MyStatefulWidgetState();
}

class _MyStatefulWidgetState extends State<MyStatefulWidget> {
  int _index = 0;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stepper(
        type: StepperType.horizontal,
        // type: StepperType.vertical,
        currentStep: _index,
        onStepCancel: () {
          if (_index > 0) {
            setState(() {
              _index -= 1;
            });
          }
        },
        onStepContinue: () {
          if (_index < 3) {
            setState(() {
              _index += 1;
            });
          }
        },
        onStepTapped: (int index) {
          setState(() {
            _index = index;
          });
        },
        steps: <Step>[
          Step(
            isActive: _index == 0,
            title: const Text('Step 1 title'),
            content: Container(
                alignment: Alignment.centerLeft,
                child: const Text('Content for Step 1')),
            label: const Text('Step 1'),
            subtitle: const Text('Step 1 subtitle'),
          ),
          Step(
            isActive: _index == 1,
            title: const Text('Step 2 title'),
            content: const Text('Content for Step 2'),
            subtitle: const Text('Step 2 subtitle'),
            label: const Text('Step 2'),
          ),
          Step(
            isActive: _index == 2,
            title: const Text('Step 3 title'),
            content: const Text('Content for Step 3'),
            subtitle: const Text('Step 3 subtitle'),
            label: const Text('Step 3'),
          ),
          Step(
            isActive: _index == 3,
            title: const Text('Step 4 title'),
            content: const Text('Content for Step 4'),
            subtitle: const Text('Step 4 subtitle'),
            label: const Text('Step 4'),
          ),
        ],
      ),
    );
  }
}
```

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-10-08 23:43 UTC, craiglabenz commented
Thanks for the confirmation on tests, @KKimj. If you're new to widget tests, the existing Stepper widget tests contain many great examples of meaningful tests :)

2021-10-09 09:29 UTC, KKimj commented
@craiglabenz 
Hello, I add new test for lable ( Alternative Label ) with stepper.
Please check, and give me some comments.
Thanks, HAGW!

2021-10-18 16:06 UTC, craiglabenz requested changes
Thanks so much for this PR, @KKimj :)

I left two comments, after which I think this will be good to go!

2021-11-13 16:22 UTC, KKimj commented
@craiglabenz 
Hello, how are you doing?
Can you give me a new feedback?
Thank you.

2022-01-26 22:25 UTC, craiglabenz commented
@KKimj 

I am *So. So.* sorry for disappearing for so long. Somehow, the alert for this PR snuck past me and I never caught it.

In my last comment, I wrote "it would be nice to add another one that confirms the styling logic you've written is behaving as anticipated", which I now realize was a little unclear. The key function I would like to see tested is `_labelStyle`, since it accepts an index and merges that with the user's progress through the stepper and the Dark Mode / Light Mode status before ultimately yielding a `TextStyle`. The internals of that function are pretty complicated, so I think we should have unit tests to verify that a Stepper with X steps, and currently at step Y, is rendering each label correctly. There a few scenarios to cover there - steps before, on, and after the active step; in both light mode and dark mode.

Does all of that make sense?

PS - I promise not to disappear this time!

2022-01-31 03:47 UTC, KKimj commented
Hello!! LTNS!!
I understand what you say.

I will update test-codes soon.
Something like below.

- Let, `X := currentStepIndex`, `Y := arbitraryStepIndex (except current)`

1. set X = 0.
2. Check Styles of X and Y.
3. set X = 1.
4. Invoke `setState()`.
5. Check Styles of X and Y.

P.S 
`Happy New Year!`

2022-01-31 04:06 UTC, craiglabenz commented
Yes, that looks like the right pseudocode. Thanks so much and 🌔 Happy New Year 🌔 to you, too!

2022-04-19 23:10 UTC, Hixie commented
@KKimj Is this a PR you are interested in doing further work on? It's perfectly understandable if you don't have time right now, and if that's the case we can save what you've done so far and put it aside so that if someone else wants to work on this they can start from your PR. But if you do have the time to work on this, that would be great!

2022-04-19 23:15 UTC, KKimj commented
@Hixie 
Hello!
I always had it in mind. I want to finish all the work within April. How does that sound?

2022-04-21 09:23 UTC, KKimj commented on packages/flutter/test/material/stepper_test.dart
> +  });
@craiglabenz 
Hello..! It's been so long. How have you been?

I pushed a commit for test about `TextStyles` of Label Widget.

Please Review my commit.
Thanks!

2022-04-21 09:23 UTC, KKimj commented
@craiglabenz 
Hello..! It's been so long. How have you been?

I pushed a commit for test about `TextStyles` of Label Widget.

Please Review my commit.
Thanks!

2022-04-22 16:25 UTC, craiglabenz commented
That test looks good, @KKimj. However, I just tested the code myself directly, and the padding / alignment issue does still seem to be in play. Is this something you're also looking to address?

2022-04-25 15:41 UTC, KKimj commented
@craiglabenz 
Hello!

Now I realize again that there is no alternative label in the Vertical type, `StepperType.vertical`.
- https://material.io/archive/guidelines/components/steppers.html#steppers-types-of-steppers
![image](https://user-images.githubusercontent.com/40026920/165121235-2afb541b-844e-490c-91d1-9c698f85f85c.png)

Anyway, I found a way to solve the `padding / alignment issue`.
The method is to modify the function '_buildVerticalHeader', forcing width to 24.0, according to the Material Guide.
- Code diff here, (It was not pushed.) 
- <img width="1361" alt="image" src="https://user-images.githubusercontent.com/40026920/165122074-60d7b522-4767-4c3a-90ca-657ca4880172.png">
- An example UI can be similar to the following.
<img width="738" alt="image" src="https://user-images.githubusercontent.com/40026920/165122620-15a2094b-ac9a-45ae-a10f-18cba3271774.png">
But it's too small, and as I said above, it's dubious because `alternative label` is not in the Vertical type. I'd like to ask for advice on how to do it.

Thanks, Have a good day!

2022-04-25 16:10 UTC, craiglabenz commented
Oh dear, we're running out of pixels below the circle. To be honest, I'm not sure that it makes sense to put anything in this spot, given the screenshots you shared and how cramped the area is. The fact that only such short strings will fit is a bit of a problem, in my opinion.

Taking a step back - what informed your desire to land this change? Is there possibly another way that need could be satsified?

2022-04-25 16:53 UTC, KKimj commented
@craiglabenz 
I was motivated for the horizontal type.
Is it right to exclude it from the vertical type?

Or is it right to include even more width?
But this would violate the width or margin value of the Material design.

2022-04-25 16:55 UTC, craiglabenz commented
I think it's probably fair to have this be horizontal-only, and to spell that out in the relevant docstrings.

2022-04-25 16:59 UTC, KKimj commented
Thank you!

Then, when the label attribute is given in the vertical type, how should I handle it?
Should I use an asset or something?

2022-04-25 17:04 UTC, craiglabenz commented
My ideal solution would simply be to do nothing in the vertical case. Have the new attribute's docstring mention that it is only honored in the horizontal alignment and then make no changes to the vertical build methods.

2022-04-25 17:17 UTC, KKimj commented
Thank you for letting me know about your Insight!
I just did some new push.
Please check. Thank you!

2022-04-25 18:16 UTC, craiglabenz commented
I like that this is currently horizontal-only, but I'm also seeing a spacing issue there. Note that before adding a `label`, everything is appropriately centered:

<img width="150" alt="Screen Shot 2022-04-25 at 11 13 19 AM" src="https://user-images.githubusercontent.com/855034/165149113-8bfe89a3-4df8-40c0-a604-60514630d8fe.png">

But then after adding a label, the horizontal connectors shift and are no-longer centered. fwiw, I think this is largely the core challenge of this PR - you can no longer as easily predict the heights of each component to know how to keep the horizontal connectors centered within the circle.

<img width="163" alt="Screen Shot 2022-04-25 at 11 13 33 AM" src="https://user-images.githubusercontent.com/855034/165149255-2611be6e-3b86-4a64-94ae-5ecb8e10a002.png">

The horizontal connectors look centered within the entire column of circle-and-label, but my hunch is that it should remain centered within the _circle_.

2022-04-25 19:01 UTC, KKimj commented
@craiglabenz 

This is what you're expecting, right?
<img width="866" alt="스크린샷 2022-04-26 오전 3 59 09" src="https://user-images.githubusercontent.com/40026920/165156240-85d6b0ff-dce5-403f-a4e4-9e18d2b86a77.png">

2022-04-25 19:10 UTC, craiglabenz commented
That centering looks good! I forget, is the elevation coming from the Stepper itself, or have you wrapped it in something in this demo? If it comes from the Stepper itself, then some padding below the `label` would help.

2022-04-25 20:20 UTC, KKimj commented
@craiglabenz 
Hello!! 
I Pushed some commits.
Please review!

<img width="866" alt="image" src="https://user-images.githubusercontent.com/40026920/165168082-bd222110-cf50-499f-a610-1ccab17f64b7.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/40026920/165168200-6ed7e6ba-9eac-419e-92cc-21d3a50b37dc.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/40026920/165168236-7faa14a2-c223-43d8-92a1-f2598de5d64c.png">

2022-04-25 20:31 UTC, KKimj commented
And also, Please check out these corner cases, which are related to `fontSize`.

<img width="866" alt="image" src="https://user-images.githubusercontent.com/40026920/165169690-c84f65b8-6aa3-4f1c-841c-3e391f9875c4.png">

2022-06-03 08:54 UTC, craiglabenz approved these changes
Nice, I think this is ready!

2022-06-03 09:00 UTC, KKimj commented
@craiglabenz 
Wow, thank you.
Is there anything I need to do for `customer_testing-linux`, CI that has failed?

2022-06-03 09:53 UTC, craiglabenz commented
I strongly suspect that failure is a false-negative, but we'll have to see if it happens again.

2022-06-04 04:48 UTC, KKimj commented on packages/flutter/lib/src/material/stepper.dart
> +  /// [label] appears under the number icon.
@craiglabenz 
Would you change to status resolved?

2022-06-04 04:48 UTC, KKimj commented on packages/flutter/test/material/stepper_test.dart
> +  });
@craiglabenz 
Would you change to status resolved?
Thanks!

2022-06-06 21:43 UTC, merged