Improvements to SearchDelegate
flutter/flutter pull request #91982
Opened 2021-10-18 07:30 UTC by prateekmedia

Use `searchFieldStyle` for `SearchDelegate`'s `TextStyle` as an alternative to regular `headline6`, so that someone can easily change the text style without messing with the app's theme.

*List which issues are fixed by this PR. You must list at least one issue.*
#93861

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-11-07 16:49 UTC, prateekmedia commented
@darrenaustin Can you please review this PR.

Use Case:
- When your TextTheme's `headline6` is set to custom font size which is either too high or too low to be used as a font size of a search field.

Why:
I can't find any other way to change the font size of that field, also note that you can't wrap search delegate with Theme class. If that was the case then I would simply just wrap it with `Theme` and change the font size of headline6 from their.

So the only possible way to change search field text style was to make the field use `searchFieldStyle`(if provided), else to use the default `headline6`.

2022-02-15 20:26 UTC, darrenaustin requested changes
Thanks for the contribution. Sorry it has taken me so long to look at it.

This looks like a reasonable change. We need to have a test for this to verify that `searchFieldStyle` is being used here.  You can add a new test or perhaps add an expect cause to the existing 'Custom searchFieldStyle value' test in `packages/flutter/test/material/search_test.dart`.

2022-02-16 05:51 UTC, prateekmedia commented
@darrenaustin I have added some test and also rebased the PR.

2022-02-22 23:56 UTC, darrenaustin approved these changes
LGTM. Thx.

2022-03-07 20:29 UTC, HansMuller approved these changes
LGTM. This is effectively an incompatible change; hopefully it will not inadvertently break anything.

2022-03-25 13:53 UTC, prateekmedia commented
OK so two **LGTM** from official contributors, Is there anything which is stopping this PR?

2022-04-28 19:38 UTC, CaseyHillers commented
re Google testing being stuck, can you try rebasing your PR with the latest from upstream?

The PR is 1000 commits behind master, so it's unable to be tested

2022-04-29 19:24 UTC, merged