[flutter_tools] xcresult parser.
flutter/flutter pull request #92604
Opened 2021-10-27 20:50 UTC by cyanglaz

Add `XCResultGenerator`, this object generates an `XCResult`, which contains useful information in an iOS or macOS build.
As this initial version. `XCResult` only contains issues such as warning and error messages.

Part of https://github.com/flutter/flutter/issues/22536
After this lands, the build_ios.dart can adopt this and show the warning and error messages to the console.

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-10-27 21:24 UTC, jmagman requested changes

2021-10-28 22:24 UTC, jmagman reviewed
Tests are failing
```
01:05 +1864 ~4 -1: test\general.shard\ios\xcresult_test.dart: error: `xcresulttool get` process fail should return an `XCResult with `parsingErrorMessage` as stderr. [E]                              
  Expected: 'Fake: fail to parse result json.'
    Actual: 'xcresult parser: Unrecognized top level json format.'
     Which: is different.
            Expected: Fake: fail ...
              Actual: xcresult p ...
                      ^
             Differ at offset 0
  
  package:test_api                                 expect
  test\general.shard\ios\xcresult_test.dart 127:5  main.<fn>
```

2021-10-29 18:36 UTC, cyanglaz reviewed
@jmagman Updated with all your comments, (now with the enum type and double checked line length), PTAL

2021-10-29 18:36 UTC, cyanglaz commented on packages/flutter_tools/lib/src/ios/xcresult.dart
> +import 'dart:convert' show json;
done

2021-10-29 18:36 UTC, cyanglaz commented on packages/flutter_tools/lib/src/ios/xcresult.dart
> +  final String type;
yup, done.
I made the enum named type, and added a subType field as String

2021-10-29 20:35 UTC, jmagman approved these changes
Small nit, thanks for the edits, LGTM!

2021-10-29 20:35 UTC, jmagman commented on packages/flutter_tools/lib/src/ios/xcresult.dart
> +      required Map<String, Object?> issueJson}) {
Trailing comma

2021-10-30 01:29 UTC, merged