migrate some file to null safety
flutter/flutter pull request #92957
Opened 2021-11-03 03:29 UTC by wanglikun7342

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-11-03 08:33 UTC, wanglikun7342 commented
@jmagman null safe mirgate pr

2021-11-03 17:22 UTC, jmagman requested changes

2021-11-03 17:22 UTC, jmagman commented on packages/flutter_tools/test/integration.shard/command_output_test.dart
> +      .trim()) as Map<String, dynamic>;
These should be `Object` or `Object?` not `dynamic`.  `dynamic` removes static type checking and shouldn't be used in null safe libraries.
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-using-var-and-dynamic

2021-11-05 06:35 UTC, wanglikun7342 commented
i think the check errors  make mistake, jmagman. The files I modified is irrelevant.

2021-11-05 16:06 UTC, jmagman commented
> i think the check errors make mistake, jmagman. The files I modified is irrelevant.

You're right, it's https://github.com/flutter/flutter/issues/93133. That will be fixed soon, and then you can rebase onto the fix and the tests should pass.

2021-11-05 16:07 UTC, jmagman approved these changes
LGTM

2021-11-05 19:48 UTC, christopherfujino commented on packages/flutter_tools/test/integration.shard/debug_adapter/flutter_adapter_test.dart
> +    await Future.wait(<Future<void>>[
why was this changed to `void`?

2021-12-12 18:56 UTC, christopherfujino commented
@wanglikun7342 are you still working on this?

2021-12-14 14:56 UTC, wanglikun7342 commented
@christopherfujino I have resolved it , please review it again

2021-12-14 15:02 UTC, skia-gold commented
Gold has detected about 1 new digest(s) on patchset 10.
View them at https://flutter-gold.skia.org/cl/github/92957

2021-12-14 15:07 UTC, skia-gold commented
Gold has detected about 1 new digest(s) on patchset 10.
View them at https://flutter-gold.skia.org/cl/github/92957

2021-12-16 18:55 UTC, christopherfujino approved these changes
LGTM thanks!

2021-12-16 19:39 UTC, merged