implemented TapUp within InkResponse and InkWell
flutter/flutter pull request #93833
Opened 2021-11-18 00:33 UTC by gslender

implemented the missing TapUp event within InkResponse and InkWell

Issue #93683 identified this as missing 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-11-18 01:17 UTC, dkwingsmt reviewed
LGTM except for nit documentation. Also needs a 2nd review.

2021-11-18 01:17 UTC, dkwingsmt commented on packages/flutter/lib/src/material/ink_well.dart
> +  /// Called when the user releases and before [onTap].
```suggestion
  /// Called when the user taps this part of the material and releases the tap,
  /// invoked before [onTap].
```

2021-11-27 11:05 UTC, werainkhatri requested changes
You may need to create a new issue for this PR and add it to the description like **Fixes #ISSUE_NUMBER**.

2021-11-27 12:12 UTC, werainkhatri approved these changes
LGTM. Thank you for your contribution.

2021-11-27 12:12 UTC, werainkhatri commented on packages/flutter/lib/src/material/ink_well.dart
> +  /// Called when the user releases a tap that was started on this part of the
Just a minor analysis fix.

```suggestion
  /// Called when the user releases a tap that was started on this part of the
```

2022-02-09 05:18 UTC, merged