Initial Commit to Add borderRadius to InkWell in TabBar
flutter/flutter pull request #94291
Opened 2021-11-27 12:56 UTC by nayeemtby

This PR is adding splashBorderRadius to TabBar that provides borderRadius to InkWell.

Addresses Feature Request #94290

Before: https://youtu.be/S2qBpaE2wOo
After: https://youtu.be/xvK_uZXVmDc

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-11-27 14:59 UTC, nayeemtby commented
Requesting any recommendation regarding the parameter name.

2021-11-27 15:25 UTC, nayeemtby commented
Any recommendation on the parameter name?

2021-11-28 06:01 UTC, innos123 commented
> This PR is adding splashBorderRadius to TabBar that provides borderRadius to InkWell.
> 
> Addresses Feature Request #94290
> 
> Before: https://youtu.be/S2qBpaE2wOo After: https://youtu.be/xvK_uZXVmDc
> 
> ## Pre-launch Checklist
> * [x]  I read the [Contributor Guide](https://github.com/flutter/flutter/wiki/Tree-hygiene#overview) and followed the process outlined there for submitting PRs.
> * [x]  I read the [Tree Hygiene](https://github.com/flutter/flutter/wiki/Tree-hygiene) wiki page, which explains my responsibilities.
> * [x]  I read and followed the [Flutter Style Guide](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo), including [Features we expect every widget to implement](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement).
> * [x]  I signed the [CLA](https://cla.developers.google.com/).
> * [x]  I listed at least one issue that this PR fixes in the description above.
> * [x]  I updated/added relevant documentation (doc comments with `///`).
> * [x]  I added new tests to check the change I am making, or this PR is [test-exempt](https://github.com/flutter/flutter/wiki/Tree-hygiene#tests).
> * [x]  All existing and new tests are passing.
> 
> If you need help, consider asking for advice on the #hackers-new channel on [Discord](https://github.com/flutter/flutter/wiki/Chat).

2021-12-03 16:31 UTC, werainkhatri requested changes

2021-12-03 16:31 UTC, werainkhatri commented on packages/flutter/lib/src/material/tabs.dart
> +  /// Defines the [InkWell]'s `borderRadius` property.
The doc should not reference something the developer may not know about, like `TabBar` using `InkWell`. Try documenting it like below.

```dart
/// The clipping radius of splashes that extend outside the bounds of the tab.
```

Try reading docs of similar API from other parts of the framework to get a better idea.

2021-12-03 16:31 UTC, werainkhatri commented on packages/flutter/lib/src/material/tabs.dart
> +  /// `indicator` to this [TabBar].
Instead of here, add `splashBorderRadius` in the `See also` section of the doc of `indicator`, explaining this point there.

2021-12-03 16:31 UTC, werainkhatri commented on packages/flutter/test/material/tabs_test.dart
> +                                    const Radius.circular(_radius))));
The formatting needs correction. Refer to the Style Guide or other tests to know more.

2021-12-03 16:31 UTC, werainkhatri commented on packages/flutter/test/material/tabs_test.dart
> +                ]))));
The formatting needs correction.

2021-12-04 07:21 UTC, nayeemtby commented
Is the plugins error related to my PR?

2021-12-04 07:46 UTC, werainkhatri commented
Could you try to rebase/merge this with the master branch? Looks like there are conflicts too.

2021-12-06 06:57 UTC, nayeemtby commented
> Could you try to rebase/merge this with the master branch? Looks like there are conflicts too.

Done

2021-12-07 10:47 UTC, werainkhatri requested changes

2021-12-07 10:47 UTC, werainkhatri commented on packages/flutter/lib/src/material/tabs.dart
> +  ///   * [splashBorderRadius] to define the clipping radius of the splash if borderRadius of BoxDecoration is defined.
```suggestion
  ///  * [splashBorderRadius], which defines the clipping radius of the splash
  ///    and is generally used with [BoxDecoration.borderRadius].
```

2021-12-07 10:47 UTC, werainkhatri commented on packages/flutter/lib/src/material/tabs.dart
> +  /// If this property is null, then [BorderRadius.zero] is used.
```suggestion
  /// If this is null, it is interpreted as [BorderRadius.zero].
```

2021-12-07 10:47 UTC, werainkhatri commented on packages/flutter/lib/src/material/tabs.dart
> +  /// If this property is null, then [BorderRadius.zero] is used.
```suggestion
  /// When null, it is interpreted as [BorderRadius.zero].
```

2021-12-07 10:47 UTC, werainkhatri commented on packages/flutter/lib/src/material/tabs.dart
> +  /// `indicator` to this [TabBar].
Remove this from here as you have added it in the see also section.

2021-12-07 10:47 UTC, werainkhatri commented on packages/flutter/test/material/tabs_test.dart
> +      )
```suggestion
              ),
            ],
          ),
        ),
      ),
```

2021-12-07 10:47 UTC, werainkhatri commented on packages/flutter/test/material/tabs_test.dart
> +      )
```suggestion
        ),
      ),
```

2021-12-07 10:47 UTC, werainkhatri commented on packages/flutter/test/material/tabs_test.dart
> +  testWidgets("TabBar accepts 'splashBorderRadius' that gives 'borderRadius' to InkWell", (WidgetTester tester) async {
```suggestion
  testWidgets("splashBorderRadius is passed to InkWell.borderRadius", (WidgetTester tester) async {
```

2021-12-23 17:48 UTC, chunhtai approved these changes
LGTM

2021-12-23 17:48 UTC, chunhtai commented
can you rebase off the latest master and see if it fixes the build?

2021-12-24 03:15 UTC, nayeemtby commented
> can you rebase off the latest master and see if it fixes the build?

Done, but I think the problem is internal. 

> /root/.pub-cache/hosted/pub.dartlang.org/platform-2.2.1/lib/src/interface/local_platform.dart:45:41: Error: Member not found: 'packageRoot'.
|   String get packageRoot => io.Platform.packageRoot;

This error is all over the place.

2022-01-21 18:30 UTC, chunhtai commented
Looks like there is a bunch formatting error, can you fix them as well?

2022-01-27 03:10 UTC, closed without merging