Better separation between app and plugin main.dart and fix plugin main.dart issues.
flutter/flutter pull request #9491
Opened 2017-04-20 12:34 UTC by mit-mit

Clearly separate the main part of the main.dart into regular app and plugin app.

Fix mounted bug in plugin.

Simplify plugin app to not have counter logic, and instructional comments that are plugin specific.

Fixes https://github.com/flutter/flutter/issues/9458

2017-04-20 12:55 UTC, jakobr-google requested changes
Almost LGTM. :)

2017-04-20 12:55 UTC, jakobr-google commented on packages/flutter_tools/templates/create/lib/main.dart.tmpl
> +      platformVersion = await Testplugin.platformVersion;
You'll want to use `{{pluginDartClass}}` instead of `Testplugin` here.

2017-04-20 12:55 UTC, jakobr-google commented on packages/flutter_tools/templates/create/lib/main.dart.tmpl
> +import 'package:flutter/services.dart';
What do we need this one for?

2017-04-20 13:00 UTC, mit-mit commented on packages/flutter_tools/templates/create/lib/main.dart.tmpl
> +import 'package:flutter/services.dart';
For the try/catch; that's where `PlatformException` is defined

2017-04-20 13:01 UTC, mit-mit commented on packages/flutter_tools/templates/create/lib/main.dart.tmpl
> +      platformVersion = await Testplugin.platformVersion;
Thanks, fixed

2017-04-20 13:03 UTC, jakobr-google approved these changes
LGTM

2017-04-20 17:46 UTC, Hixie commented on packages/flutter_tools/templates/create/lib/main.dart.tmpl
> +      platformVersion = await {{pluginDartClass}}.platformVersion;
It's unfortunate that there's no way to cancel the platformVersion call. Imagine if the call did a lot of computation, but the user triggered it then left the page that cares about the result. The work would still get done, but the result would then be thrown away.

Anyway that's an issue for another bug.

2017-04-20 17:46 UTC, Hixie commented on packages/flutter_tools/templates/create/lib/main.dart.tmpl
> +    if (!mounted) return;
newline before return

2017-04-20 17:47 UTC, Hixie commented
LGTM but why not a FutureBuilder?

2017-04-21 10:49 UTC, mit-mit commented
Merging. The broken flutter-build appears to be a flake as it passed in a re-run.

2017-04-21 10:49 UTC, merged

2017-04-21 10:50 UTC, mit-mit commented
RE FutureBuilder: As I think it's hard to motivate and explain that concept in a sample where the widget tree is entirely fixed. I think we need to have a more complete example for it to be meaningful, for example add something to gallery.

2017-04-21 16:24 UTC, Hixie commented
I don't understand. It would simplify this code, no? Isn't the motivation just that you wouldn't have to do the setState/mounted dance?