Create a text validator/formatter mechanism
flutter/flutter pull request #9535
Opened 2017-04-21 21:18 UTC by xster

#9511

Add a text formatter interface used by EditingText. Provide some default implementations.

2017-04-21 21:18 UTC, xster commented
Soliciting some feedback before I put in all the tests

2017-04-21 21:36 UTC, Hixie commented on packages/flutter/lib/src/services/text_editing.dart
> +  TextSelection copyWith({int baseOffset, int extentOffset}) {
why only those two instead of all four?

nit: spaces around named argument declarations

2017-04-21 23:07 UTC, xster commented on packages/flutter/lib/src/services/text_editing.dart
> +  TextSelection copyWith({int baseOffset, int extentOffset}) {
it was arbitrary :) changed

2017-04-22 00:16 UTC, cbracken requested changes

2017-04-22 00:16 UTC, cbracken commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +/// sensible values.
Maybe: 
```
/// This formatter attempts to preserve the [TextEditingValue.selection].
```

That said, as-is, I'm not convinced this adds much. It feels like we're saying 'This formatter behaves how you'd expect it to.' Perhaps more directly state that this formatter will adjust the selection in the case that blacklisted characters were removed?

2017-04-22 00:16 UTC, cbracken commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      = new BlacklistingTextInputFormatter(new RegExp(r'\n'));
Is this correct? 

During a copy-paste, I'd assume a replacementString where every contiguous string of newlines is collapsed to a single `0x20` space. 

During text entry, _ideally_ I'd want `\n` to be replaced with the empty string, but in single-line text fields, I suspect we'll also set a keyboard that only supplies a `Done` key so using a space is probably a non-issue.

2017-04-22 00:20 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      = new BlacklistingTextInputFormatter(new RegExp(r'\n'));
Not sure I fully caught what you meant. Can you add an example? Or did you want r'\n+'? 

if the user pastes:
```


```
with a replacement string of `' '` (1 space), it outputting `'   '` (3 spaces) feels more predictable.

2017-04-22 00:24 UTC, cbracken commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      = new BlacklistingTextInputFormatter(new RegExp(r'\n'));
Corrected my original statement. Should be a straight-up 1:1 replacement of `\n` with a space.

2017-04-22 00:26 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    assert(blacklistedPattern != null);
nit: the formatting here isn't consistent with the style we normally use

2017-04-22 00:27 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +  /// String used to replace found patterns.
nit: newline between the members

2017-04-22 00:27 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    // Don't apply formatting to text still under composition.
can we guarantee that you can't compose something with a newline?

2017-04-22 00:29 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      = new BlacklistingTextInputFormatter(new RegExp(r'\n'));
I think that's true no? If there's 20 \n in whichever placement, replaceAll will replace them all with 20 spaces right?

2017-04-22 00:29 UTC, Hixie commented on packages/flutter/lib/src/widgets/editable_text.dart
> +                 ..add(BlacklistingTextInputFormatter.singleLineFormatter)
mutating the list is sketchy. if someone creates one then passes it in each time, it'll get progressively longer.
if someone passes in a const list, it'll crash.

2017-04-22 00:36 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    // Don't apply formatting to text still under composition.
Can't but I think it's a bit too edge case-y to worry about. My intent is just handle cases where if someone blacklists latin characters and starts typing chinese, there should still be latin characters in the composition interim. If the user presses send/save/wtv right at that moment, I think we should 'commit' the composition first (which triggers the formatting) and then pass it out.

2017-04-22 00:48 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    // Don't apply formatting to text still under composition.
I think when you're in a single-line text field, we need to be able to guarantee that you cannot ever enter a newline.

2017-04-22 00:56 UTC, cbracken commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      = new BlacklistingTextInputFormatter(new RegExp(r'\n'));
Exactly - yep.

2017-04-22 02:20 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +/// A [TextInputFormatter] that prevents the insertion of blacklisted.
done

2017-04-22 02:20 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +/// sensible values.
reworded a bit

2017-04-22 02:20 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    assert(blacklistedPattern != null);
changed

2017-04-22 02:20 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +  /// String used to replace found patterns.
done

2017-04-22 02:21 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    // Don't apply formatting to text still under composition.
I was pedantic with the wording. But pragmatically, I don't think it's possible to enter a newline while composing.

2017-04-22 02:21 UTC, xster commented on packages/flutter/lib/src/widgets/editable_text.dart
> +                 ..add(BlacklistingTextInputFormatter.singleLineFormatter)
Ya, good call, that was a disaster... Changed

2017-04-22 02:32 UTC, xster commented
I expanded this PR a bit to avoid diffbase gymnastics. 
- Added a WhitelistingTextInputFormatter
- Use a digits only whitelisting formatter in the gallery demo
- Add a phone number formatter in the gallery demo

Now fixes #9511. Fixes #9340. And fixes a bug in the gallery on iOS that prevents me from testing #9200.

2017-04-24 15:42 UTC, Hixie commented on examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart
> +      return '(###) ###-#### - Please enter a valid phone number.';
US phone number

2017-04-24 17:21 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    {this.replacementString: ''}
put the `{` on the previous line and the `}` on the next line to match similar code elsewhere in the codebase

2017-04-24 17:21 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      (String substring) =>
nit: don't use => if you have a line break

2017-04-24 17:22 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      (String substring) => whitelistedPattern
same here

2017-04-24 17:23 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    // Don't apply formatting to text still under composition.
How about if the code passes in a newline in the original string? Or if someone writes a custom keyboard that does it?

2017-04-25 01:11 UTC, xster commented on examples/flutter_gallery/lib/demo/material/text_form_field_demo.dart
> +      return '(###) ###-#### - Please enter a valid phone number.';
Done

2017-04-25 01:11 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    {this.replacementString: ''}
Done

2017-04-25 01:11 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      (String substring) =>
Done

2017-04-25 01:11 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +      (String substring) => whitelistedPattern
Done

2017-04-25 01:11 UTC, xster commented
Added tests

2017-04-25 01:14 UTC, xster commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    // Don't apply formatting to text still under composition.
what did you mean the code passes in? Did you mean if the user passes in a second formatter that breaks the first one?

Either way, added handling to format text under composition

2017-04-25 02:18 UTC, Hixie commented on packages/flutter/lib/src/widgets/text_formatter.dart
> +    // Don't apply formatting to text still under composition.
I meant if someone writes Flutter code that sets the initial value of the editable text field to `'a\nb'`.

2017-04-28 19:50 UTC, xster commented
Gentle ping

2017-04-28 20:43 UTC, Hixie commented
LGTM but @cbracken should rereview since he marked it as X.

2017-04-28 21:09 UTC, cbracken approved these changes
lgtm

Since `TextInputFormatter` & co. aren't strictly dependent on anything in `widgets`, consider moving those to `services`. On the off chance anyone else decided to implement their own `widgets` alternative, they could still deal with the existing validators.

2017-04-28 22:26 UTC, xster commented
oh ya, that's a really good point. Since the TextSelection stuff is already in services. Done

2017-04-28 22:33 UTC, merged