Fix showSearch not showing Toolbar on empty text
flutter/flutter pull request #95589
Opened 2021-12-20 17:22 UTC by masewo

Changes the setter of `query` in `SearchDelegate` to only be called when the text is not empty. While initialization the setter gets called with an empty value and the corresponding `TextSelection` change prevents the `Toolbar` to show up properly on double tap.

Fixes issue https://github.com/flutter/flutter/issues/95588

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

2022-01-21 19:21 UTC, chunhtai commented
I still can't bring up the toolbar using the sample code with the fix.

2022-02-04 23:18 UTC, chunhtai commented
Hi @masewo, are you still planning on coming back to this PR?

2022-04-04 20:20 UTC, chunhtai requested changes

2022-05-24 23:29 UTC, Hixie commented
@masewo Thanks for your contribution! Based on @chunhtai's comments it sounds like this is not the approach we would like to follow to fix this, so I'm going to close this PR for now. Please don't hesitate to file a new PR if you would like to follow up on this!

2022-05-24 23:29 UTC, closed without merging