Add sksl path option to build ios-frameworks
flutter/flutter pull request #95843
Opened 2021-12-27 08:30 UTC by lukaszdebowski

This PR adds the --bundle-sksl-path option to the build ios-framework command.

Fixes https://github.com/flutter/flutter/issues/88874

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2021-12-27 08:59 UTC, lukaszdebowski commented
The bot complains about missing tests, but I've noticed that other command files such as `build ios` don't have tests for the flags they accept, and I'm not really sure if I should be adding those now. If someone could point me in the right direction that would be great 👍🏻  

Also, I didn't really know how to test that change locally, so help with that would also be much appreciated 🥺

2022-01-28 00:13 UTC, christopherfujino commented
@lukaszdebowski thanks for opening this PR; however, just adding the flag is not enough, fixing this issue would require actually implementing the code that would use that flag :)

I'm closing this PR for now, feel free to discuss further on the bug https://github.com/flutter/flutter/issues/88874

2022-01-28 00:19 UTC, jmagman commented
I think this would work since the code is already implemented when the `buildInfo` is constructed:
https://github.com/flutter/flutter/blob/3138cce7b223be3c872da53f97b9c44a61eebe71/packages/flutter_tools/lib/src/runner/flutter_command.dart#L1063-L1065

However this does need tests.  You can see how tests for a similar flag was added to https://github.com/flutter/flutter/pull/91590.

2022-01-28 00:20 UTC, jmagman requested changes
Requesting changes for tests.

2022-01-28 00:20 UTC, christopherfujino commented
Actually, it looks like this SHOULD work because of https://github.com/flutter/flutter/blob/3138cce7b223be3c872da53f97b9c44a61eebe71/packages/flutter_tools/lib/src/runner/flutter_command.dart#L1063-L1065.

However, this would need an integration test to verify the behavior.

2022-02-17 22:01 UTC, christopherfujino commented
Closing this as stale. Feel free to re-open with tests.

2022-02-17 22:01 UTC, closed without merging