fix rsync output utf8decode bug
flutter/flutter pull request #95881
Opened 2021-12-28 03:27 UTC by intspt

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-01-04 22:50 UTC, jmagman requested changes
Thanks for tracking this down!  Minor nit for adding a comment.

I audited the other places we `rsync` and I think the following could also use this flag:
This one is our generic "unzip" code, which is used for unzipping a pre-built iOS./macOS bundles, which could contain Chinese or other valid encoded file names:
https://github.com/flutter/flutter/blob/5b6de035ce3c43d3865243f6cebe6dcb977d8e66/packages/flutter_tools/lib/src/base/os.dart#L455
https://github.com/flutter/flutter/blob/5b6de035ce3c43d3865243f6cebe6dcb977d8e66/packages/flutter_tools/lib/src/ios/application_package.dart#L35-L37
https://github.com/flutter/flutter/blob/5b6de035ce3c43d3865243f6cebe6dcb977d8e66/packages/flutter_tools/lib/src/macos/application_package.dart#L67

______
And this one could be problematic for embedded dart-side assets file names:
https://github.com/flutter/flutter/blob/2d07436dbd535fa545eb3bae8c399a071c36ec93/packages/flutter_tools/bin/xcode_backend.dart#L191-L198

If you're willing to update those spots (and tests), that would be super helpful!  If not, you can update this PR with a comment and I'll merge it.

2022-01-04 22:50 UTC, jmagman commented on packages/flutter_tools/lib/src/ios/mac.dart
> +            '-8',
Can you add a comment about why we added this?  Staring at the `rsync` man page I don't think it's super obvious why we would use this flag.  Something like:
```suggestion
            '-8', // Avoid mangling filenames with encodings that do not match the current locale.
```

2022-01-07 03:13 UTC, intspt commented
Hi, I updated it as you suggested.

2022-01-12 01:26 UTC, jmagman approved these changes
I wasn't able to reproduce the original issue, but I did try it to validate it didn't cause (obvious) regressions to resources without UTF-8 issues.

2022-01-12 01:26 UTC, jmagman commented
+ 2nd reviewer @christopherfujino

2022-01-12 03:33 UTC, intspt commented
> I wasn't able to reproduce the original issue, but I did try it to validate it didn't cause (obvious) regressions to resources without UTF-8 issues.

Just add a picture with Chinese name to the Runner project.

2022-01-12 19:17 UTC, jmagman commented
> Just add a picture with Chinese name to the Runner project.

I did, it runs fine.  This may be related to locale settings?
<img width="318" alt="Screen Shot 2022-01-12 at 11 14 52 AM" src="https://user-images.githubusercontent.com/682784/149206780-7f2a5429-d3c4-49ba-8de6-0dd50f224a56.png">
<img width="897" alt="Screen Shot 2022-01-12 at 11 15 38 AM" src="https://user-images.githubusercontent.com/682784/149206774-bee93a0d-751f-4497-ba49-af3376d3a107.png">

I'm not worried about reproducing it to validate this change, since you can reproduce.  We'll get further verification from other reporters once we get a second review from @christopherfujino and this merges.

2022-01-13 03:08 UTC, intspt commented
> > Just add a picture with Chinese name to the Runner project.
> 
> I did, it runs fine. This may be related to locale settings? <img alt="Screen Shot 2022-01-12 at 11 14 52 AM" width="318" src="https://user-images.githubusercontent.com/682784/149206780-7f2a5429-d3c4-49ba-8de6-0dd50f224a56.png"> <img alt="Screen Shot 2022-01-12 at 11 15 38 AM" width="897" src="https://user-images.githubusercontent.com/682784/149206774-bee93a0d-751f-4497-ba49-af3376d3a107.png">
> 
> I'm not worried about reproducing it to validate this change, since you can reproduce. We'll get further verification from other reporters once we get a second review from @christopherfujino and this merges.

use flutter run. And it's only the first time that this problem occurs

2022-01-13 17:56 UTC, christopherfujino approved these changes
LGTM, thanks for this fix!

2022-01-13 18:20 UTC, merged

2022-08-17 14:50 UTC, ahyangnb commented
thanks for this fix!