[DropdownButtonFormField] Add borderRadius propertyMaster
flutter/flutter pull request #95944
Opened 2021-12-29 20:07 UTC by dheerajv09

Adds borderRadius property  to DropdownButtonFormField.

fixes #95926

2021-12-31 14:41 UTC, werainkhatri requested changes
Thank you for the contribution. This is a good addition to the API.

A just have a few suggestions.

2021-12-31 14:41 UTC, werainkhatri commented on packages/flutter/test/material/dropdown_test.dart
> +  group('BorderRadius property works properly for DropdownButtonFormField', () {
Avoid using `group`s unless you really need it.

2021-12-31 14:41 UTC, werainkhatri commented on packages/flutter/test/material/dropdown_test.dart
> +    testWidgets('When multiple items are available', (WidgetTester tester) async {
Try to test this the same way `DropdownButton.borderRadius` is tested.

<details>
<summary>reference test</summary>

https://github.com/flutter/flutter/blob/39cdeb59621b144acd7424607c3bb80af20eb4a1/packages/flutter/test/material/dropdown_test.dart#L3528-L3573
</details>

2022-01-01 16:34 UTC, werainkhatri approved these changes
LGTM. Thank you for your contribution.

Although, this needs another reviewer's approval, as per our new commit policy.

2022-01-04 19:02 UTC, Piinks commented on packages/flutter/lib/src/material/dropdown.dart
> +                     borderRadius: borderRadius,
Can you add a comment here just like this one:
https://github.com/flutter/flutter/blob/da9e87021d9641460018c69455366dd87b621d68/packages/flutter/lib/src/material/dropdown.dart#L892

That will help us stay consistent both ways in the future. :)

2022-01-04 19:03 UTC, Piinks commented on packages/flutter/lib/src/material/dropdown.dart
> +    BorderRadius? borderRadius,
Oh whoops I meant here. Thanks!

2022-01-05 15:57 UTC, Piinks commented on packages/flutter/lib/src/material/dropdown.dart
> +    // DropdownButtonFormField.
```suggestion
    // DropdownButton.
```

2022-01-05 17:51 UTC, Piinks approved these changes
![Flutter_LGTM](https://user-images.githubusercontent.com/16964204/148264990-24509c48-d622-47de-9209-358a26350996.png)
Thank you for the contribution!

2022-01-05 17:53 UTC, dheerajv09 commented
:)

2022-01-05 20:50 UTC, merged