Adds `onReorderStart` and `onReorderEnd` arguments to `ReorderableList`.
flutter/flutter pull request #96049
Opened 2022-01-03 07:51 UTC by werainkhatri

Adds `onReorderStart` and `onReorderEnd` arguments to `SliverReorderableList`, `ReorderableList`, and `ReorderableListView`.

Fixes #95809 

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-02-16 00:04 UTC, darrenaustin requested changes
Thanks for the contribution. I am not sure I understand the exact use case for this, but it seems like a reasonable API.

Looks nice (and thanks for the tests). Just a few comments/suggestions below.

2022-02-16 05:52 UTC, werainkhatri commented on packages/flutter/lib/src/widgets/reorderable_list.dart
> +  /// A callback that is called when an item is selected to be dragged.
i was a bit unsure about how to word this. thanks for the suggestion!

2022-02-16 05:58 UTC, skia-gold commented
Gold has detected about 31 new digest(s) on patchset 2.
View them at https://flutter-gold.skia.org/cl/github/96049

2022-02-23 00:26 UTC, darrenaustin approved these changes
![flutter-lgtm](https://user-images.githubusercontent.com/19588/155242632-97018b0a-f3e0-4245-8247-8f044eebe95e.png)

Thx!

2022-02-23 12:24 UTC, merged