CupertinoButton: Add clickable cursor on web
flutter/flutter pull request #96863
Opened 2022-01-19 15:56 UTC by TahaTesser

*Replace this paragraph with a description of what this PR is changing or adding, and why. Consider including before/after screenshots.*

*List which issues are fixed by this PR. You must list at least one issue.*

*If you had to change anything in the [flutter/tests] repo, include a link to the migration guide as per the [breaking change policy].*

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-03-02 21:05 UTC, Renzo-Olivares reviewed
Very straightforward implementation! I think it would be good for the test to also test when the mouse is not hovering over the button. 

Another thing I noticed on macOS-web is that for buttons/tab-bars/and other clickable items on the web there is a subtle highlight associated with a hover over the element. Though I did not find anything in regards to it on https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/

2022-03-03 21:52 UTC, Renzo-Olivares requested changes

2022-03-03 21:52 UTC, Renzo-Olivares commented on packages/flutter/test/cupertino/button_test.dart
> +  testWidgets('Cupertino button changes mouse cursor when hovered on Web', (WidgetTester tester) async {
Nit: This could be named similar to your tab bar test. `Hovering over Cupertino button updates cursor to clickable on Web`

2022-03-04 12:54 UTC, TahaTesser commented
@Renzo-Olivares 
Actually tested the test on the web using integration_test, it works as expected

2022-03-04 22:02 UTC, Renzo-Olivares approved these changes
LGTM

2022-03-04 22:28 UTC, TahaTesser commented
@Renzo-Olivares 
My pleasure! Appreciate you taking the time to review these Cupertino PRs

I've filed a bunch of other related PRs, I followed the same pattern and tested those as well using integration_test to make sure the web is in fact updating the cursor and following the same title pattern for all of them.

2022-03-04 23:31 UTC, merged