CupertinoTabBar: Add clickable cursor on web
flutter/flutter pull request #96996
Opened 2022-01-21 12:03 UTC by TahaTesser

partial fix for https://github.com/flutter/flutter/issues/86174

Complete details https://github.com/flutter/flutter/issues/86174#issuecomment-1016596648
 
## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-03-02 21:19 UTC, Renzo-Olivares reviewed
Similar to my review on [`CupertinoButton`](https://github.com/flutter/flutter/pull/96863#pullrequestreview-898169161). A test for when the cursor is not hovering on top of the button would be good.

2022-03-03 21:52 UTC, Renzo-Olivares requested changes

2022-03-03 21:52 UTC, Renzo-Olivares commented on packages/flutter/test/cupertino/bottom_tab_bar_test.dart
> +  testWidgets('Hoveing over Bar item updates cursor to clickable', (WidgetTester tester) async {
`Hoveing` -> `Hovering`, and `Bar` -> `tab bar`.

2022-03-03 21:52 UTC, Renzo-Olivares commented on packages/flutter/test/cupertino/bottom_tab_bar_test.dart
> +    ));
Nit: trailing comma for formatting.

```dart
await pumpWidgetWithBoilerplate(
    tester,
    MediaQuery(
    ...
    ...
    ),
);
```

2022-03-03 23:08 UTC, TahaTesser commented
@Renzo-Olivares 
Thanks so much for the review, appreciate it! 

I intend to make similar changes to other Cupertino widgets ASAP.  I wanted to some confirmation with these two current  PRs.

2022-03-04 13:21 UTC, TahaTesser commented
@Renzo-Olivares 
Actually tested the test on the web using integration_test, it works as expected, results in the description.

2022-03-07 21:12 UTC, Renzo-Olivares approved these changes
LGTM!

2022-03-07 22:41 UTC, merged