Let printError be able to print bold also
flutter/flutter pull request #9714
Opened 2017-05-02 01:40 UTC by xster

2017-05-02 02:31 UTC, Hixie commented on packages/flutter_tools/lib/src/base/logger.dart
> +  void printError(String message, { StackTrace stackTrace, bool emphasis: false });
you give the default here but the three subclasses don't have the default

2017-05-02 21:52 UTC, tvolkert requested changes

2017-05-02 21:52 UTC, tvolkert commented on packages/flutter_tools/lib/src/base/logger.dart
> +    return _error.writeln(message);
No need for return

2017-05-02 21:52 UTC, tvolkert commented on packages/flutter_tools/lib/src/base/logger.dart
> +  void printError(String message, { StackTrace stackTrace, bool emphasis: false });
Yep - in `daemon.dart` too.

2017-05-02 23:59 UTC, xster commented on packages/flutter_tools/lib/src/base/logger.dart
> +    return _error.writeln(message);
Done

2017-05-02 23:59 UTC, xster commented on packages/flutter_tools/lib/src/base/logger.dart
> +  void printError(String message, { StackTrace stackTrace, bool emphasis: false });
Ah, I wasn't too sure what defaults on an abstract method's parameters actually does XD

Done

2017-05-03 00:54 UTC, tvolkert commented
LGTM

2017-05-03 00:54 UTC, tvolkert approved these changes

2017-05-03 05:20 UTC, merged