CircleAvatar make fit property accessible
flutter/flutter pull request #97875
Opened 2022-02-05 17:43 UTC by robpot95

This make it possible to chang the default BoxFit, for my case it was useful to make a image to scaledown

## Pre-launch Checklist

- [ ] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [ ] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [ ] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [ ] I signed the [CLA].
- [ ] I listed at least one issue that this PR fixes in the description above.
- [ ] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-02-13 05:22 UTC, kirolous-nashaat commented
Created an issue for this PR #98350 with suggestion to add alignment parameter too

2022-02-25 22:13 UTC, cbracken commented
Thanks for your contribution. 

A few things:
* To merge any change, you'll need to [sign the CLA](https://cla.developers.google.com/). 
* Can you provide a bit more justification for this change in [the issue](https://github.com/flutter/flutter/issues/98350)? 
* Assuming the justification for this looks good, we'll need a test before we can land any change.

2022-02-25 22:14 UTC, cbracken requested changes
Thanks for your contribution. 

A few things:
* To merge any change, you'll need to [sign the CLA](https://cla.developers.google.com/). 
* Can you provide a bit more justification for this change in [the issue](https://github.com/flutter/flutter/issues/98350)? 
* Assuming the justification for this looks good, we'll need a test before we can land any change.

2022-02-26 06:24 UTC, maheshmnj commented on packages/flutter/lib/src/material/circle_avatar.dart
> +
You need to remove trailing space here

2022-04-25 23:13 UTC, cbracken commented
Since we haven't seen an update on this issue, I'm going to close it for now. If you send a new updated patch with a test and a bit more detail covering the background of this change, we'll be more than happy to take another look.

2022-04-25 23:13 UTC, closed without merging