[flutter_tools] Update error matching regex in build_windows
flutter/flutter pull request #98137
Opened 2022-02-09 17:22 UTC by miltosdoul

Updates Windows build error-matching regular expression to match error regarding invalid asset files added in pubspec.yaml project file.

Fixes [#97065](https://github.com/flutter/flutter/issues/97065).

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [ ] I added new tests to check the change I am making, or this PR is [test-exempt].
- [ ] All existing and new tests are passing.

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-02-10 11:03 UTC, miltosdoul commented
I wasn't sure where to write tests for this so I didn't add any, if they are needed let me know where to add them.

2022-02-17 22:24 UTC, christopherfujino commented
@stuartmorgan can you take a look at this one?

2022-02-20 02:22 UTC, stuartmorgan requested changes
Yes, this needs tests. Unit tests for this file are in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/commands.shard/hermetic/build_windows_test.dart

2022-02-20 02:22 UTC, stuartmorgan commented on packages/flutter_tools/lib/src/windows/build_windows.dart
> +  final RegExp errorMatcher = RegExp(r':\s*(?:warning|(?:fatal )?error).*?:|.*Error detected in pubspec.yaml:.*|.*No file or variants found for asset: .*');
Having to encode the specific error message is very unfortunate; any other pubspec error is going to be missing all of the actual details until we add each one as it comes up. But without fundamentally reworking `stream` I don't have a better suggestion.

We should at least make this more maintainable and clearly documented though. Something like:
```
final List<String> errorMessages = <String>[
  r':\s*(?:warning|(?:fatal )?error).*?:',
  r'Error detected in pubspec.yaml:',
];
// Known secondary error lines for pubspec.yaml errors:
final List<String> pubspecErrorDetails = <String>[
  r'No file or variants found for asset:',
];
final RegExp errorMatcher = RegExp(<String>[
  ...errorMessages,
  ...pubspecErrorDetails,
].join('|'));
```

(Note that I have remove the leading and trailing `.*` from your strings. As you can see from the existing regex, this is not a full-line match.)

2022-03-24 21:04 UTC, christopherfujino commented
Closing this as stale. Feel free to re-open if you are ready to respond to code review. Thanks!

2022-03-24 21:04 UTC, closed without merging