Drawer width
flutter/flutter pull request #99777
Opened 2022-03-08 20:20 UTC by TytaniumDev

Elevate the internal width parameter for the `Drawer` widget to the constructor, and default it to the previous constant value. More info on #99776 

Fixes #99776  

## Pre-launch Checklist

- [x] I read the [Contributor Guide] and followed the process outlined there for submitting PRs.
- [x] I read the [Tree Hygiene] wiki page, which explains my responsibilities.
- [x] I read and followed the [Flutter Style Guide], including [Features we expect every widget to implement].
- [x] I signed the [CLA].
- [x] I listed at least one issue that this PR fixes in the description above.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] I added new tests to check the change I am making, or this PR is [test-exempt].
- [x] All existing and new tests are passing.

If you need help, consider asking for advice on the #hackers-new channel on [Discord].

[Contributor Guide]: https://github.com/flutter/flutter/wiki/Tree-hygiene#overview
[Tree Hygiene]: https://github.com/flutter/flutter/wiki/Tree-hygiene
[test-exempt]: https://github.com/flutter/flutter/wiki/Tree-hygiene#tests
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[Features we expect every widget to implement]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#features-we-expect-every-widget-to-implement
[CLA]: https://cla.developers.google.com/
[flutter/tests]: https://github.com/flutter/tests
[breaking change policy]: https://github.com/flutter/flutter/wiki/Tree-hygiene#handling-breaking-changes
[Discord]: https://github.com/flutter/flutter/wiki/Chat

2022-03-09 09:06 UTC, guidezpl requested changes
The way we typically resolve this kind of value is 1. individual instance, 2. [`DrawerThemeData`](ttps://github.com/flutter/flutter/blob/7e9793dee1/packages/flutter/lib/src/material/drawer_theme.dart#L31), then 3. default. 

Could you model this change after the other properties, e.g. `backgroundColor`?

2022-03-09 09:28 UTC, TytaniumDev commented
> The way we typically resolve this kind of value is 1. individual instance, 2. `DrawerThemeData`, then 3. default.
> 
> Could you model this change after the other properties, e.g. `backgroundColor`?

Can do! Is it okay if I add the existing `_kWidth` default to `DrawerThemeData`?

2022-03-10 10:11 UTC, guidezpl approved these changes
```
  _    ___ _____ __  __ 
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
                        
```

Great!

2022-03-23 04:37 UTC, darrenaustin approved these changes
Sorry it took me so long to review this. Just had a minor nit. Nice work!

![flutter-lgtm](https://user-images.githubusercontent.com/19588/159625027-07def959-c41a-4c77-85dd-e4c4e42cd734.png)

2022-03-23 04:37 UTC, darrenaustin commented on packages/flutter/test/material/drawer_test.dart
> +      (WidgetTester tester) async {
Minor nit, can these be on one line like the other tests?

2022-03-25 20:19 UTC, merged